// --- START OF FILE example-data.ts ---

export interface ExampleSentence {
  english: string;
  vietnamese: string;
}

// Dữ liệu thô chứa các câu ví dụ và bản dịch
const exampleSentencesText = `


This car uses premium grade fuel. (Chiếc xe này sử dụng nhiên liệu cao cấp.)
We arrived at the train station an hour early. (Chúng tôi đến ga tàu sớm một tiếng.)
You can report a lost item at the police station. (Bạn có thể báo mất đồ tại đồn cảnh sát.)
I need to stop at the gas station to fill up the tank. (Tôi cần ghé trạm xăng để đổ đầy bình.)
We shared many happy moments during our trip. (Chúng tôi đã chia sẻ nhiều khoảnh khắc hạnh phúc trong chuyến đi của mình.)
Could you give me a few moments to finish this? (Bạn có thể cho tôi một lát để hoàn thành việc này không?)
Life is a collection of precious moments. (Cuộc sống là một tập hợp những khoảnh khắc quý giá.)
The ocean waves were huge after the storm. (Những con sóng biển rất lớn sau cơn bão.)
She gave a quick wave before getting into her car. (Cô ấy vẫy tay nhanh chóng trước khi lên xe.)
He waved goodbye to his friends from the train window. (Anh ấy vẫy tay chào tạm biệt bạn bè từ cửa sổ tàu.)
The construction blocked the entire street. (Công trình xây dựng đã chặn toàn bộ con phố.)
Children often play with colorful building blocks. (Trẻ em thường chơi với những khối xếp hình đầy màu sắc.)
He tried to block out the noise from the street. (Anh ấy cố gắng ngăn chặn tiếng ồn từ đường phố.)
Compared to other cities, this one is quite peaceful. (So với các thành phố khác, thành phố này khá yên bình.)
The new model is faster and more efficient compared to its predecessor. (Mẫu mới nhanh hơn và hiệu quả hơn so với mẫu tiền nhiệm.)
When compared side by side, the differences between the two products are clear. (Khi đặt cạnh nhau để so sánh, sự khác biệt giữa hai sản phẩm rất rõ ràng.)
He trains every day to build his strength. (Anh ấy tập luyện mỗi ngày để xây dựng sức mạnh của mình.)
She found the strength to overcome her difficulties. (Cô ấy đã tìm thấy sức mạnh để vượt qua những khó khăn của mình.)
Teamwork is our greatest strength. (Tinh thần đồng đội là sức mạnh lớn nhất của chúng tôi.)
We are currently in the planning phase of the project. (Chúng ta hiện đang ở giai đoạn lập kế hoạch của dự án.)
The moon goes through different phases during its cycle. (Mặt trăng trải qua các giai đoạn khác nhau trong chu kỳ của nó.)
Don't worry, it's just a phase; he'll probably grow out of it soon. (Đừng lo lắng, đó chỉ là một giai đoạn thôi; có lẽ thằng bé sẽ sớm vượt qua.)
She told me a big secret yesterday. (Hôm qua cô ấy đã kể cho tôi một bí mật lớn.)
The secret to a happy life is often simplicity. (Bí quyết cho một cuộc sống hạnh phúc thường là sự đơn giản.)
Mount Everest is the highest mountain in the world. (Núi Everest là ngọn núi cao nhất thế giới.)
She achieved the highest score on the test. (Cô ấy đạt điểm cao nhất trong bài kiểm tra.)
The company's goal is to maintain the highest standards of customer service. (Mục tiêu của công ty là duy trì các tiêu chuẩn cao nhất về dịch vụ khách hàng.)
She is leaving the office early today. (Cô ấy sẽ rời văn phòng sớm hôm nay.)
He's leaving his current job to start his own business. (Anh ấy sẽ nghỉ công việc hiện tại để bắt đầu kinh doanh riêng.)
Are you leaving tonight or tomorrow morning? (Bạn sẽ đi tối nay hay sáng mai?)
It was obvious that she wasn't happy with the decision. (Rõ ràng là cô ấy không hài lòng với quyết định đó.)
The answer to the puzzle became obvious after I looked at it again. (Câu trả lời cho câu đố trở nên rõ ràng sau khi tôi xem lại nó.)
His nervousness was obvious to everyone in the room. (Sự lo lắng của anh ấy rõ ràng với tất cả mọi người trong phòng.)
I feel terrible today, I think I'm coming down with something. (Hôm nay tôi cảm thấy rất tệ, tôi nghĩ mình sắp bị ốm rồi.)
The food at that new restaurant was absolutely terrible. (Đồ ăn ở nhà hàng mới đó tệ kinh khủng.)
We heard the terrible news about the earthquake this morning. (Sáng nay chúng tôi đã nghe tin tức kinh hoàng về trận động đất.)
The earth's constant motion around the sun creates our seasons. (Sự chuyển động không ngừng của Trái đất quanh mặt trời tạo ra các mùa của chúng ta.)
He made a hand motion to signal for silence. (Anh ấy ra hiệu bằng tay để yêu cầu im lặng.)
The council passed a motion to increase funding for public parks. (Hội đồng đã thông qua một kiến nghị về việc tăng ngân sách cho các công viên công cộng.)
The cat loves to sit by the window and watch the birds. (Con mèo thích ngồi bên cửa sổ và ngắm chim.)
Please close the window, it's getting cold. (Làm ơn đóng cửa sổ lại, trời đang lạnh dần.)
Let's not assume the worst right away. (Đừng vội cho rằng điều tồi tệ nhất.)
She will assume her new duties next month. (Cô ấy sẽ đảm nhận nhiệm vụ mới vào tháng tới.)
I assume you've already finished the report. (Tôi cho rằng bạn đã hoàn thành báo cáo rồi.)
I often cycle to work to stay fit. (Tôi thường đạp xe đi làm để giữ dáng.)
The business cycle includes periods of growth and recession. (Chu kỳ kinh doanh bao gồm các giai đoạn tăng trưởng và suy thoái.)
The washing machine has a delicate cycle for fragile clothes. (Máy giặt có chu trình giặt nhẹ nhàng cho quần áo mỏng manh.)
Suddenly, the lights went out. (Đột nhiên, đèn tắt.)
She suddenly started to cry. (Cô ấy đột nhiên bật khóc.)
I suddenly remembered I had an appointment. (Tôi đột nhiên nhớ ra mình có một cuộc hẹn.)
Many people are fascinated by Western fashion trends. (Nhiều người bị cuốn hút bởi các xu hướng thời trang phương Tây.)
He enjoys watching classic Western films on the weekends. (Anh ấy thích xem những bộ phim cao bồi kinh điển vào cuối tuần.)
The company is planning to expand into the Western market. (Công ty đang có kế hoạch mở rộng sang thị trường phương Tây.)
The vase fell and is now broken. (Chiếc bình bị rơi và giờ đã vỡ.)
He can't play soccer because his arm is broken. (Anh ấy không thể chơi bóng đá vì tay anh ấy bị gãy.)
The washing machine is broken again. (Máy giặt lại bị hỏng rồi.)
The new policy will define the scope of our project. (Chính sách mới sẽ xác định phạm vi dự án của chúng ta.)
He is on a spiritual journey to find inner peace. (Anh ấy đang trên một hành trình tâm linh để tìm thấy sự bình yên nội tại.)
Many people believe there's a spiritual dimension to life beyond the physical. (Nhiều người tin rằng có một khía cạnh tâm linh của cuộc sống vượt ra ngoài thể xác.)
She finds great comfort in her spiritual practices, like yoga and meditation. (Cô ấy tìm thấy sự an ủi lớn lao trong các thực hành tâm linh của mình, như yoga và thiền định.)
The residents voiced their concerns about the increasing traffic. (Cư dân đã bày tỏ những lo ngại của họ về tình trạng giao thông ngày càng tăng.)
We have some serious concerns regarding the safety of the new bridge. (Chúng tôi có một số lo ngại nghiêm trọng về sự an toàn của cây cầu mới.)
Her main concerns are her children's health and education. (Những mối quan tâm chính của cô ấy là sức khỏe và giáo dục của các con.)
The winning numbers were selected at random. (Các số trúng thưởng được chọn ngẫu nhiên.)
We had a random encounter with an old friend at the supermarket. (Chúng tôi tình cờ gặp một người bạn cũ ở siêu thị.)
Please don't just pick random items; follow the list. (Làm ơn đừng chỉ chọn ngẫu nhiên các món đồ; hãy làm theo danh sách.)
The moon shines brightly tonight. (Mặt trăng chiếu sáng rực rỡ tối nay.)
The full moon is beautiful. (Trăng tròn thật đẹp.)
Humans first walked on the moon in 1969. (Con người lần đầu tiên đặt chân lên mặt trăng vào năm 1969.)
It's dangerous to swim in the ocean when there are strong currents. (Sẽ rất nguy hiểm khi bơi ở đại dương khi có dòng chảy mạnh.)
Driving under the influence of alcohol is extremely dangerous. (Lái xe khi say rượu là vô cùng nguy hiểm.)
He warned us that the road ahead was dangerous due to recent landslides. (Anh ấy cảnh báo chúng tôi rằng con đường phía trước nguy hiểm do sạt lở đất gần đây.)
Trees provide us with oxygen and shade. (Cây cối cung cấp oxy và bóng mát cho chúng ta.)
Many birds build their nests in trees. (Nhiều loài chim làm tổ trên cây.)
We need to protect our forests and plant more trees. (Chúng ta cần bảo vệ rừng của mình và trồng thêm nhiều cây.)
We're planning a trip to the mountains this weekend. (Chúng tôi đang lên kế hoạch cho một chuyến đi đến vùng núi vào cuối tuần này.)
How was your business trip to Japan? (Chuyến công tác Nhật Bản của bạn thế nào?)
She accidentally tripped over the rug and almost fell. (Cô ấy vô tình vấp phải tấm thảm và suýt ngã.)
Children are often very curious about the world around them. (Trẻ em thường rất tò mò về thế giới xung quanh chúng.)
I'm curious to know why she left so suddenly. (Tôi tò mò muốn biết tại sao cô ấy lại rời đi đột ngột như vậy.)
He has a curious mind, always asking questions. (Anh ấy có một trí óc tò mò, luôn đặt câu hỏi.)
This box is very heavy. (Cái hộp này rất nặng.)
We are expecting heavy rain this afternoon. (Chúng tôi dự kiến trời mưa lớn vào chiều nay.)
There was heavy traffic on the way to work. (Có tắc đường nghiêm trọng trên đường đi làm.)
Birds fly south for the winter. (Chim bay về phương Nam tránh rét.)
I need to fly to London next month for a conference. (Tôi cần bay đến Luân Đôn vào tháng tới để dự hội nghị.)
There's a fly buzzing around the kitchen. (Có một con ruồi đang vo ve quanh bếp.)
I noticed a new coffee shop has opened up on the corner. (Tôi nhận thấy một quán cà phê mới đã mở ở góc phố.)
Did you notice anything unusual about her behavior today? (Bạn có nhận thấy điều gì bất thường về hành vi của cô ấy hôm nay không?)
He didn't notice me standing there until I spoke. (Anh ấy không để ý tôi đang đứng đó cho đến khi tôi lên tiếng.)
Good evening, everyone. (Chào buổi tối, mọi người.)
I usually go for a walk in the evening. (Tôi thường đi dạo vào buổi tối.)
We spent a pleasant evening talking and laughing. (Chúng tôi đã trải qua một buổi tối vui vẻ trò chuyện và cười đùa.)
There are many interesting objects in the museum. (Có rất nhiều hiện vật thú vị trong bảo tàng.)
Please put all your personal objects in the locker. (Vui lòng đặt tất cả đồ dùng cá nhân của bạn vào tủ khóa.)
The children learned to identify different shapes and objects. (Những đứa trẻ học cách nhận biết các hình dạng và đồ vật khác nhau.)
The two countries signed a new trade agreement. (Hai quốc gia đã ký một thỏa thuận thương mại mới.)
We are in complete agreement on this matter. (Chúng tôi hoàn toàn đồng ý về vấn đề này.)
After a long discussion, they finally came to an agreement. (Sau một cuộc thảo luận dài, cuối cùng họ đã đạt được một thỏa thuận.)
Youth is a time of discovery and adventure. (Tuổi trẻ là thời gian của khám phá và phiêu lưu.)
The youth of today are the leaders of tomorrow. (Giới trẻ ngày nay là những nhà lãnh đạo của tương lai.)
She has maintained her youth remarkably well. (Cô ấy đã giữ được vẻ trẻ trung của mình một cách đáng kinh ngạc.)
The police are investigating a recent crime in the neighborhood. (Cảnh sát đang điều tra một vụ án gần đây trong khu phố.)
Crime rates have been a major concern for local authorities. (Tỷ lệ tội phạm là một mối quan tâm lớn đối với chính quyền địa phương.)
He committed a serious crime and was sentenced to prison. (Anh ta đã phạm một tội nghiêm trọng và bị kết án tù.)
Please pay attention to every detail. (Hãy chú ý đến từng chi tiết.)
Can you detail the steps involved in the process? (Bạn có thể trình bày chi tiết các bước liên quan đến quy trình không?)
We need to discuss the details of the plan. (Chúng ta cần thảo luận các chi tiết của kế hoạch.)
That car is very expensive. (Chiếc xe đó rất đắt tiền.)
Eating out in the city can be expensive. (Ăn ngoài ở thành phố có thể tốn kém.)
She bought an expensive watch as a gift. (Cô ấy đã mua một chiếc đồng hồ đắt tiền làm quà.)
The fire caused extensive damage to the building. (Vụ hỏa hoạn đã gây ra thiệt hại lớn cho tòa nhà.)
Smoking can seriously damage your health. (Hút thuốc lá có thể gây hại nghiêm trọng cho sức khỏe của bạn.)
We need to assess the damage after the earthquake. (Chúng ta cần đánh giá thiệt hại sau trận động đất.)
Can you fix my computer? (Bạn có thể sửa máy tính của tôi không?)
I'll fix you a cup of coffee. (Tôi sẽ pha cho bạn một tách cà phê.)
We need to fix this problem immediately. (Chúng ta cần giải quyết vấn đề này ngay lập tức.)
Many people believe that good souls go to Heaven after death. (Nhiều người tin rằng những linh hồn tốt đẹp sẽ lên Thiên Đàng sau khi chết.)
This quiet little village feels like heaven on Earth. (Ngôi làng nhỏ yên bình này giống như thiên đường trên Trái Đất vậy.)
After a long day, a warm bath feels like heaven. (Sau một ngày dài, được tắm nước ấm cảm giác như thiên đường.)
Please select the correct answer from the given choices. (Vui lòng chọn câu trả lời đúng từ các lựa chọn đã cho.)
You need to select the file before you can delete it. (Bạn cần chọn tệp tin trước khi có thể xóa nó.)
The committee will select a new leader next month. (Ủy ban sẽ chọn một lãnh đạo mới vào tháng tới.)
He struggled to understand the complex instructions. (Anh ấy gặp khó khăn để hiểu những hướng dẫn phức tạp.)
Many small businesses struggle to survive in the current economic climate. (Nhiều doanh nghiệp nhỏ phải vật lộn để tồn tại trong bối cảnh kinh tế hiện nay.)
She had to struggle against the strong current to reach the shore. (Cô ấy phải vật lộn chống lại dòng chảy mạnh để đến được bờ.)
The gym has a wide range of modern fitness equipment. (Phòng gym có nhiều loại thiết bị tập thể dục hiện đại.)
Always check your safety equipment before starting the climb. (Luôn kiểm tra thiết bị an toàn của bạn trước khi bắt đầu leo núi.)
Our company invested in new manufacturing equipment to improve efficiency. (Công ty chúng tôi đã đầu tư vào thiết bị sản xuất mới để cải thiện hiệu quả.)
Don't let a failure define who you are. (Đừng để một thất bại định nghĩa con người bạn.)
The power failure caused widespread disruption. (Sự cố mất điện đã gây gián đoạn trên diện rộng.)
The blackout caused widespread disruption. (Vụ mất điện đã gây ra gián đoạn trên diện rộng.)
The children love to play in the garden. (Những đứa trẻ thích chơi trong vườn.)
We grow a lot of vegetables in our garden. (Chúng tôi trồng rất nhiều rau trong vườn của mình.)
She enjoys reading a book in her quiet garden. (Cô ấy thích đọc sách trong khu vườn yên tĩnh của mình.)
The manager approved my leave request. (Người quản lý đã duyệt đơn xin nghỉ phép của tôi.)
She was promoted to sales manager last month. (Cô ấy được thăng chức quản lý bán hàng vào tháng trước.)
Please speak to the manager if you have any complaints. (Vui lòng nói chuyện với người quản lý nếu bạn có bất kỳ khiếu nại nào.)
He spent five years in prison for his crime. (Anh ấy đã ở tù năm năm vì tội của mình.)
The new prison has strict security measures. (Nhà tù mới có các biện pháp an ninh nghiêm ngặt.)
Many people believe that prison should focus more on rehabilitation than just punishment. (Nhiều người tin rằng nhà tù nên tập trung nhiều hơn vào cải tạo hơn là chỉ trừng phạt.)
I need to feed my dog. (Tôi cần cho chó của tôi ăn.)
She feeds her baby every three hours. (Cô ấy cho em bé bú/ăn mỗi ba giờ.)
Please feed the fish before you leave. (Làm ơn cho cá ăn trước khi bạn đi.)
Lions are wild animals. (Sư tử là động vật hoang dã.)
She has a wild imagination. (Cô ấy có một trí tưởng tượng phong phú.)
That was just a wild guess. (Đó chỉ là một phỏng đoán liều lĩnh.)
The valley was covered in a thick mist this morning. (Thung lũng sáng nay bị bao phủ bởi một lớp sương mù dày đặc.)
We hiked down into the valley to reach the river. (Chúng tôi đi bộ xuống thung lũng để đến con sông.)
The village is nestled in a beautiful green valley between two mountains. (Ngôi làng nằm gọn trong một thung lũng xanh tươi tuyệt đẹp giữa hai ngọn núi.)
The company plans to expand its operations into new markets next year. (Công ty có kế hoạch mở rộng hoạt động sang các thị trường mới vào năm tới.)
Reading helps you expand your vocabulary and understanding of the world. (Đọc sách giúp bạn mở rộng vốn từ vựng và hiểu biết về thế giới.)
Hot air will expand and rise, which is why hot air balloons float. (Không khí nóng sẽ nở ra và bốc lên, đó là lý do tại sao khinh khí cầu nổi được.)
The firefighters quickly put out the fire. (Lính cứu hỏa đã nhanh chóng dập tắt đám cháy.)
Can you start a fire in the fireplace? (Bạn có thể nhóm lửa trong lò sưởi không?)
I spend hours looking at a computer screen every day. (Tôi dành hàng giờ nhìn vào màn hình máy tính mỗi ngày.)
Be careful not to crack your phone screen. (Hãy cẩn thận đừng làm vỡ màn hình điện thoại của bạn.)
The doctor advised me to limit screen time for my eyes. (Bác sĩ khuyên tôi nên hạn chế thời gian nhìn màn hình để bảo vệ mắt.)
Climate change is a major global concern. (Biến đổi khí hậu là một mối quan ngại lớn trên toàn cầu.)
The climate in tropical regions is often hot and humid. (Khí hậu ở các vùng nhiệt đới thường nóng và ẩm ướt.)
We need to create a positive climate for innovation. (Chúng ta cần tạo ra một môi trường tích cực cho sự đổi mới.)
The doctor asked me to step on the scale. (Bác sĩ yêu cầu tôi bước lên cân.)
The company operates on a global scale. (Công ty hoạt động trên quy mô toàn cầu.)
She practiced her scales on the piano every day. (Cô ấy luyện tập các gam nhạc trên đàn piano mỗi ngày.)
The test results will be announced next Friday. (Kết quả thi sẽ được công bố vào thứ Sáu tới.)
Hard work often leads to excellent results. (Làm việc chăm chỉ thường mang lại kết quả xuất sắc.)
We need to analyze the survey results carefully. (Chúng ta cần phân tích kết quả khảo sát một cách cẩn thận.)
Could we get the bill, please? (Làm ơn cho chúng tôi hóa đơn được không?)
The new bill is expected to pass next month. (Dự luật mới dự kiến sẽ được thông qua vào tháng tới.)
He paid for the groceries with a twenty-dollar bill. (Anh ấy trả tiền hàng tạp hóa bằng một tờ hai mươi đô la.)
There are many new opportunities available for recent graduates in this field. (Có nhiều cơ hội mới dành cho sinh viên mới tốt nghiệp trong lĩnh vực này.)
We believe in providing equal opportunities for everyone, regardless of their background. (Chúng tôi tin vào việc cung cấp cơ hội bình đẳng cho mọi người, bất kể xuất thân của họ.)
Seize every opportunity that comes your way to learn and grow. (Hãy nắm bắt mọi cơ hội đến với bạn để học hỏi và phát triển.)
Blood is essential for life. (Máu rất cần thiết cho sự sống.)
He lost a lot of blood from the wound. (Anh ấy mất rất nhiều máu từ vết thương.)
Blood is thicker than water. (Máu mủ tình thâm.)
The singer walked onto the stage to a round of applause. (Ca sĩ bước lên sân khấu trong tràng vỗ tay.)
The singer stepped onto the stage to applause. (Ca sĩ bước lên sân khấu trong tiếng vỗ tay.)
The project is currently in its final stage of development. (Dự án hiện đang ở giai đoạn cuối cùng của quá trình phát triển.)
The project is currently in its final development stage. (Dự án hiện đang ở giai đoạn phát triển cuối cùng.)
They are going to stage a play next month. (Họ sẽ dàn dựng một vở kịch vào tháng tới.)
Please keep this information private. (Xin hãy giữ bí mật thông tin này.)
They held a private wedding ceremony. (Họ đã tổ chức một buổi lễ cưới riêng tư.)
She enrolled her child in a private school. (Cô ấy cho con mình học ở một trường tư.)
His hearing has deteriorated with age. (Thính giác của ông ấy đã suy giảm theo tuổi tác.)
The court hearing is scheduled for next Tuesday. (Phiên điều trần được lên lịch vào thứ Ba tuần tới.)
I recently watched a very interesting documentary. (Gần đây tôi đã xem một bộ phim tài liệu rất thú vị.)
Have you seen him recently? (Bạn có gặp anh ấy gần đây không?)
The weather has been quite unpredictable recently. (Thời tiết gần đây khá thất thường.)
Good leaders inspire confidence in their people. (Những nhà lãnh đạo giỏi truyền cảm hứng tự tin cho những người đi theo họ.)
The company's leaders announced a new strategy. (Các nhà lãnh đạo của công ty đã công bố một chiến lược mới.)
Effective leaders often lead by example. (Những nhà lãnh đạo hiệu quả thường lãnh đạo bằng cách làm gương.)
You need to understand the context to grasp the full meaning of the word. (Bạn cần hiểu ngữ cảnh để nắm bắt được ý nghĩa đầy đủ của từ đó.)
His actions must be viewed within the historical context of the time. (Hành động của anh ấy phải được xem xét trong bối cảnh lịch sử của thời đại đó.)
A statement can have different meanings depending on the context. (Một câu nói có thể có những ý nghĩa khác nhau tùy thuộc vào ngữ cảnh.)
What was the actual cost of the trip? (Chi phí thực tế của chuyến đi là bao nhiêu?)
The actual number of attendees was much higher than we expected. (Số lượng người tham dự thực tế cao hơn nhiều so với chúng tôi mong đợi.)
We need to know all the facts before making a decision. (Chúng ta cần biết toàn bộ sự thật trước khi đưa ra quyết định.)
We received multiple applications for the position. (Chúng tôi đã nhận được nhiều đơn ứng tuyển cho vị trí này.)
The suspect gave multiple conflicting statements. (Nghi phạm đã đưa ra nhiều lời khai mâu thuẫn.)
This software allows multiple users to work on the same document simultaneously. (Phần mềm này cho phép nhiều người dùng làm việc đồng thời trên cùng một tài liệu.)
What channel is the news on? (Tin tức đang chiếu trên kênh nào?)
Ships navigate through the narrow channel. (Các con tàu điều hướng qua kênh hẹp.)
She learned to channel her energy into her artwork. (Cô ấy học cách định hướng năng lượng của mình vào tác phẩm nghệ thuật.)
The bill passed both houses of Congress and is now awaiting the President's signature. (Dự luật đã được cả hai viện của Quốc hội thông qua và hiện đang chờ chữ ký của Tổng thống.)
Congress has the power to declare war and make laws. (Quốc hội có quyền tuyên chiến và ban hành luật pháp.)
She attended an international medical congress in Geneva last month. (Cô ấy đã tham dự một hội nghị y tế quốc tế ở Geneva vào tháng trước.)
The meeting lasted for an hour. (Cuộc họp kéo dài một giờ.)
I'll be back in an hour. (Tôi sẽ quay lại trong một giờ nữa.)
I expect him to arrive around 3 PM. (Tôi dự kiến anh ấy sẽ đến khoảng 3 giờ chiều.)
We expect high quality from our products. (Chúng tôi mong đợi chất lượng cao từ sản phẩm của mình.)
They are expecting their first baby next month. (Họ đang chờ đón đứa con đầu lòng vào tháng tới.)
Professor Miller gave a fascinating lecture on quantum physics. (Giáo sư Miller đã có một bài giảng hấp dẫn về vật lý lượng tử.)
Students often consult their professors for guidance on their studies. (Sinh viên thường tham khảo ý kiến giáo sư của họ để được hướng dẫn về việc học.)
He has been a distinguished professor at Harvard for over thirty years. (Ông ấy đã là một giáo sư ưu tú tại Harvard trong hơn ba mươi năm.)
He turned the key in the lock and opened the door. (Anh ấy vặn chìa khóa vào ổ khóa và mở cửa.)
The weather suddenly turned cold last night. (Thời tiết đột ngột trở lạnh vào tối qua.)
She turned her head to look towards the sound behind her. (Cô ấy quay đầu lại nhìn theo hướng tiếng động phát ra từ phía sau.)
Could you tell me the direction to the nearest hospital? (Bạn có thể chỉ cho tôi hướng đến bệnh viện gần nhất được không?)
The team needs clear direction from the project manager. (Nhóm cần sự chỉ đạo rõ ràng từ quản lý dự án.)
After graduation, she wasn't sure what direction her life would take. (Sau khi tốt nghiệp, cô ấy không chắc cuộc đời mình sẽ đi theo hướng nào.)
The team successfully completed their mission. (Nhóm đã hoàn thành nhiệm vụ của mình một cách thành công.)
Our company's mission is to provide excellent customer service. (Sứ mệnh của công ty chúng tôi là cung cấp dịch vụ khách hàng xuất sắc.)
He considers it his life's mission to help the less fortunate. (Anh ấy coi việc giúp đỡ những người kém may mắn là sứ mệnh cuộc đời mình.)
The company's computer network crashed this morning. (Mạng máy tính của công ty bị sập sáng nay.)
Building a strong professional network is crucial for career advancement. (Xây dựng một mạng lưới chuyên nghiệp vững chắc là rất quan trọng cho sự thăng tiến trong sự nghiệp.)
The city has an extensive network of bus routes. (Thành phố có một mạng lưới tuyến xe buýt rộng khắp.)
The ocean is a deep blue. (Đại dương có màu xanh thẫm.)
She felt a little blue after hearing the news. (Cô ấy cảm thấy hơi buồn sau khi nghe tin tức đó.)
He bought a new blue car last month. (Anh ấy đã mua một chiếc ô tô màu xanh dương mới vào tháng trước.)
The police arrived quickly at the scene. (Cảnh sát đã nhanh chóng có mặt tại hiện trường.)
The police swiftly arrived at the scene. (Cảnh sát đã nhanh chóng đến hiện trường.)
She has excellent communication skills. (Cô ấy có kỹ năng giao tiếp xuất sắc.)
Developing new skills is crucial for career growth. (Phát triển các kỹ năng mới là rất quan trọng cho sự phát triển sự nghiệp.)
The job requires strong problem-solving skills. (Công việc này đòi hỏi kỹ năng giải quyết vấn đề mạnh mẽ.)
The world is constantly changing. (Thế giới đang không ngừng thay đổi.)
She is changing her clothes in the fitting room. (Cô ấy đang thay quần áo trong phòng thử đồ.)
Adapting to changing technology is crucial for businesses. (Thích nghi với công nghệ đang thay đổi là rất quan trọng đối với các doanh nghiệp.)
The new building has a very modern structure. (Tòa nhà mới có một cấu trúc rất hiện đại.)
The structure of the company's management is quite complex. (Cấu trúc quản lý của công ty khá phức tạp.)
You need to structure your essay clearly for a good grade. (Bạn cần cấu trúc bài luận của mình rõ ràng để đạt điểm cao.)
She wants to develop her skills in coding. (Cô ấy muốn phát triển kỹ năng lập trình của mình.)
The company is developing a new product for the market. (Công ty đang phát triển một sản phẩm mới cho thị trường.)
We need to develop a plan to address the issue. (Chúng ta cần phát triển một kế hoạch để giải quyết vấn đề.)
Please pull the door to close it. (Xin hãy kéo cửa để đóng lại.)
The car was stuck, so we had to pull it out of the mud. (Chiếc xe bị kẹt, nên chúng tôi phải kéo nó ra khỏi bùn.)
He accidentally pulled a muscle while lifting weights. (Anh ấy vô tình bị căng cơ khi nâng tạ.)
Can you send me the link to that article? (Bạn có thể gửi cho tôi đường dẫn đến bài viết đó không?)
There's a strong link between diet and overall health. (Có một mối liên hệ chặt chẽ giữa chế độ ăn uống và sức khỏe tổng thể.)
The two events are closely linked in history. (Hai sự kiện này có mối liên hệ chặt chẽ trong lịch sử.)
I am learning English. (Tôi đang học tiếng Anh.)
English is a global language. (Tiếng Anh là một ngôn ngữ toàn cầu.)
Do you speak English? (Bạn có nói được tiếng Anh không?)
This car is worth a lot of money. (Chiếc xe này trị giá rất nhiều tiền.)
It's worth the effort to learn a new language. (Rất đáng để nỗ lực học một ngôn ngữ mới.)
The movie is definitely worth watching. (Bộ phim chắc chắn đáng xem.)
She's been experiencing a lot of back pain recently. (Cô ấy gần đây bị đau lưng rất nhiều.)
The pain of rejection can be hard to overcome. (Nỗi đau bị từ chối có thể khó vượt qua.)
No pain, no gain. (Không đau đớn, không thành quả.)
I apologize for being late to the meeting. (Tôi xin lỗi vì đã đến muộn cuộc họp.)
We often stay up late watching movies on weekends. (Chúng tôi thường thức khuya xem phim vào cuối tuần.)
It's never too late to start pursuing your dreams. (Không bao giờ là quá muộn để bắt đầu theo đuổi ước mơ của bạn.)
I totally forgot about our meeting today. (Tôi hoàn toàn quên mất cuộc họp của chúng ta hôm nay.)
That concert was totally amazing! (Buổi hòa nhạc đó thật sự tuyệt vời!)
You're totally wrong about that. (Bạn hoàn toàn sai về điều đó.)
I have faith in your ability to complete this project. (Tôi có niềm tin vào khả năng của bạn để hoàn thành dự án này.)
Her faith helped her overcome the challenges. (Niềm tin của cô ấy đã giúp cô ấy vượt qua những thử thách.)
It's important to have faith in yourself. (Điều quan trọng là phải có niềm tin vào bản thân.)
Please leave your comments below the article. (Xin hãy để lại bình luận của bạn bên dưới bài viết.)
Do you have any comments on the new proposal? (Bạn có bất kỳ nhận xét nào về đề xuất mới không?)
Her comments during the meeting were very insightful. (Những nhận xét của cô ấy trong cuộc họp rất sâu sắc.)
He lives on a quiet street. (Anh ấy sống trên một con phố yên tĩnh.)
What's the name of this street? (Tên con phố này là gì?)
The children were playing in the street. (Những đứa trẻ đang chơi trên phố.)
I need to search for my lost wallet. (Tôi cần tìm chiếc ví bị mất của mình.)
You can search for more information on their website. (Bạn có thể tìm kiếm thêm thông tin trên trang web của họ.)
The search for survivors continued throughout the night. (Cuộc tìm kiếm những người sống sót tiếp tục suốt đêm.)
Her artwork has a truly unique style. (Tác phẩm nghệ thuật của cô ấy có một phong cách thực sự độc đáo.)
Each person's fingerprints are unique. (Dấu vân tay của mỗi người là độc nhất.)
This is a unique opportunity that won't come again. (Đây là một cơ hội duy nhất sẽ không lặp lại.)
She was diagnosed with lung cancer last month. (Cô ấy được chẩn đoán mắc ung thư phổi vào tháng trước.)
Many organizations raise money for cancer research. (Nhiều tổ chức gây quỹ cho nghiên cứu ung thư.)
Early detection is crucial for successfully treating many types of cancer. (Phát hiện sớm là yếu tố then chốt để điều trị thành công nhiều loại ung thư.)
She's crazy about her new puppy. (Cô ấy phát cuồng vì chú chó con mới của mình.)
That's a crazy idea! (Đó là một ý tưởng điên rồ!)
This traffic is making me crazy! (Tình trạng giao thông này khiến tôi phát điên!)
Please keep a detailed record of all expenses. (Hãy giữ một bản ghi chi tiết về tất cả các khoản chi.)
The band went into the studio to record their new album. (Ban nhạc đã vào phòng thu để thu âm album mới của họ.)
She broke the world record for the fastest marathon. (Cô ấy đã phá kỷ lục thế giới về chạy marathon nhanh nhất.)
I'm trying to save money for a down payment on a house. (Tôi đang cố gắng tiết kiệm tiền để đặt cọc mua nhà.)
The firefighters worked hard to save everyone from the burning building. (Các lính cứu hỏa đã làm việc cật lực để cứu mọi người khỏi tòa nhà đang cháy.)
Don't forget to save your document before you close the application. (Đừng quên lưu tài liệu của bạn trước khi đóng ứng dụng.)
The view from the top of the mountain was incredible. (Quang cảnh từ đỉnh núi thật tuyệt vời.)
She told an incredible story about her travels. (Cô ấy kể một câu chuyện khó tin về những chuyến đi của mình.)
The chef prepared an incredible meal for us. (Đầu bếp đã chuẩn bị một bữa ăn ngon không thể tin nổi cho chúng tôi.)
The United Nations promotes peace among nations. (Liên Hợp Quốc thúc đẩy hòa bình giữa các quốc gia.)
It's important for a nation to protect its cultural heritage. (Điều quan trọng là một quốc gia phải bảo vệ di sản văn hóa của mình.)
The entire nation mourned the loss of its beloved leader. (Toàn thể quốc gia đã thương tiếc trước sự ra đi của vị lãnh đạo yêu quý.)
The building materials were delivered to the construction site. (Vật liệu xây dựng đã được chuyển đến công trường.)
What material is your new dress made of? (Chiếc váy mới của bạn được làm từ chất liệu gì?)
We need to gather more research material for the project. (Chúng tôi cần thu thập thêm tài liệu nghiên cứu cho dự án.)
It's your choice to stay or leave. (Đó là lựa chọn của bạn để ở lại hay rời đi.)
The restaurant offers a wide choice of dishes. (Nhà hàng cung cấp nhiều lựa chọn món ăn.)
Making the right choice can be challenging. (Đưa ra lựa chọn đúng đắn có thể khó khăn.)
What shape is that cloud? (Đám mây đó có hình gì?)
He's in great shape after months of training. (Anh ấy có thể lực rất tốt sau nhiều tháng tập luyện.)
Education plays a crucial role in shaping a child's character. (Giáo dục đóng vai trò quan trọng trong việc định hình tính cách của một đứa trẻ.)
After dinner, we sometimes play card games or board games. (Sau bữa tối, thỉnh thoảng chúng tôi chơi bài hoặc cờ bàn.)
There are many educational games available for young children. (Có rất nhiều trò chơi giáo dục dành cho trẻ nhỏ.)
Freedom is a fundamental human right. (Tự do là một quyền cơ bản của con người.)
Many people around the world are fighting for their freedom. (Nhiều người trên khắp thế giới đang đấu tranh cho tự do của họ.)
The bird flew out of the cage, enjoying its newfound freedom. (Con chim bay ra khỏi lồng, tận hưởng sự tự do mới tìm thấy của nó.)
A fish can swim very fast. (Một con cá có thể bơi rất nhanh.)
We often eat fish for dinner on Fridays. (Chúng tôi thường ăn cá vào bữa tối vào thứ Sáu.)
My grandfather loves to fish in the lake. (Ông tôi rất thích câu cá ở hồ.)
Don't worry about the small things. (Đừng lo lắng về những chuyện nhỏ nhặt.)
I often worry about my future. (Tôi thường lo lắng về tương lai của mình.)
She has a lot of worries on her mind. (Cô ấy có rất nhiều nỗi lo trong lòng.)
I need to get at least eight hours of sleep every night. (Tôi cần ngủ ít nhất tám tiếng mỗi đêm.)
Did you sleep well last night? (Tối qua bạn ngủ ngon không?)
The baby finally fell asleep in his mother's arms. (Em bé cuối cùng cũng ngủ thiếp đi trong vòng tay mẹ.)
Would you like an extra pillow for your bed? (Bạn có muốn lấy thêm một cái gối cho giường của mình không?)
We need to be extra careful when driving in the rain. (Chúng ta cần phải hết sức cẩn thận khi lái xe trong mưa.)
He earned some money working as an extra in a movie. (Anh ấy kiếm được một ít tiền nhờ làm diễn viên quần chúng trong một bộ phim.)
The setting of the novel is a small town in the 1950s. (Bối cảnh của cuốn tiểu thuyết là một thị trấn nhỏ vào những năm 1950.)
The park provides a beautiful setting for a wedding. (Công viên tạo nên một khung cảnh tuyệt đẹp cho một đám cưới.)
Please check the temperature setting on the air conditioner. (Vui lòng kiểm tra cài đặt nhiệt độ trên máy điều hòa.)
What is the date today? (Hôm nay là ngày mấy?)
She has a date with him on Friday night. (Cô ấy có một buổi hẹn hò với anh ấy vào tối thứ Sáu.)
Dried dates are a sweet and healthy snack. (Quả chà là sấy khô là một món ăn vặt ngọt và tốt cho sức khỏe.)
Don't forget to put on sunscreen to protect your skin from the sun. (Đừng quên thoa kem chống nắng để bảo vệ da khỏi mặt trời.)
The Earth revolves around the Sun. (Trái Đất quay quanh Mặt Trời.)
Please connect the printer cable to the computer. (Vui lòng kết nối dây cáp máy in với máy tính.)
I find it hard to connect with my new colleagues. (Tôi thấy khó kết nối với các đồng nghiệp mới.)
Our flight will connect in Singapore before heading to Australia. (Chuyến bay của chúng tôi sẽ quá cảnh ở Singapore trước khi đến Úc.)
Let's stick to the topic of the meeting, please. (Làm ơn hãy bám sát chủ đề của cuộc họp.)
The environment is a popular topic for student essays. (Môi trường là một chủ đề phổ biến cho các bài luận của sinh viên.)
He tried to change the topic because he felt uncomfortable. (Anh ấy đã cố gắng đổi chủ đề vì cảm thấy không thoải mái.)
We went for a walk in the park. (Chúng tôi đã đi dạo trong công viên.)
You can't park your car in front of the gate. (Bạn không thể đỗ xe trước cổng.)
The children are playing on the swings in the park. (Bọn trẻ đang chơi xích đu ở công viên.)
My family lives on the east side of the city. (Gia đình tôi sống ở phía đông của thành phố.)
He is planning a trip to the Far East next year. (Anh ấy đang lên kế hoạch cho một chuyến đi đến vùng Viễn Đông vào năm tới.)
I wish I were on a beach right now. (Ước gì tôi đang ở trên bãi biển ngay bây giờ.)
I wish I had studied harder for the test. (Ước gì tôi đã học chăm chỉ hơn cho bài kiểm tra.)
We wish you the best of luck in your new job. (Chúc bạn gặp nhiều may mắn và thành công trong công việc mới.)
She will graduate from university next year. (Cô ấy sẽ tốt nghiệp đại học vào năm sau.)
He graduated with a bachelor's degree in economics. (Anh ấy tốt nghiệp cử nhân kinh tế.)
The company is looking to hire recent graduates. (Công ty đang tìm cách tuyển dụng những sinh viên mới tốt nghiệp.)
The children are playing in the town square. (Bọn trẻ đang chơi ở quảng trường thành phố.)
Please draw a square with sides of five centimeters. (Làm ơn vẽ một hình vuông có các cạnh dài năm centimet.)
His answer didn't quite square with the facts. (Câu trả lời của anh ấy không hoàn toàn khớp với sự thật.)
The politician launched his re-election campaign last month. (Vị chính trị gia đã phát động chiến dịch tái tranh cử của mình vào tháng trước.)
Our new advertising campaign is designed to attract younger customers. (Chiến dịch quảng cáo mới của chúng tôi được thiết kế để thu hút những khách hàng trẻ tuổi hơn.)
The government has started a campaign to raise awareness about climate change. (Chính phủ đã bắt đầu một chiến dịch nhằm nâng cao nhận thức về biến đổi khí hậu.)
The long-term effects of pollution on the environment are a major concern. (Những tác động lâu dài của ô nhiễm đối với môi trường là một mối quan ngại lớn.)
This medication may have some unwanted side effects. (Loại thuốc này có thể có một số tác dụng phụ không mong muốn.)
The movie was praised for its stunning visual effects. (Bộ phim được khen ngợi nhờ phần hiệu ứng hình ảnh vô cùng ấn tượng.)
We need to stop for gas before we get on the highway. (Chúng ta cần dừng lại đổ xăng trước khi lên đường cao tốc.)
This stove uses natural gas, which is cheaper than electricity. (Bếp này dùng khí gas tự nhiên, rẻ hơn so với dùng điện.)
Oxygen is a gas that is essential for human life. (Oxy là một chất khí cần thiết cho sự sống của con người.)
English is not my native language. (Tiếng Anh không phải là ngôn ngữ mẹ đẻ của tôi.)
The kangaroo is native to Australia. (Chuột túi là loài bản địa của Úc.)
She is a native of California, born and raised in Los Angeles. (Cô ấy là người gốc California, sinh ra và lớn lên ở Los Angeles.)
I need to charge my phone. (Tôi cần sạc điện thoại của mình.)
How much do you charge for delivery? (Bạn tính phí bao nhiêu cho việc giao hàng?)
The suspect was charged with theft. (Nghi phạm bị buộc tội trộm cắp.)
The family was too poor to afford proper medical care. (Gia đình đó quá nghèo để có thể chi trả cho việc chăm sóc y tế đúng mức.)
Her eyesight is very poor, so she needs to wear glasses. (Thị lực của cô ấy rất kém, vì vậy cô ấy cần đeo kính.)
Oh, you poor thing, you must be exhausted after such a long day. (Ôi, tội nghiệp bạn quá, chắc hẳn bạn đã kiệt sức sau một ngày dài như vậy.)
Be careful not to drop your phone. (Cẩn thận đừng làm rơi điện thoại của bạn.)
Temperatures are expected to drop significantly tonight. (Nhiệt độ dự kiến sẽ giảm đáng kể vào tối nay.)
Could you drop me off at the next corner? (Bạn có thể cho tôi xuống ở góc phố tiếp theo được không?)
The doctor prescribed a new drug for her high blood pressure. (Bác sĩ đã kê một loại thuốc mới cho bệnh cao huyết áp của cô ấy.)
Drug abuse is a serious problem in many societies. (Lạm dụng ma túy là một vấn đề nghiêm trọng ở nhiều xã hội.)
Always read the label before taking any new drug. (Luôn đọc nhãn trước khi dùng bất kỳ loại thuốc mới nào.)
The sea is vast and mysterious. (Biển cả rộng lớn và huyền bí.)
We spent the day swimming in the sea. (Chúng tôi đã dành cả ngày để bơi ở biển.)
The ship sailed across the calm sea. (Con tàu lướt trên mặt biển lặng.)
The new season of the TV show will be released next month. (Mùa mới của chương trình truyền hình sẽ được phát hành vào tháng tới.)
Don't forget to season the chicken with herbs and spices. (Đừng quên nêm gia vị thảo mộc và gia vị cho thịt gà.)
My grandmother is currently in the hospital for some tests. (Bà tôi hiện đang ở bệnh viện để làm một số xét nghiệm.)
You should go to the hospital if the pain doesn't go away. (Bạn nên đến bệnh viện nếu cơn đau không hết.)
The new hospital is much larger and has more facilities. (Bệnh viện mới lớn hơn nhiều và có nhiều cơ sở vật chất hơn.)
They are looking to buy a house. (Họ đang tìm mua một căn nhà.)
The universe is incredibly vast and full of wonders. (Vũ trụ vô cùng rộng lớn và đầy rẫy những điều kỳ diệu.)
Scientists are constantly searching for new discoveries about the universe. (Các nhà khoa học không ngừng tìm kiếm những khám phá mới về vũ trụ.)
Many theories exist about how the universe began. (Có nhiều lý thuyết tồn tại về cách vũ trụ hình thành.)
Work can cause a lot of stress. (Công việc có thể gây ra rất nhiều căng thẳng.)
Try not to stress too much about the presentation. (Cố gắng đừng quá căng thẳng về bài thuyết trình.)
Exercise is a great way to relieve stress. (Tập thể dục là một cách tuyệt vời để giải tỏa căng thẳng.)
The car costs over twenty thousand dollars. (Chiếc xe có giá hơn hai mươi nghìn đô la.)
Thousands of fans gathered to see their favorite band. (Hàng nghìn người hâm mộ đã tụ tập để xem ban nhạc yêu thích của họ.)
The city has a population of over one hundred thousand. (Thành phố có dân số hơn một trăm nghìn người.)
The river is very wide at this point. (Con sông rất rộng tại điểm này.)
The store offers a wide selection of products. (Cửa hàng cung cấp nhiều lựa chọn sản phẩm phong phú.)
She opened her eyes wide in surprise. (Cô ấy mở to mắt ngạc nhiên.)
Please double-check your work before you submit it. (Vui lòng kiểm tra kỹ lại công việc của bạn trước khi nộp.)
The restaurant offers a double portion for a small extra charge. (Nhà hàng cung cấp một phần ăn gấp đôi với một khoản phụ phí nhỏ.)
We need to double our efforts to finish the project on time. (Chúng ta cần tăng gấp đôi nỗ lực để hoàn thành dự án đúng hạn.)
This is mine. (Đây là của tôi.)
He works in a coal mine. (Anh ấy làm việc trong một mỏ than.)
They mine for diamonds in that region. (Họ khai thác kim cương ở khu vực đó.)
Can you throw the ball to me? (Bạn có thể ném quả bóng cho tôi không?)
Please throw away the trash. (Làm ơn vứt rác đi.)
They decided to throw a party to celebrate. (Họ quyết định tổ chức một bữa tiệc để ăn mừng.)
The majority of people prefer coffee over tea in the morning. (Đa số mọi người thích cà phê hơn trà vào buổi sáng.)
The proposal was passed by a clear majority of the votes. (Đề xuất đã được thông qua với đa số phiếu rõ ràng.)
A majority of the employees supported the new flexible working hours. (Phần lớn nhân viên ủng hộ giờ làm việc linh hoạt mới.)
The virus can spread quickly in crowded places. (Vi-rút có thể lây lan nhanh chóng ở những nơi đông người.)
She spread the blanket on the grass for a picnic. (Cô ấy trải tấm chăn lên cỏ để dã ngoại.)
He loves to spread cream cheese on his bagel. (Anh ấy thích phết phô mai kem lên bánh mì vòng của mình.)
We have several options for dinner tonight. (Chúng ta có vài lựa chọn cho bữa tối nay.)
Is there an option to pay online? (Có lựa chọn thanh toán trực tuyến không?)
You always have the option to say no. (Bạn luôn có quyền lựa chọn nói không.)
The company has been in business for decades. (Công ty đã hoạt động kinh doanh trong nhiều thập kỷ.)
Technology has advanced rapidly over the past few decades. (Công nghệ đã phát triển nhanh chóng trong vài thập kỷ qua.)
They have been friends for decades. (Họ đã là bạn bè trong nhiều thập kỷ.)
I wonder if she will come to the party tonight. (Tôi tự hỏi liệu tối nay cô ấy có đến bữa tiệc không.)
The Grand Canyon is a natural wonder of the world. (Grand Canyon là một kỳ quan thiên nhiên của thế giới.)
He watched the magician's trick with a sense of wonder. (Anh ấy xem trò ảo thuật của nhà ảo thuật với cảm giác kinh ngạc.)
I wrote a letter to my grandmother last week. (Tôi đã viết một lá thư cho bà tôi vào tuần trước.)
The letter 'B' is the second letter of the English alphabet. (Chữ 'B' là chữ cái thứ hai trong bảng chữ cái tiếng Anh.)
She received a letter of acceptance from her dream university. (Cô ấy đã nhận được thư chấp nhận nhập học từ ngôi trường đại học mơ ước của mình.)
What is the best method for learning a new language? (Phương pháp tốt nhất để học một ngôn ngữ mới là gì?)
The company has developed a new method for manufacturing its products. (Công ty đã phát triển một phương pháp mới để sản xuất sản phẩm của mình.)
Her teaching method is very effective and engaging for students. (Phương pháp giảng dạy của cô ấy rất hiệu quả và thu hút học sinh.)
What are you going to wear to the party tonight? (Tối nay bạn định mặc gì đi tiệc?)
What are you wearing to the party tonight? (Tối nay bạn mặc gì đi tiệc?)
You should always wear a seatbelt for your own safety. (Bạn nên luôn thắt dây an toàn để bảo vệ chính mình.)
For your own safety, always wear a seatbelt. (Vì sự an toàn của chính bạn, hãy luôn thắt dây an toàn.)
My favorite pair of jeans is starting to wear thin at the knees. (Chiếc quần jean tôi thích nhất đã bắt đầu sờn ở phần đầu gối.)
These are my favorite jeans. (Đây là chiếc quần jean yêu thích của tôi.)
The police arrived at the scene of the accident. (Cảnh sát đã đến hiện trường vụ tai nạn.)
My favorite scene in the movie is when the hero finally confronts the villain. (Phân cảnh tôi thích nhất trong phim là lúc nhân vật chính diện cuối cùng cũng chạm trán nhân vật phản diện.)
This is a good spot for a picnic. (Đây là một địa điểm tốt để đi dã ngoại.)
I spotted a mistake in the report. (Tôi đã phát hiện ra một lỗi trong bản báo cáo.)
The dog has a black spot over its eye. (Con chó có một đốm đen trên mắt.)
Please enter the room quietly. (Xin hãy vào phòng một cách lặng lẽ.)
You need to enter your password to access the account. (Bạn cần nhập mật khẩu để truy cập vào tài khoản.)
She will enter the university next fall. (Cô ấy sẽ nhập học đại học vào mùa thu tới.)
Many people dream of going on a safari in Africa. (Nhiều người mơ ước được đi xem thú hoang dã ở châu Phi.)
Africa is the world's second-largest and second-most-populous continent. (Châu Phi là lục địa lớn thứ hai và đông dân thứ hai trên thế giới.)
The Sahara Desert covers a large part of North Africa. (Sa mạc Sahara bao phủ một phần lớn của Bắc Phi.)
With hard work, you can achieve anything. (Với sự chăm chỉ, bạn có thể đạt được bất cứ điều gì.)
She finally achieved her dream of becoming a doctor. (Cuối cùng cô ấy đã đạt được ước mơ trở thành bác sĩ.)
The team worked together to achieve their sales targets. (Cả đội đã làm việc cùng nhau để đạt được các mục tiêu doanh số.)
She's afraid of spiders. (Cô ấy sợ nhện.)
Don't be afraid to speak your mind. (Đừng ngại nói ra suy nghĩ của mình.)
I'm afraid I can't help. (Tôi e rằng mình không thể giúp được.)
The government will fund the new research program. (Chính phủ sẽ tài trợ cho chương trình nghiên cứu mới.)
They are raising funds for the local animal shelter. (Họ đang gây quỹ cho trại cứu trợ động vật ở địa phương.)
The hospital has set up a special fund to buy new equipment. (Bệnh viện đã lập một quỹ đặc biệt để mua sắm trang thiết bị mới.)
She lives in a tiny apartment in the city. (Cô ấy sống trong một căn hộ nhỏ xíu ở thành phố.)
We will be friends forever. (Chúng ta sẽ là bạn mãi mãi.)
The meeting seemed to last forever. (Cuộc họp dường như kéo dài vô tận.)
Nothing lasts forever, so cherish every moment. (Không có gì tồn tại mãi mãi, vì vậy hãy trân trọng từng khoảnh khắc.)
Vietnam declared itself an independent nation in 1945. (Việt Nam tuyên bố là một quốc gia độc lập vào năm 1945.)
He has been financially independent since he started his own business. (Anh ấy đã độc lập về tài chính kể từ khi bắt đầu kinh doanh riêng.)
What is the current status of your project? (Tiến độ dự án của bạn đến đâu rồi?)
Regular hand washing can help prevent the spread of germs. (Rửa tay thường xuyên có thể giúp ngăn chặn sự lây lan của vi trùng.)
The new law is designed to prevent tax evasion. (Luật mới được đưa ra nhằm ngăn chặn hành vi trốn thuế.)
The teacher asked us to solve the equation on the board. (Thầy giáo bảo chúng em giải phương trình trên bảng.)
Many people struggle with credit card debt. (Nhiều người phải vật lộn với nợ thẻ tín dụng.)
It took him ten years to pay off his student debt. (Anh ấy đã mất mười năm để trả hết khoản nợ sinh viên.)
I owe you a debt of gratitude for all your help. (Tôi mang ơn bạn rất nhiều vì tất cả sự giúp đỡ của bạn.)
The first unit of this textbook covers basic grammar. (Chương đầu tiên của sách giáo khoa này bao gồm ngữ pháp cơ bản.)
They are looking to rent a two-bedroom unit in the city center. (Họ đang tìm thuê một căn hộ hai phòng ngủ ở trung tâm thành phố.)
The family is the fundamental unit of society. (Gia đình là đơn vị cơ bản của xã hội.)
Her presence at the meeting was crucial for the decision-making. (Sự hiện diện của cô ấy tại cuộc họp là rất quan trọng cho việc ra quyết định.)
He has a very strong and commanding presence in the room. (Anh ấy có một sự hiện diện rất mạnh mẽ và uy quyền trong phòng.)
The company is expanding its presence in the international market. (Công ty đang mở rộng sự hiện diện của mình trên thị trường quốc tế.)
My wallet is missing. (Ví của tôi bị mất.)
The child has been missing since yesterday afternoon. (Đứa trẻ đã mất tích từ chiều hôm qua.)
I'm really missing the warm weather from my hometown. (Tôi thực sự rất nhớ thời tiết ấm áp ở quê hương mình.)
Water is a precious natural resource. (Nước là một tài nguyên thiên nhiên quý giá.)
The company is investing more in its human resources. (Công ty đang đầu tư nhiều hơn vào nguồn nhân lực của mình.)
We need to allocate our resources more efficiently to complete the project on time. (Chúng ta cần phân bổ các nguồn lực của mình hiệu quả hơn để hoàn thành dự án đúng hạn.)
I drink coffee every morning to wake up. (Tôi uống cà phê mỗi sáng để tỉnh táo.)
Let's meet at the coffee shop later. (Chúng ta hãy gặp nhau ở quán cà phê sau nhé.)
My flight was delayed due to bad weather. (Chuyến bay của tôi bị hoãn do thời tiết xấu.)
What time is your flight to London? (Chuyến bay của bạn đến Luân Đôn là lúc mấy giờ?)
He had to run up two flights of stairs to catch the train. (Anh ấy phải chạy lên hai tầng cầu thang để bắt kịp tàu.)
She decided to accept the job offer. (Cô ấy quyết định chấp nhận lời mời làm việc.)
It's important to accept yourself for who you are. (Điều quan trọng là phải chấp nhận bản thân bạn là ai.)
Please accept my sincere apologies. (Xin vui lòng chấp nhận lời xin lỗi chân thành của tôi.)
The local guide showed us around the historic city center. (Người hướng dẫn địa phương đã đưa chúng tôi đi thăm quan trung tâm thành phố lịch sử.)
Can you guide me to the nearest exit, please? (Bạn có thể hướng dẫn tôi đến lối ra gần nhất được không?)
This travel guide has a lot of useful tips for our trip. (Cuốn cẩm nang du lịch này có rất nhiều mẹo hữu ích cho chuyến đi của chúng ta.)
The library provides a quiet space for studying and reading. (Thư viện cung cấp một không gian yên tĩnh để học tập và đọc sách.)
This new software provides users with enhanced security features. (Phần mềm mới này cung cấp cho người dùng các tính năng bảo mật nâng cao.)
The government provides financial aid to families in need. (Chính phủ cung cấp hỗ trợ tài chính cho các gia đình khó khăn.)
The dog was tied to a tree with a heavy chain. (Con chó bị buộc vào cây bằng một sợi xích nặng.)
Starbucks is a global coffee chain. (Starbucks là một chuỗi cửa hàng cà phê toàn cầu.)
The accident set off a chain reaction of delays. (Vụ tai nạn đã gây ra một chuỗi phản ứng chậm trễ.)
The plane took off an hour ago. (Máy bay đã cất cánh một giờ trước.)
I need to catch a plane to London tomorrow. (Tôi cần bắt chuyến bay đi Luân Đôn vào ngày mai.)
The plane landed safely despite the bad weather. (Máy bay đã hạ cánh an toàn bất chấp thời tiết xấu.)
India is a large country in South Asia. (Ấn Độ là một quốc gia rộng lớn ở Nam Á.)
The capital of India is New Delhi. (Thủ đô của Ấn Độ là New Delhi.)
Many people dream of visiting India to explore its rich history and vibrant culture. (Nhiều người mơ ước được đến thăm Ấn Độ để khám phá lịch sử phong phú và văn hóa sôi động của nó.)
The university is a highly respected educational institution. (Trường đại học này là một tổ chức giáo dục rất được kính trọng.)
Many people rely on financial institutions for their savings and loans. (Nhiều người dựa vào các tổ chức tài chính để gửi tiết kiệm và vay vốn.)
Marriage is a traditional institution in most cultures. (Hôn nhân là một thể chế truyền thống ở hầu hết các nền văn hóa.)
Her eyes were filled with tears when she heard the news. (Đôi mắt cô ấy ngấn lệ khi nghe tin tức đó.)
The baker filled the donuts with cream. (Người thợ làm bánh đã bơm kem vào bánh donut.)
Please submit all your required documents by the deadline. (Vui lòng nộp tất cả các tài liệu cần thiết của bạn trước thời hạn.)
I need to save this document before closing the program. (Tôi cần lưu tài liệu này trước khi đóng chương trình.)
This historical document provides valuable insights into the past. (Tài liệu lịch sử này cung cấp những hiểu biết quý giá về quá khứ.)
The store is closed for the holiday. (Cửa hàng đóng cửa nghỉ lễ.)
Please keep the door closed to save energy. (Vui lòng giữ cửa đóng để tiết kiệm năng lượng.)
The road was closed due to heavy snow. (Con đường đã bị đóng cửa do tuyết rơi dày đặc.)
The company plans to launch its new smartphone next month. (Công ty dự kiến ra mắt điện thoại thông minh mới vào tháng tới.)
The rocket launch was delayed due to bad weather. (Vụ phóng tên lửa bị hoãn do thời tiết xấu.)
She decided to launch her own online business. (Cô ấy quyết định khởi nghiệp kinh doanh trực tuyến của riêng mình.)
The movie relies heavily on strong visual storytelling. (Bộ phim phụ thuộc rất nhiều vào cách kể chuyện bằng hình ảnh mạnh mẽ.)
She prefers visual aids when giving a presentation. (Cô ấy thích sử dụng các công cụ hỗ trợ trực quan khi thuyết trình.)
The new website has a clean and appealing visual design. (Trang web mới có thiết kế trực quan sạch sẽ và hấp dẫn.)
We need to determine the cause of the problem. (Chúng ta cần xác định nguyên nhân của vấn đề.)
The court will determine his guilt or innocence. (Tòa án sẽ quyết định anh ta có tội hay vô tội.)
Your effort will determine your success in this endeavor. (Nỗ lực của bạn sẽ quyết định thành công của bạn trong nỗ lực này.)
The financial sector plays a crucial role in the economy. (Ngành tài chính đóng một vai trò quan trọng trong nền kinh tế.)
Many new jobs are being created in the renewable energy sector. (Nhiều việc làm mới đang được tạo ra trong lĩnh vực năng lượng tái tạo.)
This coffee has a very strong taste. (Cà phê này có vị rất đậm.)
Would you like to taste the soup before I serve it? (Bạn có muốn nếm thử súp trước khi tôi phục vụ không?)
She has excellent taste in fashion. (Cô ấy có gu thời trang rất tuyệt vời.)
I'm not feeling well, so I'm staying home today. (Tôi thấy không khỏe nên hôm nay tôi nghỉ ở nhà.)
I am sick and tired of your excuses. (Tôi đã chán đến tận cổ những lời viện cớ của anh/em rồi.)
There is fierce competition for the top jobs. (Có sự cạnh tranh khốc liệt cho các vị trí hàng đầu.)
She won first prize in the singing competition. (Cô ấy đã đoạt giải nhất trong cuộc thi hát.)
We are in direct competition with several other companies. (Chúng tôi đang cạnh tranh trực tiếp với nhiều công ty khác.)
There's a coffee shop on the corner. (Có một quán cà phê ở góc đường.)
He put the chair in the corner of the room. (Anh ấy đặt chiếc ghế vào góc phòng.)
The store is just around the corner. (Cửa hàng ở ngay gần đây thôi.)
Be careful with that knife, you might hurt yourself. (Cẩn thận với con dao đó, bạn có thể tự làm mình bị thương đấy.)
My back hurts from sitting all day. (Lưng tôi bị đau do ngồi cả ngày.)
This is a prime example of a classic car. (Đây là một ví dụ điển hình về một chiếc xe hơi cổ điển.)
The prime suspect in the case was arrested this morning. (Nghi phạm chính trong vụ án đã bị bắt vào sáng nay.)
She is in the prime of her career. (Cô ấy đang ở trong thời kỳ đỉnh cao của sự nghiệp.)
The large ship sailed across the ocean. (Con tàu lớn đã băng qua đại dương.)
We can ship the package to your home address. (Chúng tôi có thể vận chuyển gói hàng đến địa chỉ nhà của bạn.)
The company ships its products worldwide. (Công ty giao sản phẩm của mình đi khắp thế giới.)
We are studying the history of ancient Greece. (Chúng tôi đang nghiên cứu lịch sử của Hy Lạp cổ đại.)
The explorers discovered an ancient city in the jungle. (Các nhà thám hiểm đã phát hiện ra một thành phố cổ trong rừng rậm.)
This castle is an ancient monument that attracts many tourists. (Lâu đài này là một di tích cổ xưa thu hút rất nhiều khách du lịch.)
Mix the flour, sugar, and eggs together in a large bowl. (Trộn đều bột mì, đường và trứng với nhau trong một cái tô lớn.)
She likes to mix with different kinds of people. (Cô ấy thích giao thiệp với nhiều kiểu người khác nhau.)
The city is a vibrant mix of different cultures. (Thành phố này là một sự pha trộn sôi động của các nền văn hóa khác nhau.)
We need to get to the root of the problem. (Chúng ta cần tìm ra gốc rễ của vấn đề.)
I'll be rooting for you in the competition. (Tôi sẽ cổ vũ cho bạn trong cuộc thi.)
Can you make a copy of this document for me? (Bạn có thể sao cho tôi một bản của tài liệu này được không?)
Please copy this text and paste it into the email. (Vui lòng sao chép đoạn văn bản này và dán nó vào email.)
He got in trouble for trying to copy his friend's homework. (Cậu ấy đã gặp rắc rối vì cố gắng chép bài tập về nhà của bạn mình.)
We need your input on the new marketing strategy. (Chúng tôi cần ý kiến đóng góp của bạn về chiến lược tiếp thị mới.)
Please input your name and address into the form. (Vui lòng nhập tên và địa chỉ của bạn vào biểu mẫu.)
The quality of the output depends on the quality of the input. (Chất lượng của đầu ra phụ thuộc vào chất lượng của đầu vào.)
The new law is aimed at the protection of endangered species. (Bộ luật mới nhằm mục đích bảo vệ các loài có nguy cơ tuyệt chủng.)
This helmet offers good protection for your head. (Chiếc mũ bảo hiểm này bảo vệ tốt cho đầu của bạn.)
The witness and his family were placed under police protection. (Nhân chứng và gia đình anh ấy đã được cảnh sát bảo vệ.)
We need to consider every aspect of the problem before making a decision. (Chúng ta cần phải xem xét kỹ lưỡng mọi khía cạnh của vấn đề trước khi đưa ra quyết định.)
We must consider all aspects of the issue before making a decision. (Chúng ta cần cân nhắc mọi khía cạnh của vấn đề trước khi đưa ra quyết định.)
What I enjoy most about my job is working with new people. (Điều tôi thích nhất trong công việc của mình là được làm việc với những người mới.)
The most interesting part of my job is meeting new people. (Phần thú vị nhất trong công việc của tôi là được gặp gỡ những người mới.)
His illness has a profound impact on nearly every aspect of his life. (Căn bệnh của anh tác động sâu sắc đến hầu hết mọi phương diện trong đời sống.)
His illness impacts nearly every facet of his life. (Căn bệnh của anh tác động đến gần như mọi khía cạnh trong cuộc sống.)
I can't find my mobile, have you seen it anywhere? (Tôi không tìm thấy điện thoại di động của mình, bạn có thấy nó ở đâu không?)
Many companies are now offering mobile banking services. (Nhiều công ty hiện đang cung cấp dịch vụ ngân hàng di động.)
The army has a highly mobile infantry unit. (Quân đội có một đơn vị bộ binh cơ động cao.)
Be careful not to break the glass. (Cẩn thận đừng làm vỡ tấm kính.)
She poured some juice into a glass. (Cô ấy rót một ít nước trái cây vào ly.)
I can't see without my glasses. (Tôi không thể nhìn thấy gì nếu không có kính.)
The weather is nice today. (Thời tiết hôm nay đẹp.)
What's the weather forecast for tomorrow? (Dự báo thời tiết ngày mai thế nào?)
We had to cancel the picnic because of the bad weather. (Chúng tôi đã phải hủy chuyến dã ngoại vì thời tiết xấu.)
He walked slowly because his leg was injured. (Anh ấy đi bộ chậm chạp vì chân bị thương.)
Please speak more slowly, I can't understand you. (Làm ơn nói chậm lại, tôi không thể hiểu bạn.)
The sun slowly set behind the mountains. (Mặt trời từ từ lặn sau những ngọn núi.)
The country received international aid after the earthquake. (Quốc gia đó đã nhận được viện trợ quốc tế sau trận động đất.)
A hearing aid helps my grandfather hear much better. (Máy trợ thính giúp ông tôi nghe rõ hơn nhiều.)
The new equipment will aid in the search for the missing hikers. (Thiết bị mới sẽ hỗ trợ việc tìm kiếm những người đi bộ đường dài bị mất tích.)
She is strongly opposed to the new policy. (Cô ấy kịch liệt phản đối chính sách mới.)
The two groups are completely opposed on this issue. (Hai nhóm hoàn toàn đối lập về vấn đề này.)
I am opposed to any form of discrimination. (Tôi phản đối bất kỳ hình thức phân biệt đối xử nào.)
Many homeowners are seeing their home equity increase. (Nhiều chủ nhà đang chứng kiến vốn chủ sở hữu nhà của họ tăng lên.)
Investors are looking for opportunities in private equity. (Các nhà đầu tư đang tìm kiếm cơ hội trong vốn cổ phần tư nhân.)
The company is committed to promoting diversity and equity in the workplace. (Công ty cam kết thúc đẩy sự đa dạng và công bằng tại nơi làm việc.)
Could I have a sample of this perfume? (Tôi có thể xin một mẫu thử nước hoa này không?)
The scientist collected a soil sample for analysis. (Nhà khoa học đã thu thập một mẫu đất để phân tích.)
We got to sample various local dishes at the festival. (Chúng tôi đã được nếm thử nhiều món ăn địa phương khác nhau tại lễ hội.)
The factory produced 500 units last quarter. (Nhà máy đã sản xuất 500 đơn vị sản phẩm vào quý trước.)
This song was produced by a renowned music producer. (Bài hát này được sản xuất bởi một nhà sản xuất âm nhạc nổi tiếng.)
The new farming techniques produced a much larger harvest. (Các kỹ thuật canh tác mới đã mang lại một vụ mùa bội thu hơn hẳn.)
The story tells of a giant who lived in the mountains. (Câu chuyện kể về một người khổng lồ sống trên núi.)
They discovered a giant footprint in the mud. (Họ phát hiện một dấu chân khổng lồ trong bùn.)
That company is a giant in the tech industry. (Công ty đó là một gã khổng lồ trong ngành công nghệ.)
They decided to buy a farm and start growing organic vegetables. (Họ quyết định mua một trang trại và bắt đầu trồng rau hữu cơ.)
My grandparents live on a small farm in the countryside. (Ông bà tôi sống trên một trang trại nhỏ ở vùng nông thôn.)
The children enjoyed seeing all the animals at the farm. (Những đứa trẻ rất thích nhìn ngắm tất cả các con vật ở trang trại.)
I suggest we go for a walk. (Tôi đề nghị chúng ta đi dạo.)
Can you suggest a good restaurant nearby? (Bạn có thể gợi ý một nhà hàng ngon gần đây không?)
My doctor suggested I exercise more. (Bác sĩ của tôi gợi ý tôi nên tập thể dục nhiều hơn.)
This candy is too sweet for me. (Cây kẹo này quá ngọt đối với tôi.)
She has a very sweet personality. (Cô ấy có một tính cách rất ngọt ngào/dễ mến.)
What a sweet gesture from your friend! (Thật là một cử chỉ đáng yêu từ bạn của bạn!)
There's a speed limit on this road. (Có giới hạn tốc độ trên con đường này.)
We need to limit our spending this month. (Chúng ta cần hạn chế chi tiêu trong tháng này.)
Please try to stay within the time limit. (Xin hãy cố gắng tuân thủ giới hạn thời gian.)
Could you please flip the light switch? (Bạn có thể gạt công tắc đèn được không?)
Let's switch to a different topic. (Chúng ta hãy chuyển sang một chủ đề khác.)
The company decided to switch to renewable energy sources. (Công ty đã quyết định chuyển sang các nguồn năng lượng tái tạo.)
The autumn leaves are falling. (Lá mùa thu đang rụng.)
She collected some beautiful leaves for her craft project. (Cô ấy đã thu thập một số chiếc lá đẹp cho dự án thủ công của mình.)
The tree has large, green leaves. (Cây có những chiếc lá to, màu xanh.)
You should maintain your car regularly. (Bạn nên bảo dưỡng xe của mình thường xuyên.)
She works hard to maintain a healthy lifestyle. (Cô ấy làm việc chăm chỉ để duy trì một lối sống lành mạnh.)
The company strives to maintain high quality standards. (Công ty cố gắng duy trì các tiêu chuẩn chất lượng cao.)
The heavy rain caused severe flooding in the area. (Mưa lớn đã gây ra lũ lụt nghiêm trọng trong khu vực.)
His careless mistake caused a lot of problems for the team. (Lỗi bất cẩn của anh ấy đã gây ra rất nhiều vấn đề cho đội.)
The sudden noise caused her to jump. (Tiếng ồn đột ngột đã khiến cô ấy giật mình.)
I have a math lesson this afternoon. (Chiều nay tôi có một tiết học toán.)
Learning from your mistakes is a valuable lesson. (Học hỏi từ những sai lầm của bạn là một bài học quý giá.)
She is taking piano lessons once a week. (Cô ấy đang học piano mỗi tuần một buổi.)
She has a beautiful soul. (Cô ấy có một tâm hồn đẹp.)
He put his heart and soul into building his business. (Anh ấy đã dồn hết tâm huyết và sức lực để xây dựng công việc kinh doanh của mình.)
Many believe the soul is immortal. (Nhiều người tin rằng linh hồn là bất tử.)
To what extent do you agree with the new proposal? (Bạn đồng ý với đề xuất mới ở mức độ nào?)
I understand your concerns to some extent, but we need to move forward. (Tôi hiểu những lo ngại của bạn ở một mức độ nào đó, nhưng chúng ta cần phải tiến lên.)
The company is still assessing the full extent of the financial losses. (Công ty vẫn đang đánh giá toàn bộ mức độ thiệt hại tài chính.)
I need to get rid of these old clothes. (Tôi cần loại bỏ đống quần áo cũ này.)
We need to get rid of this bad habit. (Chúng ta cần loại bỏ thói quen xấu này.)
How can I get rid of the mice in my kitchen? (Làm sao tôi có thể đuổi lũ chuột trong bếp của mình?)
He enrolled in an advanced programming class. (Anh ấy đã đăng ký một lớp lập trình nâng cao.)
The company is known for its advanced research in AI. (Công ty được biết đến với nghiên cứu tiên tiến về AI.)
We need an advanced solution to this complex problem. (Chúng ta cần một giải pháp tiên tiến cho vấn đề phức tạp này.)
A bear hibernates in winter. (Một con gấu ngủ đông vào mùa đông.)
I can't bear the thought of losing you. (Tôi không thể chịu đựng được ý nghĩ mất em.)
This tree will bear fruit next season. (Cây này sẽ ra quả vào mùa tới.)
The postman delivers mail to our house every day. (Người đưa thư giao thư đến nhà chúng tôi mỗi ngày.)
The company promised to deliver the products within three business days. (Công ty hứa sẽ giao sản phẩm trong vòng ba ngày làm việc.)
She is scheduled to deliver a presentation at the conference next week. (Cô ấy dự kiến sẽ trình bày một bài thuyết trình tại hội nghị vào tuần tới.)
He was lucky to escape the accident without any injuries. (Anh ấy đã may mắn thoát khỏi vụ tai nạn mà không bị thương tích gì.)
I feel so lucky to have you in my life. (Tôi cảm thấy thật may mắn khi có bạn trong đời.)
You're so lucky to win the lottery! (Bạn thật may mắn khi trúng xổ số!)
The clothes are not completely dry yet. (Quần áo vẫn chưa khô hẳn.)
This region is known for its hot and dry climate. (Vùng này nổi tiếng với khí hậu nóng và khô.)
My skin gets very dry in the winter. (Da của tôi trở nên rất khô vào mùa đông.)
Could you pass me the sugar, please? (Bạn có thể đưa cho tôi lọ đường được không?)
This drink contains a lot of sugar. (Thức uống này chứa rất nhiều đường.)
You should try to reduce your sugar intake for better health. (Bạn nên cố gắng giảm lượng đường nạp vào để có sức khỏe tốt hơn.)
He is pushing open the heavy door. (Anh ấy đang gắng sức đẩy mở cánh cửa nặng.)
Stop pushing me to make a decision so quickly. (Đừng thúc ép tôi phải đưa ra quyết định nhanh như vậy.)
My grandfather is pushing 80, but he's still very active. (Ông tôi sắp 80 tuổi nhưng vẫn còn rất năng động.)
A police officer helped the lost child find her way home. (Một sĩ quan cảnh sát đã giúp cô bé bị lạc tìm đường về nhà.)
He is a high-ranking officer in the army. (Anh ấy là một sĩ quan cấp cao trong quân đội.)
The chief financial officer is responsible for the company's finances. (Giám đốc tài chính chịu trách nhiệm về tài chính của công ty.)
I enjoy reading, hiking, and photography. (Tôi thích đọc sách, leo núi và chụp ảnh.)
My hobbies include reading, hiking, and photography. (Sở thích của tôi bao gồm đọc sách, đi bộ đường dài và nhiếp ảnh.)
The new policy benefits the entire community. (Chính sách mới mang lại lợi ích cho toàn thể cộng đồng.)
The new policy benefits the community as a whole. (Chính sách mới này mang lại lợi ích cho cả cộng đồng.)
The well was much deeper than we thought. (Cái giếng sâu hơn nhiều so với chúng tôi nghĩ.)
To solve this, we need a deeper understanding of the problem. (Để giải quyết việc này, chúng ta cần một sự hiểu biết sâu sắc hơn về vấn đề.)
Their friendship grew deeper over the years. (Tình bạn của họ ngày càng sâu đậm hơn qua năm tháng.)
We have seats in the front row of the theater. (Chúng tôi có ghế ở hàng đầu của rạp hát.)
He likes to row his boat on the lake every morning. (Anh ấy thích chèo thuyền trên hồ vào mỗi buổi sáng.)
My neighbors had a loud row last night. (Hàng xóm của tôi đã có một cuộc cãi vã ầm ĩ tối qua.)
He sold his car for a very good price. (Anh ấy đã bán chiếc xe của mình với giá rất hời.)
All the tickets for the show were sold out in just one hour. (Tất cả vé cho buổi biểu diễn đã được bán hết chỉ trong một giờ.)
After hearing your proposal, I'm completely sold on the idea. (Sau khi nghe đề xuất của bạn, tôi hoàn toàn bị thuyết phục bởi ý tưởng đó.)
Adulthood entails great responsibility. (Trưởng thành đồng nghĩa với việc gánh vác nhiều trách nhiệm.)
This movie is for adults only. (Bộ phim này chỉ dành cho người lớn.)
Children must be accompanied by an adult. (Trẻ em phải có người lớn đi kèm.)
My schedule is very busy this week. (Lịch trình của tôi tuần này rất bận rộn.)
Let's schedule a meeting for next Monday. (Chúng ta hãy lên lịch một cuộc họp vào thứ Hai tới.)
The train is running behind schedule. (Chuyến tàu đang chạy trễ so với lịch trình.)
The band spent all night in the recording studio to finish their new album. (Ban nhạc đã ở trong phòng thu cả đêm để hoàn thành album mới của họ.)
He lives in a small studio apartment in the city center. (Anh ấy sống trong một căn hộ studio nhỏ ở trung tâm thành phố.)
The painter works in her studio overlooking the garden. (Nữ họa sĩ làm việc trong xưởng vẽ của mình nhìn ra khu vườn.)
Our company is looking to improve its product distribution channels. (Công ty chúng tôi đang tìm cách cải thiện các kênh phân phối sản phẩm.)
The Red Cross is in charge of the distribution of food and medical supplies. (Hội Chữ thập đỏ phụ trách việc phân phát thực phẩm và vật tư y tế.)
The study analyzed the geographical distribution of the population. (Nghiên cứu đã phân tích sự phân bố dân cư theo địa lý.)
He quickly flipped through the pages of the magazine. (Anh ấy lật nhanh qua các trang của tờ tạp chí.)
This book has more than 500 pages. (Quyển sách này có hơn 500 trang.)
Please turn to page 20 for the next chapter. (Mời các bạn lật sang trang 20 để vào chương tiếp theo.)
She sliced an apple for the fruit salad. (Cô ấy cắt một quả táo để làm salad trái cây.)
Apple Inc. is one of the world's most valuable technology companies. (Apple Inc. là một trong những công ty công nghệ giá trị nhất thế giới.)
His youngest child is the apple of his eye. (Đứa con út là cục cưng của anh ấy.)
She decided to start therapy to help manage her stress. (Cô ấy quyết định bắt đầu trị liệu để giúp kiểm soát căng thẳng của mình.)
Physical therapy helped him recover from his knee injury. (Vật lý trị liệu đã giúp anh ấy hồi phục sau chấn thương đầu gối.)
Sometimes, just talking to a friend can be a form of therapy. (Đôi khi, chỉ cần nói chuyện với một người bạn cũng có thể là một hình thức trị liệu.)
We are thinking about buying a new car. (Chúng tôi đang nghĩ đến việc mua một chiếc ô tô mới.)
Buying groceries online has become very popular. (Việc mua sắm tạp hóa trực tuyến đã trở nên rất phổ biến.)
She is always buying new clothes. (Cô ấy lúc nào cũng mua quần áo mới.)
The player scored a magnificent goal in the final minute. (Cầu thủ đó đã ghi một bàn thắng tuyệt đẹp ở phút cuối cùng.)
She is a skilled violin player. (Cô ấy là một người chơi violin điêu luyện.)
He is a key player in the company's success. (Anh ấy là một nhân tố chủ chốt trong thành công của công ty.)
January is the first month of the year. (Tháng Giêng là tháng đầu tiên của năm.)
Many people make New Year's resolutions in January. (Nhiều người đặt ra các mục tiêu cho năm mới vào tháng Giêng.)
It often snows heavily in January in this region. (Ở khu vực này, tháng Giêng thường có tuyết rơi dày đặc.)
I don't eat meat because I'm a vegetarian. (Tôi không ăn thịt vì tôi là người ăn chay.)
Red meat should be consumed in moderation for a healthy diet. (Thịt đỏ nên được tiêu thụ ở mức độ vừa phải để có một chế độ ăn uống lành mạnh.)
She marinated the meat overnight before grilling it. (Cô ấy ướp thịt qua đêm trước khi nướng.)
The farmer tested the soil for nutrients before planting. (Người nông dân đã kiểm tra đất để tìm chất dinh dưỡng trước khi trồng.)
Soil erosion is a serious environmental problem. (Xói mòn đất là một vấn đề môi trường nghiêm trọng.)
Please provide a list of all your references. (Vui lòng cung cấp danh sách tất cả các tài liệu tham khảo của bạn.)
My former boss gave me a good reference for the new job. (Sếp cũ của tôi đã cho tôi một thư giới thiệu tốt cho công việc mới.)
He made a direct reference to their earlier discussion. (Anh ấy đã đề cập trực tiếp đến cuộc thảo luận trước đó của họ.)
Winter is my favorite season. (Mùa đông là mùa yêu thích của tôi.)
It gets very cold in winter here. (Ở đây trời rất lạnh vào mùa đông.)
We often drink hot chocolate during the winter months. (Chúng tôi thường uống sô cô la nóng trong những tháng mùa đông.)
The company announced some internal changes to its management structure. (Công ty đã công bố một số thay đổi nội bộ đối với cơ cấu quản lý của mình.)
Doctors performed an examination to check for any internal damage. (Các bác sĩ đã tiến hành kiểm tra để xem có bất kỳ tổn thương nội tạng nào không.)
She experienced an internal conflict about whether to accept the offer. (Cô ấy trải qua một cuộc xung đột nội tâm về việc có nên chấp nhận lời đề nghị hay không.)
Could you please turn down the volume? (Bạn có thể vặn nhỏ âm lượng xuống được không?)
This is the third volume in the series. (Đây là tập thứ ba trong bộ truyện này.)
The company reported a high volume of sales last quarter. (Công ty đã báo cáo doanh số bán hàng cao trong quý trước.)
The new building is still under construction. (Tòa nhà mới vẫn đang trong quá trình xây dựng.)
The construction industry faces many challenges. (Ngành xây dựng đối mặt với nhiều thách thức.)
We need to hire more workers for the bridge construction project. (Chúng tôi cần thuê thêm công nhân cho dự án xây dựng cầu.)
They are going to shoot a documentary next month. (Họ sẽ quay một bộ phim tài liệu vào tháng tới.)
He learned how to shoot a bow and arrow. (Anh ấy học cách bắn cung tên.)
The director asked them to do another take. (Đạo diễn yêu cầu họ quay thêm một cảnh nữa.)
We decided to take a short break in mid-afternoon. (Chúng tôi quyết định nghỉ giải lao một lát vào giữa buổi chiều.)
The company's profits grew significantly in the mid-2000s. (Lợi nhuận của công ty tăng đáng kể vào giữa những năm 2000.)
He paused in mid-sentence, trying to remember what he was saying. (Anh ấy dừng lại giữa câu, cố gắng nhớ mình đang nói gì.)
The city is experiencing rapid urban development. (Thành phố đang trải qua quá trình phát triển đô thị nhanh chóng.)
Many people prefer the convenience of an urban lifestyle. (Nhiều người thích sự tiện lợi của lối sống đô thị.)
Urban planners are working to improve public transportation. (Các nhà quy hoạch đô thị đang nỗ lực cải thiện giao thông công cộng.)
Take a deep breath and relax. (Hít thở sâu và thư giãn.)
He held his breath for a few seconds. (Anh ấy nín thở trong vài giây.)
She was out of breath after climbing the stairs. (Cô ấy bị hụt hơi sau khi leo cầu thang.)
The company conducted a survey to gather customer feedback. (Công ty đã tiến hành một cuộc khảo sát để thu thập phản hồi của khách hàng.)
We need to survey the employees about their job satisfaction. (Chúng ta cần khảo sát nhân viên về sự hài lòng trong công việc của họ.)
According to a recent survey, most people prefer working from home. (Theo một cuộc khảo sát gần đây, hầu hết mọi người thích làm việc tại nhà.)
She felt a surge of anxiety before her job interview. (Cô ấy cảm thấy một làn sóng lo âu dâng lên trước buổi phỏng vấn xin việc.)
Anxiety can manifest as physical symptoms like a racing heart. (Lo âu có thể biểu hiện thành các triệu chứng thể chất như tim đập nhanh.)
He has been dealing with a lot of anxiety about his financial situation. (Anh ấy đã phải đối mặt với rất nhiều lo lắng về tình hình tài chính của mình.)
I live in a small flat in the city center. (Tôi sống trong một căn hộ nhỏ ở trung tâm thành phố.)
The road was completely flat for miles. (Con đường hoàn toàn bằng phẳng trong nhiều dặm.)
Oh no, I have a flat tire! (Ôi không, tôi bị xịt lốp rồi!)
She has a strong desire to learn new languages. (Cô ấy có một khát khao mạnh mẽ muốn học các ngôn ngữ mới.)
I desire only happiness for my children. (Tôi chỉ mong muốn hạnh phúc cho các con của mình.)
His desire for perfection often made him work late. (Mong muốn sự hoàn hảo của anh ấy thường khiến anh ấy làm việc muộn.)
The sky is blue and clear today. (Bầu trời hôm nay trong xanh.)
Birds are flying high in the sky. (Những chú chim đang bay cao trên bầu trời.)
The night sky was filled with stars. (Bầu trời đêm đầy sao.)
He invested most of his savings in the stock market. (Anh ấy đã đầu tư phần lớn tiền tiết kiệm của mình vào thị trường chứng khoán.)
I'm sorry, that item is currently out of stock. (Xin lỗi, mặt hàng đó hiện đã hết hàng.)
The chef prepared a rich chicken stock for the soup. (Người đầu bếp đã chuẩn bị một nồi nước dùng gà đậm đà cho món súp.)
The defendant is scheduled to stand trial next month. (Bị cáo dự kiến sẽ ra hầu tòa vào tháng tới.)
You can download a free trial of the software. (Bạn có thể tải về một bản dùng thử miễn phí của phần mềm.)
The death of his son was a great trial to him. (Cái chết của con trai là một thử thách lớn đối với ông.)
The children sat in a circle on the floor. (Bọn trẻ ngồi thành một vòng tròn trên sàn nhà.)
She has a tight-knit circle of friends. (Cô ấy có một nhóm bạn thân rất khăng khít.)
Please circle the correct answer on the test. (Vui lòng khoanh tròn vào câu trả lời đúng trong bài kiểm tra.)
I was deeply moved by the film. (Tôi đã vô cùng xúc động bởi bộ phim.)
She cares deeply about animal welfare. (Cô ấy quan tâm sâu sắc đến phúc lợi động vật.)
We sincerely apologize for any inconvenience this may have caused. (Thành thật xin lỗi Quý khách vì sự bất tiện này.)
The company is facing a number of serious problems. (Công ty đang phải đối mặt với một số vấn đề nghiêm trọng.)
Our house is facing north, so it doesn't get much sun. (Nhà của chúng tôi hướng về phía bắc nên không có nhiều nắng.)
He is facing a long prison sentence if convicted. (Anh ta đang phải đối mặt với một bản án tù dài hạn nếu bị kết tội.)
I often chat with my friends on the phone. (Tôi thường trò chuyện với bạn bè qua điện thoại.)
We had a nice chat over a cup of coffee. (Chúng tôi đã có một cuộc trò chuyện vui vẻ bên tách cà phê.)
She sent me a message in the group chat. (Cô ấy đã gửi cho tôi một tin nhắn trong cuộc trò chuyện nhóm.)
The governor held a press conference to address the recent floods. (Ngài thống đốc đã tổ chức một cuộc họp báo để giải quyết vấn đề lũ lụt gần đây.)
She was elected to the school's board of governors. (Bà đã được bầu vào hội đồng quản trị của trường.)
The central bank governor is responsible for setting interest rates. (Thống đốc ngân hàng trung ương chịu trách nhiệm thiết lập lãi suất.)
There is a hole in my sock. (Có một cái lỗ trên chiếc tất của tôi.)
Be careful, there's a big hole in the road. (Cẩn thận, có một cái hố lớn trên đường.)
The mouse ran into a small hole in the wall. (Con chuột chạy vào một cái lỗ nhỏ trên tường.)
He pursued his passion for photography and became a professional. (Anh ấy theo đuổi niềm đam mê nhiếp ảnh của mình và đã trở thành một người chuyên nghiệp.)
She spoke with great passion about the need for social change. (Cô ấy đã nói đầy nhiệt huyết về sự cần thiết của việc thay đổi xã hội.)
Football is not just a game for him; it's a lifelong passion. (Bóng đá không chỉ là một trò chơi đối với anh ấy; đó là niềm đam mê suốt đời.)
The movie was a huge commercial success. (Bộ phim là một thành công lớn về mặt thương mại.)
This software is intended for personal use, not for commercial purposes. (Phần mềm này dành cho mục đích sử dụng cá nhân, không dành cho mục đích thương mại.)
I saw a funny commercial for a new phone on TV last night. (Tối qua tôi đã xem một quảng cáo hài hước cho một chiếc điện thoại mới trên TV.)
We decided to paint the kitchen walls blue. (Chúng tôi quyết định sơn tường bếp màu xanh lam.)
Be careful, the paint is still wet. (Cẩn thận, sơn vẫn còn ướt.)
She learned how to paint with watercolors. (Cô ấy đã học cách vẽ bằng màu nước.)
The train will cross the border into another country. (Chuyến tàu sẽ đi qua biên giới sang một quốc gia khác.)
She drew a decorative border around the edge of the page. (Cô ấy đã vẽ một đường viền trang trí xung quanh mép trang giấy.)
The park is bordered by a river on the south side. (Công viên giáp với một con sông ở phía nam.)
The digital era has completely changed how we access information. (Kỷ nguyên số đã thay đổi hoàn toàn cách chúng ta tiếp cận thông tin.)
The fall of the Berlin Wall marked the end of an era in world history. (Sự sụp đổ của Bức tường Berlin đã đánh dấu sự kết thúc của một thời đại trong lịch sử thế giới.)
Many people look back on the 1960s as a golden era for music. (Nhiều người coi những năm 1960 là một kỷ nguyên vàng của âm nhạc.)
AI is rapidly changing the way we live and work. (Trí tuệ nhân tạo đang nhanh chóng thay đổi cách chúng ta sống và làm việc.)
Many companies are investing heavily in AI research and development. (Nhiều công ty đang đầu tư mạnh vào nghiên cứu và phát triển AI.)
The future of AI raises both excitement and ethical concerns. (Tương lai của AI dấy lên cả sự phấn khích và những lo ngại về đạo đức.)
The road signs clearly indicated the way to the city center. (Các biển báo trên đường chỉ dẫn rõ ràng đường đến trung tâm thành phố.)
A high fever is one of the first signs of the flu. (Sốt cao là một trong những dấu hiệu đầu tiên của bệnh cúm.)
There are positive signs that the economy is starting to recover. (Có những dấu hiệu tích cực cho thấy nền kinh tế đang bắt đầu phục hồi.)
Her talent for music is truly extraordinary. (Tài năng âm nhạc của cô ấy thực sự phi thường.)
It took an extraordinary amount of courage to speak up against the injustice. (Cần một lượng lớn lòng dũng cảm phi thường để lên tiếng chống lại sự bất công.)
The view from the top of the mountain was absolutely extraordinary. (Quang cảnh từ đỉnh núi tuyệt đẹp một cách phi thường.)
The common symptoms of the flu include fever, cough, and body aches. (Các triệu chứng thông thường của bệnh cúm bao gồm sốt, ho và đau nhức cơ thể.)
What symptoms are you experiencing? (Bạn đang có những triệu chứng gì?)
If your symptoms worsen, you should see a doctor. (Nếu các triệu chứng của bạn trở nên tồi tệ hơn, bạn nên đi khám bác sĩ.)
The government pledged to reform the healthcare system. (Chính phủ cam kết cải cách hệ thống y tế.)
The government has pledged to reform the healthcare system. (Chính phủ đã cam kết cải cách hệ thống chăm sóc sức khỏe.)
Many people are calling for urgent education reform. (Nhiều người đang lên tiếng kêu gọi cải cách giáo dục khẩn cấp.)
There are widespread calls for urgent education reform. (Nhiều lời kêu gọi cải cách giáo dục khẩn cấp đang lan rộng.)


 
`;

/**
 * Phân tích chuỗi dữ liệu ví dụ thành một mảng các đối tượng có cấu trúc.
 * @param text - Chuỗi văn bản thô chứa các ví dụ.
 * @returns Một mảng các đối tượng ExampleSentence.
 */
export const parseExampleSentences = (text: string): ExampleSentence[] => {
  const lines = text.trim().split('\n');
  const examples: ExampleSentence[] = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    const match = line.match(/(.*)\s*\((.*)\)/);
    if (match && match[1] && match[2]) {
      examples.push({
        english: match[1].trim(),
        vietnamese: match[2].trim().replace(/\.$/, ''), // Bỏ dấu chấm ở cuối nếu có
      });
    } else {
      // Fallback nếu dòng không đúng định dạng
      examples.push({
        english: line.trim(),
        vietnamese: 'Bản dịch không có sẵn',
      });
    }
  }

  return examples;
};

// Xuất dữ liệu đã được phân tích để các component khác có thể sử dụng trực tiếp
export const exampleData: ExampleSentence[] = parseExampleSentences(exampleSentencesText);

// --- END OF FILE example-data.ts ---

