// --- START OF FILE example-data.ts ---

export interface ExampleSentence {
  english: string;
  vietnamese: string;
}

// Dữ liệu thô chứa các câu ví dụ và bản dịch
const exampleSentencesText = `

People have different opinions on this matter. (Mọi người có những ý kiến khác nhau về vấn đề này.)
It's important to respect other people's opinions, even if you disagree. (Điều quan trọng là phải tôn trọng ý kiến của người khác, ngay cả khi bạn không đồng ý.)
He is not afraid to express his opinions. (Anh ấy không ngại bày tỏ quan điểm của mình.)
They adopted a beautiful baby girl last year. (Họ đã nhận nuôi một bé gái xinh đẹp vào năm ngoái.)
The company adopted a new policy on remote work. (Công ty đã áp dụng một chính sách mới về làm việc từ xa.)
She quickly adopted the local customs and traditions. (Cô ấy đã nhanh chóng tiếp nhận các phong tục và truyền thống địa phương.)
I'm getting hungry, let's grab a bite to eat. (Tôi bắt đầu đói rồi, chúng ta đi kiếm gì ăn đi.)
The children are always hungry when they come home from school. (Lũ trẻ luôn đói bụng khi chúng đi học về.)
He is hungry for success and willing to work hard for it. (Anh ấy khao khát thành công và sẵn sàng làm việc chăm chỉ để đạt được điều đó.)
His main motivation for working so hard is to provide for his family. (Động lực chính để anh ấy làm việc chăm chỉ là chu cấp cho gia đình.)
I've lost all motivation to go to the gym. (Tôi đã mất hết động lực để đi đến phòng tập gym.)
A good manager knows how to boost team motivation. (Một người quản lý giỏi biết cách thúc đẩy động lực cho cả nhóm.)
Her words were very encouraging. (Lời nói của cô ấy rất khích lệ.)
The test results were encouraging. (Kết quả xét nghiệm rất khả quan.)
Thank you for your encouraging comments. (Cảm ơn những lời bình luận động viên của bạn.)
He saw his own reflection in the water. (Anh ấy nhìn thấy hình ảnh phản chiếu của chính mình dưới nước.)
Her good grades are a testament to her hard work. (Điểm số tốt của cô ấy là minh chứng cho sự chăm chỉ của mình.)
After a moment of reflection, she knew what she had to do. (Sau một lúc suy ngẫm, cô ấy đã biết mình phải làm gì.)
The city is a major center for commerce and industry. (Thành phố là một trung tâm lớn về thương mại và công nghiệp.)
The rise of e-commerce has fundamentally changed the retail landscape. (Sự trỗi dậy của thương mại điện tử đã thay đổi căn bản bối cảnh bán lẻ.)
They are studying the impact of technology on modern commerce. (Họ đang nghiên cứu tác động của công nghệ đối với thương mại hiện đại.)
Kevin is my older brother. (Kevin là anh trai của tôi.)
I'm meeting Kevin for lunch at noon. (Tôi sẽ gặp Kevin để ăn trưa vào lúc 12 giờ.)
Could you please give this book to Kevin? (Bạn có thể đưa cuốn sách này cho Kevin được không?)
Where are you headed this afternoon? (Bạn định đi đâu chiều nay?)
The company is on the brink of disaster if the situation doesn't change soon. (Công ty đang đứng trước bờ vực thảm họa nếu tình hình không sớm thay đổi.)
The research team is headed by a renowned professor. (Nhóm nghiên cứu được dẫn dắt bởi một giáo sư danh tiếng.)
This box contains old photographs. (Chiếc hộp này chứa những tấm ảnh cũ.)
This product may contain nuts. (Sản phẩm này có thể chứa các loại hạt.)
The document contains important information. (Tài liệu này chứa thông tin quan trọng.)
She tried to get his attention, but he just ignored her. (Cô ấy đã cố gắng thu hút sự chú ý của anh ta, nhưng anh ta chỉ lờ cô đi.)
If you ignore the warning signs, you might get into trouble. (Nếu bạn phớt lờ các dấu hiệu cảnh báo, bạn có thể sẽ gặp rắc rối.)
You can't just ignore your problems and hope they disappear. (Bạn không thể cứ phớt lờ các vấn đề của mình và hy vọng chúng sẽ biến mất.)
The final result exceeded all our expectations. (Kết quả cuối cùng đã vượt ngoài mọi sự mong đợi của chúng tôi.)
She went to college with great expectations. (Cô ấy vào đại học với những kỳ vọng lớn lao.)
It's important to manage your clients' expectations from the start. (Việc quản lý kỳ vọng của khách hàng ngay từ đầu là rất quan trọng.)
The nearest gas station is about a mile from here. (Trạm xăng gần nhất cách đây khoảng một dặm.)
I run three miles every morning. (Tôi chạy ba dặm mỗi sáng.)
She always goes the extra mile for her students. (Cô ấy luôn nỗ lực hết mình (làm nhiều hơn yêu cầu) vì học sinh của mình.)
They are discussing the new project. (Họ đang thảo luận về dự án mới.)
We spent hours discussing the best way to solve the problem. (Chúng tôi đã dành hàng giờ để thảo luận về cách tốt nhất để giải quyết vấn đề.)
The committee is currently discussing the budget proposal. (Ủy ban hiện đang thảo luận đề xuất ngân sách.)
What time does the clock say? (Đồng hồ báo mấy giờ?)
I need to set my alarm clock for tomorrow morning. (Tôi cần đặt đồng hồ báo thức cho sáng mai.)
The clock on the wall stopped working. (Chiếc đồng hồ trên tường đã ngừng chạy.)
The children built a sandcastle on the beach. (Những đứa trẻ xây lâu đài cát trên bãi biển.)
The desert stretches for miles, covered in golden sand. (Sa mạc trải dài hàng dặm, phủ đầy cát vàng.)
I got sand in my shoes after walking on the beach. (Tôi bị cát vào giày sau khi đi bộ trên bãi biển.)
He put his keys in his pocket. (Anh ấy bỏ chìa khóa vào túi.)
I found some money in my old jacket pocket. (Tôi tìm thấy một ít tiền trong túi áo khoác cũ của mình.)
The player quickly pocketed the ball. (Người chơi nhanh chóng đánh bóng vào túi.)
Please read the instructions carefully before you start. (Vui lòng đọc kỹ hướng dẫn trước khi bạn bắt đầu.)
The assembly instructions were very clear and easy to follow. (Hướng dẫn lắp ráp rất rõ ràng và dễ làm theo.)
I need further instructions on how to complete this task. (Tôi cần thêm hướng dẫn về cách hoàn thành nhiệm vụ này.)
The police issued a warning about the increased car thefts in the area. (Cảnh sát đã đưa ra cảnh báo về tình trạng trộm cắp xe ô tô gia tăng trong khu vực.)
She ignored the warning signs and continued to walk on the thin ice. (Cô ấy đã phớt lờ các dấu hiệu cảnh báo và tiếp tục chơi với lửa.)
The doctor gave him a serious warning about his unhealthy lifestyle. (Bác sĩ đã đưa ra một lời cảnh báo nghiêm khắc cho anh ấy về lối sống không lành mạnh của mình.)
The taxi driver took us to the airport. (Người lái xe taxi đã đưa chúng tôi đến sân bay.)
She is a very skilled driver. (Cô ấy là một người lái xe rất lành nghề.)
You need to install the correct driver for your new printer. (Bạn cần cài đặt đúng trình điều khiển cho máy in mới của mình.)
The university offers research grants to its students. (Trường đại học cung cấp các khoản tài trợ nghiên cứu cho sinh viên của mình.)
She applied for several grants to fund her innovative project. (Cô ấy đã nộp đơn xin một số khoản tài trợ để cấp vốn cho dự án đổi mới của mình.)
Many non-profit organizations rely heavily on government grants. (Nhiều tổ chức phi lợi nhuận phụ thuộc rất nhiều vào các khoản tài trợ của chính phủ.)
The Great Wall of China has stood for centuries. (Vạn Lý Trường Thành của Trung Quốc đã đứng vững qua nhiều thế kỷ.)
It took centuries for the Earth's continents to drift into their current positions. (Mất hàng thế kỷ để các lục địa của Trái Đất trôi dạt đến vị trí hiện tại của chúng.)
Many traditions have been passed down through families for centuries. (Nhiều truyền thống đã được truyền lại qua các gia đình trong hàng thế kỷ.)
You need to combine the flour and sugar in a large bowl. (Bạn cần trộn bột mì và đường trong một cái bát lớn.)
Let's combine our efforts to finish the project on time. (Hãy kết hợp nỗ lực của chúng ta để hoàn thành dự án đúng hạn.)
The new software allows users to combine text and images easily. (Phần mềm mới cho phép người dùng kết hợp văn bản và hình ảnh một cách dễ dàng.)
The customer service team handles all incoming requests promptly. (Đội ngũ chăm sóc khách hàng xử lý tất cả các yêu cầu đến một cách nhanh chóng.)
We've received many requests for the new product. (Chúng tôi đã nhận được nhiều yêu cầu về sản phẩm mới.)
Please make sure all your requests are clear and concise. (Vui lòng đảm bảo tất cả các yêu cầu của bạn rõ ràng và súc tích.)
We often eat at restaurants on weekends. (Chúng tôi thường ăn ở nhà hàng vào cuối tuần.)
There are many good restaurants in this neighborhood. (Có nhiều nhà hàng ngon trong khu phố này.)
Let's try that new restaurant for dinner tonight. (Tối nay chúng ta hãy thử nhà hàng mới đó để ăn tối.)
Joseph is a very kind person. (Joseph là một người rất tốt bụng.)
We're meeting Joseph for lunch tomorrow. (Chúng tôi sẽ gặp Joseph ăn trưa vào ngày mai.)
Have you seen Joseph's new car? (Bạn đã thấy xe mới của Joseph chưa?)
I'll wait till you come back. (Tôi sẽ đợi cho đến khi bạn quay lại.)
The store is open till 9 PM. (Cửa hàng mở cửa đến 9 giờ tối.)
Please pay at the till. (Vui lòng thanh toán tại quầy thu ngân.)
Atoms are the basic building blocks of all matter. (Nguyên tử là những khối xây dựng cơ bản của mọi vật chất.)
Every object around us, including ourselves, is made of atoms. (Mọi vật thể xung quanh chúng ta, kể cả chúng ta, đều được tạo thành từ các nguyên tử.)
Scientists use powerful microscopes to observe the behavior of individual atoms. (Các nhà khoa học sử dụng kính hiển vi mạnh mẽ để quan sát hành vi của từng nguyên tử.)
Please adjust the temperature in the room. (Làm ơn điều chỉnh nhiệt độ trong phòng.)
It takes time to adjust to a new job. (Cần thời gian để thích nghi với công việc mới.)
He adjusted his tie before the meeting. (Anh ấy điều chỉnh cà vạt trước cuộc họp.)
Be careful, that knife is very sharp. (Hãy cẩn thận, con dao đó rất sắc.)
She has a sharp mind and quickly understands complex ideas. (Cô ấy có một trí óc sắc sảo và nhanh chóng hiểu được những ý tưởng phức tạp.)
The meeting starts at 9 o'clock sharp. (Cuộc họp bắt đầu đúng 9 giờ.)
I usually sleep in on Saturday mornings. (Tôi thường ngủ nướng vào các sáng thứ Bảy.)
Do you have any plans for next Saturday? (Bạn có kế hoạch gì cho thứ Bảy tuần tới không?)
Saturday is the first day of the weekend. (Thứ Bảy là ngày đầu tiên của cuối tuần.)
The car crashed into a pole. (Chiếc xe hơi đâm vào một cái cột.)
My computer crashed, and I lost all my unsaved work. (Máy tính của tôi bị sập nguồn, và tôi mất hết công việc chưa lưu.)
We could hear the waves crash against the shore. (Chúng tôi có thể nghe thấy tiếng sóng vỗ vào bờ.)
The dog loves to chew on bones. (Con chó rất thích gặm xương.)
He fell off his bike and broke a few bones. (Anh ấy bị ngã xe và gãy vài cái xương.)
I feel it in my bones that something good is going to happen. (Tôi có linh cảm sâu sắc rằng điều gì đó tốt đẹp sắp xảy ra.)
After much consideration, he decided to quit his job and travel the world. (Sau nhiều cân nhắc, anh ấy đã quyết định nghỉ việc và đi du lịch vòng quanh thế giới.)
It's very difficult to quit smoking, but it's worth it for your health. (Rất khó để bỏ thuốc lá, nhưng điều đó xứng đáng cho sức khỏe của bạn.)
Never quit on your dreams, no matter how hard it gets. (Đừng bao giờ từ bỏ ước mơ của mình, cho dù có khó khăn đến đâu.)
Recognizing the problem is the first step towards finding a solution. (Thừa nhận vấn đề là bước đầu tiên để tìm ra giải pháp.)
I almost didn't recognize her with her new haircut. (Tôi suýt không nhận ra cô ấy với mái tóc mới.)
The company is recognizing his efforts with a bonus. (Công ty đang ghi nhận những nỗ lực của anh ấy bằng một khoản tiền thưởng.)
The boy is throwing a ball to his dog. (Cậu bé đang ném một quả bóng cho con chó của mình.)
Please stop throwing your clothes on the floor. (Làm ơn đừng vứt quần áo của bạn xuống sàn nhà nữa.)
We are throwing a surprise party for her birthday. (Chúng tôi đang tổ chức một bữa tiệc bất ngờ cho sinh nhật của cô ấy.)
He drives to work every morning. (Anh ấy lái xe đi làm mỗi buổi sáng.)
Her ambition drives her to succeed in her career. (Tham vọng của cô ấy thúc đẩy cô ấy thành công trong sự nghiệp.)
Competition drives prices down. (Sự cạnh tranh thúc đẩy giá cả đi xuống.)
She gave a detailed explanation of the new company policy. (Cô ấy đã đưa ra một lời giải thích chi tiết về chính sách mới của công ty.)
The police asked him for a detailed report of the incident. (Cảnh sát đã yêu cầu anh ấy cung cấp một bản báo cáo chi tiết về vụ việc.)
Please follow the detailed instructions in the manual carefully. (Vui lòng làm theo hướng dẫn chi tiết trong sách hướng dẫn một cách cẩn thận.)
There are many beautiful old churches in this city. (Thành phố này có rất nhiều nhà thờ cổ kính xinh đẹp.)
We visited several historic churches during our trip to Europe. (Chúng tôi đã ghé thăm một vài nhà thờ lịch sử trong chuyến đi châu Âu của mình.)
Many churches offer shelter and support to the local community. (Nhiều nhà thờ cung cấp nơi ở và sự hỗ trợ cho cộng đồng địa phương.)
He gave her a beautiful bouquet of flowers for her birthday. (Anh ấy đã tặng cô ấy một bó hoa đẹp nhân dịp sinh nhật.)
Many people believe that flowers can brighten up any room. (Nhiều người tin rằng hoa có thể làm bừng sáng bất kỳ căn phòng nào.)
The design of the new office is more functional than beautiful. (Thiết kế của văn phòng mới thì thực dụng hơn là đẹp.)
After the repairs, the old machine is now fully functional. (Sau khi sửa chữa, chiếc máy cũ giờ đã hoạt động hoàn toàn bình thường.)
The website is not yet functional on mobile devices. (Trang web vẫn chưa hoạt động được trên các thiết bị di động.)
A dove is a symbol of peace. (Bồ câu là biểu tượng của hòa bình.)
The bald eagle is a national symbol of the United States. (Đại bàng đầu trắng là biểu tượng quốc gia của Hoa Kỳ.)
The lion tore at the flesh of its prey. (Sư tử xé toạc da thịt của con mồi.)
The mango has sweet, juicy yellow flesh. (Quả xoài có phần thịt quả màu vàng, ngọt và mọng nước.)
The spirit is willing, but the flesh is weak. (Tinh thần thì muốn lắm, nhưng thể xác lại yếu đuối.)
The two companies have formed strong partnerships over the years. (Hai công ty đã hình thành mối quan hệ đối tác bền chặt trong nhiều năm qua.)
Strategic partnerships are essential for our company's growth and innovation. (Các mối quan hệ đối tác chiến lược là điều cần thiết cho sự phát triển và đổi mới của công ty chúng tôi.)
We are open to new partnerships with organizations that share our values. (Chúng tôi sẵn sàng hợp tác với các tổ chức có chung giá trị.)
The Earth has a strong magnetic field. (Trái Đất có một từ trường mạnh.)
He has a magnetic personality that everyone is drawn to. (Anh ấy có một cá tính lôi cuốn mà ai cũng bị thu hút.)
The metal strip on a credit card is magnetic. (Dải kim loại trên thẻ tín dụng có từ tính.)
The study of magnetism is a fundamental part of physics. (Việc nghiên cứu về từ tính là một phần cơ bản của vật lý học.)
He has a natural magnetism that makes people want to follow him. (Anh ấy có một sức hút tự nhiên khiến mọi người muốn đi theo.)
There was an undeniable magnetism between the two main characters in the movie. (Có một sức lôi cuốn không thể phủ nhận giữa hai nhân vật chính trong phim.)
My son is currently attending secondary school. (Con trai tôi hiện đang học trung học.)
For me, salary is a secondary consideration; the most important thing is job satisfaction. (Đối với tôi, lương bổng chỉ là yếu tố thứ yếu; điều quan trọng nhất là sự hài lòng trong công việc.)
The drug has a number of secondary effects that patients should be aware of. (Loại thuốc này có một số tác dụng phụ mà bệnh nhân nên biết.)
She earned a promotion and a significant pay raise. (Cô ấy đã được thăng chức và tăng lương đáng kể.)
He earned the respect of his teammates through his hard work. (Anh ấy đã giành được sự tôn trọng của đồng đội nhờ sự chăm chỉ của mình.)
After a long week, I think I've earned a day off. (Sau một tuần dài, tôi nghĩ mình xứng đáng có một ngày nghỉ.)
I spend the first hour of my day reading and responding to emails. (Tôi dành giờ đầu tiên trong ngày để đọc và trả lời email.)
She has to reply to hundreds of emails from customers every day. (Cô ấy phải trả lời hàng trăm email từ khách hàng mỗi ngày.)
Please delete any suspicious emails immediately. (Vui lòng xóa ngay lập tức bất kỳ email đáng ngờ nào.)
The teacher's explanation of the complex topic was easy to understand. (Lời giải thích của giáo viên về chủ đề phức tạp rất dễ hiểu.)
I think you owe me an explanation for your behavior. (Tôi nghĩ bạn nợ tôi một lời giải thích cho hành vi của mình.)
There is no logical explanation for what happened. (Không có lời giải thích hợp lý nào cho những gì đã xảy ra.)
To be frank, I don't think that's a good idea. (Thành thật mà nói, tôi không nghĩ đó là một ý hay.)
She gave him a frank answer about her decision. (Cô ấy đã cho anh ấy một câu trả lời thẳng thắn về quyết định của mình.)
Let me be frank with you; this project needs more effort. (Hãy để tôi thẳng thắn với bạn; dự án này cần nhiều nỗ lực hơn nữa.)
The concert starts at approximately 8 PM. (Buổi hòa nhạc bắt đầu vào khoảng 8 giờ tối.)
The population of the city is approximately two million. (Dân số của thành phố là khoảng hai triệu người.)
It will take approximately three hours to finish the task. (Sẽ mất khoảng ba giờ để hoàn thành nhiệm vụ này.)
Athletes train hard to compete in the Olympics. (Các vận động viên luyện tập chăm chỉ để thi đấu tại Thế vận hội.)
Many companies compete for market share in the tech industry. (Nhiều công ty cạnh tranh giành thị phần trong ngành công nghệ.)
They will compete for the championship title this weekend. (Họ sẽ tranh tài cho chức vô địch vào cuối tuần này.)
She drew a beautiful picture of her cat. (Cô ấy đã vẽ một bức tranh đẹp về con mèo của mình.)
The event drew a large crowd from all over the city. (Sự kiện đã thu hút một lượng lớn khán giả từ khắp thành phố.)
He drew a deep breath before speaking. (Anh ấy hít một hơi thật sâu trước khi nói.)
The team celebrated their hard-earned victory. (Đội đã ăn mừng chiến thắng nhọc nhằn của mình.)
It was a great victory for human rights. (Đó là một chiến thắng vĩ đại cho nhân quyền.)
She finally achieved victory over her illness. (Cô ấy cuối cùng đã giành được chiến thắng trước căn bệnh của mình.)
The new skyscraper is built with a strong steel frame. (Tòa nhà chọc trời mới được xây dựng với khung thép chắc chắn.)
Stainless steel is a popular material for kitchen appliances. (Thép không gỉ là vật liệu phổ biến cho các thiết bị nhà bếp.)
Her determination was as hard as steel. (Quyết tâm của cô ấy cứng rắn như thép.)
This book belongs to me. (Cuốn sách này thuộc về tôi.)
I finally feel like I belong here. (Cuối cùng tôi cũng cảm thấy mình thuộc về nơi này.)
These shoes don't belong in the kitchen. (Mấy đôi giày này không thuộc về nhà bếp.)
She decided to volunteer her time at the local animal shelter. (Cô ấy quyết định dành thời gian làm tình nguyện viên tại trại cứu hộ động vật địa phương.)
Many volunteers helped clean up the park after the storm. (Nhiều tình nguyện viên đã giúp dọn dẹp công viên sau cơn bão.)
Volunteering is a great way to give back to the community. (Tình nguyện là một cách tuyệt vời để đóng góp cho cộng đồng.)
The Caribbean islands are popular tourist destinations. (Quần đảo Caribe là những điểm đến du lịch nổi tiếng.)
The Caribbean islands are a popular tourist destination. (Các hòn đảo Caribe là một điểm đến du lịch nổi tiếng.)
She is representing her country at the Olympic Games. (Cô ấy đang đại diện cho quốc gia của mình tại Thế vận hội.)
The statue represents the goddess of justice. (Bức tượng tượng trưng cho nữ thần công lý.)
The chart represents the sales figures for the last quarter. (Biểu đồ này thể hiện số liệu bán hàng của quý trước.)
She showed me an old photograph of her family. (Cô ấy cho tôi xem một bức ảnh cũ của gia đình cô ấy.)
I love to photograph nature and wildlife. (Tôi thích chụp ảnh thiên nhiên và động vật hoang dã.)
Please don't take a photograph inside the museum. (Xin đừng chụp ảnh bên trong bảo tàng.)
The meeting follows the presentation. (Cuộc họp diễn ra sau buổi thuyết trình.)
The little duckling always follows its mother. (Chú vịt con luôn đi theo mẹ của nó.)
Can you explain it again? I don't quite follow. (Bạn có thể giải thích lại không? Tôi không hiểu lắm.)
She was encouraged by her parents to pursue her passion. (Cô ấy được bố mẹ khuyến khích theo đuổi đam mê của mình.)
The students were encouraged to ask questions during the lecture. (Các học sinh được khuyến khích đặt câu hỏi trong suốt buổi giảng.)
He felt encouraged after receiving positive feedback on his project. (Anh ấy cảm thấy được khích lệ sau khi nhận được phản hồi tích cực về dự án của mình.)
Imagination is more important than knowledge. (Trí tưởng tượng quan trọng hơn kiến thức.)
Children often have a vivid imagination. (Trẻ em thường có một trí tưởng tượng phong phú.)
Use your imagination to create something new. (Hãy sử dụng trí tưởng tượng của bạn để tạo ra điều gì đó mới mẻ.)
The sign directed us to the exit. (Biển báo chỉ đường cho chúng tôi đến lối ra.)
The new film was directed by Christopher Nolan. (Bộ phim mới được đạo diễn bởi Christopher Nolan.)
All questions should be directed to the customer service department. (Tất cả các câu hỏi nên được gửi đến phòng dịch vụ khách hàng.)
Our meeting is scheduled for Tuesday morning. (Cuộc họp của chúng ta được lên lịch vào sáng thứ Ba.)
The library is closed on Tuesdays. (Thư viện đóng cửa vào các ngày thứ Ba.)
I have a dentist appointment next Tuesday. (Tôi có cuộc hẹn với nha sĩ vào thứ Ba tới.)
The library opens at 10 AM every weekday. (Thư viện mở cửa lúc 10 giờ sáng vào các ngày trong tuần.)
She always opens the window to let in fresh air. (Cô ấy luôn mở cửa sổ để không khí trong lành tràn vào.)
The new exhibition opens to the public next month. (Triển lãm mới sẽ mở cửa cho công chúng vào tháng tới.)
Our company has offices in three different cities. (Công ty chúng tôi có văn phòng ở ba thành phố khác nhau.)
Many people are returning to their offices after working remotely. (Nhiều người đang trở lại văn phòng của họ sau thời gian làm việc từ xa.)
The new offices have modern designs and plenty of natural light. (Các văn phòng mới có thiết kế hiện đại và nhiều ánh sáng tự nhiên.)
The children love to play on the soft grass. (Bọn trẻ thích chơi đùa trên bãi cỏ mềm mại.)
My dad mows the grass every Saturday. (Bố tôi cắt cỏ vào mỗi thứ Bảy.)
After the rain, the grass looks much greener. (Sau cơn mưa, cỏ trông xanh hơn nhiều.)
The store is having a big sale this weekend. (Cửa hàng đang có một đợt giảm giá lớn vào cuối tuần này.)
This product is currently on sale. (Sản phẩm này hiện đang được giảm giá.)
The real estate agent closed a difficult sale. (Nhân viên môi giới bất động sản đã hoàn thành một giao dịch bán hàng khó khăn.)
The loud music was starting to hurt my ears. (Tiếng nhạc lớn bắt đầu làm tôi đau tai.)
Tell me your story, I'm all ears. (Hãy kể câu chuyện của bạn đi, tôi đang chăm chú lắng nghe đây.)
My dog's ears perked up when he heard the treat bag. (Tai của chú chó của tôi vểnh lên khi nghe thấy tiếng túi đồ ăn vặt.)
It's not my fault that we are late. (Không phải lỗi của tôi mà chúng ta bị trễ.)
He has many faults, but dishonesty isn't one of them. (Anh ấy có nhiều khuyết điểm, nhưng thiếu trung thực không phải là một trong số đó.)
The earthquake occurred along a major fault line. (Trận động đất xảy ra dọc theo một đường đứt gãy lớn.)
She received many beautiful gifts for her birthday. (Cô ấy đã nhận được rất nhiều món quà xinh đẹp trong ngày sinh nhật của mình.)
We exchanged gifts during the Christmas party. (Chúng tôi đã trao đổi quà cho nhau trong bữa tiệc Giáng sinh.)
He is gifted in many areas, particularly in music and art. (Anh ấy có năng khiếu ở nhiều lĩnh vực, đặc biệt là âm nhạc và nghệ thuật.)
The United States imposed new sanctions on the country due to its nuclear program. (Hoa Kỳ đã áp đặt các biện pháp trừng phạt mới đối với quốc gia đó do chương trình hạt nhân của họ.)
The economic sanctions have had a severe impact on ordinary citizens. (Các biện pháp trừng phạt kinh tế đã có tác động nghiêm trọng đến những người dân thường.)
Several nations are calling for the lifting of sanctions to allow for humanitarian aid. (Một số quốc gia đang kêu gọi dỡ bỏ các biện pháp trừng phạt để cho phép viện trợ nhân đạo.)
She is pregnant with her second child. (Cô ấy đang mang thai đứa con thứ hai.)
My wife told me she was pregnant last night. (Vợ tôi đã báo tin cô ấy có thai vào tối qua.)
It is important for pregnant women to eat a healthy diet. (Phụ nữ mang thai cần có một chế độ ăn uống lành mạnh.)
What's the monthly rent for this apartment? (Tiền thuê căn hộ này mỗi tháng là bao nhiêu?)
How much is the rent for this apartment? (Tiền thuê căn hộ này là bao nhiêu?)
We decided to rent a car for our road trip. (Chúng tôi quyết định thuê ô tô cho chuyến đi phượt.)
Rất tiếc, bạn đã cung cấp một ký tự đơn lẻ `(` thay vì một cặp câu. Vui lòng cung cấp một cặp câu Anh-Việt hoàn chỉnh để tôi có thể cải thiện.
His contributions to the project were invaluable. (Những đóng góp của anh ấy cho dự án là vô giá.)
We would like to thank everyone for their generous contributions to the charity. (Chúng tôi xin cảm ơn mọi người vì những đóng góp hào phóng cho quỹ từ thiện.)
Albert Einstein's contributions to science changed the world. (Những đóng góp của Albert Einstein cho khoa học đã thay đổi thế giới.)
The price tag shows that this jacket is on sale. (Mác giá cho thấy chiếc áo khoác này đang được giảm giá.)
Don't forget to tag your friends in the photo. (Đừng quên gắn thẻ bạn bè của bạn vào bức ảnh nhé.)
My younger brother always wants to tag along when I go out with my friends. (Em trai tôi luôn muốn đi theo mỗi khi tôi ra ngoài với bạn bè.)
The cost of living has increased in the city. Similarly, rent prices have also gone up. (Chi phí sinh hoạt trong thành phố đã tăng lên. Tương tự, giá thuê nhà cũng đã tăng theo.)
My sister loves to read books. Similarly, I enjoy spending my weekends at the library. (Chị gái tôi rất thích đọc sách. Tương tự, tôi cũng thích dành những ngày cuối tuần của mình ở thư viện.)
You should treat others with respect; similarly, you should expect them to respect you in return. (Bạn nên đối xử với người khác một cách tôn trọng; tương tự, bạn cũng nên mong đợi họ tôn trọng lại bạn.)
What's your favorite sport? (Môn thể thao yêu thích của bạn là gì?)
Playing a sport is a great way to stay healthy. (Chơi thể thao là một cách tuyệt vời để giữ gìn sức khỏe.)
Football is the most popular sport in many countries. (Bóng đá là môn thể thao phổ biến nhất ở nhiều quốc gia.)
He was diagnosed with type 2 diabetes last year. (Anh ấy được chẩn đoán mắc bệnh tiểu đường tuýp 2 vào năm ngoái.)
Managing diabetes requires careful attention to diet and exercise. (Kiểm soát bệnh tiểu đường đòi hỏi phải chú ý cẩn thận đến chế độ ăn uống và tập thể dục.)
A family history of diabetes can increase your risk of developing the condition. (Tiền sử gia đình mắc bệnh tiểu đường có thể làm tăng nguy cơ mắc bệnh của bạn.)
The government announced a new fiscal policy to combat inflation. (Chính phủ đã công bố một chính sách tài khóa mới để chống lạm phát.)
Our company's fiscal year runs from July 1st to June 30th. (Năm tài chính của công ty chúng tôi bắt đầu từ ngày 1 tháng 7 đến ngày 30 tháng 6.)
The country is struggling with a large fiscal deficit. (Quốc gia này đang phải vật lộn với mức thâm hụt ngân sách lớn.)
The weather was awful, so we had to cancel the picnic. (Thời tiết thật tệ, nên chúng tôi đã phải hủy chuyến dã ngoại.)
I feel awful for yelling at you earlier. (Tôi cảm thấy thật tồi tệ vì đã la mắng bạn lúc nãy.)
The food at that restaurant tasted awful. (Đồ ăn ở nhà hàng đó có vị rất kinh khủng.)
She is a highly educated woman with a Ph.D. in physics. (Bà là một người phụ nữ có học vấn cao với bằng tiến sĩ vật lý.)
Based on the dark clouds, I made an educated guess that it was going to rain. (Dựa vào những đám mây đen, tôi đã đưa ra một phỏng đoán có cơ sở rằng trời sắp mưa.)
A well-educated population is crucial for a nation's development. (Trình độ dân trí cao là yếu tố thiết yếu cho sự phát triển của quốc gia.)
I seem to have misplaced my car keys. (Tôi dường như đã để quên chìa khóa xe ở đâu đó.)
The piano has 88 black and white keys. (Đàn dương cầm có 88 phím đen và trắng.)
Communication and trust are the keys to a strong relationship. (Giao tiếp và lòng tin là những chìa khóa cho một mối quan hệ bền chặt.)
The new law is a major step towards equality for all citizens. (Bộ luật mới là một bước tiến lớn hướng tới sự bình đẳng cho mọi công dân.)
They are fighting for racial equality and social justice. (Họ đang đấu tranh cho bình đẳng chủng tộc và công bằng xã hội.)
Gender equality is essential for a prosperous and modern society. (Bình đẳng giới là điều cần thiết cho một xã hội thịnh vượng và hiện đại.)
The new printer can create three-dimensional objects from a digital file. (Chiếc máy in mới có thể tạo ra các vật thể ba chiều từ một tệp kỹ thuật số.)
Her analysis of the problem was multi-dimensional, considering all possible aspects. (Phân tích của cô ấy về vấn đề này rất đa chiều, xem xét mọi khía cạnh có thể.)
The villain of the story was one-dimensional and lacked any compelling motivation. (Nhân vật phản diện của câu chuyện vừa hời hợt lại thiếu đi động cơ thuyết phục.)
The United Kingdom is a constitutional monarchy. (Vương quốc Anh là một quốc gia quân chủ lập hiến.)
Freedom of speech is a constitutional right guaranteed to all citizens. (Tự do ngôn luận là một quyền hiến định được đảm bảo cho mọi công dân.)
He began each day with a constitutional walk around the village. (Ông ấy bắt đầu mỗi ngày bằng một cuộc đi bộ thể dục quanh làng.)
I will see you next Thursday. (Tôi sẽ gặp bạn vào thứ Năm tới.)
The package is scheduled to arrive on Thursday. (Gói hàng dự kiến sẽ đến vào thứ Năm.)
We always have a special lunch at the office on Thursdays. (Chúng tôi luôn có một bữa trưa đặc biệt tại văn phòng vào các ngày thứ Năm.)
The new job will involve a lot of travel. (Công việc mới sẽ liên quan đến nhiều chuyến đi.)
We need to involve more people in the decision-making process. (Chúng ta cần thu hút thêm nhiều người tham gia vào quá trình ra quyết định.)
The accident involved three cars and a truck. (Vụ tai nạn liên quan đến ba ô tô và một xe tải.)
The universe is vast and seems eternal. (Vũ trụ rộng lớn và dường như là vĩnh cửu.)
She believed in an eternal life after death. (Cô ấy tin vào một cuộc sống vĩnh hằng sau khi chết.)
The memory of that day will be forever etched in my heart. (Ký ức về ngày hôm đó sẽ mãi mãi khắc sâu trong trái tim tôi.)
She is known for her unwavering integrity. (Cô ấy được biết đến với sự chính trực kiên định của mình.)
Maintaining professional integrity is crucial in this field. (Duy trì sự liêm chính nghề nghiệp là rất quan trọng trong lĩnh vực này.)
His integrity makes him a trustworthy leader. (Sự chính trực của anh ấy khiến anh ấy trở thành một nhà lãnh đạo đáng tin cậy.)
The TV screen is 55 inches wide. (Màn hình TV rộng 55 inch.)
He grew a couple of inches last year. (Anh ấy cao thêm vài inch vào năm ngoái.)
The rainfall measured three inches during the storm. (Lượng mưa đo được là ba inch trong cơn bão.)
The future is full of uncertainty. (Tương lai đầy rẫy sự không chắc chắn.)
The company's shares dropped due to market uncertainty. (Cổ phiếu của công ty giảm do sự không chắc chắn của thị trường.)
She felt a sense of uncertainty about her new job. (Cô ấy cảm thấy một sự không chắc chắn về công việc mới của mình.)
He had to drag the heavy box across the floor. (Anh ấy phải kéo lê cái hộp nặng ngang qua sàn nhà.)
The meeting started to drag on after two hours. (Cuộc họp bắt đầu lê thê sau hai giờ.)
You can drag and drop the image file here. (Bạn có thể kéo và thả tệp hình ảnh vào đây.)
The fight for liberty has been a recurring theme throughout history. (Cuộc đấu tranh giành tự do đã là một chủ đề lặp đi lặp lại xuyên suốt lịch sử.)
The Statue of Liberty stands as a beacon of hope and freedom. (Tượng Nữ thần Tự do đứng vững như một ngọn hải đăng của hy vọng và tự do.)
Every individual deserves the right to life, liberty, and the pursuit of happiness. (Mỗi cá nhân đều xứng đáng có quyền được sống, tự do và mưu cầu hạnh phúc.)
They often disagree on political issues. (Họ thường bất đồng về các vấn đề chính trị.)
They often disagree about political issues. (Họ thường bất đồng về các vấn đề chính trị.)
My sister is visiting us for the holidays. (Chị gái tôi đang đến thăm chúng tôi trong dịp lễ.)
They enjoy visiting new places during their travels. (Họ thích thăm những địa điểm mới trong các chuyến đi của mình.)
The visiting team played an excellent game yesterday. (Đội khách đã chơi một trận đấu xuất sắc ngày hôm qua.)
The dentist said my wisdom tooth was impacted. (Nha sĩ nói rằng răng khôn của tôi bị mọc ngầm.)
The local economy was severely impacted by the factory closure. (Nền kinh tế địa phương bị ảnh hưởng nghiêm trọng bởi việc đóng cửa nhà máy.)
The global supply chain was heavily impacted by the pandemic. (Chuỗi cung ứng toàn cầu bị ảnh hưởng nặng nề bởi đại dịch.)
Ensuring long-term sustainability is crucial for our planet's future. (Đảm bảo sự bền vững dài hạn là điều cốt yếu cho tương lai hành tinh chúng ta.)
Many businesses are now focusing on sustainability in their operations. (Nhiều doanh nghiệp hiện đang chú trọng tính bền vững trong hoạt động của mình.)
Many businesses are currently focusing on sustainability in their operations. (Nhiều doanh nghiệp hiện đang tập trung vào tính bền vững trong hoạt động của mình.)
I read the newspaper every morning with my coffee. (Tôi đọc báo mỗi sáng cùng cà phê.)
She bought a newspaper from the convenience store. (Cô ấy mua một tờ báo từ cửa hàng tiện lợi.)
The newspaper reported on the local elections. (Tờ báo đã đưa tin về cuộc bầu cử địa phương.)
The washing machine spins the clothes dry. (Máy giặt quay vắt quần áo cho khô.)
Do you want to go for a spin in my new car? (Bạn có muốn đi dạo một vòng bằng chiếc xe mới của tôi không?)
The politician tried to spin the news in his favor. (Chính trị gia cố gắng bóp méo tin tức theo hướng có lợi cho mình.)
She was so tired she could barely keep her eyes open. (Cô ấy mệt đến mức gần như không thể mở mắt được.)
He barely made it to the train before it left. (Anh ấy vừa kịp lên tàu trước khi nó rời đi.)
The tiny print was barely readable without a magnifying glass. (Chữ in nhỏ đến mức hầu như không thể đọc được nếu không có kính lúp.)
She showed great compassion for the victims of the natural disaster. (Cô ấy thể hiện lòng trắc ẩn sâu sắc đối với các nạn nhân của thảm họa thiên nhiên.)
His compassion led him to dedicate his life to helping the less fortunate. (Lòng trắc ẩn của anh ấy đã khiến anh ấy dành cả đời mình để giúp đỡ những người kém may mắn.)
Compassion is a fundamental human quality that fosters understanding and empathy. (Lòng trắc ẩn là một phẩm chất cơ bản của con người, giúp thúc đẩy sự thấu hiểu và đồng cảm.)
The company experienced rapid growth in the last quarter. (Công ty đã trải qua sự tăng trưởng nhanh chóng trong quý vừa qua.)
She made rapid progress in learning the new language. (Cô ấy đã đạt được tiến bộ nhanh chóng trong việc học ngôn ngữ mới.)
Emergency services provided a rapid response to the accident. (Các dịch vụ khẩn cấp đã phản ứng nhanh chóng với vụ tai nạn.)
The concert lighting was spectacular, with lasers and smoke. (Hệ thống chiếu sáng buổi hòa nhạc thật ngoạn mục, với tia laze và khói.)
Soft lighting can make a room feel more cozy and inviting. (Ánh sáng dịu nhẹ có thể làm cho căn phòng trở nên ấm cúng và hấp dẫn hơn.)
We need better lighting in the kitchen for cooking. (Chúng tôi cần ánh sáng tốt hơn trong bếp để nấu ăn.)
It's important to establish a good study routine. (Điều quan trọng là phải thiết lập một thói quen học tập tốt.)
She tries not to let her life fall into a boring routine. (Cô ấy cố gắng không để cuộc sống của mình rơi vào một thói quen nhàm chán.)
The company released new versions of its popular software. (Công ty đã phát hành các phiên bản mới của phần mềm phổ biến của mình.)
I've heard several different versions of what happened that night. (Tôi đã nghe một vài phiên bản khác nhau về những gì đã xảy ra đêm đó.)
This classic novel has been adapted into many film versions. (Cuốn tiểu thuyết kinh điển này đã được chuyển thể thành nhiều phiên bản phim.)
The car's leather interior is very luxurious. (Nội thất da của chiếc xe rất sang trọng.)
We hired a designer to decorate the interior of our house. (Chúng tôi đã thuê một nhà thiết kế để trang trí nội thất cho ngôi nhà của mình.)
The interior walls need a fresh coat of paint. (Các bức tường bên trong cần một lớp sơn mới.)
The cause of the accident is still unknown. (Nguyên nhân của vụ tai nạn vẫn chưa được xác định.)
He was a completely unknown actor before this film. (Anh ấy là một diễn viên hoàn toàn vô danh trước bộ phim này.)
Many people have a fear of the unknown. (Nhiều người có nỗi sợ hãi đối với những điều chưa biết.)
The aid workers provided food and shelter to the victims of the earthquake. (Các nhân viên cứu trợ đã cung cấp thức ăn và nơi ở cho các nạn nhân của trận động đất.)
She portrayed herself as the victim, but she was equally to blame. (Cô ấy tỏ ra mình là nạn nhân, nhưng thực chất cũng có lỗi ngang bằng.)
He was a victim of his own success, unable to cope with the fame. (Anh ấy là nạn nhân của chính sự thành công của mình, không thể đối phó với sự nổi tiếng.)
She suffers from severe headaches. (Cô ấy bị những cơn đau đầu dữ dội.)
The company suffered heavy losses last quarter. (Công ty đã chịu tổn thất nặng nề vào quý trước.)
I can't bear to see children suffer. (Tôi không thể chịu được khi thấy trẻ em phải đau khổ.)
She had great difficulty understanding the instructions. (Cô ấy gặp rất nhiều khó khăn trong việc hiểu lời hướng dẫn.)
The main difficulty is the lack of funding for the project. (Khó khăn chính là việc thiếu kinh phí cho dự án.)
He did manage to finish the race, albeit with great difficulty. (Anh ấy đã hoàn thành được cuộc đua, dù vô cùng vất vả.)
The long-term stress had a significant psychological effect on him. (Căng thẳng kéo dài đã có ảnh hưởng tâm lý đáng kể đối với anh ấy.)
It's important to take care of your psychological well-being. (Việc chăm sóc sức khỏe tâm lý của bạn là rất quan trọng.)
Thank you for participating in our survey. (Cảm ơn bạn đã tham gia vào cuộc khảo sát của chúng tôi.)
Many countries are participating in the Olympic Games this year. (Nhiều quốc gia đang tham gia Thế vận hội Olympic năm nay.)
Everyone participating in the project must attend the meeting. (Tất cả mọi người tham gia vào dự án đều phải tham dự cuộc họp.)
The plane made a smooth landing despite the bad weather. (Máy bay đã hạ cánh êm ái bất chấp thời tiết xấu.)
She left her shoes on the landing at the top of the stairs. (Cô ấy để giày trên chiếu nghỉ ở đầu cầu thang.)
After months of searching, he finally succeeded in landing a new job. (Sau nhiều tháng tìm kiếm, cuối cùng anh ấy đã thành công trong việc có được một công việc mới.)
The world's population is now over eight billion. (Dân số thế giới hiện đã hơn tám tỷ người.)
He made billions of dollars in the tech industry. (Anh ấy đã kiếm được hàng tỷ đô la trong ngành công nghệ.)
The airline's logo is painted on the tail of the plane. (Logo của hãng hàng không được sơn trên phần đuôi máy bay.)
The private investigator was hired to tail the cheating husband. (Vị thám tử tư được thuê để bám đuôi người chồng ngoại tình.)
Scores of people lined up for the new product launch. (Rất nhiều người đã xếp hàng để chờ ra mắt sản phẩm mới.)
He checks the football scores every morning. (Anh ấy kiểm tra tỷ số bóng đá mỗi buổi sáng.)
She scores the highest marks in the class on the final exam. (Cô ấy đạt điểm cao nhất lớp trong bài thi cuối kỳ.)
Their car is new, but ours is more reliable. (Xe của họ thì mới, nhưng xe của chúng tôi thì đáng tin cậy hơn.)
Is this your coat or ours? (Đây là áo khoác của bạn hay của chúng tôi?)
The responsibility to protect the environment is ours. (Trách nhiệm bảo vệ môi trường là của chúng ta.)
The company plans to integrate the new software into its existing system. (Công ty có kế hoạch tích hợp phần mềm mới vào hệ thống hiện có.)
It can be difficult for immigrants to integrate into a new community. (Người nhập cư có thể gặp khó khăn trong việc hòa nhập vào một cộng đồng mới.)
We need to integrate the sales and marketing teams to improve efficiency. (Chúng ta cần hợp nhất các đội ngũ bán hàng và tiếp thị để nâng cao hiệu quả.)
There's a clear distinction between being assertive and being aggressive. (Có một sự khác biệt rõ ràng giữa việc quyết đoán và việc hung hăng.)
She graduated from the university with distinction. (Cô ấy đã tốt nghiệp đại học với tấm bằng xuất sắc.)
He is a writer of great distinction. (Ông ấy là một nhà văn rất lỗi lạc.)
After a long career, he is looking forward to his retirement. (Sau nhiều năm cống hiến, ông ấy mong chờ ngày được nghỉ hưu.)
The small town and its surrounding villages are very peaceful. (Thị trấn nhỏ và các ngôi làng xung quanh rất yên bình.)
The police set up a cordon around the building and the surrounding area. (Cảnh sát đã thiết lập một hàng rào quanh tòa nhà và khu vực lân cận.)
We were captivated by the breathtaking scenery during our hike. (Chúng tôi đã bị hớp hồn bởi cảnh sắc ngoạn mục trong chuyến đi bộ đường dài.)
You need to register for the course before the deadline. (Bạn cần đăng ký khóa học trước hạn chót.)
A look of surprise registered on her face. (Một vẻ ngạc nhiên hiện rõ trên khuôn mặt cô ấy.)
The cashier opened the register to give him his change. (Nhân viên thu ngân mở máy tính tiền để thối tiền cho anh ấy.)
She is searching for her lost keys. (Cô ấy đang tìm chìa khóa bị mất của mình.)
He spent all morning searching online for information. (Anh ấy đã dành cả buổi sáng để tìm kiếm thông tin trực tuyến.)
The police are searching the area for clues. (Cảnh sát đang tìm kiếm manh mối trong khu vực.)
We need to stock up on essential supplies for the camping trip. (Chúng ta cần dự trữ đồ dùng thiết yếu cho chuyến đi cắm trại.)
The company ordered new office supplies, including pens, paper, and staplers. (Công ty đã đặt mua văn phòng phẩm mới, bao gồm bút, giấy và dập ghim.)
Emergency supplies like food and water were quickly distributed to the flood victims. (Đồ dùng khẩn cấp như thực phẩm và nước đã nhanh chóng được phân phát cho các nạn nhân lũ lụt.)
Drug addiction can destroy lives and families. (Nghiện ma túy có thể hủy hoại cuộc sống và gia đình.)
She sought professional help to overcome her gambling addiction. (Cô ấy đã tìm kiếm sự giúp đỡ chuyên nghiệp để vượt qua chứng nghiện cờ bạc của mình.)
His addiction to social media made him constantly check his phone. (Chứng nghiện mạng xã hội khiến anh ấy liên tục kiểm tra điện thoại.)
The sudden news of her departure was a huge shock to us all. (Tin tức đột ngột về việc cô ấy ra đi là một cú sốc lớn đối với tất cả chúng tôi.)
His unexpected confession shocked everyone in the room. (Lời thú tội bất ngờ của anh ấy đã làm mọi người trong phòng sốc.)
She was in a state of shock after witnessing the accident. (Cô ấy đã ở trong tình trạng sốc sau khi chứng kiến vụ tai nạn.)
My sisters and I often go shopping together. (Các chị em gái của tôi và tôi thường đi mua sắm cùng nhau.)
She has two younger sisters. (Cô ấy có hai em gái.)
The three sisters always support each other. (Ba chị em gái luôn hỗ trợ lẫn nhau.)
The art exhibition features works by local artists. (Triển lãm nghệ thuật trưng bày các tác phẩm của các nghệ sĩ địa phương.)
We plan to visit the science exhibition next week. (Chúng tôi dự định đến thăm triển lãm khoa học vào tuần tới.)
The museum is hosting a new exhibition on ancient civilizations. (Bảo tàng đang tổ chức một triển lãm mới về các nền văn minh cổ đại.)
He's been going through a rough patch at work lately. (Gần đây anh ấy đang trải qua một giai đoạn khó khăn trong công việc.)
Could you give me a ballpark figure for the cost? (Bạn có thể cho tôi một ước tính sơ bộ về chi phí được không?)
The police finally captured the suspect after a long chase. (Cảnh sát cuối cùng đã bắt giữ nghi phạm sau một cuộc truy đuổi dài.)
The camera captured the exact moment the bird took flight. (Máy ảnh đã ghi lại khoảnh khắc chính xác khi con chim cất cánh.)
Her captivating story captured the imagination of everyone in the room. (Câu chuyện lôi cuốn của cô ấy đã khơi dậy trí tưởng tượng của mọi người trong phòng.)
The continuous rain made it difficult to go outside. (Cơn mưa liên tục khiến việc ra ngoài trở nên khó khăn.)
Continuous effort is key to achieving your goals. (Nỗ lực không ngừng là chìa khóa để đạt được mục tiêu của bạn.)
The machine requires a continuous power supply to function properly. (Cỗ máy yêu cầu nguồn điện liên tục để hoạt động đúng cách.)
The report is divided into three main sections. (Báo cáo được chia thành ba phần chính.)
You can find fresh produce in the first section of the supermarket. (Bạn có thể tìm thấy rau củ tươi sống ở khu vực đầu tiên của siêu thị.)
The museum has dedicated sections for ancient art and modern art. (Bảo tàng có các khu vực dành riêng cho nghệ thuật cổ đại và nghệ thuật hiện đại.)
He always wears a baseball cap when he goes out. (Anh ấy luôn đội một chiếc mũ lưỡi trai khi ra ngoài.)
Please put the cap back on the bottle tightly. (Làm ơn đậy chặt nắp chai lại.)
The company decided to put a cap on executive salaries. (Công ty quyết định đặt ra mức trần cho lương của các giám đốc điều hành.)
The FBI is investigating the recent cyberattack. (Cục Điều tra Liên bang đang điều tra vụ tấn công mạng gần đây.)
An FBI agent briefed the press on the ongoing situation. (Một đặc vụ FBI đã thông báo cho báo chí về tình hình đang diễn ra.)
The FBI's headquarters are located in Washington, D.C. (Trụ sở chính của Cục Điều tra Liên bang nằm ở Washington, D.C.)
The baby is sleeping soundly in her crib. (Em bé đang ngủ say trong nôi của mình.)
I need a new sleeping bag for the camping trip. (Tôi cần một túi ngủ mới cho chuyến đi cắm trại.)
He often has trouble sleeping at night. (Anh ấy thường khó ngủ vào ban đêm.)
She is highly motivated to succeed in her new role. (Cô ấy rất có động lực để thành công trong vai trò mới của mình.)
His decision was motivated by a desire for personal growth. (Quyết định của anh ấy được thúc đẩy bởi mong muốn phát triển bản thân.)
The team felt motivated after receiving positive feedback from their manager. (Cả đội cảm thấy có động lực sau khi nhận được phản hồi tích cực từ người quản lý của họ.)
The company offered a reward for finding the lost dog. (Công ty đã đưa ra phần thưởng cho việc tìm thấy chú chó bị lạc.)
Your hard work will be rewarded. (Sự chăm chỉ của bạn sẽ được đền đáp.)
Parents often reward children for good behavior. (Cha mẹ thường thưởng cho con cái khi chúng cư xử tốt.)
The building's structural design is very innovative. (Thiết kế kết cấu của tòa nhà rất sáng tạo.)
Engineers found several structural flaws in the old bridge. (Các kỹ sư đã tìm thấy một số lỗi kết cấu trong cây cầu cũ.)
The company announced a structural change in its management. (Công ty đã công bố một thay đổi cơ cấu trong ban quản lý của mình.)
What are the basic requirements for this job? (Những yêu cầu cơ bản cho công việc này là gì?)
All students must meet the university's academic requirements to graduate. (Tất cả sinh viên phải đáp ứng các yêu cầu học tập của trường đại học để tốt nghiệp.)
The new software must satisfy all the client's requirements. (Phần mềm mới phải đáp ứng tất cả các yêu cầu của khách hàng.)
The delivery van just pulled up. (Chiếc xe van giao hàng vừa dừng lại.)
They rented a van for their road trip. (Họ thuê một chiếc xe van cho chuyến đi đường dài của mình.)
We need a bigger van to transport all this equipment. (Chúng ta cần một chiếc xe van lớn hơn để vận chuyển tất cả thiết bị này.)
The team joined the new professional league this season. (Đội bóng đã gia nhập giải đấu chuyên nghiệp mới mùa này.)
He felt she was beautiful and intelligent, completely out of his league. (Anh ấy cảm thấy cô ấy xinh đẹp và thông minh, hoàn toàn không cùng đẳng cấp với anh.)
When it comes to customer service, that company is in a league of its own. (Khi nói đến dịch vụ khách hàng, công ty đó ở một đẳng cấp riêng.)
Water is vital for all living things. (Nước rất cần thiết cho mọi sinh vật sống.)
Effective communication is vital for a successful team. (Giao tiếp hiệu quả là yếu tố sống còn đối với một đội ngũ thành công.)
It's vital that we act quickly to prevent further damage. (Điều cực kỳ quan trọng là chúng ta phải hành động nhanh chóng để ngăn chặn thiệt hại thêm.)
The average household consists of four people. (Một hộ gia đình trung bình bao gồm bốn người.)
She is responsible for managing the household expenses. (Cô ấy chịu trách nhiệm quản lý các chi tiêu trong gia đình.)
Many household products can be bought at this supermarket. (Nhiều sản phẩm gia dụng có thể được mua tại siêu thị này.)
Marine pollution is a serious threat to our oceans. (Ô nhiễm biển là một mối đe dọa nghiêm trọng đối với các đại dương của chúng ta.)
He is a marine biologist who studies dolphins. (Anh ấy là một nhà sinh vật học biển chuyên nghiên cứu về cá heo.)
Her brother joined the marines after finishing high school. (Anh trai cô ấy đã gia nhập lực lượng lính thủy đánh bộ sau khi tốt nghiệp trung học.)
The pressure on the government is mounting. (Áp lực lên chính phủ đang ngày càng gia tăng.)
She gracefully mounted the horse and prepared to ride. (Cô ấy duyên dáng leo lên lưng ngựa và chuẩn bị phi.)
They plan to mount a new marketing campaign next month. (Họ dự định tổ chức một chiến dịch tiếp thị mới vào tháng tới.)
The city's streets are laid out in a grid pattern. (Các con đường của thành phố được bố trí theo dạng lưới.)
A massive power outage affected the entire electrical grid. (Một sự cố mất điện lớn đã ảnh hưởng đến toàn bộ lưới điện.)
He decided to live off the grid, relying on solar panels for energy. (Anh ấy quyết định sống không phụ thuộc vào mạng lưới điện, dựa vào các tấm pin mặt trời để lấy năng lượng.)
He arrived later than usual. (Anh ấy đến muộn hơn thường lệ.)
Is this the usual procedure? (Đây có phải là thủ tục thông thường không?)
She sat in her usual seat by the window. (Cô ấy ngồi vào chỗ ngồi quen thuộc của mình cạnh cửa sổ.)
It was not my intent to cause any trouble. (Ý định của tôi không phải là gây ra bất kỳ rắc rối nào.)
He entered the building with the intent of stealing the documents. (Anh ta vào tòa nhà với ý định đánh cắp tài liệu.)
She was intent on finishing her project by the deadline. (Cô ấy quyết tâm hoàn thành dự án của mình trước thời hạn.)
Don't cry, everything will be okay. (Đừng khóc, mọi chuyện rồi sẽ ổn thôi.)
The sad movie made her cry. (Bộ phim buồn đã làm cô ấy khóc.)
He cried for help, but no one could hear him. (Anh ấy đã kêu cứu, nhưng không ai có thể nghe thấy anh.)
Don't blame me for your own mistakes. (Đừng đổ lỗi cho tôi vì những sai lầm của chính bạn.)
He took the blame for the team's failure. (Anh ấy đã nhận trách nhiệm về thất bại của cả đội.)
The police have attributed the accident to the driver's carelessness. (Cảnh sát nhận định nguyên nhân vụ tai nạn là do sự bất cẩn của người lái xe.)
The country's political stability is a major concern for foreign investors. (Sự ổn định chính trị của đất nước là mối quan tâm lớn đối với các nhà đầu tư nước ngoài.)
Engineers are testing the stability of the new bridge design. (Các kỹ sư đang kiểm tra độ ổn định của thiết kế cây cầu mới.)
He is looking for a job that offers more stability and security. (Anh ấy đang tìm kiếm một công việc mang lại sự ổn định và an toàn hơn.)
The network consists of several interconnected nodes. (Mạng lưới bao gồm nhiều nút được kết nối với nhau.)
The doctor checked for swollen lymph nodes in his neck. (Bác sĩ đã kiểm tra các hạch bạch huyết bị sưng ở cổ của anh ấy.)
A new leaf will sprout from the node on the plant's stem. (Một chiếc lá mới sẽ nảy mầm từ đốt trên thân cây.)
The disappearance of the famous painting remains a mystery. (Sự biến mất của bức tranh nổi tiếng vẫn còn là một điều bí ẩn.)
She loves to read mystery novels on rainy days. (Cô ấy thích đọc tiểu thuyết trinh thám vào những ngày mưa.)
There was an air of mystery about him that intrigued her. (Vẻ bí ẩn toát ra từ anh đã khơi gợi trí tò mò của cô.)
The new software is designed to increase office productivity. (Phần mềm mới được thiết kế để tăng năng suất văn phòng.)
Getting enough sleep is essential for maintaining high productivity throughout the day. (Ngủ đủ giấc là điều cần thiết để duy trì năng suất cao trong suốt cả ngày.)
The country's economic growth is closely linked to its labor productivity. (Tăng trưởng kinh tế của đất nước có liên quan chặt chẽ đến năng suất lao động.)
It is important to preserve our cultural heritage for future generations. (Việc bảo tồn di sản văn hóa của chúng ta cho các thế hệ tương lai là rất quan trọng.)
The ancient city is a UNESCO World Heritage site. (Thành phố cổ này là một Di sản Thế giới được UNESCO công nhận.)
She is very proud of her Vietnamese heritage. (Cô ấy rất tự hào về di sản Việt Nam của mình.)
The company operates within a strict regulatory framework. (Công ty hoạt động trong một khuôn khổ pháp lý nghiêm ngặt.)
Businesses need to stay updated on the latest regulatory changes. (Các doanh nghiệp cần cập nhật những thay đổi mới nhất về quy định.)
The new law imposes stricter regulatory controls on the banking industry. (Luật mới áp đặt các biện pháp kiểm soát chặt chẽ hơn đối với ngành ngân hàng.)
The company's commitment to diversity and inclusion has created a better work environment. (Cam kết của công ty về sự đa dạng và hòa nhập đã tạo ra một môi trường làm việc tốt hơn.)
The inclusion of his name on the guest list was a last-minute decision. (Việc thêm tên anh ấy vào danh sách khách mời là một quyết định vào phút chót.)
This report synthesizes all relevant data from the past year. (Báo cáo này tổng hợp toàn bộ dữ liệu liên quan trong năm qua.)
The new online ads are targeted at young consumers. (Các quảng cáo trực tuyến mới nhắm vào đối tượng người tiêu dùng trẻ.)
The criticism was targeted at the new manager. (Lời chỉ trích nhắm vào người quản lý mới.)
Targeted therapy is a cancer treatment that attacks specific cancer cells. (Liệu pháp nhắm trúng đích là một phương pháp điều trị ung thư tấn công các tế bào ung thư cụ thể.)
Her smile can light up a room. (Nụ cười của cô ấy có thể thắp sáng cả căn phòng.)
He greeted me with a warm smile. (Anh ấy chào tôi bằng một nụ cười ấm áp.)
When you smile, the whole world smiles with you. (Khi bạn mỉm cười, cả thế giới mỉm cười với bạn.)
I dream of visiting Italy someday. (Tôi mơ ước được đến thăm Ý vào một ngày nào đó.)
Italian food is famous all over the world. (Ẩm thực Ý nổi tiếng khắp thế giới.)
The team's productivity improved once they understood the group dynamics. (Năng suất của đội đã cải thiện một khi họ hiểu được động lực nhóm.)
Understanding the market dynamics is crucial for any successful business. (Hiểu rõ động lực thị trường là rất quan trọng đối với bất kỳ doanh nghiệp thành công nào.)
The new manager quickly adapted to the office dynamics. (Người quản lý mới nhanh chóng thích nghi với môi trường làm việc của văn phòng.)
The National Assembly passed a new law yesterday. (Quốc hội đã thông qua một đạo luật mới vào ngày hôm qua.)
The assembly of the new bicycle was surprisingly easy. (Việc lắp ráp chiếc xe đạp mới bất ngờ dễ dàng.)
All students gathered in the hall for the morning assembly. (Tất cả học sinh tập trung tại hội trường cho buổi tập trung buổi sáng.)
She suffered a minor injury in the accident. (Cô ấy bị một chấn thương nhẹ trong vụ tai nạn.)
It's important to prevent injury when playing sports. (Điều quan trọng là phải phòng ngừa chấn thương khi chơi thể thao.)
He is recovering well from his knee injury. (Anh ấy đang hồi phục tốt sau chấn thương đầu gối.)
We arrived at the airport early to check in our luggage. (Chúng tôi đến sân bay sớm để làm thủ tục ký gửi hành lý.)
Could you please drop me off at the airport? (Bạn có thể vui lòng đưa tôi đến sân bay được không?)
The new international airport is much larger than the old one. (Sân bay quốc tế mới lớn hơn nhiều so với sân bay cũ.)
The doctor explained the surgical procedure in detail. (Bác sĩ đã giải thích chi tiết về quy trình phẫu thuật.)
Please follow the correct procedure for logging a complaint. (Vui lòng tuân thủ đúng quy trình để gửi khiếu nại.)
The new safety procedure will be implemented next week. (Quy trình an toàn mới sẽ được áp dụng vào tuần tới.)
The police interviewed a key witness. (Cảnh sát đã phỏng vấn một nhân chứng quan trọng.)
Many people witnessed the accident. (Nhiều người đã chứng kiến vụ tai nạn.)
You need a witness to sign this legal document. (Bạn cần một nhân chứng để ký vào tài liệu pháp lý này.)
The pace of life in the city is much faster than in the countryside. (Nhịp sống ở thành phố nhanh hơn nhiều so với ở nông thôn.)
She started to pace the room, waiting for the phone call. (Cô ấy bắt đầu đi đi lại lại trong phòng, chờ cuộc điện thoại.)
We need to set a realistic pace for this project to avoid burnout. (Chúng ta cần đặt ra một tốc độ thực tế cho dự án này để tránh kiệt sức.)
I tried to convince her that I was telling the truth. (Tôi đã cố gắng thuyết phục cô ấy rằng tôi đang nói sự thật.)




`;

/**
 * Phân tích chuỗi dữ liệu ví dụ thành một mảng các đối tượng có cấu trúc.
 * @param text - Chuỗi văn bản thô chứa các ví dụ.
 * @returns Một mảng các đối tượng ExampleSentence.
 */
export const parseExampleSentences = (text: string): ExampleSentence[] => {
  const lines = text.trim().split('\n');
  const examples: ExampleSentence[] = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    const match = line.match(/(.*)\s*\((.*)\)/);
    if (match && match[1] && match[2]) {
      examples.push({
        english: match[1].trim(),
        vietnamese: match[2].trim().replace(/\.$/, ''), // Bỏ dấu chấm ở cuối nếu có
      });
    } else {
      // Fallback nếu dòng không đúng định dạng
      examples.push({
        english: line.trim(),
        vietnamese: 'Bản dịch không có sẵn',
      });
    }
  }

  return examples;
};

// Xuất dữ liệu đã được phân tích để các component khác có thể sử dụng trực tiếp
export const exampleData: ExampleSentence[] = parseExampleSentences(exampleSentencesText);

// --- END OF FILE example-data.ts ---

