// --- START OF FILE example-data.ts ---

export interface ExampleSentence {
  english: string;
  vietnamese: string;
}

// Dữ liệu thô chứa các câu ví dụ và bản dịch
const exampleSentencesText = `

The river is the main source of water for the town. (Dòng sông là nguồn nước chính cho thị trấn.)
Solar energy is a renewable source of power. (Năng lượng mặt trời là một nguồn năng lượng tái tạo.)
The company is looking for a new source of raw materials. (Công ty đang tìm kiếm một nguồn nguyên liệu thô mới.)
Health insurance is a must for all employees. (Bảo hiểm sức khỏe là điều bắt buộc đối với tất cả nhân viên.)
The car was totalled, but luckily she had insurance. (Chiếc xe đã bị hỏng hoàn toàn, nhưng may mắn là cô ấy đã có bảo hiểm.)
We offer a range of insurance services to our clients. (Chúng tôi cung cấp một loạt các dịch vụ bảo hiểm cho khách hàng của mình.)
The couple had an argument about spending money. (Cặp đôi đã tranh cãi về việc tiêu tiền.)
His main argument is supported by recent studies. (Luận điểm chính của anh ấy được hỗ trợ bởi các nghiên cứu gần đây.)
They got into an argument over politics. (Họ đã tranh cãi về chính trị.)
Social media has a big influence on young people. (Mạng xã hội có ảnh hưởng lớn đối với giới trẻ.)
He has a lot of influence in the company. (Anh ấy có nhiều ảnh hưởng trong công ty.)
Her parents had a strong influence on her career choice. (Bố mẹ cô ấy có ảnh hưởng mạnh mẽ đến sự lựa chọn nghề nghiệp của cô ấy.)
The band is planning to release a new album next month. (Ban nhạc đang lên kế hoạch phát hành một album mới vào tháng tới.)
After years of research, the scientist is ready to release his findings to the public. (Sau nhiều năm nghiên cứu, nhà khoa học sẵn sàng công bố phát hiện của mình cho công chúng.)
The movie is scheduled for release during the holiday season. (Bộ phim được lên lịch phát hành trong mùa lễ hội.)
The stadium has a seating capacity of 50,000. (Sân vận động có sức chứa 50.000 chỗ ngồi.)
The battery has a capacity of 2000 milliampere-hours. (Pin có dung lượng 2000 miliampe-giờ.)
The memory card has a storage capacity of 128 gigabytes. (Thẻ nhớ có dung lượng lưu trữ 128 gigabyte.)
The Senate passed the bill with a large majority. (Thượng viện đã thông qua dự luật với đa số lớn.)
He announced his candidacy for the U.S. Senate. (Anh ấy đã công bố ứng cử vào Thượng viện Mỹ.)
The proposal needs approval from both the House and the Senate. (Đề xuất cần được sự chấp thuận từ cả Hạ viện và Thượng viện.)
The earthquake caused massive damage to the city. (Trận động đất đã gây ra thiệt hại lớn cho thành phố.)
She received massive support from her fans. (Cô ấy đã nhận được sự ủng hộ lớn từ người hâm mộ.)
The company is undertaking a massive project. (Công ty đang tiến hành một dự án lớn.)
He picked up a stick to defend himself. (Anh ấy nhặt một cây gậy để tự vệ.)
He used a stick to poke the fire. (Anh ấy dùng một cây gậy để khều lửa.)
She used a walking stick on her hike. (Cô ấy đã sử dụng một cây gậy khi đi bộ đường dài.)
He lives in the downtown district. (Anh ấy sống ở khu vực trung tâm thành phố.)
The school district is implementing new policies. (Khu vực trường học đang thực hiện các chính sách mới.)
This district is known for its vibrant nightlife. (Khu vực này nổi tiếng với cuộc sống về đêm sôi động.)
The project went over budget. (Dự án đã vượt quá ngân sách.)
We need to cut our monthly budget. (Chúng ta cần cắt giảm ngân sách hàng tháng của mình.)
The government is preparing the annual budget. (Chính phủ đang chuẩn bị ngân sách hàng năm.)
We need to measure the room before buying new furniture. (Chúng ta cần đo căn phòng trước khi mua đồ nội thất mới.)
Measure the distance between the two points. (Đo khoảng cách giữa hai điểm.)
This ruler can measure up to 30 centimeters. (Cái thước này có thể đo lên đến 30 centimet.)
Be careful when you cross the street. (Hãy cẩn thận khi bạn băng qua đường.)
The idea didn't even cross my mind. (Ý tưởng đó thậm chí không hề xuất hiện trong đầu tôi.)
Cross off the names of the guests who have confirmed they are not coming. (Gạch tên của những vị khách đã xác nhận là họ sẽ không đến.)
The central theme of the book is love and forgiveness. (Chủ đề trung tâm của cuốn sách là tình yêu và sự tha thứ.)
He lives in a central location, convenient for all. (Anh ấy sống ở một vị trí trung tâm, thuận tiện cho tất cả mọi người.)
Central heating is a common feature in these homes. (Sưởi trung tâm là một tính năng phổ biến trong những ngôi nhà này.)
She was proud of her children's achievements. (Cô ấy tự hào về thành tích của con mình.)
He stood tall and proud, despite the challenges. (Anh ấy đứng thẳng và tự hào, bất chấp những thách thức.)
They are proud to serve their community. (Họ tự hào phục vụ cộng đồng của mình.)
Honesty is the core value of our company. (Trung thực là giá trị cốt lõi của công ty chúng tôi.)
The core of the problem lies in communication issues. (Cốt lõi của vấn đề nằm ở các vấn đề về giao tiếp.)
An apple's core contains seeds. (Lõi của quả táo chứa hạt.)
She was elected as the sheriff of the county. (Cô ấy đã được bầu làm cảnh sát trưởng của hạt.)
The county fair is held every summer. (Hội chợ hạt được tổ chức mỗi mùa hè.)
Our library system serves the entire county. (Hệ thống thư viện của chúng tôi phục vụ toàn bộ hạt.)
This species of bird is known for its colorful plumage. (Loài chim này được biết đến với bộ lông sặc sỡ.)
Several species are endangered due to habitat destruction. (Một số loài đang bị đe dọa do phá hủy môi trường sống.)
Scientists discovered a new species in the rainforest. (Các nhà khoa học đã phát hiện một loài mới trong rừng mưa.)
The conditions of the contract are clear and binding. (Các điều kiện của hợp đồng là rõ ràng và có tính ràng buộc.)
They had to work in harsh conditions. (Họ phải làm việc trong điều kiện khắc nghiệt.)
The road conditions are poor due to the snow. (Điều kiện đường xá kém do tuyết.)
She felt a touch on her shoulder. (Cô ấy cảm thấy một cái chạm trên vai mình.)
Don't touch the wet paint. (Đừng chạm vào sơn ướt.)
She has a gentle touch with flowers. (Cô ấy rất nhẹ tay với hoa.)
The mass of the sun is incredibly large. (Khối lượng của mặt trời rất lớn.)
A mass of people attended the concert. (Một đám đông người đã tham dự buổi hòa nhạc.)
The product is sold at mass market retailers. (Sản phẩm được bán tại các cửa hàng bán lẻ đại chúng.)
The social media platform has millions of users. (Nền tảng mạng xã hội có hàng triệu người dùng.)
The train arrived at the platform. (Tàu đã đến sân ga.)
Developers can create applications on this platform. (Các nhà phát triển có thể tạo ứng dụng trên nền tảng này.)
Keep the picture straight on the wall. (Giữ bức tranh thẳng trên tường.)
I drove straight home after work. (Tôi lái xe thẳng về nhà sau khi tan làm.)
She has straight A's in all her subjects. (Cô ấy đạt toàn điểm A trong tất cả các môn học của mình.)
The doctor said it was a serious condition. (Bác sĩ nói đó là một tình trạng nghiêm trọng.)
We need to have a serious discussion about our future. (Chúng ta cần phải có một cuộc thảo luận nghiêm túc về tương lai của chúng ta.)
She is serious about her career in music. (Cô ấy rất nghiêm túc với sự nghiệp âm nhạc của mình.)
We encourage healthy eating habits. (Chúng tôi khuyến khích thói quen ăn uống lành mạnh.)
Teachers should encourage students to ask questions. (Giáo viên nên khuyến khích học sinh đặt câu hỏi.)
Positive feedback can encourage employees to perform better. (Phản hồi tích cực có thể khuyến khích nhân viên làm việc tốt hơn.)
The project is due next Monday. (Dự án đến hạn vào thứ Hai tới.)
Payment is due at the end of the month. (Việc thanh toán đến hạn vào cuối tháng.)
The success of the event was due to the hard work of volunteers. (Sự thành công của sự kiện là nhờ vào sự chăm chỉ của các tình nguyện viên.)
I have a fond memory of our vacation. (Tôi có một ký ức đẹp về kỳ nghỉ của chúng tôi.)
The computer has 8GB of RAM for memory. (Máy tính có 8GB RAM cho bộ nhớ.)
She has a great memory for names and faces. (Cô ấy có trí nhớ rất tốt về tên và khuôn mặt.)
The secretary scheduled a meeting for next week. (Thư ký đã lên lịch một cuộc họp cho tuần tới.)
He worked as a secretary before becoming a lawyer. (Anh ấy đã làm thư ký trước khi trở thành luật sư.)
The secretary took notes during the meeting. (Thư ký đã ghi chú trong cuộc họp.)
I caught a cold last week. (Tôi bị cảm lạnh tuần trước.)
The water was too cold for swimming. (Nước quá lạnh để bơi.)
Keep the food cold in the refrigerator. (Giữ thức ăn lạnh trong tủ lạnh.)
For instance, let's consider the company's growth last year. (Chẳng hạn, hãy xem xét sự tăng trưởng của công ty trong năm ngoái.)
This is an instance where patience is required. (Đây là một trường hợp cần có sự kiên nhẫn.)
In this instance, we should follow the guidelines. (Trong trường hợp này, chúng ta nên tuân theo hướng dẫn.)
The foundation of the house needs to be strong. (Nền móng của ngôi nhà cần phải vững chắc.)
She set up a foundation to help underprivileged children. (Cô ấy đã thành lập một quỹ từ thiện để giúp đỡ trẻ em kém may mắn.)
Trust is the foundation of a good relationship. (Tin tưởng là nền tảng của một mối quan hệ tốt đẹp.)
Please keep the clean and dirty clothes separate. (Vui lòng để riêng quần áo sạch và bẩn.)
They decided to separate after ten years of marriage. (Họ quyết định chia tay sau mười năm kết hôn.)
The teacher asked the students to work in separate groups. (Giáo viên yêu cầu học sinh làm việc trong các nhóm riêng biệt.)
We used a map to find our way to the hotel. (Chúng tôi đã sử dụng bản đồ để tìm đường đến khách sạn.)
The treasure map led them to an isolated island. (Bản đồ kho báu dẫn họ đến một hòn đảo biệt lập.)
You can see the country's topography on this map. (Bạn có thể thấy địa hình của đất nước trên bản đồ này.)
She added some ice to her drink to cool it down. (Cô ấy thêm một ít đá vào thức uống của mình để làm mát.)
The pond was covered with a thin layer of ice. (Hồ nước được phủ một lớp băng mỏng.)
They went ice skating on the frozen lake. (Họ đi trượt băng trên hồ đóng băng.)
The company issued a statement regarding the merger. (Công ty đã đưa ra một tuyên bố liên quan đến việc sáp nhập.)
His statement was recorded by the police. (Lời khai của anh ấy đã được cảnh sát ghi lại.)
The financial statement shows a profit for the last quarter. (Báo cáo tài chính cho thấy lợi nhuận trong quý vừa qua.)
The country is rich in natural resources. (Quốc gia này giàu tài nguyên thiên nhiên.)
He dreams of becoming rich and famous. (Anh ấy mơ ước trở nên giàu có và nổi tiếng.)
This dessert is too rich for my taste. (Món tráng miệng này quá ngậy so với khẩu vị của tôi.)
In his previous job, he was a teacher. (Trong công việc trước đây, anh ấy là một giáo viên.)
The previous owner of the house planted these trees. (Chủ nhân trước của ngôi nhà đã trồng những cây này.)
Refer to the previous chapter for more information. (Tham khảo chương trước để biết thêm thông tin.)
It's necessary to wear a helmet while riding a bike. (Việc đeo mũ bảo hiểm khi đi xe đạp là cần thiết.)
Please fill out all the necessary paperwork. (Vui lòng điền vào tất cả các giấy tờ cần thiết.)
Taking breaks is necessary for maintaining productivity. (Việc nghỉ ngơi là cần thiết để duy trì năng suất.)
He is studying engineering at the university. (Anh ấy đang học kỹ thuật tại đại học.)
The bridge is a marvel of modern engineering. (Cây cầu là một kỳ quan của kỹ thuật hiện đại.)
Environmental engineering focuses on improving natural environments. (Kỹ thuật môi trường tập trung vào việc cải thiện môi trường tự nhiên.)
The heat in the desert can be unbearable during the day. (Cái nóng ở sa mạc có thể không thể chịu đựng nổi vào ban ngày.)
Turn up the heat, it's too cold in here. (Tăng nhiệt độ lên, ở đây lạnh quá.)
The heat from the fire kept us warm. (Hơi ấm từ ngọn lửa đã giữ ấm cho chúng tôi.)
She donated her entire art collection to the museum. (Cô ấy đã quyên góp toàn bộ bộ sưu tập nghệ thuật của mình cho bảo tàng.)
The library has a vast collection of books. (Thư viện có một bộ sưu tập sách khổng lồ.)
His collection of vintage cars is impressive. (Bộ sưu tập xe cổ của anh ấy rất ấn tượng.)
The construction project will require a lot of skilled labor. (Dự án xây dựng sẽ yêu cầu nhiều lao động có tay nghề.)
She went into labor early in the morning. (Cô ấy bắt đầu chuyển dạ vào sáng sớm.)
Labor costs can significantly affect the price of goods. (Chi phí nhân công có thể ảnh hưởng đáng kể đến giá cả hàng hóa.)
The river's flow is strong after the rain. (Dòng chảy của sông rất mạnh sau cơn mưa.)
They are studying the flow of traffic in urban areas. (Họ đang nghiên cứu luồng giao thông ở khu vực đô thị.)
The flow of information is essential for decision making. (Dòng thông tin là thiết yếu cho việc ra quyết định.)
Please wipe the floor after spilling the water. (Vui lòng lau sàn sau khi làm đổ nước.)
He dropped his keys on the floor. (Anh ấy đã làm rơi chìa khóa xuống sàn.)
The book fell to the floor with a loud thud. (Quyển sách rơi xuống sàn nhà với một tiếng 'bịch' lớn.)
The restaurant offers a variety of dishes. (Nhà hàng phục vụ nhiều món ăn đa dạng.)
We need to add more variety to our daily routine. (Chúng ta cần thêm sự đa dạng vào thói quen hàng ngày.)
Genetic diversity is important for the variety of species. (Sự đa dạng di truyền rất quan trọng đối với sự đa dạng của các loài.)
Math is her favorite subject in school. (Toán là môn học yêu thích của cô ấy ở trường.)
He's doing his math homework. (Anh ấy đang làm bài tập về nhà môn toán.)
We need better math education to improve problem-solving skills. (Chúng ta cần giáo dục toán học tốt hơn để cải thiện kỹ năng giải quyết vấn đề.)
She booked a session with a personal trainer. (Cô ấy đã đặt một buổi tập với huấn luyện viên cá nhân.)
The next session of Congress begins in January. (Phiên họp tiếp theo của Quốc hội bắt đầu vào tháng Giêng.)
The therapy session helped him understand his emotions better. (Buổi trị liệu đã giúp anh ấy hiểu rõ hơn về cảm xúc của mình.)
Nuclear energy is a major source of electricity. (Năng lượng hạt nhân là một nguồn điện chính.)
The country is developing its nuclear capabilities. (Quốc gia này đang phát triển năng lực hạt nhân của mình.)
There are concerns about nuclear waste disposal. (Có những lo ngại về việc xử lý chất thải hạt nhân.)
She loves to roll down the hill in the park. (Cô ấy thích lăn xuống đồi trong công viên.)
Please roll the dough into a flat circle. (Vui lòng cán bột thành một hình tròn dẹt.)
The dice roll decides your move in the game. (Việc gieo xúc xắc quyết định nước đi của bạn trong trò chơi.)
The museum houses a collection of ancient artifacts. (Bảo tàng lưu giữ một bộ sưu tập các hiện vật cổ đại.)
We visited the art museum last weekend. (Chúng tôi đã thăm bảo tàng nghệ thuật vào cuối tuần trước.)
The museum is free on Sundays. (Bảo tàng miễn phí vé vào cửa các ngày Chủ nhật.)
The edition is limited to 500 copies. (Ấn bản này được giới hạn ở 500 bản.)
We have limited time to complete this project. (Chúng ta có thời gian hạn chế để hoàn thành dự án này.)
Resources are limited, so we must use them wisely. (Nguồn lực có hạn, vì vậy chúng ta phải sử dụng chúng một cách khôn ngoan.)
The constant noise from the construction site is annoying. (Tiếng ồn liên tục từ công trường xây dựng rất khó chịu.)
She is in constant communication with her team. (Cô ấy liên lạc liên tục với đội của mình.)
The speed of light is a constant in physics. (Tốc độ ánh sáng là một hằng số trong vật lý.)
The temperature dropped significantly overnight. (Nhiệt độ giảm đáng kể qua đêm.)
Please check the water temperature before bathing the baby. (Vui lòng kiểm tra nhiệt độ nước trước khi tắm cho em bé.)
The average room temperature is comfortable for most people. (Nhiệt độ phòng trung bình thì dễ chịu với hầu hết mọi người.)
The description of the suspect was very detailed. (Sự mô tả về nghi phạm rất chi tiết.)
Please provide a brief description of the incident. (Vui lòng cung cấp mô tả ngắn gọn về vụ việc.)
The job description includes various responsibilities. (Bản mô tả công việc bao gồm nhiều trách nhiệm khác nhau.)
The transition from high school to college can be challenging. (Sự chuyển tiếp từ trường trung học lên đại học có thể đầy thách thức.)
The country is undergoing a political transition. (Đất nước đang trải qua một cuộc chuyển giao chính trị.)
We need to ensure a smooth transition for the new employees. (Chúng ta cần đảm bảo một sự chuyển tiếp suôn sẻ cho các nhân viên mới.)
He pulled up a chair and sat down. (Anh ấy kéo một cái ghế lại và ngồi xuống.)
The chair is made of solid wood. (Cái ghế được làm từ gỗ nguyên khối.)
Please return the chair to its original position. (Vui lòng trả ghế về vị trí ban đầu.)
The dress has a floral pattern. (Chiếc váy có họa tiết hoa.)
He noticed a pattern in the test results. (Anh ấy nhận thấy một quy luật trong kết quả kiểm tra.)
The wallpaper pattern matches the overall decor. (Họa tiết giấy dán tường phù hợp với tổng thể trang trí.)
There is a high demand for organic products. (Nhu cầu đối với sản phẩm hữu cơ rất cao.)
The workers demand better working conditions. (Công nhân yêu cầu điều kiện làm việc tốt hơn.)
The demand for new housing is increasing. (Nhu cầu về nhà ở mới đang tăng.)
I hate being stuck in traffic. (Tôi ghét bị kẹt xe.)
She expressed her hate for injustice. (Cô ấy bày tỏ sự căm ghét đối với sự bất công.)
He learned to hate the war. (Anh ấy đã học cách căm ghét chiến tranh.)
The classroom was filled with students. (Lớp học chật kín học sinh.)
New technology is being integrated into the classroom. (Công nghệ mới đang được tích hợp vào lớp học.)
She decorated the classroom with educational posters. (Cô ấy trang trí lớp học bằng những tấm áp phích giáo dục.)
He served in the army for ten years. (Anh ấy đã phục vụ trong quân đội mười năm.)
The army deployed troops to the conflict zone. (Quân đội đã triển khai quân đến khu vực xung đột.)
The army provides disaster relief and humanitarian aid. (Quân đội cung cấp cứu trợ thảm họa và viện trợ nhân đạo.)
The flowers bloom in spring. (Hoa nở vào mùa xuân.)
Spring is a time for new beginnings. (Mùa xuân là thời điểm cho những khởi đầu mới.)
We plan to start the garden project in early spring. (Chúng tôi dự định bắt đầu dự án khu vườn vào đầu mùa xuân.)
She is a senior manager at the firm. (Cô ấy là quản lý cấp cao tại công ty.)
Senior citizens receive a discount at the museum. (Người cao tuổi được giảm giá tại bảo tàng.)
It's her senior year in high school. (Đây là năm cuối cấp của cô ấy ở trường trung học.)
The wind blew through the trees. (Gió thổi qua hàng cây.)
Wind turbines generate electricity. (Tua bin gió tạo ra điện.)
He could hear the wind howling at night. (Anh ấy có thể nghe thấy tiếng gió rít vào ban đêm.)
She received an award for her contributions to science. (Cô ấy đã nhận được một giải thưởng cho những đóng góp của mình cho khoa học.)
He was honored with a lifetime achievement award. (Anh ấy đã được vinh danh với giải thưởng thành tựu trọn đời.)
The committee decided to award the scholarship to the most deserving student. (Ủy ban đã quyết định trao học bổng cho sinh viên xứng đáng nhất.)
Clinical trials are necessary before a new drug can be approved. (Các thử nghiệm lâm sàng là cần thiết trước khi một loại thuốc mới có thể được phê duyệt.)
She is undergoing clinical treatment for her condition. (Cô ấy đang trải qua điều trị lâm sàng cho tình trạng của mình.)
Clinical studies show the effectiveness of the new therapy. (Các nghiên cứu lâm sàng cho thấy hiệu quả của liệu pháp mới.)
He found himself in trouble with the law. (Anh ấy thấy mình gặp rắc rối với pháp luật.)
If you need help, don't hesitate to call me. I don't want you to get into trouble. (Nếu bạn cần giúp đỡ, đừng ngần ngại gọi cho tôi. Tôi không muốn bạn gặp rắc rối.)
Her outspokenness sometimes causes trouble at work. (Sự thẳng thắn của cô ấy đôi khi gây rắc rối tại nơi làm việc.)
He received a good grade on his math exam. (Anh ấy nhận được điểm tốt trong bài thi toán.)
She teaches third grade at the local elementary school. (Cô ấy dạy lớp ba tại trường tiểu học địa phương.)
The road has a steep grade near the summit. (Con đường có một độ dốc lớn gần đỉnh.)
The train arrived at the station. (Tàu đã đến ga.)
She listens to her favorite music station on the radio. (Cô ấy nghe kênh radio âm nhạc yêu thích của mình.)
The police station is just around the corner. (Đồn cảnh sát ở ngay góc đường.)
The wedding was filled with beautiful moments. (Đám cưới tràn ngập những khoảnh khắc đẹp.)
He captured the moments on his camera. (Anh ấy đã ghi lại những khoảnh khắc bằng máy ảnh của mình.)
Moments like these remind us to appreciate life. (Những khoảnh khắc như thế này nhắc nhở chúng ta hãy trân trọng cuộc sống.)
The surfer rode a huge wave to the shore. (Người lướt sóng đã cưỡi một con sóng khổng lồ vào bờ.)
The physicist explained the wave theory of light. (Nhà vật lý giải thích lý thuyết sóng của ánh sáng.)
The wave of protests spread across the country. (Làn sóng biểu tình lan rộng khắp đất nước.)
Please move this block of ice to the cooler. (Làm ơn di chuyển tảng băng này vào thùng giữ lạnh.)
The new apartment block is under construction. (Khu chung cư mới đang được xây dựng.)
This software can block all unwanted ads. (Phần mềm này có thể chặn tất cả các quảng cáo không mong muốn.)
Compared to last year, our profits have increased. (So với năm ngoái, lợi nhuận của chúng tôi đã tăng lên.)
Her cooking skills are often compared to a professional chef's. (Kỹ năng nấu nướng của cô ấy thường được so sánh với một đầu bếp chuyên nghiệp.)
Compared with his brother, he is more outgoing. (So với anh trai mình, anh ấy cởi mở hơn.)
Lifting weights regularly increases muscle strength. (Nâng tạ thường xuyên giúp tăng cường sức mạnh cơ bắp.)
She showed great strength during difficult times. (Cô ấy đã thể hiện sức mạnh to lớn trong những thời điểm khó khăn.)
Unity is our greatest strength. (Đoàn kết là sức mạnh lớn nhất của chúng ta.)
The project is in the planning phase. (Dự án đang trong giai đoạn lập kế hoạch.)
Adolescence is a challenging phase of life. (Tuổi vị thành niên là một giai đoạn đầy thách thức của cuộc đời.)
The clinical trial has entered Phase III. (Thử nghiệm lâm sàng đã bước vào Giai đoạn III.)
They shared a secret that nobody else knew. (Họ chia sẻ một bí mật mà không ai khác biết.)
The recipe is a family secret. (Công thức nấu ăn là một bí mật gia đình.)
He kept his plans secret until the last moment. (Anh ấy giữ bí mật kế hoạch của mình cho đến phút cuối.)
Mount Everest is the highest mountain in the world. (Núi Everest là ngọn núi cao nhất thế giới.)
She achieved the highest score in the class. (Cô ấy đạt điểm số cao nhất trong lớp.)
The highest priority is given to safety. (Ưu tiên cao nhất được dành cho sự an toàn.)
He is leaving for New York tomorrow. (Anh ấy sẽ rời New York vào ngày mai.)
Leaving the job was a difficult decision for him. (Nghỉ việc là một quyết định khó khăn đối với anh ấy.)
He mentioned leaving his job to start his own business. (Anh ấy đã đề cập đến việc nghỉ việc để bắt đầu kinh doanh riêng.)
It was obvious that he was lying. (Rõ ràng là anh ấy đang nói dối.)
The solution to the problem was not immediately obvious. (Giải pháp cho vấn đề không ngay lập tức rõ ràng.)
Her happiness was obvious to everyone. (Niềm hạnh phúc của cô ấy hiện rõ trước mắt mọi người.)
The storm caused terrible damage. (Cơn bão đã gây ra thiệt hại khủng khiếp.)
He had a terrible feeling that something was wrong. (Anh ấy có một cảm giác tồi tệ rằng có điều gì đó không ổn.)
The food at that restaurant was terrible. (Đồ ăn ở nhà hàng đó thật tệ.)
The dancer's graceful motion captivated the audience. (Chuyển động duyên dáng của vũ công đã làm say đắm khán giả.)
He made a motion to the waiter for the bill. (Anh ấy ra hiệu cho người phục vụ để tính tiền.)
The machine's motion is controlled by a series of gears. (Chuyển động của máy được điều khiển bởi một loạt bánh răng.)
She opened the window to let in some fresh air. (Cô ấy mở cửa sổ để cho không khí trong lành vào.)
The bird flew straight into the window. (Con chim bay thẳng vào cửa sổ.)
He looked out the window at the rain pouring down. (Anh ấy nhìn ra ngoài cửa sổ thấy mưa như trút nước.)
We cannot assume everyone knows the rules. (Chúng ta không thể cho rằng mọi người đều biết các quy tắc.)
Let's not assume the worst without evidence. (Chúng ta đừng cho rằng điều tồi tệ nhất sẽ xảy ra khi không có bằng chứng.)
You shouldn't assume that everyone shares your opinion. (Bạn không nên cho rằng mọi người đều có chung quan điểm với bạn.)
The water cycle is essential for the Earth's ecosystem. (Chu kỳ nước là thiết yếu cho hệ sinh thái của Trái Đất.)
She follows a strict training cycle for the marathon. (Cô ấy tuân theo một chu kỳ luyện tập nghiêm ngặt cho cuộc thi marathon.)
The cycle of the moon affects the tides of the ocean. (Chu kỳ của mặt trăng ảnh hưởng đến thủy triều của đại dương.)
The weather changed suddenly, catching us off guard. (Thời tiết thay đổi đột ngột, khiến chúng tôi bất ngờ.)
She suddenly realized she had left her keys at home. (Cô ấy đột nhiên nhận ra mình đã để quên chìa khóa ở nhà.)
The room fell silent suddenly when the principal walked in. (Căn phòng đột ngột im bặt khi hiệu trưởng bước vào.)
Western movies often depict life in the American frontier. (Phim miền Tây thường mô tả cuộc sống ở biên giới Mỹ.)
She has a great interest in Western philosophy. (Cô ấy rất quan tâm đến triết học phương Tây.)
Western cultures have different norms and values. (Các nền văn hóa phương Tây có những quy chuẩn và giá trị khác nhau.)
He had a broken arm from playing football. (Anh ấy bị gãy tay do chơi bóng đá.)
Their relationship was broken beyond repair. (Mối quan hệ của họ đã tan vỡ không thể hàn gắn.)
I've broken my promise, and I regret it deeply. (Tôi đã thất hứa, và tôi vô cùng hối hận.)
It's hard to define the exact moment when everything changed. (Thật khó để xác định chính xác khoảnh khắc mọi thứ thay đổi.)
How do you define success? (Bạn định nghĩa thành công như thế nào?)
It's hard to define the exact moment when childhood ends. (Thật khó để định nghĩa chính xác khoảnh khắc tuổi thơ kết thúc.)
She embarked on a spiritual journey to find inner peace. (Cô ấy bắt đầu một hành trình tâm linh để tìm thấy sự bình yên nội tâm.)
Meditation is a key practice in many spiritual traditions. (Thiền là một thực hành chính trong nhiều truyền thống tâm linh.)
Spiritual leaders often emphasize the importance of compassion. (Các nhà lãnh đạo tâm linh thường nhấn mạnh tầm quan trọng của lòng trắc ẩn.)
Environmental concerns are at the forefront of global discussions. (Các mối quan ngại về môi trường đang là tâm điểm của các cuộc thảo luận toàn cầu.)
She voiced her concerns about the project's feasibility. (Cô ấy đã bày tỏ mối quan ngại của mình về tính khả thi của dự án.)
Health concerns have led to increased interest in organic food. (Những lo ngại về sức khỏe đã dẫn đến sự quan tâm ngày càng tăng đối với thực phẩm hữu cơ.)
The computer program generates random numbers for the lottery. (Chương trình máy tính tạo ra các số ngẫu nhiên cho xổ số.)
Random acts of kindness can brighten someone's day. (Những hành động tử tế ngẫu nhiên có thể làm một ngày của ai đó bừng sáng.)
He was selected from a random sample of the population. (Anh ấy được chọn từ một mẫu ngẫu nhiên trong dân số.)
The moon was full and bright in the night sky. (Mặt trăng tròn và sáng trên bầu trời đêm.)
Astronauts landed on the moon in 1969. (Các phi hành gia đã hạ cánh lên mặt trăng vào năm 1969.)
The moon looked especially large tonight. (Mặt trăng trông đặc biệt lớn vào tối nay.)
It's dangerous to drive in such severe weather conditions. (Lái xe trong điều kiện thời tiết khắc nghiệt như vậy rất nguy hiểm.)
Wild animals can be dangerous if provoked. (Động vật hoang dã có thể trở nên nguy hiểm nếu bị khiêu khích.)
He warned them of the dangerous chemicals in the lab. (Anh ấy đã cảnh báo họ về các hóa chất nguy hiểm trong phòng thí nghiệm.)
The forest is home to a wide variety of trees. (Khu rừng là nhà của rất nhiều loại cây.)
We planted fruit trees in our backyard. (Chúng tôi đã trồng cây ăn quả ở sân sau.)
Trees provide oxygen and improve air quality. (Cây cối cung cấp oxy và cải thiện chất lượng không khí.)
We're planning a trip to Europe next summer. (Chúng tôi đang lên kế hoạch cho một chuyến đi châu Âu vào mùa hè tới.)
The school organized a field trip to the museum. (Nhà trường đã tổ chức một chuyến đi thực tế đến bảo tàng.)
His first trip abroad was to Canada. (Chuyến đi nước ngoài đầu tiên của anh ấy là đến Canada.)
The child was curious about everything around him. (Đứa trẻ tò mò về mọi thứ xung quanh mình.)
I'm curious to know how it works. (Tôi tò mò muốn biết nó hoạt động như thế nào.)
Her curious nature led her to explore new places. (Bản tính tò mò đã dẫn dắt cô ấy khám phá những nơi mới.)
The box was too heavy for her to lift. (Cái hộp quá nặng để cô ấy có thể nhấc lên.)
Heavy rain caused flooding in the area. (Mưa lớn đã gây ra lũ lụt trong khu vực.)
He breathed a heavy sigh of relief. (Anh ấy thở phào một hơi nhẹ nhõm.)
Birds fly south for the winter. (Chim bay về phương nam để tránh mùa đông.)
The plane will fly from New York to London. (Máy bay sẽ bay từ New York đến London.)
I always wanted to fly a kite on the beach. (Tôi luôn muốn thả diều trên bãi biển.)
She noticed a change in his behavior. (Cô ấy nhận thấy một sự thay đổi trong hành vi của anh ấy.)
He hadn't noticed that the time was so late. (Anh ấy đã không nhận ra trời đã muộn như vậy.)
They noticed the bird as it flew past the window. (Họ nhận thấy con chim khi nó bay qua cửa sổ.)
Spring begins in March in the Northern Hemisphere. (Mùa xuân bắt đầu vào tháng Ba ở Bắc bán cầu.)
Her birthday is in March. (Sinh nhật của cô ấy là vào tháng Ba.)
The protest march took place on the first of March. (Cuộc tuần hành phản đối diễn ra vào ngày mùng một tháng Ba.)
The party will start in the evening. (Bữa tiệc sẽ bắt đầu vào buổi tối.)
I prefer reading books in the quiet of the evening. (Tôi thích đọc sách trong sự yên tĩnh của buổi tối.)
We saw a beautiful sunset last evening. (Chúng tôi đã thấy một hoàng hôn tuyệt đẹp tối qua.)
The room was filled with strange objects. (Căn phòng chứa đầy những vật thể kỳ lạ.)
He collects objects from the beach for his artwork. (Anh ấy sưu tầm các vật thể từ bãi biển cho tác phẩm nghệ thuật của mình.)
Objects in the mirror are closer than they appear. (Các vật thể trong gương gần hơn so với vẻ ngoài của chúng.)
We finally reached an agreement after hours of discussion. (Chúng tôi cuối cùng đã đạt được một thỏa thuận sau nhiều giờ thảo luận.)
The agreement was signed by both parties. (Thỏa thuận đã được ký bởi cả hai bên.)
Breaking this agreement could have serious consequences. (Vi phạm thỏa thuận này có thể gây ra hậu quả nghiêm trọng.)
Youth is the best time to learn new skills. (Tuổi trẻ là thời gian tốt nhất để học các kỹ năng mới.)
He spent his youth traveling around the world. (Anh ấy đã dành cả tuổi trẻ của mình để đi du lịch khắp thế giới.)
The festival is aimed at the youth of the city. (Lễ hội hướng đến giới trẻ của thành phố.)
The police are investigating a serious crime. (Cảnh sát đang điều tra một vụ án nghiêm trọng.)
Crime rates have fallen in the city. (Tỷ lệ tội phạm trong thành phố đã giảm.)
He was found guilty of committing a crime. (Anh ấy bị kết tội phạm pháp.)
She explained the plan in great detail. (Cô ấy đã giải thích kế hoạch một cách rất chi tiết.)
The artist captured every detail of the landscape. (Người họa sĩ đã nắm bắt mọi chi tiết của phong cảnh.)
Please provide more detail about the incident. (Vui lòng cung cấp thêm chi tiết về vụ việc.)
That restaurant is too expensive for our budget. (Nhà hàng đó quá đắt so với ngân sách của chúng tôi.)
Luxury cars are often very expensive. (Xe hơi sang trọng thường rất đắt.)
She wears very expensive jewelry. (Cô ấy đeo trang sức rất đắt tiền.)
The storm caused significant damage to the building. (Cơn bão đã gây ra thiệt hại đáng kể cho tòa nhà.)
We need to assess the damage before making repairs. (Chúng ta cần đánh giá thiệt hại trước khi tiến hành sửa chữa.)
Water damage can be very costly to fix. (Thiệt hại do nước có thể rất tốn kém để khắc phục.)
I need to fix the leak in the roof. (Tôi cần sửa chỗ rò rỉ trên mái nhà.)
Can you fix my computer? It's not starting. (Bạn có thể sửa máy tính của tôi được không? Nó không khởi động.)
I need to fix my bike before I can ride it to work. (Tôi cần sửa xe đạp trước khi có thể đi làm bằng nó.)
Heaven is often depicted as a place of peace and serenity. (Thiên đường thường được miêu tả là một nơi bình yên và thanh thản.)
The view from the mountain was like heaven on earth. (Khung cảnh từ trên núi giống như thiên đường trên mặt đất.)
Many people hope to find heaven after they die. (Nhiều người hy vọng sẽ lên thiên đường sau khi qua đời.)
Please select your preferred option. (Vui lòng chọn phương án bạn ưa thích.)
Only a select few were invited to the dinner. (Chỉ một vài người được chọn mời đến bữa tối.)
Select the right tool for the job. (Hãy chọn đúng công cụ cho công việc.)
Life is a constant struggle between good and evil. (Cuộc sống là một cuộc đấu tranh không ngừng giữa thiện và ác.)
She continues to struggle with her health issues. (Cô ấy tiếp tục vật lộn với các vấn đề sức khỏe của mình.)
Many small businesses struggle to survive in the first year. (Nhiều doanh nghiệp nhỏ phải vật lộn để tồn tại trong năm đầu tiên.)
The laboratory was equipped with the latest equipment. (Phòng thí nghiệm được trang bị các thiết bị mới nhất.)
Please check all equipment before starting the experiment. (Vui lòng kiểm tra tất cả thiết bị trước khi bắt đầu thí nghiệm.)
Safety equipment is mandatory in construction sites. (Thiết bị an toàn là bắt buộc tại các công trường xây dựng.)
Failure is just a step towards success. (Thất bại chỉ là một bước đệm đến thành công.)
The project ended in failure. (Dự án đã kết thúc trong thất bại.)
He considered his inability to find a solution as a personal failure. (Anh ấy coi việc không thể tìm ra giải pháp là một thất bại cá nhân.)
We planted roses in the garden. (Chúng tôi đã trồng hoa hồng trong vườn.)
The garden was a beautiful sight in spring. (Khu vườn là một cảnh tượng tuyệt đẹp vào mùa xuân.)
The botanical garden is home to many exotic plants. (Vườn bách thảo là nơi sinh sống của nhiều loài thực vật ngoại lai.)
The manager approved the budget for the project. (Quản lý đã phê duyệt ngân sách cho dự án.)
She is the manager of the marketing department. (Cô ấy là trưởng phòng của bộ phận tiếp thị.)
A good manager knows how to motivate their team. (Một người quản lý giỏi biết cách động viên đội nhóm của mình.)
He was sentenced to five years in prison. (Anh ấy bị kết án năm năm tù.)
The prison was known for its harsh conditions. (Nhà tù này nổi tiếng với điều kiện khắc nghiệt.)
They visited the old prison, now a museum. (Họ đã thăm nhà tù cũ, nay là một bảo tàng.)
Please feed the cat twice a day. (Xin hãy cho mèo ăn hai lần một ngày.)
The documentary showed how lions feed in the wild. (Bộ phim tài liệu cho thấy cách sư tử kiếm ăn trong tự nhiên.)
You should feed your mind with positive thoughts. (Bạn nên nuôi dưỡng tâm trí mình bằng những suy nghĩ tích cực.)
The wild landscape was breathtaking. (Cảnh quan hoang dã thật ngoạn mục.)
She has a wild imagination. (Cô ấy có một trí tưởng tượng bay bổng.)
Wild animals can be dangerous. (Động vật hoang dã có thể nguy hiểm.)
The valley was filled with fog in the morning. (Thung lũng đầy sương mù vào buổi sáng.)
They went hiking in the valley. (Họ đã đi bộ đường dài trong thung lũng.)
The river flows through the valley. (Dòng sông chảy qua thung lũng.)
We need to expand our operations to new markets. (Chúng tôi cần mở rộng hoạt động sang các thị trường mới.)
The company has plans to expand its product line. (Công ty có kế hoạch mở rộng dòng sản phẩm của mình.)
Reading extensively can expand your vocabulary. (Đọc nhiều có thể mở rộng vốn từ vựng của bạn.)
The fire spread quickly through the building. (Ngọn lửa lan nhanh khắp tòa nhà.)
They had to fire him for breaking company policies. (Họ phải sa thải anh ta vì vi phạm chính sách công ty.)
The fire alarm went off, causing panic throughout the office. (Chuông báo cháy vang lên, gây hoảng loạn khắp văn phòng.)
I spend too much time looking at a computer screen. (Tôi dành quá nhiều thời gian nhìn vào màn hình máy tính.)
The movie will be shown on the big screen at the theater tonight. (Bộ phim sẽ được chiếu trên màn ảnh rộng tại rạp tối nay.)
They used a green screen to create the background effects in the movie. (Họ đã sử dụng phông xanh để tạo hiệu ứng nền trong phim.)
The climate in this region is very humid. (Khí hậu ở vùng này rất ẩm.)
Climate change is a critical global issue. (Biến đổi khí hậu là một vấn đề toàn cầu nghiêm trọng.)
We need to adapt to the changing climate. (Chúng ta cần phải thích nghi với khí hậu đang thay đổi.)
The company has grown in scale significantly. (Công ty đã phát triển đáng kể về quy mô.)
Please weigh the package on the scale. (Làm ơn đặt gói hàng lên cân.)
The scale of the disaster was unprecedented. (Quy mô của thảm họa là chưa từng có.)
The results of the experiment were surprising. (Kết quả của thí nghiệm thật đáng ngạc nhiên.)
We are waiting for the election results. (Chúng tôi đang chờ kết quả bầu cử.)
The results showed a significant improvement. (Kết quả cho thấy một sự cải thiện đáng kể.)
Can we get the bill, please? (Làm ơn cho chúng tôi hóa đơn.)
The bill was passed by the Senate. (Dự luật đã được Thượng viện thông qua.)
He forgot to pay his electricity bill. (Anh ấy đã quên thanh toán hóa đơn tiền điện.)
The job offers many growth opportunities. (Công việc này mang lại nhiều cơ hội phát triển.)
We must seize any opportunities that come our way. (Chúng ta phải nắm bắt mọi cơ hội đến với mình.)
The city is full of opportunities for young entrepreneurs. (Thành phố đầy cơ hội cho các doanh nhân trẻ.)
Doctors managed to stop the blood loss. (Các bác sĩ đã cầm được máu.)
Blood donations can save lives. (Hiến máu có thể cứu người.)
His blood type is O positive. (Nhóm máu của anh ấy là O+.)
The play is now on stage at the local theater. (Vở kịch hiện đang được công diễn trên sân khấu tại nhà hát địa phương.)
She always dreamed of performing on stage. (Cô ấy luôn mơ ước được biểu diễn trên sân khấu.)
The director decided to stage the play in a modern setting. (Đạo diễn đã quyết định dàn dựng vở kịch trong bối cảnh hiện đại.)
This is a private matter, and it should not be discussed publicly. (Đây là chuyện riêng tư và không nên được thảo luận công khai.)
He prefers to keep his life private. (Anh ấy thích giữ cuộc sống của mình riêng tư.)
This is my private diary, please don't read it. (Đây là nhật ký riêng của tôi, xin đừng đọc.)
He has a hearing problem and uses a hearing aid. (Anh ấy có vấn đề về thính giác và sử dụng máy trợ thính.)
The court scheduled a hearing for next week. (Tòa án đã lên lịch một phiên điều trần vào tuần tới.)
Her hearing is very acute. (Thính giác của cô ấy rất nhạy bén.)
I recently started a new job. (Gần đây tôi đã bắt đầu một công việc mới.)
He has been feeling a lot better recently. (Anh ấy cảm thấy khỏe hơn nhiều gần đây.)
They recently moved into the neighborhood. (Họ mới chuyển đến khu này gần đây.)
The leaders of the two countries met to discuss peace. (Lãnh đạo hai nước đã gặp nhau để thảo luận về hòa bình.)
Young leaders are emerging in the community. (Các nhà lãnh đạo trẻ đang nổi lên trong cộng đồng.)
The company's leaders are considering a merger. (Các lãnh đạo của công ty đang xem xét việc sáp nhập.)
Without the proper context, the statement can be misleading. (Nếu không có bối cảnh phù hợp, phát biểu có thể gây hiểu lầm.)
The historical context is important for understanding the novel. (Bối cảnh lịch sử rất quan trọng để hiểu được cuốn tiểu thuyết.)
In the context of the meeting, his comments were inappropriate. (Trong bối cảnh của cuộc họp, bình luận của anh ta là không phù hợp.)
The actual cost was much higher than the estimate. (Chi phí thực tế cao hơn nhiều so với ước tính.)
His story is different from the actual events. (Câu chuyện của anh ấy khác với những sự kiện thực tế.)
We need to compare the planned budget against the actual expenses. (Chúng ta cần so sánh ngân sách dự kiến với chi tiêu thực tế.)
She has multiple responsibilities at work. (Cô ấy có nhiều trách nhiệm tại nơi làm việc.)
The accident caused multiple injuries. (Vụ tai nạn gây ra nhiều thương tích.)
He holds multiple degrees in engineering. (Anh ấy có nhiều bằng cấp về kỹ thuật.)
We watched the news on the local channel. (Chúng tôi đã xem tin tức trên kênh địa phương.)
Please change the channel to watch the football game. (Làm ơn chuyển kênh để xem trận bóng đá.)
The news channel is very popular for its unbiased reporting. (Kênh tin tức này rất nổi tiếng vì đưa tin khách quan.)
Congress passed a new law to improve healthcare. (Quốc hội đã thông qua một đạo luật mới để cải thiện chăm sóc sức khỏe.)
The member of Congress is holding a town hall meeting. (Thành viên Quốc hội đang tổ chức một cuộc họp với cử tri.)
The proposal will be presented to Congress next month. (Đề xuất sẽ được trình lên Quốc hội vào tháng tới.)
The meeting lasted an hour longer than expected. (Cuộc họp kéo dài hơn một giờ so với dự kiến.)
We have to leave in an hour. (Chúng ta phải rời đi trong một giờ nữa.)
We will start the meeting in an hour. (Chúng ta sẽ bắt đầu cuộc họp trong một giờ nữa.)
I expect to hear from them soon. (Tôi mong sẽ sớm nhận được tin từ họ.)
What do you expect me to do? (Bạn mong đợi tôi làm gì?)
They expect the project to be finished by the end of the year. (Họ kỳ vọng dự án sẽ hoàn thành vào cuối năm.)
The professor gave a lecture on the importance of sustainable development. (Giáo sư đã có một bài giảng về tầm quan trọng của phát triển bền vững.)
She is a professor of history at the university. (Bà ấy là giáo sư lịch sử tại trường đại học.)
He received an email from his professor about his thesis. (Anh ấy nhận được email từ giáo sư của mình về luận văn.)
He turned the key in the lock. (Anh ấy đã vặn chìa khóa trong ổ khóa.)
She turned to look at him. (Cô ấy quay lại nhìn anh ấy.)
The milk has turned sour. (Sữa đã bị chua.)
The company is moving in a new direction. (Công ty đang đi theo một hướng mới.)
Follow the direction of the arrow to reach the exit. (Hãy đi theo hướng mũi tên để đến lối ra.)
He has a good sense of direction. (Anh ấy có khả năng định hướng tốt.)
Their mission is to provide aid to those in need. (Nhiệm vụ của họ là cung cấp viện trợ cho những người gặp khó khăn.)
He was sent on a secret mission. (Anh ấy được cử đi làm một nhiệm vụ bí mật.)
The space mission was a success. (Nhiệm vụ không gian đã thành công.)
She's building her professional network. (Cô ấy đang xây dựng mạng lưới quan hệ chuyên nghiệp của mình.)
The network of roads facilitates easy transportation. (Mạng lưới đường bộ tạo điều kiện thuận lợi cho việc di chuyển.)
Their network is down due to technical issues. (Mạng của họ bị sập do sự cố kỹ thuật.)
The sky is a clear blue today. (Bầu trời hôm nay trong xanh.)
She wore a beautiful blue dress. (Cô ấy mặc một chiếc váy màu xanh tuyệt đẹp.)
Feeling a bit blue today. (Hôm nay cảm thấy hơi buồn.)
The police arrested the suspect. (Cảnh sát đã bắt giữ nghi phạm.)
She called the police to report a theft. (Cô ấy đã gọi cảnh sát để báo một vụ trộm.)
Police are investigating the crime scene. (Cảnh sát đang điều tra hiện trường vụ án.)
He has excellent communication skills. (Anh ấy có kỹ năng giao tiếp xuất sắc.)
She's working to improve her leadership skills. (Cô ấy đang nỗ lực cải thiện kỹ năng lãnh đạo của mình.)
Technical skills are important in this job. (Kỹ năng kỹ thuật rất quan trọng trong công việc này.)
The world is constantly changing. (Thế giới đang không ngừng thay đổi.)
She's changing her major to biology. (Cô ấy đang chuyển chuyên ngành sang sinh học.)
Changing the oil regularly is important for car maintenance. (Thay dầu định kỳ rất quan trọng cho việc bảo dưỡng xe hơi.)
The structure of the building is solid. (Kết cấu của tòa nhà rất vững chắc.)
They discussed the structure of the essay. (Họ đã thảo luận về cấu trúc của bài luận.)
The course has a very clear structure. (Khóa học có một cấu trúc rất rõ ràng.)
They plan to develop a new product. (Họ có kế hoạch phát triển một sản phẩm mới.)
The company plans to develop a new software platform. (Công ty có kế hoạch phát triển một nền tảng phần mềm mới.)
Children develop their language skills at an early age. (Trẻ em phát triển kỹ năng ngôn ngữ từ khi còn nhỏ.)
Pull the door to open it. (Kéo cửa để mở.)
You need to pull harder to start the engine. (Bạn cần kéo mạnh hơn để khởi động động cơ.)
Let's pull a prank on our friend tonight. (Chúng ta hãy chơi khăm bạn mình tối nay đi.)
Please send me the link to the document. (Làm ơn gửi cho tôi đường link đến tài liệu.)
They found a link between the two cases. (Họ đã tìm thấy một mối liên hệ giữa hai vụ án.)
Click on the link to visit our website. (Nhấp vào đường link để truy cập trang web của chúng tôi.)
I downloaded a new app for editing photos. (Tôi đã tải một ứng dụng mới để chỉnh sửa ảnh.)
This app helps you track your fitness goals. (Ứng dụng này giúp bạn theo dõi các mục tiêu thể chất của mình.)
She's using a language learning app. (Cô ấy đang sử dụng một ứng dụng học ngôn ngữ.)
She is taking an English course online. (Cô ấy đang tham gia một khóa học tiếng Anh trực tuyến.)
English literature is my favorite subject. (Văn học Anh là môn học yêu thích của tôi.)
He speaks English fluently. (Anh ấy nói tiếng Anh lưu loát.)
This book is worth reading. (Quyển sách này rất đáng đọc.)
The necklace is worth a lot of money. (Chiếc vòng cổ này rất có giá trị.)
It's worth trying the new restaurant. (Rất đáng để thử nhà hàng mới.)
She felt a sharp pain in her leg. (Cô ấy cảm thấy đau nhói ở chân.)
He's in a lot of pain after the surgery. (Anh ấy rất đau sau ca phẫu thuật.)
The medication helped ease the pain. (Thuốc đã giúp làm dịu cơn đau.)
I'm sorry for being late. (Tôi xin lỗi vì đã đến muộn.)
The train is running late. (Tàu đang chạy muộn.)
She stayed up late working on her project. (Cô ấy đã thức khuya để làm dự án của mình.)
The company stands by its core values. (Công ty luôn tuân thủ các giá trị cốt lõi của mình.)
Teaching children good values is important. (Dạy cho trẻ những giá trị tốt đẹp là điều quan trọng.)
Her values align with those of the organization. (Các giá trị của cô ấy phù hợp với các giá trị của tổ chức.)
I totally agree with you. (Tôi hoàn toàn đồng ý với bạn.)
That movie was totally awesome. (Bộ phim đó thực sự tuyệt vời.)
He was totally unaware of the situation. (Anh ấy hoàn toàn không biết gì về tình hình.)
She has a strong faith in God. (Cô ấy có một niềm tin mãnh liệt vào Chúa.)
Keep faith in yourself and you'll find a way. (Hãy giữ niềm tin vào bản thân và bạn sẽ tìm ra con đường.)
Their faith in each other was unshakeable. (Niềm tin của họ dành cho nhau không thể lay chuyển.)
He left some positive comments on my blog post. (Anh ấy đã để lại một vài bình luận tích cực trên bài đăng blog của tôi.)
The teacher's comments on my essay were very helpful. (Những nhận xét của giáo viên về bài luận của tôi rất hữu ích.)
Please read the comments below for more information. (Vui lòng đọc các bình luận bên dưới để biết thêm thông tin.)
They live on Maple Street. (Họ sống trên phố Maple.)
The street was crowded with people. (Đường phố đông nghịt người.)
Street food can be really delicious. (Đồ ăn đường phố có thể rất ngon.)
I'll search the internet for the answer. (Tôi sẽ tìm kiếm câu trả lời trên internet.)
The police are conducting a search for the missing child. (Cảnh sát đang tiến hành một cuộc tìm kiếm đứa trẻ mất tích.)
Search your feelings, you know it to be true. (Hãy tìm lại cảm xúc của mình, bạn biết đó là sự thật.)
Every person has a unique fingerprint. (Mỗi người có một dấu vân tay độc nhất.)
This painting is quite unique and valuable. (Bức tranh này khá độc đáo và có giá trị.)
Her style is very unique. (Phong cách của cô ấy rất độc đáo.)
Cancer is a serious disease that requires early detection. (Ung thư là một căn bệnh nghiêm trọng đòi hỏi phải được phát hiện sớm.)
Research on cancer treatment has advanced significantly. (Nghiên cứu về điều trị ung thư đã có những bước tiến đáng kể.)
Skin cancer can be prevented by protecting the skin from excessive sun exposure. (Ung thư da có thể được ngăn chặn bằng cách bảo vệ da khỏi việc tiếp xúc quá mức với ánh nắng mặt trời.)
That was a crazy idea, but it actually worked. (Đó là một ý tưởng điên rồ, nhưng nó thực sự hiệu quả.)
You're crazy if you think I'm going to do that! (Bạn thật điên nếu bạn nghĩ tôi sẽ làm điều đó!)
The party was absolutely crazy last night. (Bữa tiệc tối qua thực sự điên rồ.)
She holds the world record for the 100 meters sprint. (Cô ấy giữ kỷ lục thế giới cho cự ly chạy 100 mét.)
Please record your name and address. (Vui lòng ghi lại tên và địa chỉ của bạn.)
The device can record both audio and video. (Thiết bị có thể ghi lại cả âm thanh và hình ảnh.)
Remember to save your work frequently. (Nhớ lưu công việc của bạn thường xuyên.)
He managed to save enough money to buy a new car. (Anh ấy đã tiết kiệm đủ tiền để mua một chiếc xe mới.)
We need to save water by fixing leaky faucets. (Chúng ta cần tiết kiệm nước bằng cách sửa chữa vòi nước bị rò rỉ.)
The magician's performance was simply incredible. (Màn trình diễn của ảo thuật gia đơn giản là không thể tin được.)
It's incredible how much she has achieved in a year. (Thật không thể tin được khi cô ấy đã đạt được bao nhiêu trong một năm.)
The view from the top of the mountain is incredible. (Cảnh từ đỉnh núi là không thể tin nổi.)
The entire nation celebrated the victory. (Cả quốc gia đã ăn mừng chiến thắng.)
Healthcare is a major issue for the nation. (Chăm sóc sức khỏe là một vấn đề lớn cho quốc gia.)
The president addressed the nation last night. (Tổng thống đã phát biểu trước quốc gia tối qua.)
This dress is made of silk material. (Bộ váy này được làm từ chất liệu lụa.)
The teacher provided a lot of educational material. (Giáo viên đã cung cấp rất nhiều tài liệu giáo dục.)
The examination will cover all the material we've studied this semester. (Kỳ thi sẽ bao gồm tất cả tài liệu chúng ta đã học trong học kỳ này.)
You have the choice between tea and coffee. (Bạn có sự lựa chọn giữa trà và cà phê.)
She faced a difficult choice that could change her life. (Cô ấy đối mặt với một lựa chọn khó khăn có thể thay đổi cuộc đời mình.)
Your choice of paths could lead you to different destinations. (Sự lựa chọn của bạn về các con đường có thể dẫn bạn đến các điểm đến khác nhau.)
That was a weird noise coming from the attic. (Đó là một tiếng động kỳ lạ phát ra từ gác mái.)
He has some weird habits that are hard to understand. (Anh ấy có một số thói quen kỳ quặc khó hiểu.)
I had a really weird dream last night. (Tôi đã có một giấc mơ thực sự kỳ lạ tối qua.)
The cake was in the shape of a heart. (Chiếc bánh có hình dạng của một trái tim.)
He's in great shape because he exercises daily. (Anh ấy có sức khỏe tốt vì anh ấy tập thể dục hàng ngày.)
The shape of the moon tonight is a crescent. (Hình dạng của mặt trăng tối nay là hình lưỡi liềm.)
We played board games all evening. (Chúng tôi đã chơi trò chơi trên bàn cả buổi tối.)
Video games can be both fun and educational. (Trò chơi video có thể vừa vui vẻ vừa giáo dục.)
The Olympic Games are held every four years. (Thế vận hội Olympic được tổ chức mỗi bốn năm một lần.)
Freedom of speech is a fundamental human right. (Tự do ngôn luận là một quyền cơ bản của con người.)
After years of struggle, the country won its freedom. (Sau nhiều năm đấu tranh, đất nước đã giành được tự do.)
Retirement gave him the freedom to travel the world. (Việc nghỉ hưu đã cho anh ấy tự do đi du lịch khắp thế giới.)
We're having fish for dinner tonight. (Tối nay chúng tôi ăn cá.)
This pond is stocked with various types of fish. (Ao này được nuôi nhiều loại cá khác nhau.)
The fish tank needs cleaning. (Bể cá cần được làm sạch.)
Don't worry, everything will be okay. (Đừng lo, mọi thứ sẽ ổn.)
There's no need to worry about the details right now. (Không cần phải lo lắng về các chi tiết ngay bây giờ.)
They worry that the new policy may harm their business. (Họ lo ngại rằng chính sách mới có thể làm hại đến doanh nghiệp của họ.)
I need to get some sleep before the long drive tomorrow. (Tôi cần phải ngủ một chút trước chuyến lái xe dài ngày mai.)
Too much screen time before bed can disrupt your sleep. (Quá nhiều thời gian sử dụng màn hình trước khi đi ngủ có thể làm gián đoạn giấc ngủ của bạn.)
A regular sleep schedule helps improve overall health. (Một lịch trình ngủ đều đặn giúp cải thiện sức khỏe tổng thể.)
Would you like extra cheese on your pizza? (Bạn có muốn thêm phô mai vào pizza của mình không?)
I'll need to work extra hours to finish this project. (Tôi sẽ cần làm thêm giờ để hoàn thành dự án này.)
She always puts in extra effort to help her students understand. (Cô ấy luôn nỗ lực thêm để giúp học sinh của mình hiểu.)
Please check the internet setting on your phone. (Vui lòng kiểm tra cài đặt internet trên điện thoại của bạn.)
The dinner table was set in an elegant setting. (Bàn ăn được sắp xếp trong một không gian sang trọng.)
Adjusting the setting can optimize the device's performance. (Điều chỉnh cài đặt có thể tối ưu hiệu suất của thiết bị.)
The press has been covering the event extensively. (Báo chí đã đưa tin rộng rãi về sự kiện.)
Press the button to start the machine. (Nhấn nút để khởi động máy.)
He had to press the clothes before the meeting. (Anh ấy phải ủi quần áo trước cuộc họp.)
What's the date today? (Hôm nay là ngày mấy?)
They went on a date to the movies. (Họ đã đi xem phim với nhau.)
The expiration date is printed on the package. (Ngày hết hạn được in trên bao bì.)
It's an honor to meet you. (Được gặp bạn là một vinh dự.)
The ceremony was held in honor of the war heroes. (Lễ kỷ niệm được tổ chức để tôn vinh các anh hùng chiến tranh.)
He acted with honor and integrity. (Anh ấy hành động với danh dự và liêm chính.)
I can't decide what to wear tonight. (Tôi không thể quyết định mặc gì tối nay.)
Let's decide on a location for our next meeting. (Hãy quyết định một địa điểm cho cuộc họp tiếp theo của chúng ta.)
It's hard to decide without all the facts. (Thật khó để quyết định khi không có đủ thông tin.)
The sun rises in the east. (Mặt trời mọc ở phía đông.)
Sun exposure can damage your skin. (Phơi nắng có thể làm hại làn da của bạn.)
Always wear sunscreen to protect yourself from the sun. (Luôn thoa kem chống nắng để bảo vệ bản thân khỏi ánh nắng mặt trời.)
Please connect the printer to the computer. (Vui lòng kết nối máy in với máy tính.)
Social media has changed the way we connect with others. (Mạng xã hội đã thay đổi cách chúng ta kết nối với người khác.)
It's important to connect with nature for mental health. (Việc kết nối với thiên nhiên rất quan trọng cho sức khỏe tinh thần.)
The topic of today's discussion is climate change. (Chủ đề của cuộc thảo luận hôm nay là biến đổi khí hậu.)
She chose a controversial topic for her thesis. (Cô ấy chọn một chủ đề gây tranh cãi cho luận văn của mình.)
We should change the topic; this is getting too heated. (Chúng ta nên đổi chủ đề; cuộc thảo luận này đang trở nên quá nóng.)
Let's have a picnic in the park. (Hãy tổ chức một bữa picnic trong công viên.)
Please park the car in the garage. (Vui lòng đậu xe trong nhà để xe.)
The park is beautiful in the fall. (Công viên rất đẹp vào mùa thu.)
She is very active in local politics. (Cô ấy rất tích cực trong chính trị địa phương.)
Discussing politics can sometimes lead to heated arguments. (Thảo luận về chính trị đôi khi có thể dẫn đến tranh cãi nảy lửa.)
He has a degree in politics. (Anh ấy có bằng về chính trị.)
Japan is located to the east of China. (Nhật Bản nằm ở phía đông của Trung Quốc.)
We watched the sunrise in the east. (Chúng tôi đã xem mặt trời mọc ở hướng đông.)
The wind is coming from the east. (Gió đang thổi từ phía đông.)
I wish you a happy birthday. (Chúc bạn sinh nhật vui vẻ.)
My wish is to travel around the world. (Ước mơ của tôi là đi du lịch vòng quanh thế giới.)
He made a wish before blowing out the candles. (Anh ấy đã ước trước khi thổi tắt nến.)
She will graduate from university next year. (Cô ấy sẽ tốt nghiệp đại học vào năm tới.)
After I graduate, I plan to start my own business. (Sau khi tôi tốt nghiệp, tôi dự định sẽ khởi nghiệp.)
He's a recent graduate with a degree in engineering. (Anh ấy là sinh viên mới tốt nghiệp với bằng kỹ sư.)
Times Square is a major commercial intersection in New York. (Times Square là một ngã tư thương mại lớn ở New York.)
Draw a square on the board. (Vẽ một hình vuông trên bảng.)
The room is 100 square meters in size. (Phòng có diện tích 100 mét vuông.)
The candidate launched his campaign for mayor. (Ứng cử viên đã khởi động chiến dịch tranh cử chức thị trưởng.)
They started a campaign to raise awareness about climate change. (Họ bắt đầu một chiến dịch để nâng cao nhận thức về biến đổi khí hậu.)
The advertising campaign was a huge success. (Chiến dịch quảng cáo đã thành công lớn.)
The medication has several side effects. (Thuốc có một số tác dụng phụ.)
Climate change effects are being felt worldwide. (Ảnh hưởng của biến đổi khí hậu đang được cảm nhận trên toàn thế giới.)
The effects of the new law will be monitored closely. (Ảnh hưởng của luật mới sẽ được theo dõi chặt chẽ.)
We need to stop for gas before we hit the road. (Chúng ta cần dừng lại đổ xăng trước khi lên đường.)
Natural gas is used for heating and cooking. (Khí tự nhiên được sử dụng để sưởi ấm và nấu ăn.)
The gas station is just around the corner. (Trạm xăng ngay ở góc đường.)
She is a native speaker of Spanish. (Cô ấy là người bản xứ nói tiếng Tây Ban Nha.)
The native plants are well adapted to the local climate. (Các loại cây bản địa thích nghi tốt với khí hậu địa phương.)
He returned to his native country after many years abroad. (Anh ấy trở về nước bản địa sau nhiều năm ở nước ngoài.)
Please charge the phone as the battery is low. (Hãy sạc điện thoại vì pin đang yếu.)
The restaurant will charge a fee for water. (Nhà hàng sẽ tính phí tiền nước.)
The soldier led the charge against the enemy. (Người lính dẫn đầu cuộc tấn công chống lại kẻ thù.)
She comes from a poor family. (Cô ấy đến từ một gia đình nghèo.)
The poor lighting made it hard to read. (Ánh sáng kém khiến việc đọc sách trở nên khó khăn.)
He has a poor sense of direction. (Anh ấy có khả năng phán đoán hướng đi kém.)
The temperature will drop overnight. (Nhiệt độ sẽ giảm qua đêm.)
I need to drop off my clothes at the laundry. (Tôi cần đưa quần áo của mình đến tiệm giặt.)
Please drop me off at the next corner. (Làm ơn cho tôi xuống ở góc đường tiếp theo.)
The doctor prescribed a new drug for her condition. (Bác sĩ đã kê đơn một loại thuốc mới cho tình trạng của cô ấy.)
Drug abuse is a serious problem. (Lạm dụng ma túy là một vấn đề nghiêm trọng.)
The pharmaceutical company has developed a new drug to treat cancer. (Công ty dược phẩm đã phát triển một loại thuốc mới để điều trị ung thư.)
We spent the day at the sea. (Chúng tôi đã dành cả ngày ở biển.)
The sea was calm today. (Biển yên bình hôm nay.)
He loves sea animals. (Anh ấy yêu thích động vật biển.)
Summer is my favorite season. (Mùa hè là mùa yêu thích của tôi.)
This fruit is in season now. (Loại quả này đang vào mùa.)
They season the meat with salt and pepper. (Họ ướp thịt với muối và tiêu.)
She was taken to the hospital for surgery. (Cô ấy đã được đưa đến bệnh viện để phẫu thuật.)
The hospital is on the next street. (Bệnh viện ở phố tiếp theo.)
He works as a nurse in a local hospital. (Anh ấy làm việc như một y tá tại một bệnh viện địa phương.)
The property prices have increased recently. (Giá bất động sản đã tăng gần đây.)
Trespassing on private property is illegal. (Xâm nhập trái phép vào tài sản riêng là bất hợp pháp.)
They put their property on the market last month. (Họ đã đưa tài sản của mình ra thị trường vào tháng trước.)
Scientists are studying the origins of the universe. (Các nhà khoa học đang nghiên cứu nguồn gốc của vũ trụ.)
The universe is constantly expanding. (Vũ trụ đang không ngừng mở rộng.)
There are billions of galaxies in the universe. (Có hàng tỷ thiên hà trong vũ trụ.)
She's under a lot of stress at work. (Cô ấy đang chịu rất nhiều áp lực tại công việc.)
Exercise can help reduce stress. (Tập thể dục có thể giúp giảm căng thẳng.)
Stress affects your health. (Căng thẳng ảnh hưởng đến sức khỏe của bạn.)
I have walked a thousand miles. (Tôi đã đi bộ một nghìn dặm.)
A picture is worth a thousand words. (Một bức ảnh đáng giá ngàn lời.)
There are a thousand reasons to be happy. (Có hàng nghìn lý do để cảm thấy hạnh phúc.)
The river is very wide here. (Con sông rất rộng ở đây.)
They have a wide range of products. (Họ có một loạt sản phẩm rộng lớn.)
Open your eyes wide. (Mở to mắt ra.)
I'll have a double espresso. (Tôi sẽ uống một ly espresso gấp đôi.)
The recipe calls for double the amount of sugar. (Công thức yêu cầu gấp đôi lượng đường.)
They hope to double their sales this year. (Họ hy vọng gấp đôi doanh số bán hàng của mình trong năm nay.)
The diamonds were extracted from a mine. (Kim cương được khai thác từ một mỏ.)
That book is mine. (Quyển sách đó là của tôi.)
They discovered a new coal mine. (Họ đã phát hiện một mỏ than mới.)
He can throw a ball very far. (Anh ấy có thể ném bóng rất xa.)
Don't throw your clothes on the floor. (Đừng vứt quần áo của bạn xuống sàn.)
If you throw that glass on the floor, it will break. (Nếu bạn ném cái ly đó xuống sàn, nó sẽ vỡ.)
The majority of people agree with the decision. (Đa số mọi người đồng ý với quyết định.)
He won by a large majority. (Anh ấy đã thắng với phần lớn áp đảo.)
A majority vote is needed to pass the law. (Cần có số phiếu đa số để thông qua luật.)
The news spread quickly through the town. (Tin tức lan truyền nhanh chóng khắp thị trấn.)
The disease can spread through direct contact. (Bệnh có thể lan truyền qua tiếp xúc trực tiếp.)
The virus can spread easily in crowded conditions. (Virus có thể lây lan dễ dàng trong điều kiện đông người.)
You have the option to decline the offer. (Bạn có quyền từ chối lời đề nghị.)
Choosing the best option can be difficult. (Việc chọn lựa phương án tốt nhất có thể khó khăn.)
You have the option to choose between tea and coffee. (Bạn có lựa chọn giữa trà và cà phê.)
She has worked there for decades. (Cô ấy đã làm việc ở đó hàng thập kỷ.)
Fashion trends have changed over the decades. (Xu hướng thời trang đã thay đổi qua các thập kỷ.)
Many decades have passed since the war. (Nhiều thập kỷ đã trôi qua kể từ khi cuộc chiến kết thúc.)
I wonder what the future holds. (Tôi tự hỏi tương lai sẽ ra sao.)
The beauty of nature is a constant wonder. (Vẻ đẹp của thiên nhiên là một điều kỳ diệu không ngừng.)
I wonder why the sky is blue. (Tôi tự hỏi tại sao bầu trời lại có màu xanh.)
She wrote a letter of complaint to the manager. (Cô ấy đã viết một lá thư phàn nàn gửi cho người quản lý.)
I received a letter from an old friend. (Tôi nhận được một lá thư từ một người bạn cũ.)
He sealed the letter with wax. (Anh ấy đã niêm phong lá thư bằng sáp.)
This is the most effective method for learning a new language. (Đây là phương pháp hiệu quả nhất để học một ngôn ngữ mới.)
The teacher introduced a new teaching method. (Giáo viên đã giới thiệu một phương pháp giảng dạy mới.)
We need to find a better method for waste disposal. (Chúng ta cần tìm một phương pháp xử lý rác tốt hơn.)
You should wear a suit to the interview. (Bạn nên mặc bộ com-lê cho cuộc phỏng vấn.)
These shoes are too worn to wear outside. (Những đôi giày này đã mòn quá để mặc ra ngoài.)
I don't have anything to wear for the party. (Tôi không có gì để mặc cho bữa tiệc.)
The movie's final scene was very emotional. (Cảnh cuối của bộ phim rất cảm động.)
The police arrived at the crime scene immediately. (Cảnh sát đã đến hiện trường vụ án ngay lập tức.)
He painted a beautiful scene of the countryside. (Anh ấy đã vẽ một cảnh đẹp của nông thôn.)
I found a perfect spot for a picnic. (Tôi đã tìm thấy một địa điểm hoàn hảo cho một buổi picnic.)
There's a spot of ink on your shirt. (Có một vết mực trên áo của bạn.)
She has a spot on her skin that she's worried about. (Cô ấy có một vết trên da mà cô ấy đang lo lắng.)
Please knock before you enter. (Vui lòng gõ cửa trước khi bạn vào.)
To access the website, you must first enter your password. (Để truy cập vào trang web, bạn phải nhập mật khẩu của mình trước.)
The company decided to enter the Asian market next year. (Công ty quyết định sẽ thâm nhập vào thị trường châu Á vào năm tới.)
Africa is known for its diverse cultures and wildlife. (Châu Phi được biết đến với các nền văn hóa đa dạng và động vật hoang dã.)
She has always wanted to go on a safari in Africa. (Cô ấy luôn muốn đi săn ảnh ở Châu Phi.)
Africa is rich in natural resources, including diamonds, gold, and oil. (Châu Phi giàu tài nguyên thiên nhiên, bao gồm kim cương, vàng và dầu mỏ.)
He worked hard to achieve his goals. (Anh ấy đã làm việc chăm chỉ để đạt được mục tiêu của mình.)
We can achieve great things when we work together. (Chúng ta có thể đạt được những điều tuyệt vời khi chúng ta cùng làm việc với nhau.)
The company aims to achieve a 20% increase in sales this year. (Công ty đặt mục tiêu đạt được sự tăng trưởng 20% về doanh số bán hàng trong năm nay.)
I'm afraid of heights. (Tôi sợ độ cao.)
She was afraid to speak in public. (Cô ấy sợ nói trước đám đông.)
Are you afraid of the dark? (Bạn có sợ bóng tối không?)
They started a fund for the victims of the earthquake. (Họ đã bắt đầu một quỹ cho các nạn nhân của trận động đất.)
He invested in a mutual fund. (Anh ấy đã đầu tư vào một quỹ tương hỗ.)
The company decided to fund a new research project. (Công ty quyết định tài trợ cho một dự án nghiên cứu mới.)
She has a tiny tattoo on her wrist. (Cô ấy có một hình xăm nhỏ bé trên cổ tay.)
They live in a tiny apartment in the city. (Họ sống trong một căn hộ nhỏ bé ở thành phố.)
A tiny amount of salt can change the flavor of a dish. (Một lượng nhỏ muối có thể thay đổi hương vị của một món ăn.)
Friends forever. (Bạn bè mãi mãi.)
This waiting seems to last forever. (Việc chờ đợi này dường như kéo dài mãi mãi.)
I will love you forever. (Anh sẽ yêu em mãi mãi.)
She's a strong, independent woman. (Cô ấy là một người phụ nữ mạnh mẽ, độc lập.)
The country declared itself independent in 1960. (Quốc gia này đã tuyên bố độc lập vào năm 1960.)
She wants to be financially independent from her parents. (Cô ấy muốn tự chủ tài chính, không phụ thuộc vào bố mẹ.)
Please update me on the project's status. (Vui lòng cập nhật cho tôi về trạng thái của dự án.)
The status of my application is still pending. (Trạng thái của đơn ứng tuyển của tôi vẫn đang chờ xử lý.)
He checked the flight status online. (Anh ấy đã kiểm tra trạng thái chuyến bay trực tuyến.)
Vaccination can prevent many diseases. (Việc tiêm chủng có thể ngăn chặn nhiều bệnh tật.)
Use sunscreen to prevent sunburn. (Sử dụng kem chống nắng để ngăn chặn cháy nắng.)
The new policy aims to prevent fraud. (Chính sách mới nhằm mục đích ngăn chặn gian lận.)
Water resistance is a key feature of this smartwatch. (Khả năng chống nước là một tính năng chính của chiếc đồng hồ thông minh này.)
Her eyes are her most striking feature. (Đôi mắt là đặc điểm nổi bật nhất của cô ấy.)
This camera's best feature is its high-quality lens. (Tính năng tốt nhất của chiếc máy ảnh này là ống kính chất lượng cao.)
The equation x^2 = 4 has two solutions. (Phương trình x^2 = 4 có hai nghiệm.)
Solving this equation requires knowledge of algebra. (Giải phương trình này đòi hỏi kiến thức về đại số.)
The physicist presented an equation that describes the behavior of particles. (Nhà vật lý đã trình bày một phương trình mô tả hành vi của các hạt.)
He was appointed vice president of the company. (Anh ấy đã được bổ nhiệm làm phó chủ tịch của công ty.)
Smoking is a harmful vice that can lead to serious health problems. (Hút thuốc là một thói hư tật xấu có thể dẫn đến các vấn đề sức khỏe nghiêm trọng.)
She works as a vice principal at the high school. (Cô ấy làm việc như một phó hiệu trưởng tại trường trung học.)
The country's external debt is growing. (Nợ nước ngoài của quốc gia đang tăng.)
They managed to stay out of debt by living within their means. (Họ đã quản lý để tránh nợ bằng cách sống trong khả năng của mình.)
The company is heavily in debt due to recent expansions. (Công ty đang nợ nần chồng chất do việc mở rộng gần đây.)
The basic unit of length is the meter. (Đơn vị cơ bản của chiều dài là mét.)
She bought a new unit in a condominium. (Cô ấy đã mua một căn hộ mới trong một chung cư.)
The military unit was sent on a mission. (Đơn vị quân đội đã được gửi đi thực hiện một nhiệm vụ.)
Her presence at the party made everyone happy. (Sự hiện diện của cô ấy tại bữa tiệc làm mọi người vui mừng.)
The presence of pollutants in the water is alarming. (Sự hiện diện của các chất ô nhiễm trong nước là đáng báo động.)
He felt a strange presence in the room. (Anh ấy cảm thấy một sự hiện diện lạ lùng trong phòng.)
Two pages are missing from this book. (Hai trang bị mất tích từ cuốn sách này.)
The police are investigating the missing person case. (Cảnh sát đang điều tra vụ mất tích.)
A key piece of evidence is missing. (Một mảnh chứng cứ quan trọng đã mất.)
Water is a precious natural resource. (Nước là một nguồn tài nguyên thiên nhiên quý giá.)
The library is an excellent resource for research. (Thư viện là một nguồn lực xuất sắc cho nghiên cứu.)
The internet is a vast resource for research and learning. (Internet là một nguồn lực mênh mông cho nghiên cứu và học hỏi.)
I need a cup of coffee to start my day. (Tôi cần một tách cà phê để bắt đầu ngày mới.)
The coffee shop on the corner is very cozy. (Quán cà phê ở góc phố rất ấm cúng.)
Do you prefer your coffee black or with milk? (Bạn thích uống cà phê đen hay pha sữa?)
Our flight has been delayed due to bad weather. (Chuyến bay của chúng tôi bị trì hoãn do thời tiết xấu.)
Please fasten your seatbelt as the flight is about to take off. (Vui lòng cài dây an toàn khi chuyến bay chuẩn bị cất cánh.)
I booked a direct flight to Paris. (Tôi đã đặt một chuyến bay thẳng tới Paris.)
You must accept the terms and conditions to proceed. (Bạn phải chấp nhận các điều khoản và điều kiện để tiếp tục.)
It's hard to accept that we lost the game. (Thật khó để chấp nhận rằng chúng ta đã thua cuộc.)
She didn't accept his friend request on social media. (Cô ấy không chấp nhận lời mời kết bạn của anh ấy trên mạng xã hội.)
The tour guide showed us around the city. (Người hướng dẫn du lịch đã đưa chúng tôi đi quanh thành phố.)
This manual will guide you through the installation process. (Sổ tay này sẽ hướng dẫn bạn qua quá trình cài đặt.)
Let your conscience be your guide. (Hãy để lương tâm của bạn là người hướng dẫn bạn.)
The company provides excellent benefits for its employees. (Công ty cung cấp lợi ích xuất sắc cho nhân viên của mình.)
The document provides detailed information about the agreement. (Tài liệu cung cấp thông tin chi tiết về thỏa thuận.)
The hotel provides a free shuttle service to the airport. (Khách sạn cung cấp dịch vụ đưa đón miễn phí tới sân bay.)
She wears a silver chain around her neck. (Cô ấy đeo một chuỗi bạc quanh cổ.)
The restaurant is part of a national chain. (Nhà hàng là một phần của một chuỗi quốc gia.)
The chain of events led to the collapse of the company. (Chuỗi sự kiện đã dẫn đến sự sụp đổ của công ty.)
The plane landed safely after a turbulent flight. (Máy bay đã hạ cánh an toàn sau một chuyến bay gió lớn.)
We need to catch our plane to New York. (Chúng ta cần bắt chuyến máy bay đi New York.)
The plane will depart at 10 a.m. (Máy bay sẽ khởi hành vào lúc 10 giờ sáng.)
India is known for its diverse cultures and traditions. (Ấn Độ được biết đến với các nền văn hóa và truyền thống đa dạng.)
I visited the Taj Mahal on my trip to India. (Tôi đã thăm Taj Mahal trong chuyến đi của mình đến Ấn Độ.)
India is the second-most populous country in the world. (Ấn Độ là quốc gia đông dân thứ hai trên thế giới.)
The institution of marriage is important in many cultures. (Tổ chức hôn nhân quan trọng trong nhiều nền văn hóa.)
He donated a large sum of money to a charitable institution. (Anh ấy đã quyên góp một số tiền lớn cho một tổ chức từ thiện.)
This financial institution offers loans and savings accounts. (Tổ chức tài chính này cung cấp vay và tài khoản tiết kiệm.)
The auditorium was filled with excited spectators. (Hội trường đã được lấp đầy bởi khán giả phấn khích.)
She filled the glass with water to the brim. (Cô ấy đã lấp đầy cốc với nước tới miệng cốc.)
The job position has already been filled. (Vị trí công việc đã được lấp đầy.)
The historical document dates back to the 18th century. (Tài liệu lịch sử có từ thế kỷ 18.)
I will document the process for future reference. (Tôi sẽ ghi lại quá trình này cho tài liệu tham khảo trong tương lai.)
He forgot to document his experiment's results. (Anh ấy quên ghi chép kết quả thí nghiệm của mình.)
The store is closed on Sundays. (Cửa hàng đóng cửa vào Chủ nhật.)
The road was closed for construction. (Con đường đã được đóng cửa để xây dựng.)
We arrived at the museum only to find it closed. (Chúng tôi đến bảo tàng chỉ để thấy nó đã đóng cửa.)
The company plans to launch a new product next month. (Công ty dự định ra mắt một sản phẩm mới vào tháng tới.)
The film's launch was postponed due to unforeseen circumstances. (Việc ra mắt phim đã bị hoãn lại do những tình huống không lường trước được.)
The presentation includes several visual aids. (Bài thuyết trình bao gồm một số công cụ hỗ trợ thị giác.)
Visual learning can be very effective for certain subjects. (Học thông qua thị giác có thể rất hiệu quả cho một số môn học.)
The artist's visual imagination is truly remarkable. (Trí tưởng tượng thị giác của họa sĩ thực sự đáng chú ý.)
Tests were conducted to determine the cause of the illness. (Các bài kiểm tra đã được thực hiện để xác định nguyên nhân của bệnh.)
The jury will determine the outcome of the case. (Ban giám khảo sẽ xác định kết quả của vụ án.)
Your attitude will determine your success. (Thái độ của bạn sẽ quyết định sự thành công của bạn.)
The technology sector has shown rapid growth. (Ngành công nghệ đã cho thấy sự tăng trưởng nhanh chóng.)
He works in the public sector. (Anh ấy làm việc trong khu vực công.)
Investments in the renewable energy sector are increasing. (Các khoản đầu tư vào ngành năng lượng tái tạo đang tăng lên.)
This dish has a very unique taste. (Món ăn này có một vị rất đặc biệt.)
I like the taste of coffee in the morning. (Tôi thích vị của cà phê vào buổi sáng.)
Taste in music varies from person to person. (Sở thích âm nhạc thay đổi từ người này sang người khác.)
I'm feeling sick today, so I won't be able to come to work. (Hôm nay tôi cảm thấy ốm, nên tôi sẽ không thể đến làm việc.)
The pollution in the city makes me sick. (Ô nhiễm ở thành phố làm tôi cảm thấy mệt mỏi.)
He has a sick sense of humor. (Anh ấy có một gu hài hước kỳ lạ.)
He is a master of martial arts. (Anh ấy là một bậc thầy võ thuật.)
You need to master the basics before moving on to advanced topics. (Bạn cần nắm vững các kiến thức cơ bản trước khi chuyển sang các chủ đề nâng cao.)
The painting was a masterpiece by a great master. (Bức tranh là một kiệt tác của một bậc thầy vĩ đại.)
The competition for the job was fierce. (Cuộc cạnh tranh cho công việc đó rất khốc liệt.)
She won first place in the singing competition. (Cô ấy đã giành được giải nhất trong cuộc thi hát.)
There's a lot of competition between companies in the tech industry. (Có rất nhiều sự cạnh tranh giữa các công ty trong ngành công nghệ.)
He waited for her at the street corner. (Anh ấy đã chờ cô ấy ở góc phố.)
The store is just around the corner. (Cửa hàng nằm ngay sau góc.)
He painted himself into a corner with no easy way out. (Anh ấy tự đẩy mình vào thế bí không dễ gì thoát ra.)
I didn't mean to hurt your feelings. (Tôi không có ý làm tổn thương cảm xúc của bạn.)
The loss hurt their chances of winning the championship. (Thất bại đã ảnh hưởng đến cơ hội giành chức vô địch của họ.)
My eyes hurt because I've been staring at the screen for too long. (Mắt tôi đau vì tôi đã nhìn chằm chằm vào màn hình quá lâu.)
The prime objective of the project is to reduce costs. (Mục tiêu chính của dự án là giảm chi phí.)
He is in his prime and capable of winning the race. (Anh ấy đang ở độ chín của sự nghiệp và có khả năng thắng cuộc đua.)
Prime numbers are fascinating to mathematicians. (Các số nguyên tố rất hấp dẫn với các nhà toán học.)
The company will ship the package tomorrow. (Công ty sẽ gửi gói hàng vào ngày mai.)
She worked on a cruise ship for a year. (Cô ấy đã làm việc trên một con tàu du lịch trong một năm.)
The ship sailed across the Atlantic Ocean. (Con tàu đã đi qua Đại Tây Dương.)
The museum houses ancient artifacts from Egypt. (Bảo tàng chứa các hiện vật cổ từ Ai Cập.)
Ancient civilizations have always fascinated historians. (Các nền văn minh cổ đại luôn làm mê hoặc các nhà sử học.)
He studies ancient languages like Latin and Greek. (Anh ấy nghiên cứu các ngôn ngữ cổ như Latin và Hy Lạp.)
Mix the flour and water to make a paste. (Trộn bột và nước để tạo thành hỗn hợp.)
The party was a mix of people from different backgrounds. (Bữa tiệc là sự pha trộn của những người từ các nền tảng khác nhau.)
He has a unique mix of skills. (Anh ấy có một sự kết hợp độc đáo của các kỹ năng.)
Carrots are a type of root vegetable. (Cà rốt là một loại rau củ.)
I need to get to the root of the problem. (Tôi cần tìm ra nguyên nhân gốc rễ của vấn đề.)
The root cause of the issue was poor communication. (Nguyên nhân gốc rễ của vấn đề là do giao tiếp kém.)
Please make a copy of the report for everyone. (Làm ơn sao chép một bản của báo cáo cho mọi người.)
This painting is a copy of a famous artwork. (Bức tranh này là bản sao của một tác phẩm nghệ thuật nổi tiếng.)
I accidentally deleted the file, but luckily I had a backup copy. (Tôi vô tình xóa file, nhưng may mắn là tôi đã có bản sao lưu.)
We need your input on this project. (Chúng tôi cần ý kiến đóng góp của bạn vào dự án này.)
Input the data into the computer system. (Nhập dữ liệu vào hệ thống máy tính.)
The device requires an input of 5 volts. (Thiết bị yêu cầu một nguồn vào 5 volt.)
The law provides protection for endangered species. (Luật pháp cung cấp sự bảo vệ cho các loài đang bị đe dọa.)
Wear a helmet for head protection. (Mặc mũ bảo hiểm để bảo vệ đầu.)
The software offers protection against viruses. (Phần mềm cung cấp sự bảo vệ chống lại virus.)
One important aspect of the plan is cost. (Một khía cạnh quan trọng của kế hoạch là chi phí.)
The social aspect of school is very important for development. (Khía cạnh xã hội của trường học rất quan trọng cho sự phát triển.)
The cultural aspect of language learning is very important. (Khía cạnh văn hóa của việc học ngôn ngữ rất quan trọng.)
I can't find my mobile phone anywhere. (Tôi không thể tìm thấy điện thoại di động của mình ở đâu cả.)
Many companies are focusing on mobile applications. (Nhiều công ty đang tập trung vào các ứng dụng di động.)
The mobile clinic provides healthcare services to remote areas. (Phòng khám di động cung cấp dịch vụ chăm sóc sức khỏe cho các khu vực xa xôi.)
Be careful not to break the glass. (Hãy cẩn thận đừng làm vỡ kính.)
Fill the glass with water, please. (Làm ơn đổ đầy cốc bằng nước.)
The building's facade is made entirely of glass. (Mặt tiền của tòa nhà được làm hoàn toàn bằng kính.)
The weather today is sunny and warm. (Thời tiết hôm nay là nắng và ấm.)
We should check the weather forecast before we go camping. (Chúng ta nên kiểm tra dự báo thời tiết trước khi đi cắm trại.)
The old bridge has withstood the weather for over a century. (Cây cầu cũ đã chống chọi với thời tiết hơn một thế kỷ.)
He walked slowly towards the door. (Anh ấy đi chậm về phía cửa.)
Slowly but surely, they made progress on the project. (Chậm rãi nhưng chắc chắn, họ đã tiến bộ trong dự án.)
The sun slowly set, ending a beautiful day. (Mặt trời từ từ lặn, kết thúc một ngày đẹp.)
The government provided aid to the flood victims. (Chính phủ đã cung cấp viện trợ cho nạn nhân lũ lụt.)
First aid is crucial in emergencies. (Sơ cứu rất quan trọng trong các tình huống khẩn cấp.)
The aid worker traveled to many countries to help those in need. (Người làm công tác viện trợ đã đi đến nhiều quốc gia để giúp đỡ những người cần.)
He made a bold claim about his invention's capabilities. (Anh ấy đã đưa ra một tuyên bố táo bạo về khả năng của phát minh của mình.)
You need to file a claim with your insurance company. (Bạn cần nộp một yêu cầu với công ty bảo hiểm của mình.)
You need to fill out this form to claim your prize. (Bạn cần phải điền vào mẫu đơn này để yêu cầu giải thưởng của mình.)
Many people are strongly opposed to the new law. (Nhiều người mạnh mẽ phản đối luật mới.)
He opposed the idea of working on weekends. (Anh ấy phản đối ý tưởng làm việc vào cuối tuần.)
The proposal was unanimously opposed by the committee. (Đề xuất đã bị ủy ban phản đối một cách nhất trí.)
The company is committed to equity and diversity in the workplace. (Công ty cam kết về sự công bằng và đa dạng trong nơi làm việc.)
They bought out his share of the business to gain full equity. (Họ mua lại phần cổ phần của anh ta trong doanh nghiệp để giành lấy toàn bộ vốn sở hữu.)
Equity in education is essential for a fair society. (Công bằng trong giáo dục là thiết yếu cho một xã hội công bằng.)
The chef offered us a sample of the new dish. (Đầu bếp đã cho chúng tôi thử một mẫu của món mới.)
The survey results are based on a random sample of the population. (Kết quả khảo sát dựa trên một mẫu ngẫu nhiên của dân số.)
We need to collect a soil sample from each field. (Chúng ta cần thu thập một mẫu đất từ mỗi cánh đồng.)
The factory produced 1000 units last month. (Nhà máy đã sản xuất 1000 đơn vị vào tháng trước.)
The documentary was produced by a famous director. (Bộ phim tài liệu được sản xuất bởi một đạo diễn nổi tiếng.)
A giant statue stood at the entrance of the city. (Một bức tượng khổng lồ đứng tại cửa vào của thành phố.)
The company is a giant in the tech industry. (Công ty là một gã khổng lồ trong ngành công nghệ.)
He faced his fears like a giant. (Anh ấy đối mặt với nỗi sợ hãi như một gã khổng lồ.)
They have a small farm where they raise chickens and grow vegetables. (Họ có một trang trại nhỏ nơi họ nuôi gà và trồng rau.)
The farm produces organic milk and cheese. (Trang trại sản xuất sữa và phô mai hữu cơ.)
The farm is located just outside the city. (Trang trại nằm ngay bên ngoài thành phố.)
Can you suggest a good restaurant in this area? (Bạn có thể đề xuất một nhà hàng tốt ở khu vực này không?)
I suggest taking an umbrella as it might rain later. (Tôi đề nghị mang theo một cái ô vì có thể sau này sẽ mưa.)
They suggest that we wait until the weather improves. (Họ đề nghị chúng ta đợi đến khi thời tiết tốt hơn.)
This cake is too sweet for my taste. (Bánh này quá ngọt đối với khẩu vị của tôi.)
She has a sweet voice that everyone loves to hear. (Cô ấy có giọng hát ngọt ngào mà mọi người đều thích nghe.)
Sweet memories of our childhood came flooding back. (Những kỷ niệm ngọt ngào về tuổi thơ ùa về.)
We need to set a strict limit on spending. (Chúng ta cần đặt một giới hạn chặt chẽ về chi tiêu.)
The sky's the limit when it comes to his potential. (Không có giới hạn nào cho tiềm năng của anh ấy.)
She decided to switch her major from English to Biology. (Cô ấy quyết định chuyển chuyên ngành từ Tiếng Anh sang Sinh học.)
Can you switch off the lights before you leave? (Bạn có thể tắt đèn trước khi bạn rời đi không?)
Can you switch the TV to channel 5? (Bạn có thể chuyển kênh tivi sang kênh 5 không?)
The ground was covered with fallen leaves. (Mặt đất được phủ kín bởi lá rụng.)
She loves the sound of leaves rustling in the wind. (Cô ấy yêu thích tiếng lá xào xạc trong gió.)
In autumn, the leaves turn beautiful shades of orange and red. (Vào mùa thu, lá chuyển sang những sắc thái đẹp của màu cam và đỏ.)
It's important to maintain a healthy lifestyle. (Quan trọng là phải duy trì một lối sống khỏe mạnh.)
The city has struggled to maintain its historic buildings. (Thành phố đã vật lộn để duy trì các tòa nhà lịch sử của mình.)
They have managed to maintain a strong friendship over the years. (Họ đã quản lý để duy trì một tình bạn mạnh mẽ qua nhiều năm.)
The lack of communication caused many problems in their relationship. (Sự thiếu giao tiếp đã gây ra nhiều vấn đề trong mối quan hệ của họ.)
The heavy rain caused flooding in many areas. (Mưa lớn đã gây ra lũ lụt ở nhiều khu vực.)
His careless driving caused an accident. (Lái xe bất cẩn của anh ta đã gây ra một tai nạn.)
Today's lesson is on the importance of teamwork. (Bài học hôm nay là về tầm quan trọng của sự làm việc nhóm.)
She learned a valuable lesson about trust. (Cô ấy đã học được một bài học quý giá về sự tin tưởng.)
The teacher prepared the lesson plan for the week. (Giáo viên đã chuẩn bị kế hoạch bài học cho tuần.)
Music speaks directly to the soul. (Âm nhạc nói chuyện trực tiếp với linh hồn.)
He was said to have sold his soul for success. (Người ta nói rằng anh ta đã bán linh hồn của mình để đổi lấy thành công.)
She poured her soul into her writing. (Cô ấy đã đổ hồn mình vào việc viết lách.)
The extent of the damage was unknown. (Mức độ thiệt hại là không biết.)
To what extent can we rely on this data? (Chúng ta có thể tin cậy vào dữ liệu này đến mức nào?)
The extent of his knowledge on the subject is impressive. (Mức độ hiểu biết của anh ấy về chủ đề này rất ấn tượng.)
They are trying to rid the house of mice. (Họ đang cố gắng loại bỏ chuột khỏi nhà.)
She wanted to rid herself of her bad habits. (Cô ấy muốn loại bỏ những thói quen xấu của mình.)
The new policy aims to rid the city of pollution. (Chính sách mới nhằm mục đích loại bỏ ô nhiễm khỏi thành phố.)
The course is designed for advanced students. (Khóa học được thiết kế cho sinh viên tiên tiến.)
They use advanced technology in their research. (Họ sử dụng công nghệ tiên tiến trong nghiên cứu của họ.)
His ideas were too advanced for his time. (Ý tưởng của anh ấy quá tiên tiến so với thời đại của mình.)
She couldn't bear the thought of losing him. (Cô ấy không thể chịu đựng được ý nghĩ về việc mất anh ấy.)
This bridge can bear the weight of heavy trucks. (Cây cầu này có thể chịu đựng trọng lượng của xe tải nặng.)
The old bridge can no longer bear the weight of heavy trucks. (Cây cầu cũ không còn chịu được trọng lượng của những chiếc xe tải nặng.)
The company promises to deliver your order within 24 hours. (Công ty hứa sẽ giao hàng cho đơn hàng của bạn trong vòng 24 giờ.)
Can you deliver this message to Mr. Smith? (Bạn có thể giao thông điệp này cho ông Smith không?)
The president will deliver a speech on the economy tomorrow. (Tổng thống sẽ phát biểu về nền kinh tế vào ngày mai.)
It was hell trying to find a taxi in the rain. (Việc tìm một chiếc taxi trong cơn mưa thật là địa ngục.)
She went through hell during her divorce. (Cô ấy đã trải qua địa ngục trong quá trình ly hôn của mình.)
This place is a hell on earth. (Nơi này là địa ngục trần gian.)


`;

/**
 * Phân tích chuỗi dữ liệu ví dụ thành một mảng các đối tượng có cấu trúc.
 * @param text - Chuỗi văn bản thô chứa các ví dụ.
 * @returns Một mảng các đối tượng ExampleSentence.
 */
export const parseExampleSentences = (text: string): ExampleSentence[] => {
  const lines = text.trim().split('\n');
  const examples: ExampleSentence[] = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    const match = line.match(/(.*)\s*\((.*)\)/);
    if (match && match[1] && match[2]) {
      examples.push({
        english: match[1].trim(),
        vietnamese: match[2].trim().replace(/\.$/, ''), // Bỏ dấu chấm ở cuối nếu có
      });
    } else {
      // Fallback nếu dòng không đúng định dạng
      examples.push({
        english: line.trim(),
        vietnamese: 'Bản dịch không có sẵn',
      });
    }
  }

  return examples;
};

// Xuất dữ liệu đã được phân tích để các component khác có thể sử dụng trực tiếp
export const exampleData: ExampleSentence[] = parseExampleSentences(exampleSentencesText);

// --- END OF FILE example-data.ts ---
