// File: defaultVocabulary.ts
// Đây là file xuất danh sách từ vựng để sử dụng cho slider hoặc bất kỳ component nào khác.

// Nếu cần mở rộng, bạn có thể chuyển mỗi phần tử thành object với thêm ví dụ, dịch, v.v.

export const defaultVocabulary: string[] = [
  "Source",
  "Insurance",
  "Argument",
  "Influence",
  "Release",
  "Capacity",
  "Senate",
  "Massive",
  "Stick",
  "District",
  "Budget",
  "Measure",
  "Cross",
  "Central",
  "Proud",
  "Core",
  "County",
  "Species",
  "Conditions",
  "Touch",
  "Mass",
  "Platform",
  "Straight",
  "Serious",
  "Encourage",
  "Due",
  "Memory",
  "Secretary",
  "Cold",
  "Instance",
  "Foundation",
  "Separate",
  "Map",
  "Ice",
  "Statement",
  "Rich",
  "Previous",
  "Necessary",
  "Engineering",
  "Heat",
];
