// --- START OF FILE: phrase-data.ts ---

interface PhrasePart {
  english: string;
  vietnamese: string;
}

interface PhraseSentence {
  parts: PhrasePart[];
  fullEnglish: string;
  fullVietnamese: string;
}

// --- DỮ LIỆU GỐC ---
// Dán toàn bộ danh sách cụm từ vào đây.
// QUAN TRỌNG: Mỗi cụm từ đơn lẻ nên nằm trên MỘT DÒNG.
const rawPhraseStream = `

Solar energy (Năng lượng mặt trời)
a renewable source of power (một nguồn năng lượng tái tạo)
The company (Công ty)
is looking for (đang tìm kiếm)
a new source of raw materials (một nguồn nguyên liệu thô mới)
Health insurance (Bảo hiểm sức khỏe)
a must (điều bắt buộc)
for all employees (đối với tất cả nhân viên)
The car (Chiếc xe)
was totalled (đã bị hỏng hoàn toàn)
but luckily (nhưng may mắn là)
a range of insurance services (một loạt các dịch vụ bảo hiểm)
to our clients (cho khách hàng của mình)
The couple (Cặp đôi)
had an argument (đã tranh cãi)
about spending money (về việc tiêu tiền)
His main argument (Luận điểm chính của anh ấy)
is supported (được hỗ trợ)
by recent studies (bởi các nghiên cứu gần đây)
got into an argument (đã tranh cãi)
over politics (về chính trị)
Social media (Mạng xã hội)
a big influence (ảnh hưởng lớn)
on young people (đối với giới trẻ)
a lot of influence (nhiều ảnh hưởng)
in the company (trong công ty)
Her parents (Bố mẹ cô ấy)
had a strong influence (có ảnh hưởng mạnh mẽ)
on her career choice (đến sự lựa chọn nghề nghiệp của cô ấy)
The band (Ban nhạc)
is planning (đang lên kế hoạch)
to release a new album (phát hành một album mới)
next month (vào tháng tới)
After years of research (Sau nhiều năm nghiên cứu)
the scientist (nhà khoa học)
is ready to release (sẵn sàng công bố)
his findings (phát hiện của mình)
to the public (cho công chúng)
The movie (Bộ phim)
is scheduled for release (được lên lịch phát hành)
during the holiday season (trong mùa lễ hội)
The stadium (Sân vận động)
a seating capacity of 50,000 (sức chứa 50000 chỗ ngồi)
The battery (Pin)
a capacity of 2000 milliampere-hours (dung lượng 2000 miliampe-giờ)
The memory card (Thẻ nhớ)
a storage capacity of 128 gigabytes (dung lượng lưu trữ 128 gigabyte)
The Senate (Thượng viện)
with a large majority (với đa số lớn)
his candidacy (ứng cử)
for the US Senate (vào Thượng viện Mỹ)
The proposal (Đề xuất)
needs approval (cần được sự chấp thuận)
from both the House and the Senate (từ cả Hạ viện và Thượng viện)
The earthquake (Trận động đất)
massive damage (thiệt hại lớn)
to the city (cho thành phố)
massive support (sự ủng hộ lớn)
from her fans (từ người hâm mộ)
The company (Công ty)
is undertaking (đang tiến hành)
a massive project (một dự án lớn)
picked up a stick (nhặt một cây gậy)
to defend himself (để tự vệ)
used a stick (dùng một cây gậy)
to poke the fire (để khều lửa)
used a walking stick (đã sử dụng một cây gậy)
on her hike (khi đi bộ đường dài)
in the downtown district (ở khu vực trung tâm thành phố)
The school district (Khu vực trường học)
is implementing (đang thực hiện)
new policies (các chính sách mới)
This district (Khu vực này)
is known for (nổi tiếng với)
its vibrant nightlife (cuộc sống về đêm sôi động)
The project (Dự án)
need to cut (cần cắt giảm)
our monthly budget (ngân sách hàng tháng của mình)
The government (Chính phủ)
is preparing (đang chuẩn bị)
the annual budget (ngân sách hàng năm)
need to measure the room (cần đo căn phòng)
before buying new furniture (trước khi mua đồ nội thất mới)
the distance (khoảng cách)
between the two points (giữa hai điểm)
This ruler (Cái thước này)
can measure (có thể đo)
up to 30 centimeters (lên đến 30 centimet)
Be careful (Hãy cẩn thận)
when you cross the street (khi bạn băng qua đường)
The idea (Ý tưởng đó)
Cross off (Gạch)
the names of the guests (tên của những vị khách)
who have confirmed they are not coming (đã xác nhận là họ sẽ không đến)
The central theme (Chủ đề trung tâm)
of the book (của cuốn sách)
love and forgiveness (tình yêu và sự tha thứ)
lives in a central location (sống ở một vị trí trung tâm)
convenient for all (thuận tiện cho tất cả mọi người)
Central heating (Sưởi trung tâm)
a common feature (một tính năng phổ biến)
in these homes (trong những ngôi nhà này)
was proud of (tự hào về)
her children's achievements (thành tích của con mình)
stood tall and proud (đứng thẳng và tự hào)
despite the challenges (bất chấp những thách thức)
are proud (tự hào)
to serve their community (phục vụ cộng đồng của mình)
the core value (giá trị cốt lõi)
of our company (của công ty chúng tôi)
The core of the problem (Cốt lõi của vấn đề)
lies in (nằm ở)
communication issues (các vấn đề về giao tiếp)
An apple's core (Lõi của quả táo)
contains seeds (chứa hạt)
was elected (đã được bầu làm)
as the sheriff (cảnh sát trưởng)
of the county (của hạt)
The county fair (Hội chợ hạt)
is held (được tổ chức)
every summer (mỗi mùa hè)
Our library system (Hệ thống thư viện của chúng tôi)
the entire county (toàn bộ hạt)
This species of bird (Loài chim này)
is known for (được biết đến với)
its colorful plumage (bộ lông sặc sỡ)
Several species (Một số loài)
are endangered (đang bị đe dọa)
due to habitat destruction (do phá hủy môi trường sống)
a new species (một loài mới)
in the rainforest (trong rừng mưa)
The conditions of the contract (Các điều kiện của hợp đồng)
clear and binding (rõ ràng và có tính ràng buộc)
had to work (phải làm việc)
in harsh conditions (trong điều kiện khắc nghiệt)
The road conditions (Điều kiện đường xá)
are poor (kém)
due to the snow (do tuyết)
a touch (một cái chạm)
on her shoulder (trên vai mình)
Don't touch (Đừng chạm vào)
the wet paint (sơn ướt)
has a gentle touch (rất nhẹ tay)
with flowers (với hoa)
The mass (Khối lượng)
of the sun (của mặt trời)
is incredibly large (rất lớn)
A mass of people (Một đám đông người)
attended the concert (đã tham dự buổi hòa nhạc)
The product (Sản phẩm)
is sold (được bán)
at mass market retailers (tại các cửa hàng bán lẻ đại chúng)
The social media platform (Nền tảng mạng xã hội)
millions of users (hàng triệu người dùng)
The train (Tàu)
at the platform (sân ga)
can create applications (có thể tạo ứng dụng)
on this platform (trên nền tảng này)
Keep the picture (Giữ bức tranh)
on the wall (trên tường)
drove straight home (lái xe thẳng về nhà)
after work (sau khi tan làm)
straight A's (toàn điểm A)
in all her subjects (trong tất cả các môn học của mình)
a serious condition (một tình trạng nghiêm trọng)
need to have (cần phải có)
a serious discussion (một cuộc thảo luận nghiêm túc)
about our future (về tương lai của chúng ta)
is serious about (rất nghiêm túc với)
her career in music (sự nghiệp âm nhạc của mình)
healthy eating habits (thói quen ăn uống lành mạnh)
should encourage students (nên khuyến khích học sinh)
to ask questions (đặt câu hỏi)
Positive feedback (Phản hồi tích cực)
can encourage employees (có thể khuyến khích nhân viên)
to perform better (làm việc tốt hơn)
The project (Dự án)
is due (đến hạn)
next Monday (vào thứ Hai tới)
is due (đến hạn)
at the end of the month (vào cuối tháng)
The success of the event (Sự thành công của sự kiện)
was due to (là nhờ vào)
the hard work of volunteers (sự chăm chỉ của các tình nguyện viên)
a fond memory (một ký ức đẹp)
of our vacation (về kỳ nghỉ của chúng tôi)
The computer (Máy tính)
8GB of RAM (8GB RAM)
for memory (cho bộ nhớ)
has a great memory (có trí nhớ rất tốt)
for names and faces (về tên và khuôn mặt)
The secretary (Thư ký)
scheduled a meeting (đã lên lịch một cuộc họp)
for next week (cho tuần tới)
worked as a secretary (đã làm thư ký)
before becoming a lawyer (trước khi trở thành luật sư)
The secretary (Thư ký)
took notes (đã ghi chú)
during the meeting (trong cuộc họp)
caught a cold (bị cảm lạnh)
last week (tuần trước)
The water (Nước)
was too cold (quá lạnh)
for swimming (để bơi)
Keep the food (Giữ thức ăn)
in the refrigerator (trong tủ lạnh)
For instance (Chẳng hạn)
let's consider (hãy xem xét)
the company's growth (sự tăng trưởng của công ty)
last year (trong năm ngoái)
This is an instance (Đây là một trường hợp)
where patience is required (cần có sự kiên nhẫn)
In this instance (Trong trường hợp này)
the guidelines (hướng dẫn)
The foundation of the house (Nền móng của ngôi nhà)
needs to be strong (cần phải vững chắc)
set up a foundation (đã thành lập một quỹ từ thiện)
to help underprivileged children (để giúp đỡ trẻ em kém may mắn)
the foundation (nền tảng)
of a good relationship (của một mối quan hệ tốt đẹp)
Please keep (Vui lòng để)
the clean and dirty clothes (quần áo sạch và bẩn)
decided to separate (quyết định chia tay)
after ten years of marriage (sau mười năm kết hôn)
The teacher (Giáo viên)
asked the students (yêu cầu học sinh)
to work in separate groups (làm việc trong các nhóm riêng biệt)
used a map (đã sử dụng bản đồ)
to find our way (để tìm đường)
to the hotel (đến khách sạn)
The treasure map (Bản đồ kho báu)
led them (dẫn họ)
to an isolated island (đến một hòn đảo biệt lập)
can see (có thể thấy)
the country's topography (địa hình của đất nước)
on this map (trên bản đồ này)
added some ice (thêm một ít đá)
to her drink (vào thức uống của mình)
to cool it down (để làm mát)
The pond (Hồ nước)
with a thin layer of ice (một lớp băng mỏng)
went ice skating (đi trượt băng)
on the frozen lake (trên hồ đóng băng)
The company (Công ty)
a statement (một tuyên bố)
regarding the merger (liên quan đến việc sáp nhập)
His statement (Lời khai của anh ấy)
was recorded (đã được ghi lại)
by the police (bởi cảnh sát)
The financial statement (Báo cáo tài chính)
a profit (lợi nhuận)
for the last quarter (trong quý vừa qua)
in natural resources (tài nguyên thiên nhiên)
dreams of becoming (mơ ước trở nên)
rich and famous (giàu có và nổi tiếng)
This dessert (Món tráng miệng này)
is too rich (quá ngậy)
for my taste (so với khẩu vị của tôi)
In his previous job, (Trong công việc trước đây,)
was a teacher (là một giáo viên)
The previous owner (Chủ nhân trước)
of the house (của ngôi nhà)
these trees (những cây này)
Refer to (Tham khảo)
the previous chapter (chương trước)
for more information (để biết thêm thông tin)
It's necessary (Việc là cần thiết)
to wear a helmet (đeo mũ bảo hiểm)
while riding a bike (khi đi xe đạp)
Please fill out (Vui lòng điền vào)
all the necessary paperwork (tất cả các giấy tờ cần thiết)
Taking breaks (Việc nghỉ ngơi)
is necessary (là cần thiết)
for maintaining productivity (để duy trì năng suất)
is studying engineering (đang học kỹ thuật)
at the university (tại đại học)
The bridge (Cây cầu)
is a marvel (là một kỳ quan)
of modern engineering (của kỹ thuật hiện đại)
Environmental engineering (Kỹ thuật môi trường)
focuses on (tập trung vào việc)
improving natural environments (cải thiện môi trường tự nhiên)
The heat (Cái nóng)
in the desert (ở sa mạc)
can be unbearable (có thể không thể chịu đựng nổi)
during the day (vào ban ngày)
Turn up the heat, (Tăng nhiệt độ lên,)
it's too cold (lạnh quá)
in here (ở đây)
The heat (Hơi ấm)
from the fire (từ ngọn lửa)
kept us warm (đã giữ ấm cho chúng tôi)
her entire art collection (toàn bộ bộ sưu tập nghệ thuật của mình)
to the museum (cho bảo tàng)
The library (Thư viện)
a vast collection of books (một bộ sưu tập sách khổng lồ)
His collection (Bộ sưu tập)
of vintage cars (xe cổ của anh ấy)
is impressive (rất ấn tượng)
The construction project (Dự án xây dựng)
will require (sẽ yêu cầu)
a lot of skilled labor (nhiều lao động có tay nghề)
went into labor (bắt đầu chuyển dạ)
early in the morning (vào sáng sớm)
Labor costs (Chi phí nhân công)
can significantly affect (có thể ảnh hưởng đáng kể đến)
the price of goods (giá cả hàng hóa)
The river's flow (Dòng chảy của sông)
is strong (rất mạnh)
after the rain (sau cơn mưa)
are studying (đang nghiên cứu)
the flow of traffic (luồng giao thông)
in urban areas (ở khu vực đô thị)
The flow of information (Dòng thông tin)
is essential (là thiết yếu)
for decision making (cho việc ra quyết định)
Please wipe the floor (Vui lòng lau sàn)
after spilling the water (sau khi làm đổ nước)
dropped his keys (đã làm rơi chìa khóa)
on the floor (xuống sàn)
The book (Quyển sách)
with a loud thud (với một tiếng 'bịch' lớn)
The restaurant (Nhà hàng)
a variety of dishes (nhiều món ăn đa dạng)
need to add (cần thêm)
more variety (sự đa dạng)
to our daily routine (vào thói quen hàng ngày)
Genetic diversity (Sự đa dạng di truyền)
is important (rất quan trọng)
for the variety of species (đối với sự đa dạng của các loài)
is her favorite subject (là môn học yêu thích của cô ấy)
in school (ở trường)
is doing his math homework (đang làm bài tập về nhà môn toán)
better math education (giáo dục toán học tốt hơn)
to improve problem-solving skills (để cải thiện kỹ năng giải quyết vấn đề)
booked a session (đã đặt một buổi)
with a personal trainer (với huấn luyện viên cá nhân)
The next session (Phiên họp tiếp theo)
of Congress (của Quốc hội)
in January (vào tháng Giêng)
The therapy session (Buổi trị liệu)
helped him (đã giúp anh ấy)
understand his emotions better (hiểu rõ hơn về cảm xúc của mình)
Nuclear energy (Năng lượng hạt nhân)
is a major source (là một nguồn chính)
of electricity (của điện)
The country (Quốc gia này)
is developing (đang phát triển)
its nuclear capabilities (năng lực hạt nhân của mình)
There are concerns (Có những lo ngại)
about nuclear waste disposal (về việc xử lý chất thải hạt nhân)
loves to roll down the hill (thích lăn xuống đồi)
in the park (trong công viên)
Please roll the dough (Vui lòng cán bột)
into a flat circle (thành một hình tròn dẹt)
The dice roll (Việc gieo xúc xắc)
decides your move (quyết định nước đi của bạn)
in the game (trong trò chơi)
The museum (Bảo tàng)
a collection of ancient artifacts (một bộ sưu tập các hiện vật cổ đại)
visited the art museum (đã thăm bảo tàng nghệ thuật)
last weekend (vào cuối tuần trước)
The museum (Bảo tàng)
on Sundays (các ngày Chủ nhật)
The edition (Ấn bản này)
to 500 copies (ở 500 bản)
have limited time (có thời gian hạn chế)
to complete this project (để hoàn thành dự án này)
are limited, (có hạn,)
so we must use them wisely (vì vậy chúng ta phải sử dụng chúng một cách khôn ngoan)
The constant noise (Tiếng ồn liên tục)
from the construction site (từ công trường xây dựng)
is annoying (rất khó chịu)
is in constant communication (liên lạc liên tục)
with her team (với đội của mình)
The speed of light (Tốc độ ánh sáng)
is a constant (là một hằng số)
in physics (trong vật lý)
The temperature (Nhiệt độ)
Please check (Vui lòng kiểm tra)
the water temperature (nhiệt độ nước)
before bathing the baby (trước khi tắm cho em bé)
The average room temperature (Nhiệt độ phòng trung bình)
is comfortable (thì dễ chịu)
for most people (với hầu hết mọi người)
The description (Sự mô tả)
of the suspect (về nghi phạm)
was very detailed (rất chi tiết)
Please provide (Vui lòng cung cấp)
a brief description (mô tả ngắn gọn)
of the incident (về vụ việc)
The job description (Bản mô tả công việc)
various responsibilities (nhiều trách nhiệm khác nhau)
The transition (Sự chuyển tiếp)
from high school to college (từ trường trung học lên đại học)
can be challenging (có thể đầy thách thức)
The country (Đất nước)
is undergoing (đang trải qua)
a political transition (một cuộc chuyển giao chính trị)
need to ensure (cần đảm bảo)
a smooth transition (một sự chuyển tiếp suôn sẻ)
for the new employees (cho các nhân viên mới)
pulled up a chair (kéo một cái ghế lại)
and sat down (và ngồi xuống)
The chair (Cái ghế)
is made of (được làm từ)
solid wood (gỗ nguyên khối)
Please return the chair (Vui lòng trả ghế)
to its original position (về vị trí ban đầu)
The dress (Chiếc váy)
has a floral pattern (có họa tiết hoa)
noticed a pattern (nhận thấy một quy luật)
in the test results (trong kết quả kiểm tra)
The wallpaper pattern (Họa tiết giấy dán tường)
the overall decor (tổng thể trang trí)
There is a high demand (Nhu cầu rất cao)
for organic products (đối với sản phẩm hữu cơ)
The workers (Công nhân)
better working conditions (điều kiện làm việc tốt hơn)
The demand (Nhu cầu)
for new housing (về nhà ở mới)
is increasing (đang tăng)
being stuck in traffic (bị kẹt xe)
expressed her hate (bày tỏ sự căm ghét)
for injustice (đối với sự bất công)
learned to hate (đã học cách căm ghét)
the war (chiến tranh)
The classroom (Lớp học)
was filled with students (chật kín học sinh)
New technology (Công nghệ mới)
is being integrated (đang được tích hợp)
into the classroom (vào lớp học)
decorated the classroom (trang trí lớp học)
with educational posters (bằng những tấm áp phích giáo dục)
served in the army (đã phục vụ trong quân đội)
for ten years (mười năm)
The army (Quân đội)
deployed troops (đã triển khai quân)
to the conflict zone (đến khu vực xung đột)
The army (Quân đội)
disaster relief and humanitarian aid (cứu trợ thảm họa và viện trợ nhân đạo)
The flowers (Hoa)
in spring (vào mùa xuân)
is a time (là thời điểm)
for new beginnings (cho những khởi đầu mới)
plan to start (dự định bắt đầu)
the garden project (dự án khu vườn)
in early spring (vào đầu mùa xuân)
is a senior manager (là quản lý cấp cao)
at the firm (tại công ty)
Senior citizens (Người cao tuổi)
receive a discount (được giảm giá)
at the museum (tại bảo tàng)
It's her senior year (Đây là năm cuối cấp của cô ấy)
in high school (ở trường trung học)
The wind (Gió)
blew through the trees (thổi qua hàng cây)
Wind turbines (Tua bin gió)
could hear (có thể nghe thấy)
the wind howling (tiếng gió rít)
at night (vào ban đêm)
received an award (đã nhận được một giải thưởng)
for her contributions (cho những đóng góp của mình)
to science (cho khoa học)
was honored (đã được vinh danh)
with a lifetime achievement award (với giải thưởng thành tựu trọn đời)
The committee (Ủy ban)
decided to award the scholarship (đã quyết định trao học bổng)
to the most deserving student (cho sinh viên xứng đáng nhất)
Clinical trials (Các thử nghiệm lâm sàng)
are necessary (là cần thiết)
before a new drug can be approved (trước khi một loại thuốc mới có thể được phê duyệt)
is undergoing (đang trải qua)
clinical treatment (điều trị lâm sàng)
for her condition (cho tình trạng của mình)
Clinical studies (Các nghiên cứu lâm sàng)
the effectiveness (hiệu quả)
of the new therapy (của liệu pháp mới)
found himself (thấy mình)
in trouble (gặp rắc rối)
with the law (với pháp luật)
If you need help, (Nếu bạn cần giúp đỡ,)
don't hesitate (đừng ngần ngại)
to call me (gọi cho tôi)
don't want you (không muốn bạn)
to get into trouble (gặp rắc rối)
Her outspokenness (Sự thẳng thắn của cô ấy)
sometimes causes trouble (đôi khi gây rắc rối)
at work (tại nơi làm việc)
received a good grade (nhận được điểm tốt)
on his math exam (trong bài thi toán)
teaches third grade (dạy lớp ba)
at the local elementary school (tại trường tiểu học địa phương)
The road (Con đường)
has a steep grade (có một độ dốc lớn)
near the summit (gần đỉnh)
The train (Tàu)
at the station (ga)
listens to (nghe)
her favorite music station (kênh âm nhạc yêu thích của mình)
on the radio (trên radio)
The police station (Đồn cảnh sát)
is just around the corner (ở ngay góc đường)
The wedding (Đám cưới)
was filled with (tràn ngập)
beautiful moments (những khoảnh khắc đẹp)
captured the moments (đã ghi lại những khoảnh khắc)
on his camera (bằng máy ảnh của mình)
Moments like these (Những khoảnh khắc như thế này)
remind us (nhắc nhở chúng ta)
to appreciate life (hãy trân trọng cuộc sống)
The surfer (Người lướt sóng)
rode a huge wave (đã cưỡi một con sóng khổng lồ)
to the shore (vào bờ)
The physicist (Nhà vật lý)
the wave theory of light (lý thuyết sóng của ánh sáng)
The wave of protests (Làn sóng biểu tình)
spread across the country (lan rộng khắp đất nước)
Please move (Làm ơn di chuyển)
this block of ice (tảng băng này)
to the cooler (vào thùng giữ lạnh)
The new apartment block (Khu chung cư mới)
is under construction (đang được xây dựng)
This software (Phần mềm này)
can block (có thể chặn)
all unwanted ads (tất cả các quảng cáo không mong muốn)
Compared to last year (So với năm ngoái)
our profits (lợi nhuận của chúng tôi)
have increased (đã tăng lên)
Her cooking skills (Kỹ năng nấu nướng của cô ấy)
are often compared to (thường được so sánh với)
a professional chef's (một đầu bếp chuyên nghiệp)
Compared with his brother (So với anh trai mình)
he is more outgoing (anh ấy cởi mở hơn)
Lifting weights regularly (Nâng tạ thường xuyên)
increases muscle strength (giúp tăng cường sức mạnh cơ bắp)
showed great strength (đã thể hiện sức mạnh to lớn)
during difficult times (trong những thời điểm khó khăn)
is our greatest strength (là sức mạnh lớn nhất của chúng ta)
The project (Dự án)
is in the planning phase (đang trong giai đoạn lập kế hoạch)
is a challenging phase of life (là một giai đoạn đầy thách thức của cuộc đời)
The clinical trial (Thử nghiệm lâm sàng)
has entered Phase III (đã bước vào Giai đoạn III)
shared a secret (chia sẻ một bí mật)
that nobody else knew (mà không ai khác biết)
The recipe (Công thức nấu ăn)
is a family secret (là một bí mật gia đình)
kept his plans secret (giữ bí mật kế hoạch của mình)
until the last moment (cho đến phút cuối)
Mount Everest (Núi Everest)
is the highest mountain (là ngọn núi cao nhất)
in the world (trên thế giới)
achieved the highest score (đạt điểm số cao nhất)
in the class (trong lớp)
The highest priority (Ưu tiên cao nhất)
is given to safety (được dành cho sự an toàn)
is leaving for New York (sẽ rời New York)
Leaving the job (Nghỉ việc)
was a difficult decision (là một quyết định khó khăn)
for him (đối với anh ấy)
mentioned leaving his job (đã đề cập đến việc nghỉ việc)
to start his own business (để bắt đầu kinh doanh riêng)
It was obvious (Rõ ràng là)
that he was lying (anh ấy đang nói dối)
The solution to the problem (Giải pháp cho vấn đề)
was not immediately obvious (không ngay lập tức rõ ràng)
Her happiness (Niềm hạnh phúc của cô ấy)
was obvious to everyone (hiện rõ trước mắt mọi người)
The storm (Cơn bão)
caused terrible damage (đã gây ra thiệt hại khủng khiếp)
had a terrible feeling (có một cảm giác tồi tệ)
that something was wrong (rằng có điều gì đó không ổn)
The food (Đồ ăn)
at that restaurant (ở nhà hàng đó)
was terrible (thật tệ)
The dancer's graceful motion (Chuyển động duyên dáng của vũ công)
captivated the audience (đã làm say đắm khán giả)
made a motion (ra hiệu)
to the waiter (cho người phục vụ)
for the bill (để tính tiền)
The machine's motion (Chuyển động của máy)
is controlled by (được điều khiển bởi)
a series of gears (một loạt bánh răng)
opened the window (mở cửa sổ)
to let in some fresh air (để cho không khí trong lành vào)
The bird (Con chim)
flew straight (bay thẳng)
into the window (vào cửa sổ)
looked out the window (nhìn ra ngoài cửa sổ)
at the rain pouring down (thấy mưa như trút nước)
cannot assume (không thể cho rằng)
everyone knows the rules (mọi người đều biết các quy tắc)
Let's not assume the worst (Chúng ta đừng cho rằng điều tồi tệ nhất)
without evidence (khi không có bằng chứng)
shouldn't assume (không nên cho rằng)
that everyone shares your opinion (mọi người đều có chung quan điểm với bạn)
The water cycle (Chu kỳ nước)
is essential (là thiết yếu)
for the Earth's ecosystem (cho hệ sinh thái của Trái Đất)
follows a strict training cycle (tuân theo một chu kỳ luyện tập nghiêm ngặt)
for the marathon (cho cuộc thi marathon)
The cycle of the moon (Chu kỳ của mặt trăng)
affects the tides of the ocean (ảnh hưởng đến thủy triều của đại dương)
The weather (Thời tiết)
changed suddenly (thay đổi đột ngột)
catching us off guard (khiến chúng tôi bất ngờ)
suddenly realized (đột nhiên nhận ra)
she had left her keys (cô ấy đã để quên chìa khóa)
at home (ở nhà)
The room (Căn phòng)
fell silent suddenly (đột ngột im bặt)
when the principal walked in (khi hiệu trưởng bước vào)
Western movies (Phim miền Tây)
often depict life (thường mô tả cuộc sống)
in the American frontier (ở biên giới Mỹ)
has a great interest in (rất quan tâm đến)
Western philosophy (triết học phương Tây)
Western cultures (Các nền văn hóa phương Tây)
have different norms and values (có những quy chuẩn và giá trị khác nhau)
had a broken arm (bị gãy tay)
from playing football (do chơi bóng đá)
Their relationship (Mối quan hệ của họ)
was broken (đã tan vỡ)
beyond repair (không thể hàn gắn)
ve broken my promise (đã thất hứa)
and I regret it deeply (và tôi vô cùng hối hận)
It's hard to define (Thật khó để xác định)
the exact moment (chính xác khoảnh khắc)
when everything changed (khi mọi thứ thay đổi)
How do you define success? (Bạn định nghĩa thành công như thế nào?)
It's hard to define (Thật khó để định nghĩa)
the exact moment (chính xác khoảnh khắc)
when childhood ends (khi tuổi thơ kết thúc)
embarked on a spiritual journey (bắt đầu một hành trình tâm linh)
to find inner peace (để tìm thấy sự bình yên nội tâm)
is a key practice (là một thực hành chính)
in many spiritual traditions (trong nhiều truyền thống tâm linh)
Spiritual leaders (Các nhà lãnh đạo tâm linh)
often emphasize (thường nhấn mạnh)
the importance of compassion (tầm quan trọng của lòng trắc ẩn)
Environmental concerns (Các mối quan ngại về môi trường)
are at the forefront (đang là tâm điểm)
of global discussions (của các cuộc thảo luận toàn cầu)
voiced her concerns (đã bày tỏ mối quan ngại của mình)
about the project's feasibility (về tính khả thi của dự án)
Health concerns (Những lo ngại về sức khỏe)
have led to increased interest (đã dẫn đến sự quan tâm ngày càng tăng)
in organic food (đối với thực phẩm hữu cơ)
The computer program (Chương trình máy tính)
generates random numbers (tạo ra các số ngẫu nhiên)
for the lottery (cho xổ số)
Random acts of kindness (Những hành động tử tế ngẫu nhiên)
can brighten someone's day (có thể làm một ngày của ai đó bừng sáng)
was selected (được chọn)
from a random sample (từ một mẫu ngẫu nhiên)
of the population (trong dân số)
The moon (Mặt trăng)
was full and bright (tròn và sáng)
in the night sky (trên bầu trời đêm)
landed on the moon (đã hạ cánh lên mặt trăng)
in 1969 (vào năm 1969)
The moon (Mặt trăng)
looked especially large (trông đặc biệt lớn)
It's dangerous (Rất nguy hiểm)
in such severe weather conditions (trong điều kiện thời tiết khắc nghiệt như vậy)
Wild animals (Động vật hoang dã)
can be dangerous (có thể trở nên nguy hiểm)
if provoked (nếu bị khiêu khích)
warned them of (đã cảnh báo họ về)
the dangerous chemicals (các hóa chất nguy hiểm)
in the lab (trong phòng thí nghiệm)
The forest (Khu rừng)
is home to (là nhà của)
a wide variety of trees (rất nhiều loại cây)
planted fruit trees (đã trồng cây ăn quả)
in our backyard (ở sân sau)
provide oxygen (cung cấp oxy)
and improve air quality (và cải thiện chất lượng không khí)
We're planning a trip (Chúng tôi đang lên kế hoạch cho một chuyến đi)
to Europe (đến châu Âu)
next summer (vào mùa hè tới)
The school (Nhà trường)
organized a field trip (đã tổ chức một chuyến đi thực tế)
to the museum (đến bảo tàng)
His first trip abroad (Chuyến đi nước ngoài đầu tiên của anh ấy)
was to Canada (là đến Canada)
The child (Đứa trẻ)
was curious about (tò mò về)
everything around him (mọi thứ xung quanh mình)
I'm curious (Tôi tò mò)
to know how it works (muốn biết nó hoạt động như thế nào)
Her curious nature (Bản tính tò mò của cô ấy)
led her to explore new places (đã dẫn dắt cô ấy khám phá những nơi mới)
The box (Cái hộp)
was too heavy (quá nặng)
for her to lift (để cô ấy có thể nhấc lên)
Heavy rain (Mưa lớn)
caused flooding (đã gây ra lũ lụt)
in the area (trong khu vực)
breathed a heavy sigh (thở phào một hơi)
of relief (nhẹ nhõm)
fly south (bay về phương nam)
for the winter (để tránh mùa đông)
The plane (Máy bay)
will fly (sẽ bay)
from New York to London (từ New York đến London)
always wanted (luôn muốn)
to fly a kite (thả diều)
on the beach (trên bãi biển)
noticed a change (nhận thấy một sự thay đổi)
in his behavior (trong hành vi của anh ấy)
hadn't noticed (đã không nhận ra)
that the time was so late (trời đã muộn như vậy)
noticed the bird (nhận thấy con chim)
as it flew past the window (khi nó bay qua cửa sổ)
begins in March (bắt đầu vào tháng Ba)
in the Northern Hemisphere (ở Bắc bán cầu)
Her birthday (Sinh nhật của cô ấy)
is in March (là vào tháng Ba)
The protest march (Cuộc tuần hành phản đối)
took place (diễn ra)
on the first of March (vào ngày mùng một tháng Ba)
The party (Bữa tiệc)
will start (sẽ bắt đầu)
in the evening (vào buổi tối)
prefer reading books (thích đọc sách)
in the quiet of the evening (trong sự yên tĩnh của buổi tối)
a beautiful sunset (một hoàng hôn tuyệt đẹp)
last evening (tối qua)
The room (Căn phòng)
was filled with (chứa đầy)
strange objects (những vật thể kỳ lạ)
collects objects (sưu tầm các vật thể)
from the beach (từ bãi biển)
for his artwork (cho tác phẩm nghệ thuật của mình)
Objects in the mirror (Các vật thể trong gương)
are closer (gần hơn)
than they appear (so với vẻ ngoài của chúng)
finally reached an agreement (cuối cùng đã đạt được một thỏa thuận)
after hours of discussion (sau nhiều giờ thảo luận)
The agreement (Thỏa thuận)
was signed (đã được ký)
by both parties (bởi cả hai bên)
Breaking this agreement (Vi phạm thỏa thuận này)
could have (có thể gây ra)
serious consequences (hậu quả nghiêm trọng)
is the best time (là thời gian tốt nhất)
to learn new skills (để học các kỹ năng mới)
spent his youth (đã dành cả tuổi trẻ của mình)
traveling around the world (để đi du lịch khắp thế giới)
The festival (Lễ hội)
is aimed at (hướng đến)
the youth of the city (giới trẻ của thành phố)
The police (Cảnh sát)
are investigating (đang điều tra)
a serious crime (một vụ án nghiêm trọng)
Crime rates (Tỷ lệ tội phạm)
have fallen (đã giảm)
in the city (trong thành phố)
was found guilty of (bị kết tội)
committing a crime (phạm pháp)
explained the plan (đã giải thích kế hoạch)
in great detail (một cách rất chi tiết)
The artist (Người họa sĩ)
every detail (mọi chi tiết)
of the landscape (của phong cảnh)
Please provide (Vui lòng cung cấp)
more detail (thêm chi tiết)
about the incident (về vụ việc)
That restaurant (Nhà hàng đó)
is too expensive (quá đắt)
for our budget (so với ngân sách của chúng tôi)
Luxury cars (Xe hơi sang trọng)
are often (thường)
very expensive (rất đắt)
very expensive jewelry (trang sức rất đắt tiền)
The storm (Cơn bão)
significant damage (thiệt hại đáng kể)
to the building (cho tòa nhà)
need to assess the damage (cần đánh giá thiệt hại)
before making repairs (trước khi tiến hành sửa chữa)
Water damage (Thiệt hại do nước)
can be very costly (có thể rất tốn kém)
to fix (để khắc phục)
need to fix (cần sửa)
the leak in the roof (chỗ rò rỉ trên mái nhà)
fix my computer? (sửa máy tính của tôi được không?)
It's not starting (Nó không khởi động)
need to fix my bike (cần sửa xe đạp)
before I can ride it to work (trước khi có thể đi làm bằng nó)
is often depicted as (thường được miêu tả là)
a place of peace and serenity (một nơi bình yên và thanh thản)
The view from the mountain (Khung cảnh từ trên núi)
was like (giống như)
heaven on earth (thiên đường trên mặt đất)
Many people (Nhiều người)
hope to find heaven (hy vọng sẽ lên thiên đường)
after they die (sau khi qua đời)
Please select (Vui lòng chọn)
your preferred option (phương án bạn ưa thích)
Only a select few (Chỉ một vài người được chọn)
were invited (được mời)
to the dinner (đến bữa tối)
the right tool (đúng công cụ)
for the job (cho công việc)
is a constant struggle (là một cuộc đấu tranh không ngừng)
between good and evil (giữa thiện và ác)
continues to struggle (tiếp tục vật lộn)
with her health issues (với các vấn đề sức khỏe của mình)
Many small businesses (Nhiều doanh nghiệp nhỏ)
struggle to survive (phải vật lộn để tồn tại)
in the first year (trong năm đầu tiên)
The laboratory (Phòng thí nghiệm)
was equipped with (được trang bị)
the latest equipment (các thiết bị mới nhất)
all equipment (tất cả thiết bị)
before starting the experiment (trước khi bắt đầu thí nghiệm)
Safety equipment (Thiết bị an toàn)
is mandatory (là bắt buộc)
in construction sites (tại các công trường xây dựng)
is just a step (chỉ là một bước đệm)
towards success (đến thành công)
The project (Dự án)
ended in failure (đã kết thúc trong thất bại)
his inability to find a solution (việc không thể tìm ra giải pháp)
as a personal failure (là một thất bại cá nhân)
planted roses (đã trồng hoa hồng)
in the garden (trong vườn)
The garden (Khu vườn)
was a beautiful sight (là một cảnh tượng tuyệt đẹp)
in spring (vào mùa xuân)
The botanical garden (Vườn bách thảo)
is home to (là nơi sinh sống của)
many exotic plants (nhiều loài thực vật ngoại lai)
The manager (Quản lý)
approved the budget (đã phê duyệt ngân sách)
for the project (cho dự án)
is the manager (là trưởng phòng)
of the marketing department (của bộ phận tiếp thị)
A good manager (Một người quản lý giỏi)
knows how (biết cách)
to motivate their team (động viên đội nhóm của mình)
was sentenced to (bị kết án)
five years in prison (năm năm tù)
The prison (Nhà tù này)
was known for (nổi tiếng với)
its harsh conditions (điều kiện khắc nghiệt)
visited the old prison, (đã thăm nhà tù cũ,)
now a museum (nay là một bảo tàng)
feed the cat (cho mèo ăn)
twice a day (hai lần một ngày)
The documentary (Bộ phim tài liệu)
how lions feed (cách sư tử kiếm ăn)
in the wild (trong tự nhiên)
should feed your mind (nên nuôi dưỡng tâm trí mình)
with positive thoughts (bằng những suy nghĩ tích cực)
The wild landscape (Cảnh quan hoang dã)
was breathtaking (thật ngoạn mục)
a wild imagination (một trí tưởng tượng bay bổng)
Wild animals (Động vật hoang dã)
can be dangerous (có thể nguy hiểm)
The valley (Thung lũng)
was filled with fog (đầy sương mù)
in the morning (vào buổi sáng)
went hiking (đã đi bộ đường dài)
in the valley (trong thung lũng)
The river (Dòng sông)
through the valley (qua thung lũng)
need to expand our operations (cần mở rộng hoạt động)
to new markets (sang các thị trường mới)
The company (Công ty)
has plans (có kế hoạch)
to expand its product line (mở rộng dòng sản phẩm của mình)
Reading extensively (Đọc nhiều)
can expand (có thể mở rộng)
your vocabulary (vốn từ vựng của bạn)
The fire (Ngọn lửa)
spread quickly (lan nhanh)
through the building (khắp tòa nhà)
had to fire him (phải sa thải anh ta)
for breaking company policies (vì vi phạm chính sách công ty)
The fire alarm (Chuông báo cháy)
went off, (vang lên,)
causing panic (gây hoảng loạn)
throughout the office (khắp văn phòng)
spend too much time (dành quá nhiều thời gian)
looking at a computer screen (nhìn vào màn hình máy tính)
The movie (Bộ phim)
will be shown (sẽ được chiếu)
on the big screen (trên màn ảnh rộng)
at the theater tonight (tại rạp tối nay)
used a green screen (đã sử dụng phông xanh)
to create the background effects (để tạo hiệu ứng nền)
in the movie (trong phim)
The climate (Khí hậu)
in this region (ở vùng này)
is very humid (rất ẩm)
Climate change (Biến đổi khí hậu)
a critical global issue (một vấn đề toàn cầu nghiêm trọng)
need to adapt (cần phải thích nghi)
to the changing climate (với khí hậu đang thay đổi)
The company (Công ty)
has grown in scale (đã phát triển về quy mô)
Please weigh (Làm ơn)
the package (đặt gói hàng)
on the scale (lên cân)
The scale of the disaster (Quy mô của thảm họa)
was unprecedented (là chưa từng có)
The results (Kết quả)
of the experiment (của thí nghiệm)
were surprising (thật đáng ngạc nhiên)
are waiting for (đang chờ)
the election results (kết quả bầu cử)
The results (Kết quả)
a significant improvement (một sự cải thiện đáng kể)
Can we get (Làm ơn cho chúng tôi)
the bill, (hóa đơn,)
The bill (Dự luật)
was passed (đã được thông qua)
by the Senate (bởi Thượng viện)
forgot to pay (đã quên thanh toán)
his electricity bill (hóa đơn tiền điện)
The job (Công việc này)
many growth opportunities (nhiều cơ hội phát triển)
must seize (phải nắm bắt)
any opportunities (mọi cơ hội)
that come our way (đến với mình)
The city (Thành phố)
is full of opportunities (đầy cơ hội)
for young entrepreneurs (cho các doanh nhân trẻ)
managed to stop (đã cầm được)
the blood loss (máu)
Blood donations (Hiến máu)
can save lives (có thể cứu người)
His blood type (Nhóm máu của anh ấy)
O positive (O+)
The play (Vở kịch)
is now on stage (hiện đang được công diễn trên sân khấu)
at the local theater (tại nhà hát địa phương)
always dreamed of (luôn mơ ước)
performing on stage (được biểu diễn trên sân khấu)
The director (Đạo diễn)
decided to stage the play (đã quyết định dàn dựng vở kịch)
in a modern setting (trong bối cảnh hiện đại)
is a private matter, (là chuyện riêng tư,)
and it should not be discussed (và không nên được thảo luận)
prefers to keep (thích giữ)
his life private (cuộc sống của mình riêng tư)
is my private diary, (là nhật ký riêng của tôi,)
please don't read it (xin đừng đọc)
has a hearing problem (có vấn đề về thính giác)
and uses a hearing aid (và sử dụng máy trợ thính)
The court (Tòa án)
scheduled a hearing (đã lên lịch một phiên điều trần)
for next week (vào tuần tới)
Her hearing (Thính giác của cô ấy)
is very acute (rất nhạy bén)
recently started (gần đây đã bắt đầu)
a new job (một công việc mới)
has been feeling (đã cảm thấy)
a lot better (khỏe hơn nhiều)
recently moved (mới chuyển đến)
into the neighborhood (khu này gần đây)
The leaders (Lãnh đạo)
of the two countries (hai nước)
Young leaders (Các nhà lãnh đạo trẻ)
are emerging (đang nổi lên)
in the community (trong cộng đồng)
The company's leaders (Các lãnh đạo của công ty)
are considering (đang xem xét)
a merger (việc sáp nhập)
Without the proper context, (Nếu không có bối cảnh phù hợp,)
the statement (phát biểu)
can be misleading (có thể gây hiểu lầm)
The historical context (Bối cảnh lịch sử)
is important (rất quan trọng)
for understanding the novel (để hiểu được cuốn tiểu thuyết)
In the context of the meeting, (Trong bối cảnh của cuộc họp,)
his comments (bình luận của anh ta)
were inappropriate (là không phù hợp)
The actual cost (Chi phí thực tế)
was much higher (cao hơn nhiều)
than the estimate (so với ước tính)
His story (Câu chuyện của anh ấy)
is different from (khác với)
the actual events (những sự kiện thực tế)
We need to compare (Chúng ta cần so sánh)
the planned budget (ngân sách dự kiến)
against the actual expenses (với chi tiêu thực tế)
has multiple responsibilities (có nhiều trách nhiệm)
at work (tại nơi làm việc)
The accident (Vụ tai nạn)
multiple injuries (nhiều thương tích)
multiple degrees (nhiều bằng cấp)
in engineering (về kỹ thuật)
watched the news (đã xem tin tức)
on the local channel (trên kênh địa phương)
Please change the channel (Làm ơn chuyển kênh)
to watch the football game (để xem trận bóng đá)
The news channel (Kênh tin tức này)
is very popular (rất nổi tiếng)
for its unbiased reporting (vì đưa tin khách quan)
passed a new law (đã thông qua một đạo luật mới)
to improve healthcare (để cải thiện chăm sóc sức khỏe)
The member of Congress (Thành viên Quốc hội)
is holding (đang tổ chức)
a town hall meeting (một cuộc họp với cử tri)
The proposal (Đề xuất)
will be presented to Congress (sẽ được trình lên Quốc hội)
next month (vào tháng tới)
The meeting (Cuộc họp)
lasted an hour longer (kéo dài hơn một giờ)
than expected (so với dự kiến)
have to leave (phải rời đi)
in an hour (trong một giờ nữa)
We will start the meeting (Chúng ta sẽ bắt đầu cuộc họp)
in an hour (trong một giờ nữa)
I expect (Tôi mong)
to hear from them (sẽ sớm nhận được tin từ họ)
What do you expect (Bạn mong đợi)
me to do? (tôi làm gì?)
They expect (Họ kỳ vọng)
the project to be finished (dự án sẽ hoàn thành)
by the end of the year (vào cuối năm)
The professor (Giáo sư)
gave a lecture (đã có một bài giảng)
on the importance of sustainable development (về tầm quan trọng của phát triển bền vững)
is a professor of history (là giáo sư lịch sử)
at the university (tại trường đại học)
received an email (nhận được email)
from his professor (từ giáo sư của mình)
about his thesis (về luận văn)
turned the key (đã vặn chìa khóa)
in the lock (trong ổ khóa)
to look at him (nhìn anh ấy)
The milk (Sữa)
has turned sour (đã bị chua)
The company (Công ty)
is moving (đang đi)
in a new direction (theo một hướng mới)
to reach the exit (để đến lối ra)
has a good sense of direction (có khả năng định hướng tốt)
Their mission (Nhiệm vụ của họ)
is to provide aid (là cung cấp viện trợ)
to those in need (cho những người gặp khó khăn)
was sent (được cử đi)
on a secret mission (làm một nhiệm vụ bí mật)
The space mission (Nhiệm vụ không gian)
was a success (đã thành công)
She's building (Cô ấy đang xây dựng)
her professional network (mạng lưới quan hệ chuyên nghiệp của mình)
The network of roads (Mạng lưới đường bộ)
easy transportation (việc di chuyển)
Their network (Mạng của họ)
is down (bị sập)
due to technical issues (do sự cố kỹ thuật)
a beautiful blue dress (một chiếc váy màu xanh tuyệt đẹp)
a bit blue (hơi buồn)
The police (Cảnh sát)
the suspect (nghi phạm)
called the police (đã gọi cảnh sát)
to report a theft (để báo một vụ trộm)
are investigating (đang điều tra)
the crime scene (hiện trường vụ án)
has excellent communication skills (có kỹ năng giao tiếp xuất sắc)
She's working to improve (Cô ấy đang nỗ lực cải thiện)
her leadership skills (kỹ năng lãnh đạo của mình)
Technical skills (Kỹ năng kỹ thuật)
are important (rất quan trọng)
in this job (trong công việc này)
The world (Thế giới)
is constantly changing (đang không ngừng thay đổi)
She's changing (Cô ấy đang chuyển)
her major (chuyên ngành)
to biology (sang sinh học)
Changing the oil regularly (Thay dầu định kỳ)
is important (rất quan trọng)
for car maintenance (cho việc bảo dưỡng xe hơi)
The structure of the building (Kết cấu của tòa nhà)
is solid (rất vững chắc)
the structure of the essay (cấu trúc của bài luận)
The course (Khóa học)
has a very clear structure (có một cấu trúc rất rõ ràng)
plan to develop (có kế hoạch phát triển)
a new product (một sản phẩm mới)
The company (Công ty)
plans to develop (có kế hoạch phát triển)
a new software platform (một nền tảng phần mềm mới)
develop their language skills (phát triển kỹ năng ngôn ngữ)
at an early age (từ khi còn nhỏ)
to open it (để mở)
You need to pull harder (Bạn cần kéo mạnh hơn)
to start the engine (để khởi động động cơ)
Let's pull a prank (Chúng ta hãy chơi khăm)
on our friend (bạn mình)
the link (đường link)
to the document (đến tài liệu)
found a link (đã tìm thấy một mối liên hệ)
between the two cases (giữa hai vụ án)
to visit our website (để truy cập trang web của chúng tôi)
downloaded a new app (đã tải một ứng dụng mới)
for editing photos (để chỉnh sửa ảnh)
This app (Ứng dụng này)
helps you track (giúp bạn theo dõi)
your fitness goals (các mục tiêu thể chất của mình)
She's using (Cô ấy đang sử dụng)
a language learning app (một ứng dụng học ngôn ngữ)
is taking an English course (đang tham gia một khóa học tiếng Anh)
English literature (Văn học Anh)
is my favorite subject (là môn học yêu thích của tôi)
speaks English (nói tiếng Anh)
felt a sharp pain (cảm thấy đau nhói)
in her leg (ở chân)
The medication (Thuốc)
helped ease the pain (đã giúp làm dịu cơn đau)
stayed up late (đã thức khuya)
working on her project (để làm dự án của mình)
The company (Công ty)
stands by (luôn tuân thủ)
its core values (các giá trị cốt lõi của mình)
Teaching children good values (Dạy cho trẻ những giá trị tốt đẹp)
is important (là điều quan trọng)
Her values (Các giá trị của cô ấy)
align with (phù hợp với)
those of the organization (các giá trị của tổ chức)
totally agree (hoàn toàn đồng ý)
with you (với bạn)
That movie (Bộ phim đó)
was totally awesome (thực sự tuyệt vời)
was totally unaware (hoàn toàn không biết gì)
of the situation (về tình hình)
has a strong faith (có một niềm tin mãnh liệt)
in God (vào Chúa)
and you'll find a way (và bạn sẽ tìm ra con đường)
Their faith in each other (Niềm tin của họ dành cho nhau)
was unshakeable (không thể lay chuyển)
left some positive comments (đã để lại một vài bình luận tích cực)
on my blog post (trên bài đăng blog của tôi)
The teacher's comments (Những nhận xét của giáo viên)
on my essay (về bài luận của tôi)
were very helpful (rất hữu ích)
Please read the comments (Vui lòng đọc các bình luận)
for more information (để biết thêm thông tin)
on Maple Street (trên phố Maple)
The street (Đường phố)
was crowded with people (đông nghịt người)
Street food (Đồ ăn đường phố)
can be really delicious (có thể rất ngon)
for the answer (câu trả lời)
The police (Cảnh sát)
are conducting a search (đang tiến hành một cuộc tìm kiếm)
for the missing child (đứa trẻ mất tích)
is a serious disease (là một căn bệnh nghiêm trọng)
that requires early detection (đòi hỏi phải được phát hiện sớm)
Research on cancer treatment (Nghiên cứu về điều trị ung thư)
has advanced significantly (đã có những bước tiến đáng kể)
Skin cancer (Ung thư da)
can be prevented (có thể được ngăn chặn)
by protecting the skin (bằng cách bảo vệ da)
from excessive sun exposure (khỏi việc tiếp xúc quá mức với ánh nắng mặt trời)
a crazy idea, (một ý tưởng điên rồ,)
but it (nhưng nó)
actually worked (thực sự hiệu quả)
if you think (nếu bạn nghĩ)
I'm going to do that! (tôi sẽ làm điều đó!)
The party (Bữa tiệc)
was absolutely crazy (thực sự điên rồ)
last night (tối qua)
the world record (kỷ lục thế giới)
for the 100 meters sprint (cho cự ly chạy 100 mét)
your name and address (tên và địa chỉ của bạn)
The device (Thiết bị)
can record (có thể ghi lại)
both audio and video (cả âm thanh và hình ảnh)
to save your work (lưu công việc của bạn)
managed to save (đã tiết kiệm)
enough money (đủ tiền)
to buy a new car (để mua một chiếc xe mới)
by fixing leaky faucets (bằng cách sửa chữa vòi nước bị rò rỉ)
The magician's performance (Màn trình diễn của ảo thuật gia)
was simply incredible (đơn giản là không thể tin được)
how much she has achieved (khi cô ấy đã đạt được bao nhiêu)
in a year (trong một năm)
The view (Cảnh)
from the top of the mountain (từ đỉnh núi)
is incredible (là không thể tin nổi)
The entire nation (Cả quốc gia)
celebrated the victory (đã ăn mừng chiến thắng)
Healthcare (Chăm sóc sức khỏe)
is a major issue (là một vấn đề lớn)
for the nation (cho quốc gia)
The president (Tổng thống)
addressed the nation (đã phát biểu trước quốc gia)
last night (tối qua)
This dress (Bộ váy này)
is made of (được làm từ)
silk material (chất liệu lụa)
The teacher (Giáo viên)
a lot of educational material (rất nhiều tài liệu giáo dục)
The examination (Kỳ thi)
will cover (sẽ bao gồm)
all the material (tất cả tài liệu)
we've studied this semester (chúng ta đã học trong học kỳ này)
You have the choice (Bạn có sự lựa chọn)
between tea and coffee (giữa trà và cà phê)
a difficult choice (một lựa chọn khó khăn)
that could change her life (có thể thay đổi cuộc đời mình)
Your choice of paths (Sự lựa chọn của bạn về các con đường)
could lead you (có thể dẫn bạn)
to different destinations (đến các điểm đến khác nhau)
That was a weird noise (Đó là một tiếng động kỳ lạ)
coming from the attic (phát ra từ gác mái)
some weird habits (một số thói quen kỳ quặc)
that are hard to understand (khó hiểu)
a really weird dream (một giấc mơ thực sự kỳ lạ)
last night (tối qua)
The cake (Chiếc bánh)
was in the shape of a heart (có hình dạng của một trái tim)
He's in great shape (Anh ấy có sức khỏe tốt)
because he exercises daily (vì anh ấy tập thể dục hàng ngày)
The shape of the moon (Hình dạng của mặt trăng)
is a crescent (là hình lưỡi liềm)
board games (trò chơi trên bàn)
all evening (cả buổi tối)
Video games (Trò chơi video)
can be (có thể)
both fun and educational (vừa vui vẻ vừa giáo dục)
The Olympic Games (Thế vận hội Olympic)
are held (được tổ chức)
every four years (mỗi bốn năm một lần)
Freedom of speech (Tự do ngôn luận)
is a fundamental human right (là một quyền cơ bản của con người)
After years of struggle, (Sau nhiều năm đấu tranh,)
the country (đất nước)
won its freedom (đã giành được tự do)
Retirement (Việc nghỉ hưu)
gave him the freedom (đã cho anh ấy tự do)
to travel the world (đi du lịch khắp thế giới)
We're having fish (Tối nay chúng tôi ăn cá)
for dinner tonight
This pond (Ao này)
is stocked with (được nuôi)
various types of fish (nhiều loại cá khác nhau)
The fish tank (Bể cá)
needs cleaning (cần được làm sạch)
everything will be okay (mọi thứ sẽ ổn)
about the details (về các chi tiết)
right now (ngay bây giờ)
that the new policy (rằng chính sách mới)
may harm their business (có thể làm hại đến doanh nghiệp của họ)
I need to get some sleep (Tôi cần phải ngủ một chút)
before the long drive tomorrow (trước chuyến lái xe dài ngày mai)
Too much screen time (Quá nhiều thời gian sử dụng màn hình)
before bed (trước khi đi ngủ)
can disrupt your sleep (có thể làm gián đoạn giấc ngủ của bạn)
A regular sleep schedule (Một lịch trình ngủ đều đặn)
helps improve (giúp cải thiện)
overall health (sức khỏe tổng thể)
extra cheese (thêm phô mai)
on your pizza? (vào pizza của mình không?)
extra hours (thêm giờ)
to finish this project (để hoàn thành dự án này)
extra effort (nỗ lực thêm)
to help her students understand (để giúp học sinh của mình hiểu)
the internet setting (cài đặt internet)
on your phone (trên điện thoại của bạn)
The dinner table (Bàn ăn)
was set (được sắp xếp)
in an elegant setting (trong một không gian sang trọng)
Adjusting the setting (Điều chỉnh cài đặt)
can optimize (có thể tối ưu)
the device's performance (hiệu suất của thiết bị)
The press (Báo chí)
has been covering the event (đã đưa tin về sự kiện)
extensively (rộng rãi)
to start the machine (để khởi động máy)
before the meeting (trước cuộc họp)
to the movies (xem phim với nhau)
The expiration date (Ngày hết hạn)
is printed (được in)
on the package (trên bao bì)
to meet you (được gặp bạn)
The ceremony (Lễ kỷ niệm)
was held (được tổ chức)
in honor of the war heroes (để tôn vinh các anh hùng chiến tranh)
with honor and integrity (với danh dự và liêm chính)
what to wear tonight (mặc gì tối nay)
a location (một địa điểm)
for our next meeting (cho cuộc họp tiếp theo của chúng ta)
It's hard to decide (Thật khó để quyết định)
without all the facts (khi không có đủ thông tin)
The sun (Mặt trời)
in the east (ở phía đông)
Sun exposure (Phơi nắng)
can damage (có thể làm hại)
your skin (làn da của bạn)
Always wear sunscreen (Luôn thoa kem chống nắng)
to protect yourself (để bảo vệ bản thân)
from the sun (khỏi ánh nắng mặt trời)
Please connect (Vui lòng kết nối)
the printer (máy in)
to the computer (với máy tính)
Social media (Mạng xã hội)
has changed the way (đã thay đổi cách)
we connect with others (chúng ta kết nối với người khác)
It's important (Việc rất quan trọng)
to connect with nature (kết nối với thiên nhiên)
for mental health (cho sức khỏe tinh thần)
The topic of today's discussion (Chủ đề của cuộc thảo luận hôm nay)
is climate change (là biến đổi khí hậu)
a controversial topic (một chủ đề gây tranh cãi)
for her thesis (cho luận văn của mình)
this is getting too heated (cuộc thảo luận này đang trở nên quá nóng)
in the park (trong công viên)
in the garage (trong nhà để xe)
The park (Công viên)
is beautiful (rất đẹp)
in the fall (vào mùa thu)
in local politics (trong chính trị địa phương)
Discussing politics (Thảo luận về chính trị)
can sometimes lead to (đôi khi có thể dẫn đến)
heated arguments (tranh cãi nảy lửa)
a degree in politics (bằng về chính trị)
Japan (Nhật Bản)
is located (nằm)
to the east of China (ở phía đông của Trung Quốc)
the sunrise (mặt trời mọc)
in the east (ở hướng đông)
The wind (Gió)
is coming (đang thổi)
from the east (từ phía đông)
a happy birthday (sinh nhật vui vẻ)
My wish (Ước mơ của tôi)
is to travel around the world (là đi du lịch vòng quanh thế giới)
before blowing out the candles (trước khi thổi tắt nến)
from university (đại học)
next year (vào năm tới)
After I graduate, (Sau khi tôi tốt nghiệp,)
my own business
He's a recent graduate (Anh ấy là sinh viên mới tốt nghiệp)
with a degree in engineering (với bằng kỹ sư)
Times Square (Times Square)
is a major commercial intersection (là một ngã tư thương mại lớn)
in New York (ở New York)
Draw (Vẽ)
a square (một hình vuông)
on the board (trên bảng)
The room (Phòng)
is 100 square meters (có diện tích 100 mét vuông)
in size
The candidate (Ứng cử viên)
launched his campaign (đã khởi động chiến dịch)
for mayor (tranh cử chức thị trưởng)
They started a campaign (Họ bắt đầu một chiến dịch)
to raise awareness (để nâng cao nhận thức)
about climate change (về biến đổi khí hậu)
The advertising campaign (Chiến dịch quảng cáo)
was a huge success (đã thành công lớn)
The medication (Thuốc)
has (có)
several side effects (một số tác dụng phụ)
Climate change effects (Ảnh hưởng của biến đổi khí hậu)
are being felt (đang được cảm nhận)
worldwide (trên toàn thế giới)
The effects of the new law (Ảnh hưởng của luật mới)
will be monitored (sẽ được theo dõi)
closely (chặt chẽ)
We need to stop for gas (Chúng ta cần dừng lại đổ xăng)
before we hit the road (trước khi lên đường)
Natural gas (Khí tự nhiên)
is used for (được sử dụng để)
heating and cooking (sưởi ấm và nấu ăn)
The gas station (Trạm xăng)
is just around the corner (ngay ở góc đường)
a native speaker (người bản xứ nói)
of Spanish (tiếng Tây Ban Nha)
The native plants (Các loại cây bản địa)
are well adapted (thích nghi tốt)
to the local climate (với khí hậu địa phương)
to his native country (nước bản địa của mình)
after many years abroad (sau nhiều năm ở nước ngoài)
the battery is low (pin đang yếu)
The restaurant (Nhà hàng)
will charge a fee (sẽ tính phí)
for water (tiền nước)
The soldier (Người lính)
led the charge (dẫn đầu cuộc tấn công)
against the enemy (chống lại kẻ thù)
a poor family (một gia đình nghèo)
The poor lighting (Ánh sáng kém)
made it hard to read (khiến việc đọc sách trở nên khó khăn)
has a poor sense of direction (có khả năng phán đoán hướng đi kém)
The temperature (Nhiệt độ)
will drop (sẽ giảm)
overnight (qua đêm)
at the laundry (đến tiệm giặt)
at the next corner (ở góc đường tiếp theo)
The doctor (Bác sĩ)
prescribed a new drug (đã kê đơn một loại thuốc mới)
for her condition (cho tình trạng của cô ấy)
Drug abuse (Lạm dụng ma túy)
is (là)
a serious problem (một vấn đề nghiêm trọng)
The pharmaceutical company (Công ty dược phẩm)
has developed a new drug (đã phát triển một loại thuốc mới)
to treat cancer (để điều trị ung thư)
spent the day (đã dành cả ngày)
at the sea (ở biển)
The sea (Biển)
was calm (yên bình)
sea animals (động vật biển)
Summer (Mùa hè)
is (là)
my favorite season (mùa yêu thích của tôi)
This fruit (Loại quả này)
is in season (đang vào mùa)
season the meat (ướp thịt)
with salt and pepper (với muối và tiêu)
was taken to the hospital (đã được đưa đến bệnh viện)
for surgery (để phẫu thuật)
The hospital (Bệnh viện)
is on the next street (ở phố tiếp theo)
works as a nurse (làm việc như một y tá)
in a local hospital (tại một bệnh viện địa phương)
The property prices (Giá bất động sản)
have increased (đã tăng)
recently (gần đây)
Trespassing on private property (Xâm nhập trái phép vào tài sản riêng)
is illegal (là bất hợp pháp)
put their property on the market (đã đưa tài sản của mình ra thị trường)
last month (vào tháng trước)
Scientists (Các nhà khoa học)
are studying (đang nghiên cứu)
the origins of the universe (nguồn gốc của vũ trụ)
The universe (Vũ trụ)
is constantly expanding (đang không ngừng mở rộng)
There are (Có)
billions of galaxies (hàng tỷ thiên hà)
in the universe (trong vũ trụ)
a lot of stress (rất nhiều áp lực)
at work (tại công việc)
Exercise (Tập thể dục)
can help reduce (có thể giúp giảm)
stress (căng thẳng)
Stress (Căng thẳng)
affects (ảnh hưởng đến)
your health (sức khỏe của bạn)
have walked (đã đi bộ)
a thousand miles (một nghìn dặm)
A picture (Một bức ảnh)
is worth a thousand words (đáng giá ngàn lời)
There are (Có)
a thousand reasons (hàng nghìn lý do)
to be happy (để cảm thấy hạnh phúc)
The river (Con sông)
is very wide (rất rộng)
a wide range of products (một loạt sản phẩm rộng lớn)
a double espresso (một ly espresso gấp đôi)
The recipe (Công thức)
calls for (yêu cầu)
double the amount of sugar (gấp đôi lượng đường)
hope to double their sales (hy vọng gấp đôi doanh số bán hàng của mình)
this year (trong năm nay)
The diamonds (Kim cương)
were extracted (được khai thác)
from a mine (từ một mỏ)
That book (Quyển sách đó)
is mine (là của tôi)
discovered (đã phát hiện)
a new coal mine (một mỏ than mới)
can throw a ball (có thể ném một quả bóng)
very far (rất xa)
Don't throw (Đừng vứt)
your clothes (quần áo của bạn)
on the floor (xuống sàn)
If you throw that glass on the floor (Nếu bạn ném cái ly đó xuống sàn)
it will break (nó sẽ vỡ)
The majority of people (Đa số mọi người)
agree with the decision (đồng ý với quyết định)
won (đã thắng)
by a large majority (với phần lớn áp đảo)
A majority vote (Số phiếu đa số)
is needed (là cần thiết)
to pass the law (để thông qua luật)
The news (Tin tức)
spread quickly (lan truyền nhanh chóng)
through the town (khắp thị trấn)
The disease (Bệnh)
can spread (có thể lan truyền)
through direct contact (qua tiếp xúc trực tiếp)
The virus (Virus)
can spread easily (có thể lây lan dễ dàng)
in crowded conditions (trong điều kiện đông người)
have the option (có quyền)
to decline the offer (từ chối lời đề nghị)
Choosing the best option (Việc chọn lựa phương án tốt nhất)
can be difficult (có thể khó khăn)
have the option (có lựa chọn)
to choose between tea and coffee (giữa trà và cà phê)
has worked there (đã làm việc ở đó)
for decades (hàng thập kỷ)
Fashion trends (Xu hướng thời trang)
have changed (đã thay đổi)
over the decades (qua các thập kỷ)
Many decades (Nhiều thập kỷ)
have passed (đã trôi qua)
since the war (kể từ khi cuộc chiến kết thúc)
what the future holds (tương lai sẽ ra sao)
The beauty of nature (Vẻ đẹp của thiên nhiên)
is (là)
a constant wonder (một điều kỳ diệu không ngừng)
why the sky is blue (tại sao bầu trời lại có màu xanh)
wrote a letter of complaint (đã viết một lá thư phàn nàn)
to the manager (gửi cho người quản lý)
received a letter (nhận được một lá thư)
from an old friend (từ một người bạn cũ)
sealed the letter (đã ni phong lá thư)
with wax (bằng sáp)
This is (Đây là)
the most effective method (phương pháp hiệu quả nhất)
for learning a new language (để học một ngôn ngữ mới)
The teacher (Giáo viên)
introduced (đã giới thiệu)
a new teaching method (một phương pháp giảng dạy mới)
need to find (cần tìm)
a better method (một phương pháp tốt hơn)
for waste disposal (để xử lý rác)
should wear a suit (nên mặc bộ com-lê)
to the interview (cho cuộc phỏng vấn)
These shoes (Những đôi giày này)
are too worn (đã mòn quá)
to wear outside (để đi ra ngoài)
don't have anything to wear (không có gì để mặc)
for the party (cho bữa tiệc)
The movie's final scene (Cảnh cuối của bộ phim)
was very emotional (rất cảm động)
The police (Cảnh sát)
arrived at the crime scene (đã đến hiện trường vụ án)
immediately (ngay lập tức)
painted (đã vẽ)
a beautiful scene (một cảnh đẹp)
of the countryside (của nông thôn)
found a perfect spot (đã tìm thấy một địa điểm hoàn hảo)
for a picnic (cho một buổi picnic)
There's a spot of ink (Có một vết mực)
on your shirt (trên áo của bạn)
has a spot on her skin (có một vết trên da)
that she's worried about (mà cô ấy đang lo lắng)
before you enter (trước khi bạn vào)
you must first enter your password (bạn phải nhập mật khẩu của mình trước)
The company (Công ty)
decided to enter (quyết định sẽ thâm nhập)
the Asian market (vào thị trường châu Á)
next year (vào năm tới)
Africa (Châu Phi)
is known for (được biết đến với)
its diverse cultures and wildlife (các nền văn hóa đa dạng và động vật hoang dã)
has always wanted to go (luôn muốn đi)
on a safari in Africa (săn ảnh ở Châu Phi)
Africa (Châu Phi)
is rich in natural resources (giàu tài nguyên thiên nhiên)
including (bao gồm)
diamonds, gold, and oil (kim cương, vàng và dầu mỏ)
worked hard (đã làm việc chăm chỉ)
to achieve his goals (để đạt được mục tiêu của mình)
can achieve great things (có thể đạt được những điều tuyệt vời)
when we work together (khi chúng ta cùng làm việc với nhau)
The company (Công ty)
aims to achieve (đặt mục tiêu đạt được)
a 20% increase in sales (sự tăng trưởng 20% về doanh số bán hàng)
this year (trong năm nay)
heights (độ cao)
was afraid (đã sợ)
to speak in public (nói trước đám đông)
the dark (bóng tối không)
started a fund (đã bắt đầu một quỹ)
for the victims of the earthquake (cho các nạn nhân của trận động đất)
invested in (đã đầu tư vào)
a mutual fund (một quỹ tương hỗ)
The company (Công ty)
decided to fund (quyết định tài trợ)


`;

// --- LOGIC TỰ ĐỘNG XỬ LÝ --- (ĐÃ SỬA LỖI)

const partRegex = /^(.*)\s\((.*)\)$/;

// Tự động xử lý toàn bộ khối văn bản để cung cấp cho ứng dụng
export const phraseData: PhraseSentence[] = rawPhraseStream
  .trim()
  // Tách thành các dòng riêng lẻ, vì mỗi dòng là một cụm từ
  .split('\n')
  // Lọc ra các dòng trống hoặc dòng comment
  .filter(line => line.trim() !== '' && !line.trim().startsWith('//'))
  .map(line => {
    const match = line.trim().match(partRegex);
    if (!match || match.length !== 3) {
      console.warn(`Dòng sau không khớp định dạng "English (Vietnamese)": ${line}`);
      return null;
    }

    const englishPart = match[1].trim().replace(/'/g, '').replace(/,/g, '');
    const vietnamesePart = match[2].trim();

    // Mỗi dòng bây giờ là một "PhraseSentence" hoàn chỉnh với một "PhrasePart" duy nhất
    return {
      parts: [{ english: englishPart, vietnamese: vietnamesePart }],
      fullEnglish: englishPart,
      fullVietnamese: vietnamesePart,
    };
  })
  // Lọc ra các kết quả rỗng (do dòng không đúng định dạng)
  .filter((item): item is PhraseSentence => item !== null);

// --- END OF FILE: phrase-data.ts ---
