// --- START OF FILE: phrase-data.ts ---

interface PhrasePart {
  english: string;
  vietnamese: string;
}

interface PhraseSentence {
  parts: PhrasePart[];
  fullEnglish: string;
  fullVietnamese: string;
}

// --- DỮ LIỆU GỐC ---
// Dán toàn bộ danh sách cụm từ vào đây.
// QUAN TRỌNG: Mỗi cụm từ đơn lẻ nên nằm trên MỘT DÒNG.
const rawPhraseStream = `

Solar energy (Năng lượng mặt trời)
a renewable source of power (một nguồn năng lượng tái tạo)
The company (Công ty)
is looking for (đang tìm kiếm)
a new source of raw materials (một nguồn nguyên liệu thô mới)
Health insurance (Bảo hiểm sức khỏe)
a must (điều bắt buộc)
for all employees (đối với tất cả nhân viên)
The car (Chiếc xe)
was totalled (đã bị hỏng hoàn toàn)
but luckily (nhưng may mắn là)
a range of insurance services (một loạt các dịch vụ bảo hiểm)
to our clients (cho khách hàng của mình)
The couple (Cặp đôi)
had an argument (đã tranh cãi)
about spending money (về việc tiêu tiền)
His main argument (Luận điểm chính của anh ấy)
is supported (được hỗ trợ)
by recent studies (bởi các nghiên cứu gần đây)
got into an argument (đã tranh cãi)
over politics (về chính trị)
Social media (Mạng xã hội)
a big influence (ảnh hưởng lớn)
on young people (đối với giới trẻ)
a lot of influence (nhiều ảnh hưởng)
in the company (trong công ty)
Her parents (Bố mẹ cô ấy)
had a strong influence (có ảnh hưởng mạnh mẽ)
on her career choice (đến sự lựa chọn nghề nghiệp của cô ấy)
The band (Ban nhạc)
is planning (đang lên kế hoạch)
to release a new album (phát hành một album mới)
next month (vào tháng tới)
After years of research (Sau nhiều năm nghiên cứu)
the scientist (nhà khoa học)
is ready to release (sẵn sàng công bố)
his findings (phát hiện của mình)
to the public (cho công chúng)
The movie (Bộ phim)
is scheduled for release (được lên lịch phát hành)
during the holiday season (trong mùa lễ hội)
The stadium (Sân vận động)
a seating capacity of 50,000 (sức chứa 50000 chỗ ngồi)
The battery (Pin)
a capacity of 2000 milliampere-hours (dung lượng 2000 miliampe-giờ)
The memory card (Thẻ nhớ)
a storage capacity of 128 gigabytes (dung lượng lưu trữ 128 gigabyte)
The Senate (Thượng viện)
with a large majority (với đa số lớn)
his candidacy (ứng cử)
for the US Senate (vào Thượng viện Mỹ)
The proposal (Đề xuất)
needs approval (cần được sự chấp thuận)
from both the House and the Senate (từ cả Hạ viện và Thượng viện)
The earthquake (Trận động đất)
massive damage (thiệt hại lớn)
to the city (cho thành phố)
massive support (sự ủng hộ lớn)
from her fans (từ người hâm mộ)
The company (Công ty)
is undertaking (đang tiến hành)
a massive project (một dự án lớn)
picked up a stick (nhặt một cây gậy)
to defend himself (để tự vệ)
used a stick (dùng một cây gậy)
to poke the fire (để khều lửa)
used a walking stick (đã sử dụng một cây gậy)
on her hike (khi đi bộ đường dài)
in the downtown district (ở khu vực trung tâm thành phố)
The school district (Khu vực trường học)
is implementing (đang thực hiện)
new policies (các chính sách mới)
This district (Khu vực này)
is known for (nổi tiếng với)
its vibrant nightlife (cuộc sống về đêm sôi động)
The project (Dự án)
need to cut (cần cắt giảm)
our monthly budget (ngân sách hàng tháng của mình)
The government (Chính phủ)
is preparing (đang chuẩn bị)
the annual budget (ngân sách hàng năm)
need to measure the room (cần đo căn phòng)
before buying new furniture (trước khi mua đồ nội thất mới)
the distance (khoảng cách)
between the two points (giữa hai điểm)
This ruler (Cái thước này)
can measure (có thể đo)
up to 30 centimeters (lên đến 30 centimet)
Be careful (Hãy cẩn thận)
when you cross the street (khi bạn băng qua đường)
The idea (Ý tưởng đó)
Cross off (Gạch)
the names of the guests (tên của những vị khách)
who have confirmed they are not coming (đã xác nhận là họ sẽ không đến)
The central theme (Chủ đề trung tâm)
of the book (của cuốn sách)
love and forgiveness (tình yêu và sự tha thứ)
lives in a central location (sống ở một vị trí trung tâm)
convenient for all (thuận tiện cho tất cả mọi người)
Central heating (Sưởi trung tâm)
a common feature (một tính năng phổ biến)
in these homes (trong những ngôi nhà này)
was proud of (tự hào về)
her children's achievements (thành tích của con mình)
stood tall and proud (đứng thẳng và tự hào)
despite the challenges (bất chấp những thách thức)
are proud (tự hào)
to serve their community (phục vụ cộng đồng của mình)
the core value (giá trị cốt lõi)
of our company (của công ty chúng tôi)
The core of the problem (Cốt lõi của vấn đề)
lies in (nằm ở)
communication issues (các vấn đề về giao tiếp)
An apple's core (Lõi của quả táo)
contains seeds (chứa hạt)
was elected (đã được bầu làm)
as the sheriff (cảnh sát trưởng)
of the county (của hạt)
The county fair (Hội chợ hạt)
is held (được tổ chức)
every summer (mỗi mùa hè)
Our library system (Hệ thống thư viện của chúng tôi)
the entire county (toàn bộ hạt)
This species of bird (Loài chim này)
is known for (được biết đến với)
its colorful plumage (bộ lông sặc sỡ)
Several species (Một số loài)
are endangered (đang bị đe dọa)
due to habitat destruction (do phá hủy môi trường sống)
a new species (một loài mới)
in the rainforest (trong rừng mưa)
The conditions of the contract (Các điều kiện của hợp đồng)
clear and binding (rõ ràng và có tính ràng buộc)
had to work (phải làm việc)
in harsh conditions (trong điều kiện khắc nghiệt)
The road conditions (Điều kiện đường xá)
are poor (kém)
due to the snow (do tuyết)
a touch (một cái chạm)
on her shoulder (trên vai mình)
Don't touch (Đừng chạm vào)
the wet paint (sơn ướt)
has a gentle touch (rất nhẹ tay)
with flowers (với hoa)
The mass (Khối lượng)
of the sun (của mặt trời)
is incredibly large (rất lớn)
A mass of people (Một đám đông người)
attended the concert (đã tham dự buổi hòa nhạc)
The product (Sản phẩm)
is sold (được bán)
at mass market retailers (tại các cửa hàng bán lẻ đại chúng)
The social media platform (Nền tảng mạng xã hội)
millions of users (hàng triệu người dùng)
The train (Tàu)
at the platform (sân ga)
can create applications (có thể tạo ứng dụng)
on this platform (trên nền tảng này)
Keep the picture (Giữ bức tranh)
on the wall (trên tường)
drove straight home (lái xe thẳng về nhà)
after work (sau khi tan làm)
straight A's (toàn điểm A)
in all her subjects (trong tất cả các môn học của mình)
a serious condition (một tình trạng nghiêm trọng)
need to have (cần phải có)
a serious discussion (một cuộc thảo luận nghiêm túc)
about our future (về tương lai của chúng ta)
is serious about (rất nghiêm túc với)
her career in music (sự nghiệp âm nhạc của mình)
healthy eating habits (thói quen ăn uống lành mạnh)
should encourage students (nên khuyến khích học sinh)
to ask questions (đặt câu hỏi)
Positive feedback (Phản hồi tích cực)
can encourage employees (có thể khuyến khích nhân viên)
to perform better (làm việc tốt hơn)
The project (Dự án)
is due (đến hạn)
next Monday (vào thứ Hai tới)
is due (đến hạn)
at the end of the month (vào cuối tháng)
The success of the event (Sự thành công của sự kiện)
was due to (là nhờ vào)
the hard work of volunteers (sự chăm chỉ của các tình nguyện viên)
a fond memory (một ký ức đẹp)
of our vacation (về kỳ nghỉ của chúng tôi)
The computer (Máy tính)
8GB of RAM (8GB RAM)
for memory (cho bộ nhớ)
has a great memory (có trí nhớ rất tốt)
for names and faces (về tên và khuôn mặt)
The secretary (Thư ký)
scheduled a meeting (đã lên lịch một cuộc họp)
for next week (cho tuần tới)
worked as a secretary (đã làm thư ký)
before becoming a lawyer (trước khi trở thành luật sư)
The secretary (Thư ký)
took notes (đã ghi chú)
during the meeting (trong cuộc họp)
caught a cold (bị cảm lạnh)
last week (tuần trước)
The water (Nước)
was too cold (quá lạnh)
for swimming (để bơi)
Keep the food (Giữ thức ăn)
in the refrigerator (trong tủ lạnh)
For instance (Chẳng hạn)
let's consider (hãy xem xét)
the company's growth (sự tăng trưởng của công ty)
last year (trong năm ngoái)
This is an instance (Đây là một trường hợp)
where patience is required (cần có sự kiên nhẫn)
In this instance (Trong trường hợp này)
the guidelines (hướng dẫn)
The foundation of the house (Nền móng của ngôi nhà)
needs to be strong (cần phải vững chắc)
set up a foundation (đã thành lập một quỹ từ thiện)
to help underprivileged children (để giúp đỡ trẻ em kém may mắn)
the foundation (nền tảng)
of a good relationship (của một mối quan hệ tốt đẹp)
Please keep (Vui lòng để)
the clean and dirty clothes (quần áo sạch và bẩn)
decided to separate (quyết định chia tay)
after ten years of marriage (sau mười năm kết hôn)
The teacher (Giáo viên)
asked the students (yêu cầu học sinh)
to work in separate groups (làm việc trong các nhóm riêng biệt)
used a map (đã sử dụng bản đồ)
to find our way (để tìm đường)
to the hotel (đến khách sạn)
The treasure map (Bản đồ kho báu)
led them (dẫn họ)
to an isolated island (đến một hòn đảo biệt lập)
can see (có thể thấy)
the country's topography (địa hình của đất nước)
on this map (trên bản đồ này)
added some ice (thêm một ít đá)
to her drink (vào thức uống của mình)
to cool it down (để làm mát)
The pond (Hồ nước)
with a thin layer of ice (một lớp băng mỏng)
went ice skating (đi trượt băng)
on the frozen lake (trên hồ đóng băng)
The company (Công ty)
a statement (một tuyên bố)
regarding the merger (liên quan đến việc sáp nhập)
His statement (Lời khai của anh ấy)
was recorded (đã được ghi lại)
by the police (bởi cảnh sát)
The financial statement (Báo cáo tài chính)
a profit (lợi nhuận)
for the last quarter (trong quý vừa qua)
in natural resources (tài nguyên thiên nhiên)
dreams of becoming (mơ ước trở nên)
rich and famous (giàu có và nổi tiếng)
This dessert (Món tráng miệng này)
is too rich (quá ngậy)
for my taste (so với khẩu vị của tôi)
In his previous job, (Trong công việc trước đây,)
was a teacher (là một giáo viên)
The previous owner (Chủ nhân trước)
of the house (của ngôi nhà)
these trees (những cây này)
Refer to (Tham khảo)
the previous chapter (chương trước)
for more information (để biết thêm thông tin)
It's necessary (Việc là cần thiết)
to wear a helmet (đeo mũ bảo hiểm)
while riding a bike (khi đi xe đạp)
Please fill out (Vui lòng điền vào)
all the necessary paperwork (tất cả các giấy tờ cần thiết)
Taking breaks (Việc nghỉ ngơi)
is necessary (là cần thiết)
for maintaining productivity (để duy trì năng suất)
is studying engineering (đang học kỹ thuật)
at the university (tại đại học)
The bridge (Cây cầu)
is a marvel (là một kỳ quan)
of modern engineering (của kỹ thuật hiện đại)
Environmental engineering (Kỹ thuật môi trường)
focuses on (tập trung vào việc)
improving natural environments (cải thiện môi trường tự nhiên)
The heat (Cái nóng)
in the desert (ở sa mạc)
can be unbearable (có thể không thể chịu đựng nổi)
during the day (vào ban ngày)
Turn up the heat, (Tăng nhiệt độ lên,)
it's too cold (lạnh quá)
in here (ở đây)
The heat (Hơi ấm)
from the fire (từ ngọn lửa)
kept us warm (đã giữ ấm cho chúng tôi)
her entire art collection (toàn bộ bộ sưu tập nghệ thuật của mình)
to the museum (cho bảo tàng)
The library (Thư viện)
a vast collection of books (một bộ sưu tập sách khổng lồ)
His collection (Bộ sưu tập)
of vintage cars (xe cổ của anh ấy)
is impressive (rất ấn tượng)
The construction project (Dự án xây dựng)
will require (sẽ yêu cầu)
a lot of skilled labor (nhiều lao động có tay nghề)
went into labor (bắt đầu chuyển dạ)
early in the morning (vào sáng sớm)
Labor costs (Chi phí nhân công)
can significantly affect (có thể ảnh hưởng đáng kể đến)
the price of goods (giá cả hàng hóa)
The river's flow (Dòng chảy của sông)
is strong (rất mạnh)
after the rain (sau cơn mưa)
are studying (đang nghiên cứu)
the flow of traffic (luồng giao thông)
in urban areas (ở khu vực đô thị)
The flow of information (Dòng thông tin)
is essential (là thiết yếu)
for decision making (cho việc ra quyết định)
Please wipe the floor (Vui lòng lau sàn)
after spilling the water (sau khi làm đổ nước)
dropped his keys (đã làm rơi chìa khóa)
on the floor (xuống sàn)
The book (Quyển sách)
with a loud thud (với một tiếng 'bịch' lớn)
The restaurant (Nhà hàng)
a variety of dishes (nhiều món ăn đa dạng)
need to add (cần thêm)
more variety (sự đa dạng)
to our daily routine (vào thói quen hàng ngày)
Genetic diversity (Sự đa dạng di truyền)
is important (rất quan trọng)
for the variety of species (đối với sự đa dạng của các loài)
is her favorite subject (là môn học yêu thích của cô ấy)
in school (ở trường)
is doing his math homework (đang làm bài tập về nhà môn toán)
better math education (giáo dục toán học tốt hơn)
to improve problem-solving skills (để cải thiện kỹ năng giải quyết vấn đề)
booked a session (đã đặt một buổi)
with a personal trainer (với huấn luyện viên cá nhân)
The next session (Phiên họp tiếp theo)
of Congress (của Quốc hội)
in January (vào tháng Giêng)
The therapy session (Buổi trị liệu)
helped him (đã giúp anh ấy)
understand his emotions better (hiểu rõ hơn về cảm xúc của mình)
Nuclear energy (Năng lượng hạt nhân)
is a major source (là một nguồn chính)
of electricity (của điện)
The country (Quốc gia này)
is developing (đang phát triển)
its nuclear capabilities (năng lực hạt nhân của mình)
There are concerns (Có những lo ngại)
about nuclear waste disposal (về việc xử lý chất thải hạt nhân)
loves to roll down the hill (thích lăn xuống đồi)
in the park (trong công viên)
Please roll the dough (Vui lòng cán bột)
into a flat circle (thành một hình tròn dẹt)
The dice roll (Việc gieo xúc xắc)
decides your move (quyết định nước đi của bạn)
in the game (trong trò chơi)
The museum (Bảo tàng)
a collection of ancient artifacts (một bộ sưu tập các hiện vật cổ đại)
visited the art museum (đã thăm bảo tàng nghệ thuật)
last weekend (vào cuối tuần trước)
The museum (Bảo tàng)
on Sundays (các ngày Chủ nhật)
The edition (Ấn bản này)
to 500 copies (ở 500 bản)
have limited time (có thời gian hạn chế)
to complete this project (để hoàn thành dự án này)
are limited, (có hạn,)
so we must use them wisely (vì vậy chúng ta phải sử dụng chúng một cách khôn ngoan)
The constant noise (Tiếng ồn liên tục)
from the construction site (từ công trường xây dựng)
is annoying (rất khó chịu)
is in constant communication (liên lạc liên tục)
with her team (với đội của mình)
The speed of light (Tốc độ ánh sáng)
is a constant (là một hằng số)
in physics (trong vật lý)
The temperature (Nhiệt độ)
Please check (Vui lòng kiểm tra)
the water temperature (nhiệt độ nước)
before bathing the baby (trước khi tắm cho em bé)
The average room temperature (Nhiệt độ phòng trung bình)
is comfortable (thì dễ chịu)
for most people (với hầu hết mọi người)
The description (Sự mô tả)
of the suspect (về nghi phạm)
was very detailed (rất chi tiết)
Please provide (Vui lòng cung cấp)

`;

// --- LOGIC TỰ ĐỘNG XỬ LÝ --- (ĐÃ SỬA LỖI)

const partRegex = /^(.*)\s\((.*)\)$/;

// Tự động xử lý toàn bộ khối văn bản để cung cấp cho ứng dụng
export const phraseData: PhraseSentence[] = rawPhraseStream
  .trim()
  // Tách thành các dòng riêng lẻ, vì mỗi dòng là một cụm từ
  .split('\n')
  // Lọc ra các dòng trống hoặc dòng comment
  .filter(line => line.trim() !== '' && !line.trim().startsWith('//'))
  .map(line => {
    const match = line.trim().match(partRegex);
    if (!match || match.length !== 3) {
      console.warn(`Dòng sau không khớp định dạng "English (Vietnamese)": ${line}`);
      return null;
    }

    const englishPart = match[1].trim().replace(/'/g, '').replace(/,/g, '');
    const vietnamesePart = match[2].trim();

    // Mỗi dòng bây giờ là một "PhraseSentence" hoàn chỉnh với một "PhrasePart" duy nhất
    return {
      parts: [{ english: englishPart, vietnamese: vietnamesePart }],
      fullEnglish: englishPart,
      fullVietnamese: vietnamesePart,
    };
  })
  // Lọc ra các kết quả rỗng (do dòng không đúng định dạng)
  .filter((item): item is PhraseSentence => item !== null);

// --- END OF FILE: phrase-data.ts ---
