// --- START OF FILE: phrase-data.ts ---

interface PhrasePart {
  english: string;
  vietnamese: string;
}

interface PhraseSentence {
  parts: PhrasePart[];
  fullEnglish: string;
  fullVietnamese: string;
}

// --- DỮ LIỆU GỐC ---
// Dán toàn bộ danh sách cụm từ vào đây.
// QUAN TRỌNG: Mỗi câu phải được cách nhau bằng MỘT DÒNG TRỐNG.
const rawPhraseStream = `
Solar energy (Năng lượng mặt trời)
is (là)
a renewable source of power (một nguồn năng lượng tái tạo)

The company (Công ty)
is looking for (đang tìm kiếm)
a new source of raw materials (một nguồn nguyên liệu thô mới)

Health insurance (Bảo hiểm sức khỏe)
is (là)
a must (điều bắt buộc)
for all employees (đối với tất cả nhân viên)

The car (Chiếc xe)
was totalled (đã bị hỏng hoàn toàn)
but luckily (nhưng may mắn là)
she had insurance (cô ấy đã có bảo hiểm)

We (Chúng tôi)
offer (cung cấp)
a range of insurance services (một loạt các dịch vụ bảo hiểm)
to our clients (cho khách hàng của mình)

The couple (Cặp đôi)
had an argument (đã tranh cãi)
about spending money (về việc tiêu tiền)

His main argument (Luận điểm chính của anh ấy)
is supported (được hỗ trợ)
by recent studies (bởi các nghiên cứu gần đây)

They (Họ)
got into an argument (đã tranh cãi)
over politics (về chính trị)

Social media (Mạng xã hội)
has (có)
a big influence (ảnh hưởng lớn)
on young people (đối với giới trẻ)

He (Anh ấy)
has (có)
a lot of influence (nhiều ảnh hưởng)
in the company (trong công ty)

Her parents (Bố mẹ cô ấy)
had a strong influence (có ảnh hưởng mạnh mẽ)
on her career choice (đến sự lựa chọn nghề nghiệp của cô ấy)

The band (Ban nhạc)
is planning (đang lên kế hoạch)
to release a new album (phát hành một album mới)
next month (vào tháng tới)

After years of research (Sau nhiều năm nghiên cứu)
the scientist (nhà khoa học)
is ready to release (sẵn sàng công bố)
his findings (phát hiện của mình)
to the public (cho công chúng)

The movie (Bộ phim)
is scheduled for release (được lên lịch phát hành)
during the holiday season (trong mùa lễ hội)

The stadium (Sân vận động)
has (có)
a seating capacity of 50000 (sức chứa 50.000 chỗ ngồi)

The battery (Pin)
has (có)
a capacity of 2000 milliampere-hours (dung lượng 2000 miliampe-giờ)

The memory card (Thẻ nhớ)
has (có)
a storage capacity of 128 gigabytes (dung lượng lưu trữ 128 gigabyte)

The Senate (Thượng viện)
passed the bill (đã thông qua dự luật)
with a large majority (với đa số lớn)

He (Anh ấy)
announced (đã công bố)
his candidacy (ứng cử)
for the U.S. Senate (vào Thượng viện Mỹ)

The proposal (Đề xuất)
needs approval (cần được sự chấp thuận)
from both the House and the Senate (từ cả Hạ viện và Thượng viện)

The earthquake (Trận động đất)
caused (đã gây ra)
massive damage (thiệt hại lớn)
to the city (cho thành phố)

She (Cô ấy)
received (đã nhận được)
massive support (sự ủng hộ lớn)
from her fans (từ người hâm mộ)

The company (Công ty)
is undertaking (đang tiến hành)
a massive project (một dự án lớn)

He (Anh ấy)
picked up a stick (nhặt một cây gậy)
to defend himself (để tự vệ)

He (Anh ấy)
used a stick (dùng một cây gậy)
to poke the fire (để khều lửa)

She (Cô ấy)
used a walking stick (đã sử dụng một cây gậy)
on her hike (khi đi bộ đường dài)

He (Anh ấy)
lives (sống)
in the downtown district (ở khu vực trung tâm thành phố)

The school district (Khu vực trường học)
is implementing (đang thực hiện)
new policies (các chính sách mới)

This district (Khu vực này)
is known for (nổi tiếng với)
its vibrant nightlife (cuộc sống về đêm sôi động)

The project (Dự án)
went over budget (đã vượt quá ngân sách)

We (Chúng ta)
need to cut (cần cắt giảm)
our monthly budget (ngân sách hàng tháng của mình)

The government (Chính phủ)
is preparing (đang chuẩn bị)
the annual budget (ngân sách hàng năm)

We (Chúng ta)
need to measure the room (cần đo căn phòng)
before buying new furniture (trước khi mua đồ nội thất mới)

Measure (Đo)
the distance (khoảng cách)
between the two points (giữa hai điểm)

This ruler (Cái thước này)
can measure (có thể đo)
up to 30 centimeters (lên đến 30 centimet)

Be careful (Hãy cẩn thận)
when you cross the street (khi bạn băng qua đường)

The idea (Ý tưởng đó)
didnt even cross my mind (thậm chí không hề xuất hiện trong đầu tôi)

Cross off (Gạch)
the names of the guests (tên của những vị khách)
who have confirmed they are not coming (đã xác nhận là họ sẽ không đến)

The central theme (Chủ đề trung tâm)
of the book (của cuốn sách)
is (là)
love and forgiveness (tình yêu và sự tha thứ)

He (Anh ấy)
lives in a central location (sống ở một vị trí trung tâm)
convenient for all (thuận tiện cho tất cả mọi người)

Central heating (Sưởi trung tâm)
is (là)
a common feature (một tính năng phổ biến)
in these homes (trong những ngôi nhà này)

She (Cô ấy)
was proud of (tự hào về)
her childrens achievements (thành tích của con mình)

He (Anh ấy)
stood tall and proud (đứng thẳng và tự hào)
despite the challenges (bất chấp những thách thức)

They (Họ)
are proud (tự hào)
to serve their community (phục vụ cộng đồng của mình)

Honesty (Trung thực)
is (là)
the core value (giá trị cốt lõi)
of our company (của công ty chúng tôi)

The core of the problem (Cốt lõi của vấn đề)
lies in (nằm ở)
communication issues (các vấn đề về giao tiếp)

An apples core (Lõi của quả táo)
contains seeds (chứa hạt)

She (Cô ấy)
was elected (đã được bầu làm)
as the sheriff (cảnh sát trưởng)
of the county (của hạt)

The county fair (Hội chợ hạt)
is held (được tổ chức)
every summer (mỗi mùa hè)

Our library system (Hệ thống thư viện của chúng tôi)
serves (phục vụ)
the entire county (toàn bộ hạt)

This species of bird (Loài chim này)
is known for (được biết đến với)
its colorful plumage (bộ lông sặc sỡ)

Several species (Một số loài)
are endangered (đang bị đe dọa)
due to habitat destruction (do phá hủy môi trường sống)

Scientists (Các nhà khoa học)
discovered (đã phát hiện)
a new species (một loài mới)
in the rainforest (trong rừng mưa)

The conditions of the contract (Các điều kiện của hợp đồng)
are (là)
clear and binding (rõ ràng và có tính ràng buộc)

They (Họ)
had to work (phải làm việc)
in harsh conditions (trong điều kiện khắc nghiệt)

The road conditions (Điều kiện đường xá)
are poor (kém)
due to the snow (do tuyết)

She (Cô ấy)
felt (cảm thấy)
a touch (một cái chạm)
on her shoulder (trên vai mình)

Dont touch (Đừng chạm vào)
the wet paint (sơn ướt)

She (Cô ấy)
has a gentle touch (rất nhẹ tay)
with flowers (với hoa)

The mass (Khối lượng)
of the sun (của mặt trời)
is incredibly large (rất lớn)

A mass of people (Một đám đông người)
attended the concert (đã tham dự buổi hòa nhạc)

The product (Sản phẩm)
is sold (được bán)
at mass market retailers (tại các cửa hàng bán lẻ đại chúng)

The social media platform (Nền tảng mạng xã hội)
has (có)
millions of users (hàng triệu người dùng)

The train (Tàu)
arrived (đã đến)
at the platform (sân ga)

Developers (Các nhà phát triển)
can create applications (có thể tạo ứng dụng)
on this platform (trên nền tảng này)

Keep the picture (Giữ bức tranh)
straight (thẳng)
on the wall (trên tường)

I (Tôi)
drove straight home (lái xe thẳng về nhà)
after work (sau khi tan làm)

She (Cô ấy)
has (đạt)
straight As (toàn điểm A)
in all her subjects (trong tất cả các môn học của mình)

The doctor said (Bác sĩ nói)
it was (đó là)
a serious condition (một tình trạng nghiêm trọng)

We (Chúng ta)
need to have (cần phải có)
a serious discussion (một cuộc thảo luận nghiêm túc)
about our future (về tương lai của chúng ta)

She (Cô ấy)
is serious about (rất nghiêm túc với)
her career in music (sự nghiệp âm nhạc của mình)

We (Chúng tôi)
encourage (khuyến khích)
healthy eating habits (thói quen ăn uống lành mạnh)

Teachers (Giáo viên)
should encourage students (nên khuyến khích học sinh)
to ask questions (đặt câu hỏi)

Positive feedback (Phản hồi tích cực)
can encourage employees (có thể khuyến khích nhân viên)
to perform better (làm việc tốt hơn)

The project (Dự án)
is due (đến hạn)
next Monday (vào thứ Hai tới)

Payment (Việc thanh toán)
is due (đến hạn)
at the end of the month (vào cuối tháng)

The success of the event (Sự thành công của sự kiện)
was due to (là nhờ vào)
the hard work of volunteers (sự chăm chỉ của các tình nguyện viên)

I (Tôi)
have (có)
a fond memory (một ký ức đẹp)
of our vacation (về kỳ nghỉ của chúng tôi)

The computer (Máy tính)
has (có)
8GB of RAM (8GB RAM)
for memory (cho bộ nhớ)

She (Cô ấy)
has a great memory (có trí nhớ rất tốt)
for names and faces (về tên và khuôn mặt)

The secretary (Thư ký)
scheduled a meeting (đã lên lịch một cuộc họp)
for next week (cho tuần tới)

He (Anh ấy)
worked as a secretary (đã làm thư ký)
before becoming a lawyer (trước khi trở thành luật sư)

The secretary (Thư ký)
took notes (đã ghi chú)
during the meeting (trong cuộc họp)

I (Tôi)
caught a cold (bị cảm lạnh)
last week (tuần trước)

The water (Nước)
was too cold (quá lạnh)
for swimming (để bơi)

Keep the food (Giữ thức ăn)
cold (lạnh)
in the refrigerator (trong tủ lạnh)

For instance (Chẳng hạn)
lets consider (hãy xem xét)
the companys growth (sự tăng trưởng của công ty)
last year (trong năm ngoái)

This is an instance (Đây là một trường hợp)
where patience is required (cần có sự kiên nhẫn)

In this instance (Trong trường hợp này)
we should follow (chúng ta nên tuân theo)
the guidelines (hướng dẫn)

The foundation of the house (Nền móng của ngôi nhà)
needs to be strong (cần phải vững chắc)

She (Cô ấy)
set up a foundation (đã thành lập một quỹ từ thiện)
to help underprivileged children (để giúp đỡ trẻ em kém may mắn)

Trust (Tin tưởng)
is (là)
the foundation (nền tảng)
of a good relationship (của một mối quan hệ tốt đẹp)

Please keep (Vui lòng để)
the clean and dirty clothes (quần áo sạch và bẩn)
separate (riêng)

They (Họ)
decided to separate (quyết định chia tay)
after ten years of marriage (sau mười năm kết hôn)

The teacher (Giáo viên)
asked the students (yêu cầu học sinh)
to work in separate groups (làm việc trong các nhóm riêng biệt)

We (Chúng tôi)
used a map (đã sử dụng bản đồ)
to find our way (để tìm đường)
to the hotel (đến khách sạn)

The treasure map (Bản đồ kho báu)
led them (dẫn họ)
to an isolated island (đến một hòn đảo biệt lập)

You (Bạn)
can see (có thể thấy)
the countrys topography (địa hình của đất nước)
on this map (trên bản đồ này)

She (Cô ấy)
added some ice (thêm một ít đá)
to her drink (vào thức uống của mình)
to cool it down (để làm mát)
The pond (Hồ nước)
was covered (được phủ)
with a thin layer of ice (một lớp băng mỏng)
They (Họ)
went ice skating (đi trượt băng)
on the frozen lake (trên hồ đóng băng)
The company (Công ty)
issued (đã đưa ra)
a statement (một tuyên bố)
regarding the merger (liên quan đến việc sáp nhập)
His statement (Lời khai của anh ấy)
was recorded (đã được ghi lại)
by the police (bởi cảnh sát)
The financial statement (Báo cáo tài chính)
shows (cho thấy)
a profit (lợi nhuận)
for the last quarter (trong quý vừa qua)
The country (Quốc gia này)
is rich (giàu)
in natural resources (tài nguyên thiên nhiên)
He (Anh ấy)
dreams of becoming (mơ ước trở nên)
rich and famous (giàu có và nổi tiếng)
This dessert (Món tráng miệng này)
is too rich (quá ngậy)
for my taste (so với khẩu vị của tôi)
In his previous job, (Trong công việc trước đây,)
he (anh ấy)
was a teacher (là một giáo viên)
The previous owner (Chủ nhân trước)
of the house (của ngôi nhà)
planted (đã trồng)
these trees (những cây này)
Refer to (Tham khảo)
the previous chapter (chương trước)
for more information (để biết thêm thông tin)
It's necessary (Việc... là cần thiết)
to wear a helmet (đeo mũ bảo hiểm)
while riding a bike (khi đi xe đạp)
Please fill out (Vui lòng điền vào)
all the necessary paperwork (tất cả các giấy tờ cần thiết)
Taking breaks (Việc nghỉ ngơi)
is necessary (là cần thiết)
for maintaining productivity (để duy trì năng suất)
He (Anh ấy)
is studying engineering (đang học kỹ thuật)
at the university (tại đại học)
The bridge (Cây cầu)
is a marvel (là một kỳ quan)
of modern engineering (của kỹ thuật hiện đại)
Environmental engineering (Kỹ thuật môi trường)
focuses on (tập trung vào việc)
improving natural environments (cải thiện môi trường tự nhiên)
The heat (Cái nóng)
in the desert (ở sa mạc)
can be unbearable (có thể không thể chịu đựng nổi)
during the day (vào ban ngày)
Turn up the heat, (Tăng nhiệt độ lên,)
it's too cold (lạnh quá)
in here (ở đây)
The heat (Hơi ấm)
from the fire (từ ngọn lửa)
kept us warm (đã giữ ấm cho chúng tôi)
She (Cô ấy)
donated (đã quyên góp)
her entire art collection (toàn bộ bộ sưu tập nghệ thuật của mình)
to the museum (cho bảo tàng)
The library (Thư viện)
has (có)
a vast collection of books (một bộ sưu tập sách khổng lồ)
His collection (Bộ sưu tập)
of vintage cars (xe cổ của anh ấy)
is impressive (rất ấn tượng)
The construction project (Dự án xây dựng)
will require (sẽ yêu cầu)
a lot of skilled labor (nhiều lao động có tay nghề)
She (Cô ấy)
went into labor (bắt đầu chuyển dạ)
early in the morning (vào sáng sớm)
Labor costs (Chi phí nhân công)
can significantly affect (có thể ảnh hưởng đáng kể đến)
the price of goods (giá cả hàng hóa)
The river's flow (Dòng chảy của sông)
is strong (rất mạnh)
after the rain (sau cơn mưa)
They (Họ)
are studying (đang nghiên cứu)
the flow of traffic (luồng giao thông)
in urban areas (ở khu vực đô thị)
The flow of information (Dòng thông tin)
is essential (là thiết yếu)
for decision making (cho việc ra quyết định)
Please wipe the floor (Vui lòng lau sàn)
after spilling the water (sau khi làm đổ nước)
He (Anh ấy)
dropped his keys (đã làm rơi chìa khóa)
on the floor (xuống sàn)
The book (Quyển sách)
fell to the floor (rơi xuống sàn nhà)
with a loud thud (với một tiếng 'bịch' lớn)
The restaurant (Nhà hàng)
offers (phục vụ)
a variety of dishes (nhiều món ăn đa dạng)
We (Chúng ta)
need to add (cần thêm)
more variety (sự đa dạng)
to our daily routine (vào thói quen hàng ngày)
Genetic diversity (Sự đa dạng di truyền)
is important (rất quan trọng)
for the variety of species (đối với sự đa dạng của các loài)
Math (Toán)
is her favorite subject (là môn học yêu thích của cô ấy)
in school (ở trường)
He (Anh ấy)
is doing his math homework (đang làm bài tập về nhà môn toán)
We (Chúng ta)
need (cần)
better math education (giáo dục toán học tốt hơn)
to improve problem-solving skills (để cải thiện kỹ năng giải quyết vấn đề)
She (Cô ấy)
booked a session (đã đặt một buổi)
with a personal trainer (với huấn luyện viên cá nhân)
The next session (Phiên họp tiếp theo)
of Congress (của Quốc hội)
begins (bắt đầu)
in January (vào tháng Giêng)
The therapy session (Buổi trị liệu)
helped him (đã giúp anh ấy)
understand his emotions better (hiểu rõ hơn về cảm xúc của mình)
Nuclear energy (Năng lượng hạt nhân)
is a major source (là một nguồn chính)
of electricity (của điện)
The country (Quốc gia này)
is developing (đang phát triển)
its nuclear capabilities (năng lực hạt nhân của mình)
There are concerns (Có những lo ngại)
about nuclear waste disposal (về việc xử lý chất thải hạt nhân)
She (Cô ấy)
loves to roll down the hill (thích lăn xuống đồi)
in the park (trong công viên)
Please roll the dough (Vui lòng cán bột)
into a flat circle (thành một hình tròn dẹt)
The dice roll (Việc gieo xúc xắc)
decides your move (quyết định nước đi của bạn)
in the game (trong trò chơi)
The museum (Bảo tàng)
houses (lưu giữ)
a collection of ancient artifacts (một bộ sưu tập các hiện vật cổ đại)
We (Chúng tôi)
visited the art museum (đã thăm bảo tàng nghệ thuật)
last weekend (vào cuối tuần trước)
The museum (Bảo tàng)
is free (miễn phí vé vào cửa)
on Sundays (các ngày Chủ nhật)
The edition (Ấn bản này)
is limited (được giới hạn)
to 500 copies (ở 500 bản)
We (Chúng ta)
have limited time (có thời gian hạn chế)
to complete this project (để hoàn thành dự án này)
Resources (Nguồn lực)
are limited, (có hạn,)
so we must use them wisely (vì vậy chúng ta phải sử dụng chúng một cách khôn ngoan)
The constant noise (Tiếng ồn liên tục)
from the construction site (từ công trường xây dựng)
is annoying (rất khó chịu)
She (Cô ấy)
is in constant communication (liên lạc liên tục)
with her team (với đội của mình)
The speed of light (Tốc độ ánh sáng)
is a constant (là một hằng số)
in physics (trong vật lý)
The temperature (Nhiệt độ)
dropped significantly (giảm đáng kể)
overnight (qua đêm)
Please check (Vui lòng kiểm tra)
the water temperature (nhiệt độ nước)
before bathing the baby (trước khi tắm cho em bé)
The average room temperature (Nhiệt độ phòng trung bình)
is comfortable (thì dễ chịu)
for most people (với hầu hết mọi người)
The description (Sự mô tả)
of the suspect (về nghi phạm)
was very detailed (rất chi tiết)
Please provide (Vui lòng cung cấp)
a brief description (mô tả ngắn gọn)
of the incident (về vụ việc)
The job description (Bản mô tả công việc)
includes (bao gồm)
various responsibilities (nhiều trách nhiệm khác nhau)
The transition (Sự chuyển tiếp)
from high school to college (từ trường trung học lên đại học)
can be challenging (có thể đầy thách thức)
The country (Đất nước)
is undergoing (đang trải qua)
a political transition (một cuộc chuyển giao chính trị)
We (Chúng ta)
need to ensure (cần đảm bảo)
a smooth transition (một sự chuyển tiếp suôn sẻ)
for the new employees (cho các nhân viên mới)
He (Anh ấy)
pulled up a chair (kéo một cái ghế lại)
and sat down (và ngồi xuống)
The chair (Cái ghế)
is made of (được làm từ)
solid wood (gỗ nguyên khối)
Please return the chair (Vui lòng trả ghế)
to its original position (về vị trí ban đầu)
The dress (Chiếc váy)
has a floral pattern (có họa tiết hoa)
He (Anh ấy)
noticed a pattern (nhận thấy một quy luật)
in the test results (trong kết quả kiểm tra)
The wallpaper pattern (Họa tiết giấy dán tường)
matches (phù hợp với)
the overall decor (tổng thể trang trí)
There is a high demand (Nhu cầu... rất cao)
for organic products (đối với sản phẩm hữu cơ)
The workers (Công nhân)
demand (yêu cầu)
better working conditions (điều kiện làm việc tốt hơn)
The demand (Nhu cầu)
for new housing (về nhà ở mới)
is increasing (đang tăng)
I (Tôi)
hate (ghét)
being stuck in traffic (bị kẹt xe)
She (Cô ấy)
expressed her hate (bày tỏ sự căm ghét)
for injustice (đối với sự bất công)
He (Anh ấy)
learned to hate (đã học cách căm ghét)
the war (chiến tranh)
The classroom (Lớp học)
was filled with students (chật kín học sinh)
New technology (Công nghệ mới)
is being integrated (đang được tích hợp)
into the classroom (vào lớp học)
She (Cô ấy)
decorated the classroom (trang trí lớp học)
with educational posters (bằng những tấm áp phích giáo dục)
He (Anh ấy)
served in the army (đã phục vụ trong quân đội)
for ten years (mười năm)
The army (Quân đội)
deployed troops (đã triển khai quân)
to the conflict zone (đến khu vực xung đột)
The army (Quân đội)
provides (cung cấp)
disaster relief and humanitarian aid (cứu trợ thảm họa và viện trợ nhân đạo)
The flowers (Hoa)
bloom (nở)
in spring (vào mùa xuân)
Spring (Mùa xuân)
is a time (là thời điểm)
for new beginnings (cho những khởi đầu mới)
We (Chúng tôi)
plan to start (dự định bắt đầu)
the garden project (dự án khu vườn)
in early spring (vào đầu mùa xuân)
She (Cô ấy)
is a senior manager (là quản lý cấp cao)
at the firm (tại công ty)
Senior citizens (Người cao tuổi)
receive a discount (được giảm giá)
at the museum (tại bảo tàng)
It's her senior year (Đây là năm cuối cấp của cô ấy)
in high school (ở trường trung học)
The wind (Gió)
blew through the trees (thổi qua hàng cây)
Wind turbines (Tua bin gió)
generate (tạo ra)
electricity (điện)
He (Anh ấy)
could hear (có thể nghe thấy)
the wind howling (tiếng gió rít)
at night (vào ban đêm)
She (Cô ấy)
received an award (đã nhận được một giải thưởng)
for her contributions (cho những đóng góp của mình)
to science (cho khoa học)
He (Anh ấy)
was honored (đã được vinh danh)
with a lifetime achievement award (với giải thưởng thành tựu trọn đời)
The committee (Ủy ban)
decided to award the scholarship (đã quyết định trao học bổng)
to the most deserving student (cho sinh viên xứng đáng nhất)
Clinical trials (Các thử nghiệm lâm sàng)
are necessary (là cần thiết)
before a new drug can be approved (trước khi một loại thuốc mới có thể được phê duyệt)
She (Cô ấy)
is undergoing (đang trải qua)
clinical treatment (điều trị lâm sàng)
for her condition (cho tình trạng của mình)
Clinical studies (Các nghiên cứu lâm sàng)
show (cho thấy)
the effectiveness (hiệu quả)
of the new therapy (của liệu pháp mới)
He (Anh ấy)
found himself (thấy mình)
in trouble (gặp rắc rối)
with the law (với pháp luật)
If you need help, (Nếu bạn cần giúp đỡ,)
don't hesitate (đừng ngần ngại)
to call me (gọi cho tôi)
I (Tôi)
don't want you (không muốn bạn)
to get into trouble (gặp rắc rối)
Chắc chắn rồi! Dưới đây là các câu đã được tách thành các cụm từ dễ hiểu, đã loại bỏ các đường gạch ngang.
Her outspokenness (Sự thẳng thắn của cô ấy)
sometimes causes trouble (đôi khi gây rắc rối)
at work (tại nơi làm việc)
He (Anh ấy)
received a good grade (nhận được điểm tốt)
on his math exam (trong bài thi toán)
She (Cô ấy)
teaches third grade (dạy lớp ba)
at the local elementary school (tại trường tiểu học địa phương)
The road (Con đường)
has a steep grade (có một độ dốc lớn)
near the summit (gần đỉnh)
The train (Tàu)
arrived (đã đến)
at the station (ga)
She (Cô ấy)
listens to (nghe)
her favorite music station (kênh âm nhạc yêu thích của mình)
on the radio (trên radio)
The police station (Đồn cảnh sát)
is just around the corner (ở ngay góc đường)
The wedding (Đám cưới)
was filled with (tràn ngập)
beautiful moments (những khoảnh khắc đẹp)
He (Anh ấy)
captured the moments (đã ghi lại những khoảnh khắc)
on his camera (bằng máy ảnh của mình)
Moments like these (Những khoảnh khắc như thế này)
remind us (nhắc nhở chúng ta)
to appreciate life (hãy trân trọng cuộc sống)
The surfer (Người lướt sóng)
rode a huge wave (đã cưỡi một con sóng khổng lồ)
to the shore (vào bờ)
The physicist (Nhà vật lý)
explained (giải thích)
the wave theory of light (lý thuyết sóng của ánh sáng)
The wave of protests (Làn sóng biểu tình)
spread across the country (lan rộng khắp đất nước)
Please move (Làm ơn di chuyển)
this block of ice (tảng băng này)
to the cooler (vào thùng giữ lạnh)
The new apartment block (Khu chung cư mới)
is under construction (đang được xây dựng)
This software (Phần mềm này)
can block (có thể chặn)
all unwanted ads (tất cả các quảng cáo không mong muốn)
Compared to last year (So với năm ngoái)
our profits (lợi nhuận của chúng tôi)
have increased (đã tăng lên)
Her cooking skills (Kỹ năng nấu nướng của cô ấy)
are often compared to (thường được so sánh với)
a professional chef's (một đầu bếp chuyên nghiệp)
Compared with his brother (So với anh trai mình)
he is more outgoing (anh ấy cởi mở hơn)
Lifting weights regularly (Nâng tạ thường xuyên)
increases muscle strength (giúp tăng cường sức mạnh cơ bắp)
She (Cô ấy)
showed great strength (đã thể hiện sức mạnh to lớn)
during difficult times (trong những thời điểm khó khăn)
Unity (Đoàn kết)
is our greatest strength (là sức mạnh lớn nhất của chúng ta)
The project (Dự án)
is in the planning phase (đang trong giai đoạn lập kế hoạch)
Adolescence (Tuổi vị thành niên)
is a challenging phase of life (là một giai đoạn đầy thách thức của cuộc đời)
The clinical trial (Thử nghiệm lâm sàng)
has entered Phase III (đã bước vào Giai đoạn III)
They (Họ)
shared a secret (chia sẻ một bí mật)
that nobody else knew (mà không ai khác biết)
The recipe (Công thức nấu ăn)
is a family secret (là một bí mật gia đình)
He (Anh ấy)
kept his plans secret (giữ bí mật kế hoạch của mình)
until the last moment (cho đến phút cuối)
Mount Everest (Núi Everest)
is the highest mountain (là ngọn núi cao nhất)
in the world (trên thế giới)
She (Cô ấy)
achieved the highest score (đạt điểm số cao nhất)
in the class (trong lớp)
The highest priority (Ưu tiên cao nhất)
is given to safety (được dành cho sự an toàn)
He (Anh ấy)
is leaving for New York (sẽ rời New York)
tomorrow (vào ngày mai)
Leaving the job (Nghỉ việc)
was a difficult decision (là một quyết định khó khăn)
for him (đối với anh ấy)
He (Anh ấy)
mentioned leaving his job (đã đề cập đến việc nghỉ việc)
to start his own business (để bắt đầu kinh doanh riêng)
It was obvious (Rõ ràng là)
that he was lying (anh ấy đang nói dối)
The solution to the problem (Giải pháp cho vấn đề)
was not immediately obvious (không ngay lập tức rõ ràng)
Her happiness (Niềm hạnh phúc của cô ấy)
was obvious to everyone (hiện rõ trước mắt mọi người)
The storm (Cơn bão)
caused terrible damage (đã gây ra thiệt hại khủng khiếp)
He (Anh ấy)
had a terrible feeling (có một cảm giác tồi tệ)
that something was wrong (rằng có điều gì đó không ổn)
The food (Đồ ăn)
at that restaurant (ở nhà hàng đó)
was terrible (thật tệ)
The dancer's graceful motion (Chuyển động duyên dáng của vũ công)
captivated the audience (đã làm say đắm khán giả)
He (Anh ấy)
made a motion (ra hiệu)
to the waiter (cho người phục vụ)
for the bill (để tính tiền)
The machine's motion (Chuyển động của máy)
is controlled by (được điều khiển bởi)
a series of gears (một loạt bánh răng)
She (Cô ấy)
opened the window (mở cửa sổ)
to let in some fresh air (để cho không khí trong lành vào)
The bird (Con chim)
flew straight (bay thẳng)
into the window (vào cửa sổ)
He (Anh ấy)
looked out the window (nhìn ra ngoài cửa sổ)
at the rain pouring down (thấy mưa như trút nước)
We (Chúng ta)
cannot assume (không thể cho rằng)
everyone knows the rules (mọi người đều biết các quy tắc)
Let's not assume the worst (Chúng ta đừng cho rằng điều tồi tệ nhất)
without evidence (khi không có bằng chứng)
You (Bạn)
shouldn't assume (không nên cho rằng)
that everyone shares your opinion (mọi người đều có chung quan điểm với bạn)
The water cycle (Chu kỳ nước)
is essential (là thiết yếu)
for the Earth's ecosystem (cho hệ sinh thái của Trái Đất)
She (Cô ấy)
follows a strict training cycle (tuân theo một chu kỳ luyện tập nghiêm ngặt)
for the marathon (cho cuộc thi marathon)
The cycle of the moon (Chu kỳ của mặt trăng)
affects the tides of the ocean (ảnh hưởng đến thủy triều của đại dương)
The weather (Thời tiết)
changed suddenly (thay đổi đột ngột)
catching us off guard (khiến chúng tôi bất ngờ)
She (Cô ấy)
suddenly realized (đột nhiên nhận ra)
she had left her keys (cô ấy đã để quên chìa khóa)
at home (ở nhà)
The room (Căn phòng)
fell silent suddenly (đột ngột im bặt)
when the principal walked in (khi hiệu trưởng bước vào)
Western movies (Phim miền Tây)
often depict life (thường mô tả cuộc sống)
in the American frontier (ở biên giới Mỹ)
She (Cô ấy)
has a great interest in (rất quan tâm đến)
Western philosophy (triết học phương Tây)
Western cultures (Các nền văn hóa phương Tây)
have different norms and values (có những quy chuẩn và giá trị khác nhau)
He (Anh ấy)
had a broken arm (bị gãy tay)
from playing football (do chơi bóng đá)
Their relationship (Mối quan hệ của họ)
was broken (đã tan vỡ)
beyond repair (không thể hàn gắn)
I (Tôi)
ve broken my promise (đã thất hứa)
and I regret it deeply (và tôi vô cùng hối hận)
It's hard to define (Thật khó để xác định)
the exact moment (chính xác khoảnh khắc)
when everything changed (khi mọi thứ thay đổi)
How do you define success? (Bạn định nghĩa thành công như thế nào?)
It's hard to define (Thật khó để định nghĩa)
the exact moment (chính xác khoảnh khắc)
when childhood ends (khi tuổi thơ kết thúc)
She (Cô ấy)
embarked on a spiritual journey (bắt đầu một hành trình tâm linh)
to find inner peace (để tìm thấy sự bình yên nội tâm)
Meditation (Thiền)
is a key practice (là một thực hành chính)
in many spiritual traditions (trong nhiều truyền thống tâm linh)
Spiritual leaders (Các nhà lãnh đạo tâm linh)
often emphasize (thường nhấn mạnh)
the importance of compassion (tầm quan trọng của lòng trắc ẩn)
Environmental concerns (Các mối quan ngại về môi trường)
are at the forefront (đang là tâm điểm)
of global discussions (của các cuộc thảo luận toàn cầu)
She (Cô ấy)
voiced her concerns (đã bày tỏ mối quan ngại của mình)
about the project's feasibility (về tính khả thi của dự án)
Health concerns (Những lo ngại về sức khỏe)
have led to increased interest (đã dẫn đến sự quan tâm ngày càng tăng)
in organic food (đối với thực phẩm hữu cơ)
The computer program (Chương trình máy tính)
generates random numbers (tạo ra các số ngẫu nhiên)
for the lottery (cho xổ số)
Random acts of kindness (Những hành động tử tế ngẫu nhiên)
can brighten someone's day (có thể làm một ngày của ai đó bừng sáng)
He (Anh ấy)
was selected (được chọn)
from a random sample (từ một mẫu ngẫu nhiên)
of the population (trong dân số)
The moon (Mặt trăng)
was full and bright (tròn và sáng)
in the night sky (trên bầu trời đêm)
Astronauts (Các phi hành gia)
landed on the moon (đã hạ cánh lên mặt trăng)
in 1969 (vào năm 1969)
The moon (Mặt trăng)
looked especially large (trông đặc biệt lớn)
tonight (vào tối nay)
It's dangerous (Rất nguy hiểm)
to drive (lái xe)
in such severe weather conditions (trong điều kiện thời tiết khắc nghiệt như vậy)
Wild animals (Động vật hoang dã)
can be dangerous (có thể trở nên nguy hiểm)
if provoked (nếu bị khiêu khích)
He (Anh ấy)
warned them of (đã cảnh báo họ về)
the dangerous chemicals (các hóa chất nguy hiểm)
in the lab (trong phòng thí nghiệm)
The forest (Khu rừng)
is home to (là nhà của)
a wide variety of trees (rất nhiều loại cây)
We (Chúng tôi)
planted fruit trees (đã trồng cây ăn quả)
in our backyard (ở sân sau)
Trees (Cây cối)
provide oxygen (cung cấp oxy)
and improve air quality (và cải thiện chất lượng không khí)
We're planning a trip (Chúng tôi đang lên kế hoạch cho một chuyến đi)
to Europe (đến châu Âu)
next summer (vào mùa hè tới)
The school (Nhà trường)
organized a field trip (đã tổ chức một chuyến đi thực tế)
to the museum (đến bảo tàng)
His first trip abroad (Chuyến đi nước ngoài đầu tiên của anh ấy)
was to Canada (là đến Canada)
The child (Đứa trẻ)
was curious about (tò mò về)
everything around him (mọi thứ xung quanh mình)
I'm curious (Tôi tò mò)
to know how it works (muốn biết nó hoạt động như thế nào)
Her curious nature (Bản tính tò mò của cô ấy)
led her to explore new places (đã dẫn dắt cô ấy khám phá những nơi mới)
The box (Cái hộp)
was too heavy (quá nặng)
for her to lift (để cô ấy có thể nhấc lên)
Heavy rain (Mưa lớn)
caused flooding (đã gây ra lũ lụt)
in the area (trong khu vực)
He (Anh ấy)
breathed a heavy sigh (thở phào một hơi)
of relief (nhẹ nhõm)
Birds (Chim)
fly south (bay về phương nam)
for the winter (để tránh mùa đông)
The plane (Máy bay)
will fly (sẽ bay)
from New York to London (từ New York đến London)
I (Tôi)
always wanted (luôn muốn)
to fly a kite (thả diều)
on the beach (trên bãi biển)
She (Cô ấy)
noticed a change (nhận thấy một sự thay đổi)
in his behavior (trong hành vi của anh ấy)
He (Anh ấy)
hadn't noticed (đã không nhận ra)
that the time was so late (trời đã muộn như vậy)
They (Họ)
noticed the bird (nhận thấy con chim)
as it flew past the window (khi nó bay qua cửa sổ)
Spring (Mùa xuân)
begins in March (bắt đầu vào tháng Ba)
in the Northern Hemisphere (ở Bắc bán cầu)
Her birthday (Sinh nhật của cô ấy)
is in March (là vào tháng Ba)
The protest march (Cuộc tuần hành phản đối)
took place (diễn ra)
on the first of March (vào ngày mùng một tháng Ba)


`;

// --- LOGIC TỰ ĐỘNG XỬ LÝ --- (Không cần sửa phần dưới này)

/**
 * Phân tích một khối chuỗi của một câu thành các phần (Anh-Việt).
 * @param block Chuỗi của một câu.
 * @returns Một mảng các đối tượng PhrasePart.
 */
const parseSingleSentenceBlock = (block: string): PhrasePart[] => {
  const lines = block.split('\n').filter(line => line.trim() !== '');
  const partRegex = /^(.*)\s\((.*)\)$/;

  return lines.map(line => {
    const match = line.trim().match(partRegex);
    if (match && match.length === 3) {
      return {
        // Tự động loại bỏ dấu ' và , khỏi tiếng Anh
        english: match[1].trim().replace(/'/g, '').replace(/,/g, ''),
        vietnamese: match[2].trim(),
      };
    }
    console.warn(`Dòng sau không khớp định dạng "English (Vietnamese)": ${line}`);
    return { english: line.trim(), vietnamese: 'N/A' };
  });
};

// Tự động xử lý toàn bộ khối văn bản để cung cấp cho ứng dụng
export const phraseData: PhraseSentence[] = rawPhraseStream
  .trim()
  // Tách thành các câu dựa trên các dòng trống
  .split(/\n\s*\n/)
  .map(block => {
    const parts = parseSingleSentenceBlock(block.trim());
    if (parts.length === 0) return null;
    return {
      parts,
      fullEnglish: parts.map(p => p.english).join(' '),
      fullVietnamese: parts.map(p => p.vietnamese).join(' '),
    };
  })
  // Lọc ra các kết quả rỗng (nếu có nhiều dòng trống liên tiếp)
  .filter((item): item is PhraseSentence => item !== null);

// --- END OF FILE: phrase-data.ts ---
