// --- START OF FILE src/data/item-database.ts ---

import { itemAssets } from '../game-assets.ts';

// THAY ĐỔI: Định nghĩa kiểu ItemRank mới để sử dụng trong toàn bộ hệ thống.
export type ItemRank = 'E' | 'D' | 'B' | 'A' | 'S' | 'SR' | 'SSR';

// THAY ĐỔI: Cập nhật cấu trúc ItemDefinition để sử dụng ItemRank mới.
export interface ItemDefinition {
    id: number;
    name: string;
    type: 'weapon' | 'potion' | 'armor' | 'accessory' | 'material' | 'currency' | 'misc' | 'quest' | 'piece';
    rarity: ItemRank; // Sử dụng hệ thống Rank mới
    description: string;
    icon: string;
    stats?: { [key: string]: any }; 
    maxLevel?: number;
}

// THAY ĐỔI: Cập nhật toàn bộ database với hệ thống Rank mới.
// Logic ánh xạ: common -> E, uncommon -> D, rare -> B, epic -> A/S, legendary -> SR/SSR
export const itemDatabase = new Map<number, ItemDefinition>([
    [1, { id: 1, name: 'Kiếm gỗ', type: 'weapon', rarity: 'E', description: 'Một thanh kiếm gỗ cơ bản, thích hợp cho người mới bắt đầu.', stats: { damage: 5, durability: 20 }, icon: itemAssets.kiemGo, maxLevel: 10 }],
    [2, { id: 2, name: 'Hard Armor', type: 'armor', rarity: 'B', description: 'Bộ giáp cứng cáp, bảo vệ tốt khỏi các đòn tấn công vật lý.', stats: { defense: 15, durability: 60 }, icon: itemAssets.hardArmor, maxLevel: 25 }],
    [3, { id: 3, name: 'Mana Potion', type: 'potion', rarity: 'E', description: 'Hồi phục một lượng nhỏ mana.', stats: { manaRestore: 30 }, icon: itemAssets.manaPotion }],
    [4, { id: 4, name: 'Health Potion', type: 'potion', rarity: 'E', description: 'Hồi phục một lượng nhỏ máu.', stats: { healthRestore: 50 }, icon: itemAssets.healthPotion }],
    [5, { id: 5, name: 'Dagger', type: 'weapon', rarity: 'D', description: 'Một con dao găm nhỏ gọn, dễ dàng sử dụng.', stats: { damage: 8, durability: 25 }, icon: itemAssets.dagger, maxLevel: 15 }],
    [6, { id: 6, name: 'Leather Armor', type: 'armor', rarity: 'D', description: 'Bộ giáp da nhẹ, cung cấp khả năng phòng thủ cơ bản.', stats: { defense: 10, durability: 40 }, icon: itemAssets.leatherArmor, maxLevel: 20 }],
    [7, { id: 7, name: 'Iron Sword', type: 'weapon', rarity: 'B', description: 'Thanh kiếm sắt chắc chắn, sát thương khá.', stats: { damage: 15, durability: 50 }, icon: itemAssets.ironSword, maxLevel: 30 }],
    [8, { id: 8, name: 'Plate Armor', type: 'armor', rarity: 'A', description: 'Bộ giáp trụ nặng, bảo vệ vượt trội.', stats: { defense: 25, durability: 80 }, icon: itemAssets.plateArmor, maxLevel: 35 }],
    [9, { id: 9, name: 'Magic Staff', type: 'weapon', rarity: 'B', description: 'Cây trượng phép thuật, tăng cường sức mạnh ma thuật.', stats: { magicDamage: 10, manaRegen: 5, durability: 40 }, icon: itemAssets.magicStaff, maxLevel: 25 }],
    [10, { id: 10, name: 'Healing Orb', type: 'accessory', rarity: 'A', description: 'Quả cầu hồi phục, tự động hồi máu cho người sử dụng.', stats: { healthRegen: 3, durability: 70 }, icon: itemAssets.healingOrb }],
    [11, { id: 11, name: 'Gold Coin', type: 'currency', rarity: 'E', description: 'Đơn vị tiền tệ chính trong trò chơi.', icon: itemAssets.goldCoin }],
    [12, { id: 12, name: 'Silver Ore', type: 'material', rarity: 'D', description: 'Quặng bạc thô, có thể dùng để chế tạo.', icon: itemAssets.silverOre }],
    [13, { id: 13, name: 'Experience Scroll', type: 'misc', rarity: 'B', description: 'Tăng một lượng lớn kinh nghiệm khi sử dụng.', stats: { expGain: 1000 }, icon: itemAssets.experienceScroll }],
    [14, { id: 14, name: 'Quest Item: Ancient Map', type: 'quest', rarity: 'A', description: 'Một tấm bản đồ cổ, dẫn đến kho báu bị lãng quên.', icon: itemAssets.ancientMap }],
    [15, { id: 15, name: 'Legendary Sword', type: 'weapon', rarity: 'SR', description: 'Thanh kiếm huyền thoại, mang sức mạnh hủy diệt.', stats: { damage: 50, criticalChance: 15, durability: 150 }, icon: itemAssets.legendarySword, maxLevel: 50 }],
    [16, { id: 16, name: 'Mythical Bow', type: 'weapon', rarity: 'SSR', description: 'Cây cung thần thoại, bắn ra những mũi tên có thể xuyên thủng mọi thứ.', stats: { damage: 45, attackSpeed: 1.2, criticalChance: 20, durability: 140 }, icon: itemAssets.mythicalBow, maxLevel: 50 }],
    [17, { id: 17, name: 'Dragon Scale Armor', type: 'armor', rarity: 'SR', description: 'Bộ giáp làm từ vảy rồng, gần như không thể xuyên thủng.', stats: { defense: 40, magicResist: 20, durability: 180 }, icon: itemAssets.dragonScaleArmor, maxLevel: 50 }],
    [18, { id: 18, name: 'Ring of Power', type: 'accessory', rarity: 'SSR', description: 'Chiếc nhẫn quyền năng, tăng cường mọi chỉ số.', stats: { damage: 10, defense: 10, magicDamage: 10, health: 100, mana: 50, durability: 100 }, icon: itemAssets.ringOfPower }],
    [19, { id: 19, name: 'Elixir of Life', type: 'potion', rarity: 'SR', description: 'Hồi phục toàn bộ máu và mana, loại bỏ mọi hiệu ứng xấu.', stats: { healthRestore: 9999, manaRestore: 9999 }, icon: itemAssets.elixirOfLife }],
    [20, { id: 20, name: 'Dark Cloak', type: 'armor', rarity: 'B', description: 'Áo choàng bóng tối, giúp người mặc ẩn mình và di chuyển nhanh hơn.', stats: { defense: 8, agility: 5, durability: 50 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_34_20%20PM.png', maxLevel: 25 }],
    [21, { id: 21, name: 'Frostmourne', type: 'weapon', rarity: 'SR', description: 'Thanh kiếm băng giá, có thể đóng băng kẻ thù.', stats: { damage: 40, iceDamage: 20, durability: 160 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_35_10%20PM.png', maxLevel: 50 }],
    [22, { id: 22, name: 'Wand of Elements', type: 'weapon', rarity: 'A', description: 'Cây đũa phép điều khiển các nguyên tố, gây sát thương phép đa dạng.', stats: { magicDamage: 25, fireDamage: 10, iceDamage: 10, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_35_48%20PM.png', maxLevel: 35 }],
    [23, { id: 23, name: 'Shield of Valor', type: 'armor', rarity: 'A', description: 'Chiếc khiên của sự dũng cảm, tăng cường phòng thủ và tinh thần.', stats: { defense: 30, health: 80, durability: 120 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_36_35%20PM.png', maxLevel: 40 }],
    [24, { id: 24, name: 'Boots of Speed', type: 'accessory', rarity: 'B', description: 'Đôi giày tốc độ, giúp di chuyển nhanh nhẹn hơn.', stats: { agility: 10, durability: 60 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_37_17%20PM.png', maxLevel: 30 }],
    [25, { id: 25, name: 'Amulet of Wisdom', type: 'accessory', rarity: 'A', description: 'Tăng cường trí tuệ và khả năng học hỏi.', stats: { intelligence: 15, manaRegen: 7, durability: 80 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_37_50%20PM.png', maxLevel: 35 }],
    [26, { id: 26, name: 'Titan Axe', type: 'weapon', rarity: 'SR', description: 'Chiếc rìu của Titan, sức mạnh vật lý vượt trội.', stats: { damage: 48, strength: 20, durability: 170 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_38_38%20PM.png', maxLevel: 50 }],
    [27, { id: 27, name: 'Robe of Archmage', type: 'armor', rarity: 'SR', description: 'Áo choàng của Tổng Pháp Sư, tăng cường ma thuật tối đa.', stats: { magicDefense: 35, intelligence: 25, mana: 150, durability: 130 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_39_18%20PM.png', maxLevel: 50 }],
    [28, { id: 28, name: 'Poison Vial', type: 'potion', rarity: 'D', description: 'Gây độc lên vũ khí hoặc kẻ thù.', stats: { poisonDamage: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_40_04%20PM.png' }],
    [29, { id: 29, name: 'Enchanting Dust', type: 'material', rarity: 'B', description: 'Bụi phép thuật, dùng để cường hóa trang bị.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_40_37%20PM.png' }],
    [30, { id: 30, name: 'Map Fragment', type: 'quest', rarity: 'D', description: 'Một mảnh bản đồ rách nát, có thể ghép lại để tìm kho báu.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_41_12%20PM.png' }],
    [31, { id: 31, name: 'Soul Gem', type: 'material', rarity: 'A', description: 'Viên đá linh hồn, chứa đựng sức mạnh bí ẩn.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_42_05%20PM.png' }],
    [32, { id: 32, name: 'Phoenix Feather', type: 'material', rarity: 'SR', description: 'Lông chim phượng hoàng, cực kỳ hiếm, dùng để chế tạo trang bị huyền thoại.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2006_42_44%20PM.png' }],
    [33, { id: 33, name: 'Berserker\'s Axe', type: 'weapon', rarity: 'A', description: 'Chiếc rìu của chiến binh cuồng nộ, sát thương cao nhưng giảm phòng thủ.', stats: { damage: 35, defense: -5, durability: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2007_58_56%20PM.png', maxLevel: 40 }],
    [34, { id: 34, name: 'Shadow Blade', type: 'weapon', rarity: 'A', description: 'Lưỡi kiếm bóng tối, có khả năng tàng hình và gây sát thương bất ngờ.', stats: { damage: 28, criticalChance: 10, agility: 7, durability: 95 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2007_59_34%20PM.png', maxLevel: 38 }],
    [35, { id: 35, name: 'Holy Greatsword', type: 'weapon', rarity: 'SR', description: 'Đại kiếm thần thánh, ban phước lành và gây sát thương lớn lên quỷ dữ.', stats: { damage: 45, holyDamage: 25, durability: 160 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_00_17%20PM.png', maxLevel: 50 }],
    [36, { id: 36, name: 'Vampiric Scepter', type: 'weapon', rarity: 'A', description: 'Quyền trượng ma cà rồng, hút máu kẻ địch để hồi phục cho người dùng.', stats: { magicDamage: 22, lifeSteal: 15, durability: 85 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_00_56%20PM.png', maxLevel: 37 }],
    [37, { id: 37, name: 'Elemental Orb', type: 'accessory', rarity: 'B', description: 'Tăng cường sức mạnh nguyên tố và khả năng kháng phép.', stats: { fireResist: 5, iceResist: 5, lightningResist: 5, durability: 75 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_01_38%20PM.png' }],
    [38, { id: 38, name: 'Thieves\' Gloves', type: 'accessory', rarity: 'D', description: 'Găng tay của đạo tặc, tăng tỉ lệ nhặt được vật phẩm hiếm.', stats: { luck: 5, durability: 30 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_02_15%20PM.png' }],
    [39, { id: 39, name: 'Alchemist\'s Manual', type: 'misc', rarity: 'B', description: 'Hướng dẫn pha chế thuốc, tăng hiệu quả các loại potion.', stats: { potionEfficiency: 20 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_02_57%20PM.png' }],
    [40, { id: 40, name: 'Orb of Enlightenment', type: 'accessory', rarity: 'S', description: 'Tăng cường nhận thức và tốc độ hồi phục năng lượng.', stats: { manaRegen: 10, intelligence: 10, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_03_36%20PM.png' }],
    [41, { id: 41, name: 'Giga Drill Breaker', type: 'weapon', rarity: 'SSR', description: 'Mũi khoan khổng lồ, phá hủy mọi thứ cản đường.', stats: { damage: 60, piercing: 30, durability: 200 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_04_31%20PM.png', maxLevel: 50 }],
    [42, { id: 42, name: 'Celestial Armor', type: 'armor', rarity: 'SSR', description: 'Bộ giáp của thiên thần, bảo vệ tuyệt đối và ban phước lành.', stats: { defense: 50, magicResist: 30, holyResist: 30, durability: 220 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_05_13%20PM.png', maxLevel: 50 }],
    [43, { id: 43, name: 'Eternal Flame Ring', type: 'accessory', rarity: 'S', description: 'Chiếc nhẫn lửa vĩnh cửu, gây sát thương lửa liên tục và tăng cường sức mạnh.', stats: { fireDamage: 15, strength: 10, durability: 110 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_06_00%20PM.png' }],
    [44, { id: 44, name: 'Time-Warp Potion', type: 'potion', rarity: 'A', description: 'Làm chậm thời gian xung quanh, tăng tốc độ di chuyển và hành động của người dùng.', stats: { speedBoost: 50, duration: 10 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_06_39%20PM.png' }],
    [45, { id: 45, name: 'Void Crystal', type: 'material', rarity: 'SR', description: 'Pha lê đến từ Hư Không, chứa đựng năng lượng tối tăm.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_07_20%20PM.png' }],
    [46, { id: 46, name: 'Thunder Hammer', type: 'weapon', rarity: 'A', description: 'Cây búa sấm sét, triệu hồi sét đánh kẻ thù và gây choáng.', stats: { damage: 32, lightningDamage: 18, stunChance: 10, durability: 110 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_08_01%20PM.png', maxLevel: 42 }],
    [47, { id: 47, name: 'Nature\'s Embrace Staff', type: 'weapon', rarity: 'S', description: 'Cây trượng ôm ấp thiên nhiên, tăng cường hồi phục và sức mạnh phép thuật tự nhiên.', stats: { magicDamage: 28, healthRegen: 5, natureDamage: 15, durability: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_08_48%20PM.png', maxLevel: 45 }],
    [48, { id: 48, name: 'Shield of the Forest', type: 'armor', rarity: 'B', description: 'Chiếc khiên của rừng xanh, bảo vệ và tăng cường sức mạnh tự nhiên.', stats: { defense: 20, natureResist: 10, durability: 80 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_09_25%20PM.png', maxLevel: 30 }],
    [49, { id: 49, name: 'Winged Boots', type: 'accessory', rarity: 'A', description: 'Đôi giày có cánh, cho phép người dùng bay lượn trong thời gian ngắn.', stats: { flightDuration: 15, agility: 15, durability: 70 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_07%20PM.png' }],
    [50, { id: 50, name: 'Orb of Distortion', type: 'accessory', rarity: 'SR', description: 'Quả cầu bóp méo không gian, có thể dịch chuyển tức thời một khoảng cách ngắn.', stats: { teleportRange: 10, manaCost: 20, durability: 95 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_45%20PM.png' }],
    [51, { id: 51, name: 'Starforged Blade', type: 'weapon', rarity: 'SSR', description: 'Lưỡi kiếm được rèn từ ánh sao, gây sát thương phép và vật lý hỗn hợp.', stats: { damage: 35, magicDamage: 35, lightDamage: 20, durability: 180 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_11_25%20PM.png', maxLevel: 50 }],
    [52, { id: 52, name: 'Cursed Amulet', type: 'accessory', rarity: 'D', description: 'Một chiếc bùa bị nguyền rủa, tăng sức mạnh nhưng gây ra tác dụng phụ tiêu cực.', stats: { damage: 10, health: -20, durability: 50 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_12_05%20PM.png' }],
    [53, { id: 53, name: 'Essence of Purity', type: 'material', rarity: 'A', description: 'Tinh túy của sự tinh khiết, dùng để thanh lọc hoặc chế tạo vật phẩm linh thiêng.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_12_41%20PM.png' }],
    [54, { id: 54, name: 'Ancient Tome', type: 'misc', rarity: 'S', description: 'Quyển sách cổ xưa, chứa đựng kiến thức bị lãng quên, tăng cường trí tuệ vĩnh viễn.', stats: { intelligence: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_13_20%20PM.png' }],
    [55, { id: 55, name: 'Venomous Dagger', type: 'weapon', rarity: 'B', description: 'Dao găm tẩm độc, gây sát thương theo thời gian.', stats: { damage: 15, poisonDamage: 5, durability: 60 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_07%20PM.png', maxLevel: 28 }],
    [56, { id: 56, name: 'Battle-worn Shield', type: 'armor', rarity: 'D', description: 'Chiếc khiên đã qua nhiều trận chiến, vẫn còn khả năng phòng thủ cơ bản.', stats: { defense: 12, durability: 35 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_45%20PM.png', maxLevel: 22 }],
    [57, { id: 57, name: 'Swift Bow', type: 'weapon', rarity: 'B', description: 'Cây cung nhanh nhẹn, cho phép bắn tên liên tục.', stats: { damage: 18, attackSpeed: 0.8, durability: 70 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_15_24%20PM.png', maxLevel: 30 }],
    [58, { id: 58, name: 'Steel Gauntlets', type: 'armor', rarity: 'B', description: 'Găng tay thép, tăng cường phòng thủ tay và sức mạnh đòn đánh.', stats: { defense: 7, strength: 3, durability: 55 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_16_04%20PM.png', maxLevel: 27 }],
    [59, { id: 59, name: 'Enchanted Quiver', type: 'accessory', rarity: 'A', description: 'Túi tên được yểm bùa, tự động tạo ra tên phép và tăng sát thương cho cung.', stats: { arrowDamage: 10, manaRegen: 3, durability: 80 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_16_42%20PM.png' }],
    [60, { id: 60, name: 'Mystic Catalyst', type: 'misc', rarity: 'B', description: 'Vật phẩm xúc tác ma thuật, tăng cường hiệu quả các phép thuật và kĩ năng.', stats: { magicEfficiency: 15 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_17_26%20PM.png' }],
    [61, { id: 61, name: 'Giant\'s Club', type: 'weapon', rarity: 'A', description: 'Cây chùy khổng lồ, gây sát thương vật lý cực lớn nhưng tấn công chậm.', stats: { damage: 40, attackSpeed: -0.5, durability: 130 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_18_07%20PM.png', maxLevel: 45 }],
    [62, { id: 62, name: 'Featherlight Armor', type: 'armor', rarity: 'A', description: 'Bộ giáp nhẹ như lông vũ, cung cấp phòng thủ tốt mà không làm giảm tốc độ.', stats: { defense: 22, agility: 8, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_18_45%20PM.png', maxLevel: 38 }],
    [63, { id: 63, name: 'Arcane Grimoire', type: 'misc', rarity: 'S', description: 'Cuốn sách phép thuật cổ, chứa đựng những câu thần chú mạnh mẽ.', stats: { spellPower: 20, mana: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_19_23%20PM.png' }],
    [64, { id: 64, name: 'Runed Blade', type: 'weapon', rarity: 'B', description: 'Thanh kiếm được khắc rune cổ xưa, gây sát thương phép bổ sung.', stats: { damage: 20, magicDamage: 8, durability: 75 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_20_08%20PM.png', maxLevel: 33 }],
    [65, { id: 65, name: 'Spirit Shroud', type: 'armor', rarity: 'S', description: 'Tấm vải liệm của linh hồn, giúp người mặc trở nên vô hình trong chốc lát.', stats: { defense: 18, stealth: 20, durability: 85 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_20_44%20PM.png', maxLevel: 40 }],
    [66, { id: 66, name: 'Gloves of the Master Thief', type: 'accessory', rarity: 'S', description: 'Găng tay của bậc thầy trộm cắp, tăng cực cao tỉ lệ thành công khi trộm đồ và mở khóa.', stats: { pickpocketChance: 30, lockpickingSkill: 25, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_21_21%20PM.png' }],
    [67, { id: 67, name: 'Orb of Summoning', type: 'misc', rarity: 'A', description: 'Quả cầu triệu hồi, cho phép người dùng triệu hồi một đồng minh tạm thời.', stats: { summonDuration: 30, summonStrength: 10, manaCost: 50 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_22_01%20PM.png' }],
    [68, { id: 68, name: 'Blade of the Fallen Star', type: 'weapon', rarity: 'SR', description: 'Lưỡi kiếm từ ngôi sao rơi, gây sát thương bùng nổ và có khả năng thiêu đốt.', stats: { damage: 42, fireDamage: 22, explosionChance: 15, durability: 170 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_22_41%20PM.png', maxLevel: 50 }],
    [69, { id: 69, name: 'Divine Quarterstaff', type: 'weapon', rarity: 'S', description: 'Cây trượng của thần linh, khuếch đại ánh sáng, tăng cường sát thương phép và hồi phục mana.', stats: { magicDamage: 20, manaRegen: 7, durability: 90, lightDamage: 8, intelligence: 10 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_23_51%20PM.png', maxLevel: 30 }], // THAY ĐỔI: Thêm Divine Quarterstaff
    [74, { id: 74, name: 'Meteor Staff', type: 'weapon', rarity: 'A', description: 'Cây trượng chứa sức mạnh của thiên thạch, có thể triệu hồi mưa sao băng.', stats: { magicDamage: 30, fireDamage: 15, intelligence: 15, durability: 110 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2010_44_50%20AM.png', maxLevel: 40 }],
    [75, { id: 75, name: 'Assassin\'s Dagger', type: 'weapon', rarity: 'D', description: 'Con dao găm của sát thủ, sắc bén và dễ dàng ẩn mình trong bóng tối.', stats: { damage: 12, criticalChance: 5, agility: 3, durability: 30 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2008_43_52%20PM.png', maxLevel: 20 }],
    [76, { id: 76, name: 'Sacrificial Sword', type: 'weapon', rarity: 'B', description: 'Thanh kiếm được sử dụng trong các nghi lễ hiến tế, mang sức mạnh huyền bí.', stats: { damage: 25, magicDamage: 5, durability: 70 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2008_39_13%20PM.png', maxLevel: 35 }], // THAY ĐỔI: Thêm Sacrificial Sword
    [77, { id: 77, name: 'Leviathan Axe', type: 'weapon', rarity: 'A', description: 'Chiếc rìu huyền thoại, có thể triệu hồi băng giá và trở về tay chủ nhân.', stats: { damage: 38, iceDamage: 12, durability: 120 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2008_56_07%20PM.png', maxLevel: 45 }], // THAY ĐỔI: Thêm Leviathan Axe
]);
