// --- START OF FILE src/data/item-database.ts ---

import { itemAssets } from '../game-assets.ts';

// THAY ĐỔI: Định nghĩa kiểu ItemRank mới để sử dụng trong toàn bộ hệ thống.
export type ItemRank = 'E' | 'D' | 'B' | 'A' | 'S' | 'SR' | 'SSR';

// THAY ĐỔI: Cập nhật cấu trúc ItemDefinition để sử dụng ItemRank mới.
export interface ItemDefinition {
    id: number;
    name: string;
    type: 'weapon' | 'potion' | 'armor' | 'accessory' | 'material' | 'currency' | 'misc' | 'quest' | 'piece';
    rarity: ItemRank; // Sử dụng hệ thống Rank mới
    description: string;
    icon: string;
    stats?: { [key: string]: any };
    maxLevel?: number;
}

// THAY ĐỔI: Cập nhật toàn bộ database với hệ thống Rank mới.
// Logic ánh xạ: common -> E, uncommon -> D, rare -> B, epic -> A/S, legendary -> SR/SSR
export const itemDatabase = new Map<number, ItemDefinition>([
    [1, { id: 1, name: 'Kiếm gỗ', type: 'weapon', rarity: 'E', description: 'Một thanh kiếm gỗ cơ bản, thích hợp cho người mới bắt đầu.', stats: { damage: 5, durability: 20 }, icon: itemAssets.kiemGo, maxLevel: 10 }],
    [2, { id: 2, name: 'Hard Armor', type: 'armor', rarity: 'B', description: 'Một bộ giáp cứng cáp, tăng cường phòng thủ và sức chịu đựng.', stats: { defense: 15, durability: 60, stamina: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_07_27%20PM.png', maxLevel: 20 }],
    [3, { id: 3, name: 'Basic Potion', type: 'potion', rarity: 'E', description: 'Một lọ thuốc cơ bản, hồi phục một lượng nhỏ máu.', stats: { heal: 30 }, icon: itemAssets.basicPotion }],
    [4, { id: 4, name: 'Mana Crystal', type: 'material', rarity: 'D', description: 'Tinh thể mana, dùng để chế tạo hoặc nâng cấp trang bị phép thuật.', icon: itemAssets.manaCrystal }],
    [5, { id: 5, name: 'Gold Coin', type: 'currency', rarity: 'E', description: 'Đồng tiền vàng, đơn vị tiền tệ cơ bản.', icon: itemAssets.goldCoin }],
    [6, { id: 6, name: 'Old Map', type: 'quest', rarity: 'B', description: 'Một tấm bản đồ cũ kỹ, có thể dẫn đến kho báu bị lãng quên.', icon: itemAssets.oldMap }],
    [7, { id: 7, name: 'Leather Boots', type: 'armor', rarity: 'D', description: 'Đôi giày da nhẹ, tăng tốc độ di chuyển.', stats: { speed: 5, durability: 30 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_07_46%20PM.png', maxLevel: 15 }],
    [8, { id: 8, name: 'Healing Orb', type: 'potion', rarity: 'B', description: 'Quả cầu hồi phục, cung cấp lượng lớn máu trong thời gian ngắn.', stats: { heal: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_08_09%20PM.png' }],
    [9, { id: 9, name: 'Iron Sword', type: 'weapon', rarity: 'D', description: 'Kiếm sắt, sát thương cao hơn kiếm gỗ.', stats: { damage: 10, durability: 35 }, icon: itemAssets.ironSword, maxLevel: 15 }],
    [10, { id: 10, name: 'Wooden Shield', type: 'armor', rarity: 'E', description: 'Khiên gỗ, phòng thủ cơ bản.', stats: { defense: 7, durability: 25 }, icon: itemAssets.woodenShield, maxLevel: 10 }],
    [11, { id: 11, name: 'Minor Mana Potion', type: 'potion', rarity: 'D', description: 'Hồi phục một lượng nhỏ mana.', stats: { manaRestore: 20 }, icon: itemAssets.minorManaPotion }],
    [12, { id: 12, name: 'Lesser Healing Potion', type: 'potion', rarity: 'D', description: 'Hồi phục một lượng nhỏ máu.', stats: { heal: 50 }, icon: itemAssets.lesserHealingPotion }],
    [13, { id: 13, name: 'Elixir of Strength', type: 'potion', rarity: 'B', description: 'Tăng cường sức mạnh tạm thời.', stats: { strengthBoost: 10 }, icon: itemAssets.elixirOfStrength }],
    [14, { id: 14, name: 'Ring of Protection', type: 'accessory', rarity: 'B', description: 'Tăng phòng thủ vật lý và phép thuật.', stats: { defense: 5, magicDefense: 5 }, icon: itemAssets.ringOfProtection }],
    [15, { id: 15, name: 'Ancient Scroll', type: 'quest', rarity: 'A', description: 'Cuộn giấy cổ, chứa đựng bí mật của một nền văn minh đã mất.', icon: itemAssets.ancientScroll }],
    [16, { id: 16, name: 'Dragon Scale', type: 'material', rarity: 'A', description: 'Vảy rồng, nguyên liệu quý hiếm để chế tạo trang bị huyền thoại.', icon: itemAssets.dragonScale }],
    [17, { id: 17, name: 'Mystic Orb', type: 'misc', rarity: 'S', description: 'Quả cầu thần bí, có thể mở ra những khả năng tiềm ẩn.', icon: itemAssets.mysticOrb }],
    [18, { id: 18, name: 'Silver Key', type: 'misc', rarity: 'C', description: 'Một chiếc chìa khóa bằng bạc, có thể mở được những cánh cửa bí mật.', icon: itemAssets.silverKey }],
    [19, { id: 19, name: 'Enchanted Bow', type: 'weapon', rarity: 'A', description: 'Cung phép, mũi tên mang theo sức mạnh ma thuật.', stats: { damage: 20, attackSpeed: 10, magicDamage: 15 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_08_32%20PM.png', maxLevel: 30 }],
    [20, { id: 20, name: 'Plate Armor', type: 'armor', rarity: 'A', description: 'Áo giáp nặng, phòng thủ tối đa nhưng giảm tốc độ di chuyển.', stats: { defense: 30, durability: 100, speed: -5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_08_48%20PM.png', maxLevel: 35 }],
    [21, { id: 21, name: 'Greater Healing Potion', type: 'potion', rarity: 'A', description: 'Hồi phục lượng máu lớn.', stats: { heal: 200 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_09_05%20PM.png' }],
    [22, { id: 22, name: 'Grand Mana Potion', type: 'potion', rarity: 'A', description: 'Hồi phục lượng mana lớn.', stats: { manaRestore: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_09_22%20PM.png' }],
    [23, { id: 23, name: 'Amulet of Wisdom', type: 'accessory', rarity: 'S', description: 'Tăng cường trí tuệ và khả năng học hỏi.', stats: { intelligence: 10, wisdom: 10 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_09_38%20PM.png' }],
    [24, { id: 24, name: 'Phoenix Feather', type: 'material', rarity: 'SR', description: 'Lông phượng hoàng, vật liệu hiếm có sức mạnh tái sinh.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_01%20PM.png' }],
    [25, { id: 25, name: 'Shadow Cloak', type: 'armor', rarity: 'S', description: 'Áo choàng bóng đêm, tăng khả năng tàng hình và né tránh.', stats: { stealth: 20, evasion: 15, durability: 70 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_23%20PM.png', maxLevel: 40 }],
    [26, { id: 26, name: 'Elemental Staff', type: 'weapon', rarity: 'S', description: 'Gậy phép thuật của các nguyên tố, gây sát thương phép thuật đa dạng.', stats: { magicDamage: 30, manaCostReduction: 0.1, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_42%20PM.png', maxLevel: 45 }],
    [27, { id: 27, name: 'Holy Relic', type: 'quest', rarity: 'SSR', description: 'Di vật thần thánh, chứa đựng sức mạnh vô biên, là mục tiêu của nhiều thế lực.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_10_58%20PM.png' }],
    [28, { id: 28, name: 'Adamantite Ore', type: 'material', rarity: 'S', description: 'Quặng Adamantite, kim loại cứng nhất, dùng để rèn vũ khí và giáp trụ.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_11_13%20PM.png' }],
    [29, { id: 29, name: 'Vampire\'s Kiss', type: 'weapon', rarity: 'SR', description: 'Thanh kiếm của ma cà rồng, hút máu đối thủ để hồi phục cho người dùng.', stats: { damage: 40, lifesteal: 0.2, durability: 120 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_11_33%20PM.png', maxLevel: 50 }],
    [30, { id: 30, name: 'Crown of the Lich King', type: 'accessory', rarity: 'SSR', description: 'Vương miện của Vua Lich, ban sức mạnh điều khiển tử linh và tăng cường phép thuật bóng tối.', stats: { magicDamage: 50, darkMagicBonus: 0.25, manaRegen: 15 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_11_54%20PM.png' }],
    [31, { id: 31, name: 'Divine Shield', type: 'armor', rarity: 'SR', description: 'Khiên thần thánh, bất hoại và phản lại sát thương.', stats: { defense: 50, blockChance: 0.3, damageReflection: 0.1 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_12_11%20PM.png', maxLevel: 55 }],
    [32, { id: 32, name: 'Tome of Eldritch Lore', type: 'misc', rarity: 'SSR', description: 'Sách cổ chứa kiến thức cấm kỵ, mở khóa phép thuật mạnh mẽ.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_12_29%20PM.png' }],
    [33, { id: 33, name: 'Essence of Chaos', type: 'material', rarity: 'SSR', description: 'Tinh túy hỗn loạn, nguyên liệu mạnh nhất để chế tạo vật phẩm cuối cùng.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_12_44%20PM.png' }],
    [34, { id: 34, name: 'Bow of the Forest Guardian', type: 'weapon', rarity: 'A', description: 'Chiếc cung của người bảo vệ rừng, cung cấp sát thương ổn định và độ chính xác cao.', stats: { damage: 22, attackSpeed: 12, accuracy: 0.85, durability: 75 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_06_40%20PM.png', maxLevel: 30 }],
    [35, { id: 35, name: 'Robes of the Archmage', type: 'armor', rarity: 'S', description: 'Áo choàng của Đại Pháp Sư, tăng cường sức mạnh phép thuật và giảm thời gian hồi chiêu.', stats: { magicDamage: 25, cooldownReduction: 0.15, durability: 80 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_13_02%20PM.png', maxLevel: 40 }],
    [36, { id: 36, name: 'Gloves of Swiftness', type: 'accessory', rarity: 'B', description: 'Đôi găng tay nhẹ, tăng tốc độ tấn công và khả năng né tránh.', stats: { attackSpeed: 10, evasion: 8 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_13_17%20PM.png' }],
    [37, { id: 37, name: 'Berserker\'s Axe', type: 'weapon', rarity: 'S', description: 'Rìu của chiến binh cuồng nộ, sát thương cực lớn khi máu thấp.', stats: { damage: 35, critChance: 0.2, healthThresholdDamageBonus: 0.5, durability: 100 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_13_32%20PM.png', maxLevel: 45 }],
    [38, { id: 38, name: 'Healer\'s Circlet', type: 'accessory', rarity: 'A', description: 'Vòng đội đầu của người chữa trị, tăng cường hiệu quả hồi máu và mana.', stats: { healingEffectiveness: 0.2, manaRegen: 10 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_13_47%20PM.png' }],
    [39, { id: 39, name: 'Orb of Scrying', type: 'misc', rarity: 'A', description: 'Quả cầu thám thính, dùng để nhìn xuyên qua màn sương mù chiến tranh và phát hiện kẻ thù.', icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_01%20PM.png' }],
    [70, { id: 70, name: 'Dragon\'s Breath Axe', type: 'weapon', rarity: 'S', description: 'Cây rìu mạnh mẽ với hơi thở rồng, gây sát thương lửa và có khả năng thiêu đốt kẻ thù.', stats: { damage: 45, fireDamage: 15, burnChance: 0.2, durability: 110, strength: 15 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_01%20PM.png', maxLevel: 50 }],
    [71, { id: 71, name: 'Forest Spirit\'s Staff', type: 'weapon', rarity: 'B', description: 'Cây trượng của linh hồn rừng, tăng cường sức mạnh phép thuật tự nhiên và hồi phục sức khỏe cho đồng minh tốt.', stats: { damage: 15, durability: 50, strength: 3 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_06_40%20PM.png', maxLevel: 15 }],
    [72, { id: 72, name: 'Demon King\'s Daggers', type: 'weapon', rarity: 'A', description: 'Cặp dao găm của Quỷ Vương, cho phép tấn công nhanh và chí mạng cao, tẩm độc gây sát thương theo thời gian.', stats: { damage: 25, attackSpeed: 30, durability: 80, agility: 10, critChance: 0.15, poisonDamage: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_19%20PM.png', maxLevel: 35 }],
    [73, { id: 73, name: 'Divine Quarterstaff', type: 'weapon', rarity: 'B', description: 'Cây gậy chiến thần thánh, mang sức mạnh của ánh sáng, tăng cường sát thương phép và hồi phục mana.', stats: { magicDamage: 20, manaRegen: 7 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_19%20PM.png', maxLevel: 35 }],
    [74, { id: 74, name: 'Meteor Staff', type: 'weapon', rarity: 'A', description: 'Gậy thiên thạch, gọi ra những trận mưa sao băng thiêu rụi kẻ thù.', stats: { magicDamage: 40, areaDamage: 10, spellCritChance: 0.1, durability: 90 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2010_44_50%20AM.png', maxLevel: 40 }]
]);
