// --- START OF FILE src/data/item-database.ts ---

import { itemAssets } from '../game-assets.ts';

// THAY ĐỔI: Định nghĩa kiểu ItemRank mới để sử dụng trong toàn bộ hệ thống.
export type ItemRank = 'E' | 'D' | 'B' | 'A' | 'S' | 'SR' | 'SSR';

// THAY ĐỔI: Cập nhật cấu trúc ItemDefinition để sử dụng ItemRank mới.
export interface ItemDefinition {
    id: number;
    name: string;
    type: 'weapon' | 'potion' | 'armor' | 'accessory' | 'material' | 'currency' | 'misc' | 'quest' | 'piece';
    rarity: ItemRank; // Sử dụng hệ thống Rank mới
    description: string;
    icon: string;
    stats?: { [key: string]: any }; 
    maxLevel?: number;
}

// THAY ĐỔI: Cập nhật toàn bộ database với hệ thống Rank mới.
// Logic ánh xạ: common -> E, uncommon -> D, rare -> B, epic -> A/S, legendary -> SR/SSR
export const itemDatabase = new Map<number, ItemDefinition>([
    [1, { id: 1, name: 'Kiếm gỗ', type: 'weapon', rarity: 'E', description: 'Một thanh kiếm gỗ cơ bản, thích hợp cho người mới bắt đầu.', stats: { damage: 5, durability: 20 }, icon: itemAssets.kiemGo, maxLevel: 10 }],
    [2, { id: 2, name: 'Hard Armor', type: 'armor', rarity: 'B', description: 'Bộ giáp cứng cáp, bảo vệ tốt hơn khỏi các đòn tấn công vật lý.', stats: { defense: 15, durability: 60 }, icon: itemAssets.hardArmor, maxLevel: 25 }],
    [3, { id: 3, name: 'Small Health Potion', type: 'potion', rarity: 'E', description: 'Hồi phục một lượng nhỏ máu.', stats: { heal: 20 }, icon: itemAssets.smallHealthPotion }],
    [4, { id: 4, name: 'Magic Wand', type: 'weapon', rarity: 'D', description: 'Một cây đũa phép đơn giản, thích hợp cho việc học các phép thuật cơ bản.', stats: { magicDamage: 10, manaCostReduction: 0.05 }, icon: itemAssets.magicWand, maxLevel: 15 }],
    [5, { id: 5, name: 'Leather Boots', type: 'armor', rarity: 'D', description: 'Đôi ủng da nhẹ, tăng cường tốc độ di chuyển.', stats: { defense: 5, speed: 2 }, icon: itemAssets.leatherBoots, maxLevel: 15 }],
    [6, { id: 6, name: 'Large Health Potion', type: 'potion', rarity: 'D', description: 'Hồi phục một lượng lớn máu.', stats: { heal: 50 }, icon: itemAssets.largeHealthPotion }],
    [7, { id: 7, name: 'Iron Sword', type: 'weapon', rarity: 'D', description: 'Thanh kiếm sắt chắc chắn, sát thương tốt hơn kiếm gỗ.', stats: { damage: 15, durability: 40 }, icon: itemAssets.ironSword, maxLevel: 20 }],
    [8, { id: 8, name: 'Iron Shield', type: 'armor', rarity: 'D', description: 'Một chiếc khiên sắt, tăng khả năng phòng thủ đáng kể.', stats: { defense: 10, durability: 50 }, icon: itemAssets.ironShield, maxLevel: 20 }],
    [9, { id: 9, name: 'Basic Mana Potion', type: 'potion', rarity: 'D', description: 'Hồi phục một lượng mana nhỏ.', stats: { manaRestore: 30 }, icon: itemAssets.basicManaPotion }],
    [10, { id: 10, name: 'Mana Potion', type: 'potion', rarity: 'B', description: 'Hồi phục một lượng mana vừa phải.', stats: { manaRestore: 70 }, icon: itemAssets.manaPotion }],
    [11, { id: 11, name: 'Light Armor', type: 'armor', rarity: 'D', description: 'Bộ giáp nhẹ, cung cấp sự cân bằng giữa phòng thủ và tốc độ.', stats: { defense: 10, speed: 1 }, icon: itemAssets.lightArmor, maxLevel: 20 }],
    [12, { id: 12, name: 'Ring of Strength', type: 'accessory', rarity: 'B', description: 'Chiếc nhẫn tăng cường sức mạnh thể chất.', stats: { strength: 5 }, icon: itemAssets.ringOfStrength }],
    [13, { id: 13, name: 'Necklace of Wisdom', type: 'accessory', rarity: 'B', description: 'Dây chuyền tăng cường trí tuệ và mana tối đa.', stats: { intelligence: 5, maxMana: 20 }, icon: itemAssets.necklaceOfWisdom }],
    [14, { id: 14, name: 'Greater Health Potion', type: 'potion', rarity: 'B', description: 'Hồi phục một lượng lớn máu và tăng nhẹ sức đề kháng.', stats: { heal: 100, resistance: 5 }, icon: itemAssets.greaterHealthPotion }],
    [15, { id: 15, name: 'Long Sword', type: 'weapon', rarity: 'B', description: 'Thanh kiếm dài, sát thương và tầm đánh tốt hơn kiếm sắt.', stats: { damage: 20, durability: 50 }, icon: itemAssets.longSword, maxLevel: 30 }],
    [16, { id: 16, name: 'Steel Armor', type: 'armor', rarity: 'B', description: 'Bộ giáp thép nặng, phòng thủ cao nhưng làm chậm di chuyển.', stats: { defense: 25, speed: -1 }, icon: itemAssets.steelArmor, maxLevel: 35 }],
    [17, { id: 17, name: 'Magic Staff', type: 'weapon', rarity: 'B', description: 'Cây trượng phép thuật, tăng cường sức mạnh phép thuật và khả năng hồi mana.', stats: { magicDamage: 15, manaRegen: 3 }, icon: itemAssets.magicStaff, maxLevel: 30 }],
    [18, { id: 18, name: 'Healing Orb', type: 'misc', rarity: 'B', description: 'Quả cầu phát ra năng lượng hồi phục, có thể sử dụng nhiều lần.', stats: { healOverTime: 5, duration: 10 }, icon: itemAssets.healingOrb }],
    [19, { id: 19, name: 'Swift Boots', type: 'armor', rarity: 'B', description: 'Đôi ủng giúp di chuyển nhanh nhẹn hơn.', stats: { defense: 7, speed: 4 }, icon: itemAssets.swiftBoots, maxLevel: 25 }],
    [20, { id: 20, name: 'Elixir of Focus', type: 'potion', rarity: 'A', description: 'Tăng cường khả năng tập trung, giảm thời gian hồi chiêu và tăng sát thương phép.', stats: { cooldownReduction: 0.1, magicDamage: 10 }, icon: itemAssets.elixirOfFocus }],
    [21, { id: 21, name: 'Plate Armor', type: 'armor', rarity: 'A', description: 'Bộ giáp tấm hạng nặng, phòng thủ tối ưu.', stats: { defense: 40, durability: 100, speed: -2 }, icon: itemAssets.plateArmor, maxLevel: 45 }],
    [22, { id: 22, name: 'Great Sword', type: 'weapon', rarity: 'A', description: 'Thanh đại kiếm khổng lồ, gây sát thương cực lớn nhưng yêu cầu sức mạnh.', stats: { damage: 40, durability: 70, strengthRequired: 20 }, icon: itemAssets.greatSword, maxLevel: 40 }],
    [23, { id: 23, name: 'Mystic Robes', type: 'armor', rarity: 'A', description: 'Bộ áo choàng của pháp sư cổ đại, tăng cường mạnh mẽ sức mạnh phép thuật.', stats: { magicDefense: 20, magicDamage: 15, intelligence: 10 }, icon: itemAssets.mysticRobes, maxLevel: 40 }],
    [24, { id: 24, name: 'Master Healing Potion', type: 'potion', rarity: 'A', description: 'Hồi phục toàn bộ máu và mana, loại bỏ mọi hiệu ứng xấu.', stats: { fullHeal: true, fullMana: true, cleanse: true }, icon: itemAssets.masterHealingPotion }],
    [25, { id: 25, name: 'Amulet of Protection', type: 'accessory', rarity: 'A', description: 'Bùa hộ mệnh, tăng cường phòng thủ và kháng phép.', stats: { defense: 10, magicDefense: 10, resistance: 10 }, icon: itemAssets.amuletOfProtection }],
    [26, { id: 26, name: 'Legendary Sword', type: 'weapon', rarity: 'S', description: 'Thanh kiếm huyền thoại, sức mạnh vô song, có khả năng gây sát thương chuẩn.', stats: { damage: 60, trueDamage: 5, durability: 120 }, icon: itemAssets.legendarySword, maxLevel: 50 }],
    [27, { id: 27, name: 'Dragon Scale Armor', type: 'armor', rarity: 'S', description: 'Bộ giáp làm từ vảy rồng, cực kỳ bền bỉ và kháng mọi loại sát thương.', stats: { defense: 60, magicDefense: 30, fireResistance: 0.5, iceResistance: 0.5, durability: 150 }, icon: itemAssets.dragonScaleArmor, maxLevel: 55 }],
    [28, { id: 28, name: 'Phoenix Feather', type: 'misc', rarity: 'S', description: 'Lông vũ của phượng hoàng, có thể hồi sinh người dùng một lần.', stats: { revive: true }, icon: itemAssets.phoenixFeather }],
    [29, { id: 29, name: 'Orb of Dominion', type: 'accessory', rarity: 'S', description: 'Quả cầu quyền năng, tăng cường tất cả các chỉ số và khả năng kiểm soát.', stats: { allStats: 15, crowdControlDuration: 0.2 }, icon: itemAssets.orbOfDominion }],
    [30, { id: 30, name: 'Staff of the Archmage', type: 'weapon', rarity: 'S', description: 'Cây trượng của Tổng pháp sư, tăng cường sức mạnh phép thuật đến mức tối đa.', stats: { magicDamage: 50, manaRegen: 10, intelligence: 20, spellCriticalChance: 0.2 }, icon: itemAssets.staffOfTheArchmage, maxLevel: 50 }],
    [31, { id: 31, name: 'Godstone Fragment', type: 'material', rarity: 'A', description: 'Mảnh vỡ của một Thần Thạch, dùng để cường hóa trang bị huyền thoại.', icon: itemAssets.godstoneFragment }],
    [32, { id: 32, name: 'Dragon Heart', type: 'material', rarity: 'S', description: 'Trái tim của một con rồng, nguyên liệu cực hiếm để chế tạo trang bị tối thượng.', icon: itemAssets.dragonHeart }],
    [33, { id: 33, name: 'Gold Coin', type: 'currency', rarity: 'E', description: 'Đơn vị tiền tệ cơ bản.', icon: itemAssets.goldCoin }],
    [34, { id: 34, name: 'Rare Ore', type: 'material', rarity: 'D', description: 'Quặng hiếm, dùng trong việc rèn các vũ khí chất lượng cao.', icon: itemAssets.rareOre }],
    [35, { id: 35, name: 'Enchanting Dust', type: 'material', rarity: 'B', description: 'Bụi phép thuật, dùng để phù phép và tăng cường chỉ số trang bị.', icon: itemAssets.enchantingDust }],
    [36, { id: 36, name: 'Experience Scroll', type: 'misc', rarity: 'D', description: 'Cuộn giấy tăng kinh nghiệm, dùng để tăng cấp nhanh chóng.', stats: { experienceBoost: 1000 }, icon: itemAssets.experienceScroll }],
    [37, { id: 37, name: 'Quest Item: Ancient Map', type: 'quest', rarity: 'B', description: 'Một tấm bản đồ cổ xưa, dẫn đến một kho báu bị lãng quên.', icon: itemAssets.ancientMap }],
    [38, { id: 38, name: 'Recipe: Master Sword', type: 'misc', rarity: 'A', description: 'Bản thiết kế để chế tạo thanh Kiếm Sư Phụ.', icon: itemAssets.recipeMasterSword }],
    [39, { id: 39, name: 'Teleportation Scroll', type: 'misc', rarity: 'D', description: 'Cuộn giấy phép dịch chuyển tức thời đến một địa điểm đã biết.', icon: itemAssets.teleportationScroll }],
    [40, { id: 40, name: 'Empty Potion Bottle', type: 'material', rarity: 'E', description: 'Chai lọ rỗng, có thể dùng để pha chế thuốc.', icon: itemAssets.emptyPotionBottle }],
    [41, { id: 41, name: 'Skill Book: Fireball', type: 'misc', rarity: 'B', description: 'Sách kỹ năng dạy phép thuật Fireball.', icon: itemAssets.skillBookFireball }],
    [42, { id: 42, name: 'Shiny Gem', type: 'material', rarity: 'B', description: 'Viên đá quý lấp lánh, có thể khảm vào trang bị hoặc bán.', icon: itemAssets.shinyGem }],
    [43, { id: 43, name: 'Dark Cloak', type: 'armor', rarity: 'B', description: 'Chiếc áo choàng tối màu, giúp ẩn mình trong bóng tối.', stats: { defense: 8, stealth: 0.15 }, icon: itemAssets.darkCloak, maxLevel: 25 }],
    [44, { id: 44, name: 'Crystal Sword', type: 'weapon', rarity: 'A', description: 'Thanh kiếm làm từ pha lê ma thuật, gây sát thương phép.', stats: { damage: 20, magicDamage: 15, durability: 60 }, icon: itemAssets.crystalSword, maxLevel: 35 }],
    [45, { id: 45, name: 'Mana Crystal', type: 'material', rarity: 'B', description: 'Tinh thể chứa đầy năng lượng mana, dùng để chế tạo hoặc phục hồi mana.', icon: itemAssets.manaCrystal }],
    [46, { id: 46, name: 'Poison Vial', type: 'material', rarity: 'D', description: 'Lọ thuốc độc, có thể dùng để tẩm độc vũ khí.', icon: itemAssets.poisonVial }],
    [47, { id: 47, name: 'Rune of Power', type: 'accessory', rarity: 'A', description: 'Một viên rune cổ, tăng cường sức mạnh phép thuật hoặc vật lý một cách đáng kể.', stats: { attackPower: 15, magicPower: 15 }, icon: itemAssets.runeOfPower }],
    [48, { id: 48, name: 'Shadow Dagger', type: 'weapon', rarity: 'B', description: 'Con dao găm bóng tối, thích hợp cho các đòn tấn công lén lút và gây sát thương độc.', stats: { damage: 18, criticalChance: 0.1, poisonDamage: 3 }, icon: itemAssets.shadowDagger, maxLevel: 30 }],
    [49, { id: 49, name: 'Elixir of Swiftness', type: 'potion', rarity: 'B', description: 'Tăng cường tốc độ di chuyển và tốc độ tấn công trong thời gian ngắn.', stats: { speedBoost: 0.2, attackSpeedBoost: 0.15, duration: 30 }, icon: itemAssets.elixirOfSwiftness }],
    [50, { id: 50, name: 'Ancient Scroll', type: 'quest', rarity: 'S', description: 'Cuộn giấy cổ chứa đựng bí mật về một nền văn minh đã mất.', icon: itemAssets.ancientScroll }],
    [51, { id: 51, name: 'Sunstone', type: 'material', rarity: 'A', description: 'Viên đá mặt trời, phát ra ánh sáng ấm áp, dùng trong các công thức chế tạo cao cấp.', icon: itemAssets.sunstone }],
    [52, { id: 52, name: 'Moonpetal', type: 'material', rarity: 'A', description: 'Cánh hoa mặt trăng, hấp thụ năng lượng từ ánh trăng, dùng trong các phép thuật chữa lành.', icon: itemAssets.moonpetal }],
    [53, { id: 53, name: 'Obsidian Shield', type: 'armor', rarity: 'A', description: 'Khiên làm từ đá obsidian, cực kỳ bền bỉ và có khả năng phản lại sát thương.', stats: { defense: 35, durability: 110, damageReflect: 0.1 }, icon: itemAssets.obsidianShield, maxLevel: 40 }],
    [54, { id: 54, name: 'Vampire Blade', type: 'weapon', rarity: 'A', description: 'Thanh kiếm của ma cà rồng, mỗi đòn đánh có thể hút một phần máu của kẻ địch.', stats: { damage: 30, lifesteal: 0.05, durability: 75 }, icon: itemAssets.vampireBlade, maxLevel: 45 }],
    [55, { id: 55, name: 'Gloves of Precision', type: 'armor', rarity: 'B', description: 'Đôi găng tay tăng cường độ chính xác khi tấn công và tỷ lệ chí mạng.', stats: { accuracy: 0.1, critChance: 0.05 }, icon: itemAssets.glovesOfPrecision, maxLevel: 30 }],
    [56, { id: 56, name: 'Boots of Легкости', type: 'armor', rarity: 'A', description: 'Đôi giày mang lại sự nhẹ nhàng tối đa, tăng cường tốc độ và né tránh.', stats: { speed: 6, evasion: 0.1 }, icon: itemAssets.bootsOfLightness, maxLevel: 35 }],
    [57, { id: 57, name: 'Scepter of Elements', type: 'weapon', rarity: 'S', description: 'Quyền trượng của các nguyên tố, có thể điều khiển lửa, băng và sét.', stats: { magicDamage: 45, fireDamage: 10, iceDamage: 10, lightningDamage: 10, manaCostReduction: 0.15 }, icon: itemAssets.scepterOfElements, maxLevel: 55 }],
    [58, { id: 58, name: 'Crown of Kings', type: 'accessory', rarity: 'SR', description: 'Vương miện của các vị vua, tăng cường tất cả các chỉ số và khả năng lãnh đạo.', stats: { allStats: 25, leadership: 10, charisma: 10 }, icon: itemAssets.crownOfKings }],
    [59, { id: 59, name: 'Essence of Life', type: 'material', rarity: 'SR', description: 'Tinh hoa sự sống, nguyên liệu cực kỳ quý hiếm dùng để tạo ra các vật phẩm hồi sinh hoặc cường hóa mạnh mẽ.', icon: itemAssets.essenceOfLife }],
    [60, { id: 60, name: 'Demonic Greatsword', type: 'weapon', rarity: 'SR', description: 'Thanh đại kiếm quỷ dữ, sức mạnh tàn phá, gây sát thương bóng tối và có khả năng hấp thụ linh hồn.', stats: { damage: 70, darkDamage: 15, soulSteal: 0.03, durability: 130 }, icon: itemAssets.demonicGreatsword, maxLevel: 60 }],
    [61, { id: 61, name: 'Holy Shield', type: 'armor', rarity: 'SR', description: 'Khiên thần thánh, bảo vệ tối đa khỏi mọi sát thương, có khả năng phản lại sát thương phép và hồi phục cho người dùng.', stats: { defense: 70, magicDefense: 40, damageReflectMagic: 0.15, healOverTime: 2, duration: 10, durability: 160 }, icon: itemAssets.holyShield, maxLevel: 65 }],
    [62, { id: 62, name: 'Ring of Immortality', type: 'accessory', rarity: 'SSR', description: 'Chiếc nhẫn bất tử, giúp người đeo miễn nhiễm với mọi loại sát thương trong thời gian ngắn và tăng cường khả năng tái tạo.', stats: { immortalityDuration: 5, regeneration: 0.1, maxHealthBoost: 100 }, icon: itemAssets.ringOfImmortality }],
    [63, { id: 63, name: 'World Tree Branch', type: 'material', rarity: 'SSR', description: 'Cành cây Thế giới, chứa đựng năng lượng nguyên thủy, có thể dùng để chế tạo vật phẩm mạnh nhất hoặc mở ra cánh cổng đến các chiều không gian khác.', icon: itemAssets.worldTreeBranch }],
    [64, { id: 64, name: 'Cosmic Blade', type: 'weapon', rarity: 'SSR', description: 'Lưỡi kiếm vũ trụ, cắt xuyên không gian và thời gian, gây sát thương chuẩn và có thể tạo ra các lỗ đen nhỏ.', stats: { damage: 100, trueDamage: 10, spatialRiftChance: 0.01, durability: 200 }, icon: itemAssets.cosmicBlade, maxLevel: 70 }],
    [65, { id: 65, name: 'Abyssal Armor', type: 'armor', rarity: 'SSR', description: 'Bộ giáp vực thẳm, hấp thụ bóng tối và năng lượng từ không gian khác, cung cấp phòng thủ vô song và khả năng kiểm soát bóng tối.', stats: { defense: 100, magicDefense: 50, darkResistance: 0.7, shadowControl: 0.2, durability: 220 }, icon: itemAssets.abyssalArmor, maxLevel: 75 }],
    [66, { id: 66, name: 'Potion of Supreme Healing', type: 'potion', rarity: 'SR', description: 'Bình thuốc hồi phục tối cao, ngay lập tức hồi phục lượng lớn máu và mana, đồng thời tăng cường tất cả các chỉ số trong thời gian ngắn.', stats: { heal: 500, manaRestore: 300, allStatsBoost: 10, duration: 60 }, icon: itemAssets.potionOfSupremeHealing }],
    [67, { id: 67, name: 'Scroll of Ancient Knowledge', type: 'misc', rarity: 'SR', description: 'Cuộn giấy chứa kiến thức cổ xưa, khi đọc sẽ tăng vĩnh viễn một lượng lớn kinh nghiệm và điểm kỹ năng.', stats: { permanentExpBoost: 5000, skillPointGain: 5 }, icon: itemAssets.scrollOfAncientKnowledge }],
    [68, { id: 68, name: 'Mana Elixir', type: 'potion', rarity: 'B', description: 'Tăng cường lượng mana hồi phục trong thời gian ngắn.', stats: { manaRegenBoost: 10, duration: 30 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2007_59_34%20PM.png' }],
    [69, { id: 69, name: 'Storm Hammer', type: 'weapon', rarity: 'A', description: 'Cây búa của bão tố, có thể triệu hồi sấm sét và gây choáng kẻ địch.', stats: { damage: 35, lightningDamage: 10, stunChance: 0.1, durability: 85 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_02_16%20PM.png', maxLevel: 40 }],
    [70, { id: 70, name: 'Forest Walker Boots', type: 'armor', rarity: 'A', description: 'Đôi ủng giúp di chuyển nhẹ nhàng trong rừng, tăng tốc độ và khả năng lẩn trốn.', stats: { defense: 12, speed: 5, evasion: 0.08 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_04_31%20PM.png', maxLevel: 35 }],
    [71, { id: 71, name: 'Ring of Elemental Resistance', type: 'accessory', rarity: 'B', description: 'Chiếc nhẫn bảo vệ khỏi các nguyên tố, tăng cường kháng lửa, băng và sét.', stats: { fireResistance: 0.1, iceResistance: 0.1, lightningResistance: 0.1 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_06_18%20PM.png' }],
    [72, { id: 72, name: 'Serpent Bow', type: 'weapon', rarity: 'A', description: 'Cây cung rắn, tẩm độc tự nhiên, gây sát thương theo thời gian.', stats: { damage: 25, attackSpeed: 30, durability: 80, agility: 10, critChance: 0.15, poisonDamage: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_14_19%20PM.png', maxLevel: 35 }],
    [73, { id: 73, name: 'Divine Quarterstaff', type: 'weapon', rarity: 'B', description: 'Cây gậy chiến thần thánh, mang sức mạnh của ánh sáng, tăng cường sát thương phép và hồi phục mana.', stats: { magicDamage: 20, manaRegen: 7, durability: 90, lightDamage: 8, intelligence: 10 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_23_51%20PM.png', maxLevel: 30 }], // THAY ĐỔI: Thêm Divine Quarterstaff
    [74, { id: 74, name: 'Meteor Staff', type: 'weapon', rarity: 'A', description: 'Cây trượng chứa sức mạnh của thiên thạch, có thể triệu hồi mưa sao băng...', stats: { magicDamage: 35, areaDamage: 15, manaCostReduction: 0.1, durability: 95, intelligence: 15 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2012%2C%202025%2C%2008_30_07%20PM.png', maxLevel: 45 }], // THAY ĐỔI: Thêm Meteor Staff
    [75, { id: 75, name: 'Assassin\'s Dagger', type: 'weapon', rarity: 'D', description: 'Con dao găm của sát thủ, sắc bén và dễ dàng ẩn mình trong bóng tối.', stats: { damage: 12, attackSpeed: 10, critChance: 0.05, agility: 5 }, icon: 'https://raw.githubusercontent.com/huyhoang247/englishleveling3/refs/heads/main/src/icon/inventory/ChatGPT%20Image%20Jun%2013%2C%202025%2C%2012_29_58%20PM.png', maxLevel: 20 }] // THÊM MỚI: Assassin's Dagger
]);

